### ISSUE TITLE
pinia版本更新导致的bug

### ISSUE THREAD

**Issue by cmlibo** [anncwb/vue-vben-admin#1010]
具体错误提示如下 

node_modules/pinia/dist/pinia.esm-browser.js:6:31: error: No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "effectScope"
    6 │ import { warn, toRaw, markRaw, effectScope, ref, isRef, isReactive, getCurrentInstance, onUnmounted, inject, watch, toRef, reactive, computed, toRefs, createApp } from 'vue';

经过查找是以下问题导致的
使用npm i 安装package
package.json中
pinia": "^2.0.0-beta.5",
由于没有package-lock.json
pinia会安装最新的2.0.0-rc.0版本
这个版本从vue中import了effectScope
而vue3的新版中没有export effectScope，import effectScope方式换了
目前的临时解决方案为指定pinia版本
pinia": "^2.0.0-beta.5", ->"pinia": "2.0.0-beta.5",

**Comment by mynetfan** [comment]
项目建议使用yarn而不是npm。因为随项目附带了yarn.lock文件

**Comment by anncwb** [comment]
等vue3.2.0正式版本在进行更新
