### ISSUE TITLE
合并2.6.1 打包内存溢出

### ISSUE THREAD

**Issue by wl19** [anncwb/vue-vben-admin#1011]
![I~YA MZ~KRW}WCX1 2O1 T5](https://user-images.githubusercontent.com/51466251/127619977-02ab5d7a-bc98-4822-8d64-f093a281256a.png)
![image](https://user-images.githubusercontent.com/51466251/127620093-d85caaaa-8703-44b5-b1c8-9ad6987fb339.png)
cans尝试减低vite版本也无效

**Comment by wl19** [comment]
经测试 node  v12.16.3 会出现该问题

**Comment by anncwb** [comment]
我刚刚用最新的代码多次尝试。都没有问题
![image](https://user-images.githubusercontent.com/28132598/127755854-ee00070c-7c26-4c9b-9e49-bb8f8d90f27a.png)

**Comment by wl19** [comment]
我这边在排查一下，先关闭

**Comment by link-zh** [comment]
请问这个问题最后是怎么解决的
