### ISSUE TITLE
tailwindcss 部分样式使用无效，比如：class="ml-6"

### ISSUE THREAD

**Issue by urfreespace** [anncwb/vue-vben-admin#1014]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

样式修改无法及时看到效果，需要手动刷新页面才能看到效果

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by urfreespace** [comment]
另外问一句，之前的版本有用windicss替换tailwindcss，后面为啥又改回来用tailwindcss了呢？windicss完全兼容tailwindcss，且不存在热更新问题

**Comment by mynetfan** [comment]
windicss之前有内存泄露问题

**Comment by urfreespace** [comment]
> windicss之前有内存泄露问题

嗯嗯，我切换到最新的windicss试了下效果，现在好像没内存问题了

**Comment by anncwb** [comment]
可以给我个复现步骤？ 是简版还是完整版？

**Comment by urfreespace** [comment]
> 可以给我个复现步骤？ 是简版还是完整版？

再次测试，发现不是热加载问题，而是`tailwindcss`**部分样式**设定无效，比如以下步骤可复现问题：

1. 任意div，设定class="ml-2"
2. 修改class="ml-6"，样式不生效，刷新也不生效

建议：切换到`windicss`3.6.1版本，我本地已做切换，且内存泄露问题已修复，不需要配置jit model等，热重载效果也非常好

@anncwb

**Comment by crazy6995** [comment]
同样的问题，刷新是没有效果的，重启就可以。   附议

**Comment by kryosssss** [comment]
我的解决方式，是先用cdn在index.html把tailwindcss引进来，开发完成后，再删掉

**Comment by urfreespace** [comment]
> 我的解决方式，是先用cdn在index.html把tailwindcss引进来，开发完成后，再删掉

确是一个不错的临时解决方案

**Comment by mynetfan** [comment]
已切换为windicss
