### ISSUE TITLE
浏览器刷新后能自动还原原来已打开的所有标签

### ISSUE THREAD

**Issue by lampo1024** [anncwb/vue-vben-admin#1017]
### 记住多标签
希望可以记住已打开的所有标签，在浏览器刷新后能自动还原原来已打开的标签。

### 问题

目前在开启【标签页】功能后，如果打开多个标签，刷新浏览器后，原来打开的其他标签丢失，只能恢复当前URL路径对应的标签。

### 自动还原原来已打开的标签
希望可以记住已打开的所有标签，在浏览器刷新后能自动还原原来已打开的标签。

**Comment by anncwb** [comment]
cache设置为true即可，不过keepalive内容会没掉
```js
multiTabsSetting:{
cache:true
}
```
