### ISSUE TITLE
table组件的isTreeTable字段没用

### ISSUE THREAD

**Issue by kryosssss** [anncwb/vue-vben-admin#1020]
![image](https://user-images.githubusercontent.com/66454922/127814647-aa989b8d-d9af-41c3-a055-e78cb9aac1e0.png)
![image](https://user-images.githubusercontent.com/66454922/127814703-c2d4b86c-c4bd-41e3-a943-d2161ffbf67e.png)
只要数据中有children字段就自动开启

**Comment by kryosssss** [comment]
只要数据中有children字段就自动开启

**Comment by mynetfan** [comment]
isTreeTable 属性并不是用于指定是否渲染为树形表格，只是用于辅助判断一些自定义的树形表格逻辑。如果你的字段中有children而又不想渲染为树形，请将childrenColumnName属性设为一个没有实际存在的字段名
