### ISSUE TITLE
项目配置 改变主题颜色后 点击重置没有生效

### ISSUE THREAD

**Issue by peirancao** [anncwb/vue-vben-admin#1021]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

项目配置 改变主题颜色后 点击重置没有生效。

### 复现 Bug

项目配置 改变主题颜色后 点击重置没有生效

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by mynetfan** [comment]
改变项目配置之后，需要清空缓存而不是点击设置抽屉里的重置
