### ISSUE TITLE
APITree 优化

### ISSUE THREAD

**Issue by ckbabby** [anncwb/vue-vben-admin#1025]
APITree 没有自定义labelField 和valueField 方法，我根据APISelect 方式弄了一个，希望您看看有什么问题，帮忙更新下，谢谢了
`<template>
  <a-tree-select v-bind="getAttrs" @change="handleChange">
    <template #[item]="data" v-for="item in Object.keys($slots)">
      <slot :name="item" v-bind="data"></slot>
    </template>
    <template #suffixIcon v-if="loading">
      <LoadingOutlined spin />
    </template>
  </a-tree-select>
</template>

<script lang="ts">
  import { computed, defineComponent, watch, ref, onMounted, unref } from 'vue';
  import { TreeSelect } from 'ant-design-vue';
  import { isArray, isFunction } from '/@/utils/is';
  import { get, omit } from 'lodash-es';
  import { propTypes } from '/@/utils/propTypes';
  import { LoadingOutlined } from '@ant-design/icons-vue';
  type OptionsItem = { label: string; value: string; disabled?: boolean; children: OptionsItem[] };
  export default defineComponent({
    name: 'ApiTreeSelect',
    components: { ATreeSelect: TreeSelect, LoadingOutlined },
    props: {
      numberToString: propTypes.bool,
      api: { type: Function as PropType<(arg?: Recordable) => Promise<Recordable>> },
      params: { type: Object },
      immediate: { type: Boolean, default: true },
      resultField: propTypes.string.def(''),
      labelField: propTypes.string.def('label'),
      valueField: propTypes.string.def('value'),
    },
    emits: ['options-change', 'change'],
    setup(props, { attrs, emit }) {
      const treeData = ref<Recordable[]>([]);
      const isFirstLoaded = ref<Boolean>(false);
      const loading = ref(false);
      const getAttrs = computed(() => {
        return {
          ...(props.api ? { treeData: unref(getTreeData) } : {}),
          ...attrs,
        };
      });

      function handleChange(...args) {
        emit('change', ...args);
      }
      const getTreeData = computed(() => {
        const { labelField, valueField, numberToString } = props;

        return unref(treeData).reduce((prev, next: Recordable) => {
          if (next) {
            const value = next[valueField];
            prev.push({
              label: next[labelField],
              value: numberToString ? `${value}` : value,
              ...omit(next, [labelField, valueField]),
            });
          }
          return prev;
        }, [] as OptionsItem[]);
      });
      watch(
        () => props.params,
        () => {
          isFirstLoaded.value && fetch();
        },
        { deep: true }
      );

      watch(
        () => props.immediate,
        (v) => {
          v && !isFirstLoaded.value && fetch();
        }
      );

      onMounted(() => {
        props.immediate && fetch();
      });

      async function fetch() {
        const { api } = props;
        if (!api || !isFunction(api)) return;
        loading.value = true;
        treeData.value = [];
        let result;
        try {
          result = await api(props.params);
        } catch (e) {
          console.error(e);
        }
        loading.value = false;
        if (!result) return;
        if (!isArray(result)) {
          result = get(result, props.resultField);
        }
        treeData.value = (result as Recordable[]) || [];
        isFirstLoaded.value = true;
        emit('options-change', treeData.value);
      }
      return { getAttrs, loading, handleChange };
    },
  });
</script>`

**Comment by ckbabby** [comment]
[Uploading ApiTreeSelect.vue.zip…]()
这里打包了代码

**Comment by mynetfan** [comment]
ApiTreeSelect有replaceFields

**Comment by M69W** [comment]
> Uploading ApiTreeSelect.vue.zip…
> 这里打包了代码

可以试试使用 markdown 格式显示代码

**Comment by ckbabby** [comment]
你好，我不明白，resultField 不是指api 返回的對象名字嗎？我這個是自定義 下拉数组项内label和value显示文本的字段,兩個不是同一個屬性吧

**Comment by mynetfan** [comment]
请查阅antdv文档

**Comment by mynetfan** [comment]
ApiTreeSelect扩展自antdv的TreeSelect，支持TreeSelect的所有属性和方法、插槽等。你的需求请查阅[TreeSelect文档](https://2x.antdv.com/components/tree-select-cn#API)中的replaceFields
