### ISSUE TITLE
二维码组件异常

### ISSUE THREAD

**Issue by JacksMaster** [anncwb/vue-vben-admin#1026]
### 描述 Bug

二维码组件不显示

### 复现 Bug

https://vvbin.cn/next/#/comp/qrcode

## 系统信息

Vben版本: 2.6.1和2.7.0

**Comment by M69W** [comment]
这个 pr (https://github.com/anncwb/vue-vben-admin/commit/fe4eae37146068f01ba08f033e0c2e8bd03e48b5) 没有测试通过吧？
当然即使没pr 前，也存在问题：无法动态绘制显示二维码。

**Comment by mynetfan** [comment]
> 这个 pr ([fe4eae3](https://github.com/anncwb/vue-vben-admin/commit/fe4eae37146068f01ba08f033e0c2e8bd03e48b5)) 没有测试通过吧？
> 当然即使没pr 前，也存在问题：无法动态绘制显示二维码。

这个PR解决的就是动态绘制二维码的问题

**Comment by M69W** [comment]
看到初始化的问题也修改了。
