### ISSUE TITLE
路由缓存的几个问题

### ISSUE THREAD

**Issue by kailong321200875** [anncwb/vue-vben-admin#103]
以Form-基础表单 和 useForm 为例，对应的name字段都已经添加进去了。正常切换是可以缓存路由。
![QQ图片20201125082951](https://user-images.githubusercontent.com/32283845/100167426-fd84b800-2ef9-11eb-81e3-05f546234654.png)
![QQ图片20201125083016](https://user-images.githubusercontent.com/32283845/100167437-037a9900-2efa-11eb-8417-54bf4df57cd1.png)
![QQ图片20201125083031](https://user-images.githubusercontent.com/32283845/100167442-05dcf300-2efa-11eb-8400-875bf9ca0f66.png)
问题1：当右键刷新如 基础表单 页面的时候，切换到 useForm 的时候会发现缓存也被清掉了。源码里面是有调用清除当前路由缓存的。
问题2：在切换到 基础表单 页面的时候，重新输入表单字段。切换到 useForm 在切换回来，会发现 基础表单的 页面已经无法缓存了。

问题1、2视频无法上传视频格式，只能打包成zip：
[Video_2020-11-25_084528-迅捷PDF转换器.zip](https://github.com/anncwb/vue-vben-admin/files/5593654/Video_2020-11-25_084528-.PDF.zip)

问题3：右键关闭已缓存的路由页面，如 基础表单，之后重新进入到该路由页面，会发现缓存依旧存在。源码里面是有调用清除当前路由缓存的。

问题3视频：
[Video_2020-11-25_085519-迅捷PDF转换器.zip](https://github.com/anncwb/vue-vben-admin/files/5593664/Video_2020-11-25_085519-.PDF.zip)

**Comment by anncwb** [comment]
这块我在调整下

**Comment by anncwb** [comment]
最新提交已经全部重构了缓存这块。支持多层级缓存了。可以再试试，有问题再提下
