### ISSUE TITLE
页面做了缓存，怎么从另一个页面进入强制刷新页面

### ISSUE THREAD

**Issue by IFnGSiYu** [anncwb/vue-vben-admin#1033]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by kryosssss** [comment]
一定要刷新页面，那为什么要做缓存呢，如果基于特定的情况下需要数据初始化的话，写函数就好了。

**Comment by IFnGSiYu** [comment]
列表和添加数据是两个页面，列表页面做了缓存（查询需要），但是添加后跳转列表页因为做了缓存，所以列表数据没有实时更新

**Comment by linrencai** [comment]
用go('url',true);

**Comment by IFnGSiYu** [comment]
只能说组件名，不能是路由地址是吗

**Comment by linrencai** [comment]
> 只能说组件名，不能是路由地址是吗

应该是，你可以参考文档有说明  useGo

**Comment by IFnGSiYu** [comment]
第二个参数true，试过了没用

**Comment by IFnGSiYu** [comment]
onActived可用，按理说go('',true)应该也是可以的，这是bug还是框架没考虑到的地方

**Comment by IFnGSiYu** [comment]
onActived可用，按理说go('',true)应该也是可以的，这是bug还是框架没考虑到的地方

**Comment by mynetfan** [comment]
go： ```(opt: PageEnum | RouteLocationRawEx | string = PageEnum.BASE_HOME, isReplace = false):void```
所以第二个参数并不是刷新路由。

要刷新某个页面，请在push或replace之后调用refreshPage。例如：
···
  import { useRouter } from 'vue-router';
  import { useTabs } from '/@/hooks/web/useTabs';

  const { push } = useRouter();
  const { refreshPage } = useTabs();
  
 function goAndRefresh() {
    push('/system/account').then(() => {
                refreshPage();
              });
 }
···
