### ISSUE TITLE
BasicTable 性能优化

### ISSUE THREAD

**Issue by wananle** [anncwb/vue-vben-admin#1037]
useTable开启了actionColumn操作项 结合TableAction组件选择100条数据数据全选或单选 选中或取消时间太久了，希望有优化

https://user-images.githubusercontent.com/48664370/128165901-e1e76d3b-18c2-4429-a756-e2fe71ec4dd6.mp4

**Comment by xietongjian** [comment]
> useTable开启了actionColumn操作项 结合TableAction组件选择100条数据数据全选或单选 选中或取消时间太久了，希望有优化
> 
>  1628072739250.mp4
大侠，请问一下，这个问题解决了吗？
