### ISSUE TITLE
安装了 yarn 就不能提交到代码服务器

### ISSUE THREAD

**Issue by snihwxf** [anncwb/vue-vben-admin#1038]
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -

> cqms_class_room_admin@2.6.1 lint:lint-staged
> lint-staged -c ./.husky/lintstagedrc.js

[STARTED] Preparing...
[SUCCESS] Preparing...
[STARTED] Running tasks...
[STARTED] Running tasks for *.{js,jsx,ts,tsx}
[STARTED] Running tasks for {!(package)*.json,*.code-snippets,.!(browserslist)*rc}
[STARTED] Running tasks for package.json
[STARTED] Running tasks for *.vue
[STARTED] Running tasks for *.{scss,less,styl,html}
[STARTED] Running tasks for *.md
[SKIPPED] No staged files match {!(package)*.json,*.code-snippets,.!(browserslist)*rc}
[SKIPPED] No staged files match package.json
[SKIPPED] No staged files match *.{scss,less,styl,html}
[SKIPPED] No staged files match *.md
[STARTED] eslint --fix
[STARTED] eslint --fix
[SUCCESS] eslint --fix
[STARTED] prettier --write
[SUCCESS] eslint --fix
[STARTED] prettier --write
[SUCCESS] prettier --write
[SUCCESS] Running tasks for *.{js,jsx,ts,tsx}
[SUCCESS] prettier --write
[STARTED] stylelint --fix
[SUCCESS] stylelint --fix
[SUCCESS] Running tasks for *.vue
[SUCCESS] Running tasks...
[STARTED] Applying modifications...
[SUCCESS] Applying modifications...
[STARTED] Cleaning up...
[SUCCESS] Cleaning up...

> cqms_class_room_admin@2.6.1 lint:pretty
> pretty-quick --staged

🔍  Finding changed files since git revision d07e77b.
🎯  Found 3 changed files.
✅  Everything is awesome!
⧗   input: test1
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky - commit-msg hook exited with code 1 (error)

**Comment by anncwb** [comment]
可以看下文档的lint规范那块，要符合规范才可以提交，不需要就关闭

**Comment by snihwxf** [comment]
我都没有改代码，那怎么关闭呢

**Comment by webxiu** [comment]
这玩意太水了, 放弃
