### ISSUE TITLE
可编辑单元格 inputnumber 改动为0时，保存后不显示

### ISSUE THREAD

**Issue by VENI-VIDIVICI** [anncwb/vue-vben-admin#1039]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

请清晰地描述此 Bug 的具体表现。
可编辑单元格 inputnumber 改动为0时，保存后不显示
### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码
https://vvbin.cn/next/#/comp/table/editCellTable
数字输入框 改动为0后，保存不显示
## 系统信息

- 操作系统: window
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by qixianc94** [comment]
我使用的是2022年3月的版本，bug依然存在。
fix方法：
```
src/components/Table/src/components/editable/EditableCell.vue
```
![image](https://user-images.githubusercontent.com/20460624/168227204-83af5d78-bd7f-40f4-b5e0-9851a9e5e994.png)
