### ISSUE TITLE
ApiSelect数据渲染不正确

### ISSUE THREAD

**Issue by FollowTrend** [anncwb/vue-vben-admin#1040]
搜索表单配置：
![image](https://user-images.githubusercontent.com/40554571/128471849-ffd223f1-e4a2-4126-9271-54eb29c618fa.png)
数据格式：
![image](https://user-images.githubusercontent.com/40554571/128471933-c6940431-f1f5-46f2-83a7-dc84cf8a2f5a.png)
效果：
![image](https://user-images.githubusercontent.com/40554571/128471977-c94b195e-f2a9-4250-b36e-a60dcfa0badf.png)
label渲染出来的是user_id，并且选择没反应，但是表单有绑定user_id的值，我在别的地方用这个就正常，在这里就这样，不知道喝后端返回的数据格式有没关系，希望解决

**Comment by M69W** [comment]
看到你点的接口不是最新的那条？

**Comment by FollowTrend** [comment]
> 看到你点的接口不是最新的那条？

什么不是最新的那条，这个接口就是ApiSelete请求的接口

**Comment by mynetfan** [comment]
未能重现此问题

**Comment by mynetfan** [comment]
未能重现且没有继续提供更多信息，暂且关闭此Issue。如果能够提供完整的复现方法，请重新打开此Issue

**Comment by keysol** [comment]
我也出现了这个问题，数据加载出来了但是没办法选中。

**Comment by keysol** [comment]
我发现了        
   resultField: 'dictItemDtos',
        labelField: 'itemText',
        valueField: 'itemVaule',

这些如果不是默认值就会出现，能显示出来数据，但是选中没有反应。labelField，valueField这两个只能是默认值，label,和value。
