### ISSUE TITLE
View目录里面，超过2层目录,修改ts文件不会热加载了

### ISSUE THREAD

**Issue by fengbindev** [anncwb/vue-vben-admin#1045]
更新到2.7.0最新版本，修改ts文件不会热加载了，需要重新启动。。。。

**Comment by fengbindev** [comment]
测试发现，2层目录时，修改里面的ts文件，页面不会热加载
![image](https://user-images.githubusercontent.com/28595220/128593169-9fb8e95b-83c5-4f30-b947-e057ad4082e3.png)

**Comment by liu-fatty** [comment]
我也遇到了这个问题，同求

**Comment by zhouhexiang12** [comment]
有办法解决么？
