### ISSUE TITLE
顶部菜单混合模式+分割二级菜单

### ISSUE THREAD

**Issue by Xianun** [anncwb/vue-vben-admin#1049]
目前的分割菜单是一级菜单，多级菜单数量较多时，是否能支持选择级数进行分割。

**Comment by anncwb** [comment]
这个应该是不会去实现，需要的人不多。可以自行实现

**Comment by wcldyx** [comment]
> 目前的分割菜单是一级菜单，多级菜单数量较多时，是否能支持选择级数进行分割。

兄弟，我也需要呀
