### ISSUE TITLE
BasicForm 自定义 autoAdvancedLine 无效

### ISSUE THREAD

**Issue by waney** [anncwb/vue-vben-admin#1051]
版本 2.7.0

```
<BasicForm @register="basic"></BasicForm>

const [basic, { validate }] = useForm({
      labelWidth: 120,
      schemas: step1Schemas,
      showAdvancedButton: true,
      autoAdvancedLine: 9,
      autoSubmitOnEnter: true,
      actionColOptions: {
        span: 24,
      },
      submitButtonOptions: {
        text: '下一步',
      },
      submitFunc: customSubmitFunc,
    });
```

**Comment by mynetfan** [comment]
请查阅文档或form源代码理解autoAdvancedLine的配置意义。它不是设置schemas数量，而是schemas所占行数

**Comment by waney** [comment]
是我没说清楚，我想说的是收起状态下可见schemas 数量，比如我想正常可见多少个schemas，其余的折叠。
如我设置autoAdvancedLine:9，实际上我有30个schemas，想折叠后面21个。

**Comment by waney** [comment]
> 如果 showAdvancedButton 为 true，超过指定行数行默认折叠

文档说的意思不是指折叠超过指定行数之后的schemas吗？

**Comment by mynetfan** [comment]
如果你每行有3个，想要折叠后面的21个只显示前面的9个，autoAdvancedLine需要设置为3（9/3=3）

**Comment by waney** [comment]
正是如此，我每行1个，无任autoAdvancedLine设置多少，均显示一行，所以我才来反馈啊。

**Comment by waney** [comment]
> 如果你每行有3个，想要折叠后面的21个只显示前面的9个，autoAdvancedLine需要设置为3（9/3=3），默认显示3行（9个）

也就是说如此设置最终也只显示3个（一行）

**Comment by waney** [comment]
从https://github.com/anncwb/vue-vben-admin下载了最新版重现这个情况。
![1](https://user-images.githubusercontent.com/69211/128955018-07ec308e-15a9-41fc-835a-a6793e458f51.png)
![2](https://user-images.githubusercontent.com/69211/128955021-3406da32-f792-4edb-974a-d717381928fb.png)
![4](https://user-images.githubusercontent.com/69211/128955122-4a67578a-f592-4de6-90b4-b9cde09d76f9.png)

**Comment by waney** [comment]
autoAdvancedLine 值小于7显示效果均如图一，大于6则全部显示。

**Comment by waney** [comment]
@mynetfan

**Comment by canvascat** [comment]
> 是我没说清楚，我想说的是收起状态下可见schemas 数量，比如我想正常可见多少个schemas，其余的折叠。
> 如我设置autoAdvancedLine:9，实际上我有30个schemas，想折叠后面21个。

收起状态显示数量是写死的, 没有暴露; autoAdvancedLine的意思是如果行数大于等于设定值则自动折叠(折叠后显示的行数无法改变)

src\components\Form\src\hooks\useAdvanced.ts
![q4m264dOyE59RPAbp8HiTg==](https://user-images.githubusercontent.com/31235016/129164440-8de61e3a-ec6b-43d4-b510-c072bbf553de.png)

![taKk0yamuje2H#jLgtIvow==](https://user-images.githubusercontent.com/31235016/129164396-da13eddc-8fbb-49e3-89da-37e755ad0f12.png)

其中每个schema的`isAdvanced`是用来控制显示的, `advanceState.isAdvanced`对应收起按钮的显示状态,
如果你想自己控制每个schema的显示,你可以单独设置每个schema的`show`属性:
![CWgSAWiysCwauDy19vZwMw==](https://user-images.githubusercontent.com/31235016/129165558-df9c006f-4068-402e-a41a-076775457fde.png)

**Comment by waney** [comment]
> > 是我没说清楚，我想说的是收起状态下可见schemas 数量，比如我想正常可见多少个schemas，其余的折叠。
> > 如我设置autoAdvancedLine:9，实际上我有30个schemas，想折叠后面21个。
> 
> 收起状态显示数量是写死的, 没有暴露; autoAdvancedLine的意思是如果行数大于等于设定值则自动折叠(折叠后显示的行数无法改变)
> 
> src\components\Form\src\hooks\useAdvanced.ts
> ![q4m264dOyE59RPAbp8HiTg==](https://user-images.githubusercontent.com/31235016/129164440-8de61e3a-ec6b-43d4-b510-c072bbf553de.png)
> 
> ![taKk0yamuje2H#jLgtIvow==](https://user-images.githubusercontent.com/31235016/129164396-da13eddc-8fbb-49e3-89da-37e755ad0f12.png)
> 
> 其中每个schema的`isAdvanced`是用来控制显示的, `advanceState.isAdvanced`对应收起按钮的显示状态,
> 如果你想自己控制每个schema的显示,你可以单独设置每个schema的`show`属性:
> ![CWgSAWiysCwauDy19vZwMw==](https://user-images.githubusercontent.com/31235016/129165558-df9c006f-4068-402e-a41a-076775457fde.png)

单独设置某一字段 show: true 并没有效果，如果autoAdvancedLine的值并不影响折叠后的显示数量，那么这个值的作用并没有发挥其价值啊，如其是代表折叠后的显示数量不也能达到同样的折叠意义嘛。

**Comment by canvascat** [comment]
@waney 疏忽了,最后的显示还有showAdvancedButton属性控制, 看来要达到里这个目的只能取改`BASIC_COL_LEN`值了😅

**Comment by mynetfan** [comment]
BASIC_COL_LEN   指的是一行的COL数量。这个常量就是固定的24，参考https://2x.antdv.com/components/grid-cn

**Comment by waney** [comment]
这里不涉及前端col排列，只需要关注折叠情况下显示多少个就可以了啊。

**Comment by mynetfan** [comment]
autoAdvancedLine   超过多少行默认折叠状态（不影响折叠行数）
alwaysShowLines   折叠时始终显示的行数
