### ISSUE TITLE
functional http register

### ISSUE THREAD

**Issue by JinPengGeng** [anncwb/vue-vben-admin#1052]
### 针对http(defHttp)模块，是否可以修改为register & use 的方式使用

整体项目中大部分的功能模块目前看来都是使用的类似 init、setup 等方式在  `main.js`  中的 `bootstrap` 方法进行注册的，

针对 `http(defHttp)` 模块，是否也可以修改为register & use 的方式使用保持整体的风格统一

### http register & use

> registerHttp(config)
> useHttp()

自己尝试了封装，但是在解决 多个接口配置时，目前没有好的想法 :(

希望是否可以给个建议

**Comment by canvascat** [comment]
像 https://vueuse.org/integrations/useaxios/#usage
或者像vuex的useStore一样的写法使用`inject`

**Comment by mynetfan** [comment]
项目中的惯例是将http访问封装为function放在api目录下以便统一管理和更新，而不是直接在组件内使用axios实例动态访问
