### ISSUE TITLE
取消table 选中行 无触发selected-change

### ISSUE THREAD

**Issue by k983551019** [anncwb/vue-vben-admin#1053]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
 取消table 选中行 无触发rowKeys   ，点击复选款可以取消并触发rowKeys   

### 复现 Bug

 const rowKeys = computed(() => {
        console.log(getSelectRowKeys(), 'getSelectRowKeys()');
        return getSelectRowKeys();
      });

https://user-images.githubusercontent.com/48147837/128805137-bf0714d1-a2ad-44e2-9036-6a8b638562ae.mp4

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:win00
- Node 版本:14.17.0
- 包管理器 (npm/yarn/pnpm) 及其版本:1.22.10

**Comment by mynetfan** [comment]
已修复`selection-change`事件。

```
<BasicTable @register="registerTable" @selection-change="onSelectChange" />
```

```
      const rowKeys = ref([]);

      function onSelectChange({ keys }) {
        rowKeys.value = keys;
        console.log(unref(rowKeys));
      }
```
