### ISSUE TITLE
Select 表单中onChange不能拿的第二个label和第三个参数extra

### ISSUE THREAD

**Issue by IFnGSiYu** [anncwb/vue-vben-admin#1058]
component: 'Select',
    labelWidth: 100,
    colProps: { span: 6 },
    componentProps:()=>{
      return {
        options: [
          { label: 'label1', value: '0' },
          { label: 'label2', value: '1' },
          { label: 'label3', value: '-1' },
        ],
        onChange:(value,label,extra)=>{
          console.log(value,label,extra);
          //-1 undefined undefined
        }
      }
    }

antd 里面change监听可以有三个返回值

change | 选中树节点时调用此函数 | function(value, label, extra)

**Comment by mynetfan** [comment]
无此问题。
![image](https://user-images.githubusercontent.com/17241274/129025059-03b73a7c-ae4d-4856-b81e-2840b083ad7e.png)

![image](https://user-images.githubusercontent.com/17241274/129025031-b7cd66ee-4ecf-4551-874c-e68e8ed5d2d9.png)

onChange参数并不是value, label, extra，请查阅[antdv 2.x文档](https://2x.antdv.com/components/select-cn#API)

**Comment by IFnGSiYu** [comment]
我用的是2.3.0版本，现在的版本是修复了这个问题吗
![微信截图_20210812173256](https://user-images.githubusercontent.com/48302866/129174747-427c2b54-3675-4a23-b6ad-3fb0b7cd7c7d.png)
![微信截图_20210812173317](https://user-images.githubusercontent.com/48302866/129174750-18286148-894c-4b2d-9455-6c5ad302869a.png)
