### ISSUE TITLE
移动端打开页面一直停留在加载页面

### ISSUE THREAD

**Issue by search-inner** [anncwb/vue-vben-admin#1059]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug
使用vben-admin-thin-next-main（精简版本）
移动端打开页面一直停留在加载页面,开发环境有问题（真机才存在，浏览器模拟也没问题），生产环境没问题。

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:window7
- Node 版本:12.16.1
- 包管理器 (npm/yarn/pnpm) 及其版本:yarn-1.9.4

**Comment by kuizuo** [comment]
苹果系统的safari有相同情况，安卓手机并未出现如上情况

**Comment by mynetfan** [comment]
开发环境本身就有浏览器版本要求，比如chrome要求v80以上。这不是BUG

**Comment by mynetfan** [comment]
生产环境下v2.6.1之前的几个版本在safari上有问题，打不开页面。如果你用的是这些有问题的版本，尝试合并此commit：https://github.com/anncwb/vue-vben-admin/commit/dafcdd898caae57104f1155b0ec660ea333e7b19
