### ISSUE TITLE
一个不是很大的Modal的问题

### ISSUE THREAD

**Issue by crazy6995** [anncwb/vue-vben-admin#106]
### Subject of the issue

openModal传递data的问题

### Your environment

- **OS**: Windows 10
- **Env**: Chorme latest version

### Steps to reproduce

![YP(U ZN3MA)A1Y8RXLE1JS9](https://user-images.githubusercontent.com/5605020/100327450-46299780-3006-11eb-84bf-5d1fc999fe0d.png)

1. 如果不把register一并声明，会引发warning（正常现象）
![2R5T7_ZJMW{Q44GX%~C1DAO](https://user-images.githubusercontent.com/5605020/100327473-4de93c00-3006-11eb-9bf3-ebd468a3517a.png)
2. 如果通过emits声明了register，那么外部openModal并传递data时，内部无法获取到这个data
3. 如果emits不填写，就没有任何问题

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub. This will get you the fastest support. 🎉

### Expected behaviour

内部modal将register声明时，外部可正常通过openModal传递数据

### Actual behaviour

内部modal将register声明时，外部并不能通过openModal传递数据，即使openOnSet=true

**Comment by anncwb** [comment]
我没有还原出这个问题，我在示例按照你写的还原没出错

**Comment by crazy6995** [comment]
我再去测试测试，把完整的示例放到codepen去

**Comment by anncwb** [comment]
我先关闭这个了。
