### ISSUE TITLE
代码格式化问题

### ISSUE THREAD

**Issue by kailong321200875** [anncwb/vue-vben-admin#1063]
![QQ图片20210812192938](https://user-images.githubusercontent.com/32283845/129189584-883c63fd-9144-4af2-8a71-9083c0d7ed84.png)

我在代码中自己写了一个less方法，可是在lint:prettier格式化的时候，会报错。

![image](https://user-images.githubusercontent.com/32283845/129189669-b65eb918-fc5c-4743-bc58-17dd85995e87.png)

请问这个怎么处理，语法上是没错的。。

**Comment by anncwb** [comment]
把这个文件加入prettierignore或者加上prettier忽略的注释即可
