### ISSUE TITLE
怎么才能在当前标签页打开另一个页面呢？

### ISSUE THREAD

**Issue by im-qrh** [anncwb/vue-vben-admin#1068]
我有个业务场景是这样的：
我有个列表页(`xxx/list`)中有个新增按钮，点击新增按钮会在新标签页打开表单编辑页面(`xxx/detail`)。表单编辑页面点击保存按钮后后台返回id数据,我想在当前页刷新为这个id的表单编辑页(`xxx/detail/1`),请教下怎么实现？
我使用了useGo()和Redirect都是打开了另一个标签页。

**Comment by mynetfan** [comment]
已添加相关方法。使用例子：

在setup中
```
const { setTitle, updatePath } = useTabs();
```
需要更新当前tab的path时
```
// 设置tab的标题
setTitle('详情：用户' + userId);
// 更新当前tab的path并跳转到新页面
const path = '你想要打开的页面的path';
updatePath(path).then(() => go(path, true));
// 此时会在当前标签打开path
```

**Comment by ZhouFX** [comment]
> 

可以详细诉说下用法吗？

**Comment by ZhouFX** [comment]
> 用push const { push } = useRouter(); 找到了。

可以详细诉说下用法吗

**Comment by gy002002** [comment]
import { useRouter } from 'vue-router';
const router = useRouter();

const openBrochurePageConfig = (row: any) => {
  router.push({ path: "/xxxxx", query: { id: 123 } });
};
