### ISSUE TITLE
Table固定列选中显示层级不正确

### ISSUE THREAD

**Issue by JZaaa** [anncwb/vue-vben-admin#1069]
### 描述 Bug

Table组件固定列模式下选中一行，会出现显示问题

### 复现 Bug

[http://localhost:3101/#/comp/table/fixedColumn](http://localhost:3101/#/comp/table/fixedColumn)

![微信截图_20210813145312](https://user-images.githubusercontent.com/26134251/129317132-7162f8a5-2274-4adc-8dda-dc88f1a9fd38.png)

## 系统信息

- 操作系统: Windows

**Comment by JZaaa** [comment]
demo也有这样的问题[https://vvbin.cn/next/#/comp/table/fixedColumn](https://vvbin.cn/next/#/comp/table/fixedColumn)

**Comment by waney** [comment]
z-index: 9999;
