### ISSUE TITLE
包裹页面组件 PageWrapper 设置dense: true时页面vben-page-wrapper-content空白

### ISSUE THREAD

**Issue by waney** [anncwb/vue-vben-admin#1070]
如题，在开发时保存文件后，[vite] hot updated，vben-page-wrapper-content 页面内容空白（版本 v2.7.0），不设置dense则正常。

**Comment by mynetfan** [comment]
https://vvbin.cn/next/#/system/account
未能重现

**Comment by waney** [comment]
> https://vvbin.cn/next/#/system/account
> 未能重现

在线重现不了，是指在本地修改了文件并保存之后[vite] hot updated，页面热更新时class="vben-page-wrapper-content" 这个Div内出现白屏。要刷新页面才能恢复。这个就是开发的时候很碍事，后来好不容易发现不设置dense可避免。 @mynetfan

**Comment by mynetfan** [comment]
我就是在本地测试的，提供的地址是想指明我具体测试的页面。我这里未能重现你所说的问题

**Comment by waney** [comment]
@mynetfan 抱歉，我现在在家里测试了如你所说正常，那可能是其他原因，因为我在办公室电脑常常遇到，有一段时间了，我再自我检查。

**Comment by waney** [comment]
@mynetfan 
下载官网例子复现了。
http://192.168.3.210:3101/#/comp/table/fetchTable
```
<template>
  <PageWrapper contentBackground contentClass="flex" dense contentFullHeight fixedHeight>
    <BasicTable
      @register="registerTable"
    >
    </BasicTable>
  </PageWrapper>
</template>

<script lang="ts" setup>
  import { ref } from 'vue';
  import { BasicTable, useTable } from '/@/components/Table';
  import { getBasicColumns } from './tableData';
  import { demoListApi } from '/@/api/demo/table';
  import { PageWrapper } from '/@/components/Page';

  const [registerTable, { reload }] = useTable({
    title: '远程加载示例1',
    api: demoListApi,
    columns: getBasicColumns()
  });
</script>

```

**Comment by mynetfan** [comment]
已找到原因：
PageWrapper的fixedHeight不可与basicTable的canResize（默认为true）同时启用，二者在功能上有冲突，都是自动计算高度。请确保只启用其中一个属性。
