### ISSUE TITLE
CollapseContainer 组件收起和展开的图标好像反了

### ISSUE THREAD

**Issue by xietongjian** [anncwb/vue-vben-admin#1075]
CollapseContainer 组件收起和展开的图标好像反了，
![image](https://user-images.githubusercontent.com/16096832/129433206-a097a258-3b8d-4b62-afd4-13f243ab3a6e.png)

收起的时候应该展示向下箭头
展开的时候应该显示向上箭头

**Comment by mynetfan** [comment]
这个图标用来展示当前状态，并没有反。请参考antdv的[Collapse 折叠面板](https://2x.antdv.com/components/collapse-cn)

**Comment by xietongjian** [comment]
好吧，看来是我理解错了。
