### ISSUE TITLE
BasicTable配置的searchFormSchema问题

### ISSUE THREAD

**Issue by acegank** [anncwb/vue-vben-admin#1086]
searchFormSchema内是否能针对某个filed进行权限判断，这个权限是从接口获取的code，前台使用v-auth这种方式，searchFormSchema内是否也可以达到这种效果。  

或者说  在searchFormSchema内定义一个solt，页面上通过auth权限，但是BasicTable的searchFormSchema配置怎么添加solt

**Comment by acegank** [comment]
通过hasPermission这个hooks目前是可以达到目的，如果能稍微封装下添加一个字段来支持code权限更好了

**Comment by zsl1549** [comment]
searchFormSchema内定义一个solt 如何在BasicTable展示  大佬门有知道的吗？
@acegank

**Comment by zsl1549** [comment]
![image](https://user-images.githubusercontent.com/32888522/205493254-9776182f-d1c4-440a-8bd6-a451d9395d99.png)

**Comment by acegank** [comment]
@zsl1549 你这样写有什么问题吗
