### ISSUE TITLE
tinymce组件不支持inline: true 模式

### ISSUE THREAD

**Issue by waney** [anncwb/vue-vben-admin#1092]
开启inline 模式需要selector,fixed_toolbar_container 支持。
tinymce不能混用textarea、selector。

**Comment by waney** [comment]
在保存文件热加载后报错：Cannot read property 'parentNode' of null
```
Uncaught TypeError: Cannot read property 'parentNode' of null
    at purgeDestroyedEditor (tinymce.js:29048)
    at Array.<anonymous> (tinymce.js:29250)
    at Object.each$2 [as each] (tinymce.js:585)
    at Object.initEditors (tinymce.js:29249)
    at EventUtils2.executeHandlers (tinymce.js:5163)
    at defaultNativeHandler (tinymce.js:4966)
    at bindOnReady (tinymce.js:4927)
    at EventUtils2.bind (tinymce.js:5033)
    at Object.bind2 [as bind] (tinymce.js:7679)
    at Object.init (tinymce.js:29268)
```
```
<Tinymce
          v-model="body"
          v-if="initTinymce"
          :options="options"
          :showImageUpload="false"
          @change="handleChange"
        />
```
```
const options = ref({
  inline: true,
  menubar: [],
  toolbar:
    'undo redo | formatselect | ' +
    'bold italic backcolor | alignleft aligncenter ' +
    'alignright alignjustify | bullist numlist outdent indent | ' +
    'removeformat | insertfile image media autosave template',
  fixed_toolbar_container: '#editorToolbar',
  selector: '#editorBody',
  toolbar_sticky: true,
  toolbar_persist: true,
  auto_focus: false,
  placeholder: 'hello world!',
  preview_styles: '',
  inline_boundaries: false,
});
```
正常效果：
![0](https://user-images.githubusercontent.com/69211/129740687-c626fc3c-a811-40a4-b923-955c6e8d9246.png)

报错后编辑器消失，工具栏不见了：
![1](https://user-images.githubusercontent.com/69211/129740747-59eccbe8-a2bd-4fb8-b398-ae68bd78cc4f.png)

**Comment by mynetfan** [comment]
请提供完整的测试代码

**Comment by mynetfan** [comment]
已修复inline模式的问题：https://github.com/anncwb/vue-vben-admin/commit/8e01377481a34cda221de6bbb01fc7d5b2824c82

**Comment by waney** [comment]
> 已修复inline模式的问题：[8e01377](https://github.com/anncwb/vue-vben-admin/commit/8e01377481a34cda221de6bbb01fc7d5b2824c82)

经过反复测试，[vite] hot updated:  onMountedOrActivated 后编辑器丢失。

**Comment by mynetfan** [comment]
tinymce的inline模式对热更新的支持不佳（它对selector指定的dom的影响超出了vue的管理范围）。这种情况目前只能刷新当前路由。
另外，这个组件并不是支持vue的版本，项目封装的只是一般性的用法，不会像一般vue组件那样及时响应所有props的变化。如果你对此组件有比较深度的依赖，请考虑其它组件或尝试自行封装。
