### ISSUE TITLE
echart 组件不支持颜色配置

### ISSUE THREAD

**Issue by zhuichen** [anncwb/vue-vben-admin#1094]
const { setOptions } = useECharts(chartBarRef as Ref<HTMLDivElement>);
  setOptions({
    color: ['#9dc3e6', '#ffe699', '#a9d18e', '#ee6666', '#73c0de', '#3ba272', '#fc8452', '#9a60b4', '#ea7ccc'],
    legend: {
        data: ['bar', 'bar2', 'bar3', 'bar4'],
        left: '10%'
    },
  ...不列出来
})
其中color配置无效，无法修改echart颜色

**Comment by mynetfan** [comment]
实际上options会被原样传递给echarts实例的setOption方法，请查阅echarts的相关文档。

**Comment by MrFu1998** [comment]
`useEcharts` 确实不支持颜色设置，但是采用原生 `echarts` 是支持的，看了下参数打印，参数也确实传到了 `setOption`
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/20925158/154642369-ce9aeab7-4ea0-4e76-b47b-9ec4f1c6a0d8.png">
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/20925158/154642523-974d83e9-fb6f-4c45-90bc-51ad89fcfaa4.png">
<img width="1389" alt="image" src="https://user-images.githubusercontent.com/20925158/154642701-9e249792-d6ed-4022-af36-aad6dfcd9015.png">

**Comment by likui628** [comment]
我也遇到了同样的问题
