### ISSUE TITLE
BasicTable 调用 reload()刷新无效的现象

### ISSUE THREAD

**Issue by zhangWeiZhuang** [anncwb/vue-vben-admin#1097]
![image](https://user-images.githubusercontent.com/44084004/129999719-a9dbe2d2-900a-41f3-bb10-5dbb1b86bf26.png)
当我页面上修改 路由地址 字段保存后，列表刷新完成后还是之前的数据
![image](https://user-images.githubusercontent.com/44084004/129999806-52e98eb7-a16b-4ba0-b3c0-4d09a50118f2.png)
需要人为点“查询按钮”才会更新成最新修改的数据
请问各位大神有遇过类似的问题吗？

**Comment by mynetfan** [comment]
因为你的保存动作是异步函数，你调用保存后没等保存完成就刷新了，所以刷新的时候仍然是你保存之前的数据。
需要await或者promise.then

**Comment by Junibl** [comment]
上面的问题就是需要将保存动做变成同步的就行了
