### ISSUE TITLE
每次修改页面都需要重启vite

### ISSUE THREAD

**Issue by dongshihao666** [anncwb/vue-vben-admin#1098]
修改css 或者 加个 debugger 都需要重启vite 才能生效

**Comment by mynetfan** [comment]
当前版本未能重现

**Comment by dongshihao666** [comment]
有时生效有时不生效 ，今天从早上上班开始到现在彻底不生效了   macOs 11.4   chrome  92.0.4515.159

**Comment by waney** [comment]
> 有时生效有时不生效 ，今天从早上上班开始到现在彻底不生效了 macOs 11.4 chrome 92.0.4515.159

应该是你的问题，从本地开始排查。

**Comment by mynetfan** [comment]
未提供有效信息，请使用最新版本。如需反馈更多信息请重新打开此Issue。
