### ISSUE TITLE
无法下载依赖，因为vite-plugin-imagemin这个插件失效了

### ISSUE THREAD

**Issue by Minori-ty** [anncwb/vue-vben-admin#1099]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

无法下载依赖，因为项目中引用的vite-plugin-imagemin失效了，单独安装这个包也是下载失败。好像是imagemin的问题。

### 复现 Bug

git clone https://github.com/anncwb/vue-vben-admin.git
npm i 

## 系统信息

- 操作系统: win10
- Node 版本: v14.17.12
- 包管理器 (npm/yarn/pnpm) 及其版本: npm v6.14.13

**Comment by mynetfan** [comment]
请查看文档中的相关说明

**Comment by Minori-ty** [comment]
> 请查看文档中的相关说明

我修改了host，翻墙了，也还是不行。一直无法下载imagemin，我也到imagemin的项目中提交了issue，但是作者也是一直没搭理

**Comment by Adaer** [comment]
connect ETIMEDOUT 199.232.4.133:443
这个问题一直困扰着，这个插件实在太难安装了

**Comment by tzwtmll** [comment]
我cnmd，你就是个jb，以后别人让我见到你，见你一次打你一次，安装个包整这么麻烦，别人image-webpack-loader怎么就没这么多花样

**Comment by Minori-ty** [comment]
> 我cnmd，你就是个jb，以后别人让我见到你，见你一次打你一次，安装个包整这么麻烦，别人image-webpack-loader怎么就没这么多花样

傻逼，别在我这里回复。推送过来吓我一跳
