### ISSUE TITLE
tree组件 slots效果和ant design vue 不符

### ISSUE THREAD

**Issue by bangxingni** [anncwb/vue-vben-admin#110]
![100688053-6cf81d00-33bc-11eb-8aad-728af7372351](https://user-images.githubusercontent.com/20875524/100688129-9022cc80-33bc-11eb-894a-73939c548f67.png)

**Comment by anncwb** [comment]
这个slot可能内部被覆盖用于右键和右侧菜单使用了。所以覆盖不了。覆盖了上面两个功能会有问题
