### ISSUE TITLE
await router.isReady()导致dom未加载

### ISSUE THREAD

**Issue by JoyZ1122** [anncwb/vue-vben-admin#1106]
token过期，刷新页面后跳转到登录页，但是dom没有挂载上导致页面显示不出来，看了下是await router.isReady()导致的，这句有必要加吗

**Comment by mynetfan** [comment]
合并此commit：https://github.com/anncwb/vue-vben-admin/commit/3a5d1a5757c0a2be17e6dd370cbb023ddbb30d5e

然后再试试

**Comment by mynetfan** [comment]
先关闭。如果合并以上commit后仍然有问题请重新打开此Issue
