### ISSUE TITLE
关于弹出框可以增加上下左右等8个方法的大小伸缩

### ISSUE THREAD

**Issue by wsxe9988** [anncwb/vue-vben-admin#1107]
### Subject of the feature

关于弹出框可以增加上下左右等8个方法的大小伸缩

![1629450283155_64CED48E-3270-4967-A0C5-E95C62F77D39](https://user-images.githubusercontent.com/5828057/130210512-1ecd36ba-289b-40fa-b508-b613f9074800.png)

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by anncwb** [comment]
这个需要重头实现一个modal，所以可以自行实现
