### ISSUE TITLE
yarn

### ISSUE THREAD

**Issue by wp-boom** [anncwb/vue-vben-admin#1109]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by wp-boom** [comment]
yarn安装以来一直卡住
![截屏2021-08-21 17 55 26](https://user-images.githubusercontent.com/52694804/130318228-be77aa33-bee4-4897-9cad-b42b34883ed7.png)

**Comment by mynetfan** [comment]
设置国内镜像源，删除yarn.lock，重新yarn install
