### ISSUE TITLE
account页面分页或者滚动异常(修改部分参数无法显示分页或无法滚动查看table数据)

### ISSUE THREAD

**Issue by zxiaozhou** [anncwb/vue-vben-admin#1111]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ✅] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

1. 打开页脚https://vvbin.cn/next/#/system/account页面分页直接无法显示
<img width="1681" alt="1" src="https://user-images.githubusercontent.com/62740686/130327420-e3f5114d-f460-42a2-ac74-c7329854a54a.png">

2. 设置table canResize为false时每页数量调大(演示站调到每页100)，https://vvbin.cn/next/#/system/account分页信息不显示，并且无法滚动页面查看table全部数据
<img width="1681" alt="2" src="https://user-images.githubusercontent.com/62740686/130327412-c108e6a6-d5a2-4217-b1e9-db4b6f56baf3.png">

## System Info

- Operating System: vben-admin 2.7.1
- Node version: v14.17.4
- Package manager (npm/yarn/pnpm) and version:  yarn 1.22.10

**Comment by mynetfan** [comment]
basicTable的canResize和PageWrapper的fixedHeight不可同时使用（2.7.1版本会在控制台针对此情况输出一个warn）。请解决此问题后再试
