### ISSUE TITLE
Table 的表尾行合计列对不齐的问题

### ISSUE THREAD

**Issue by im-qrh** [anncwb/vue-vben-admin#1112]
![image](https://user-images.githubusercontent.com/82321234/130339990-aa603f25-e91e-435b-a7e4-59969ae409f2.png)

Table 的表尾行合计列对不齐。图片显示的是 Vben Admin 中 组件-Table-表尾行合计 ，

Table 组件 使用 `canResize: true` 会没这问题，但是我的数据没那么多，不需要自适应高度，希望 `canResize: false`时 合计行右侧的滚动条也会没有。

**Comment by mynetfan** [comment]
请合并commit
