### ISSUE TITLE
新功能申请

### ISSUE THREAD

**Issue by kamaellee** [anncwb/vue-vben-admin#1113]
请求在 useGo 方法下新增带参数跳转的方法，如已有此方法请见谅，一下没找到，谢谢采纳，祝 vben 越做越好。

**Comment by mynetfan** [comment]
useGo返回的go函数功能类似vue-router的push，其参数可以接收目标路由的path字符串，也可以是一个对象。用法可以参考：
https://next.router.vuejs.org/zh/guide/essentials/navigation.html
