### ISSUE TITLE
Table 的 getSelectRowKeys()不能双向数据绑定吗？

### ISSUE THREAD

**Issue by fengbindev** [anncwb/vue-vben-admin#1117]
版本：2.7.1
场景：我使用getSelectRowKeys().length==0 判断是否禁用按钮，发现当我在同一行数据点击两次后，getSelectRowKeys()为空，但是按钮还是可以点击，请问有别的方法处理吗？

![image](https://user-images.githubusercontent.com/28595220/130453427-4933cc80-409b-4858-96f6-1c1e1fb8106e.png)

初始界面
![image](https://user-images.githubusercontent.com/28595220/130453164-a6aa6a7a-6863-4e1f-9e66-4858e1f46c72.png)

点击一次行数据后，按钮正常可以点击。

同一行数据点击两次，按钮还是可以点击，正常应该禁用
![image](https://user-images.githubusercontent.com/28595220/130453267-d0044512-8b27-4c93-9d3d-e5c4d65f8063.png)

经测试：
点击前面的checbox正常，点击行数据就不正常。
使用clearSelectedRowKeys() 也没有用

**Comment by fengbindev** [comment]
使用clearSelectedRowKeys() 也没有用

**Comment by mynetfan** [comment]
换成 ``` getRowSelection().selectedRowKeys.length === 0 ```试试

**Comment by fengbindev** [comment]
> 换成 `getRowSelection().selectedRowKeys.length === 0`试试
你好， `getRowSelection().selectedRowKeys.length === 0`可以做到，但是因为类型问题会有警告，虽然不影响结果，但是看着实在难受，强迫症。我不太清楚这是不是个bug
![image](https://user-images.githubusercontent.com/28595220/130542926-cb99cf1e-62fa-410c-8156-93ddffd75945.png)

**Comment by mynetfan** [comment]
getRowSelection()?.selectedRowKeys?.length === 0
