### ISSUE TITLE
登录超时处理，errorMessageMode配置未生效

### ISSUE THREAD

**Issue by AndroidMilk** [anncwb/vue-vben-admin#1119]
在未连接服务器的情况下，点击登录，responseInterceptorsCatch方法调用拦截错误信息处理，这里errorMessageMode取的值是none，控制台打印config发现errorMessageMode值为none，但是发现requestOptions配置里errorMessageMode为message，请问未得到服务器响应处理前错误的拦截处理errorMessageMode是在哪里配置？
![image](https://user-images.githubusercontent.com/13392610/130543522-235dd747-c8ac-4e81-8400-1d80bd58bd50.png)
![image](https://user-images.githubusercontent.com/13392610/130543575-23d0761e-870c-4fde-b627-6f00b1da1536.png)
![image](https://user-images.githubusercontent.com/13392610/130543596-aa91ebb4-a31c-428c-a7af-92f8dea20701.png)

**Comment by AndroidMilk** [comment]
![image](https://user-images.githubusercontent.com/13392610/130547063-5ab333c1-3004-4d19-bb84-758fd2c44da8.png)
添加这段方法可以解决错误显示异常的问题

**Comment by AndroidMilk** [comment]
还是想请教一下现在处理错误的逻辑是请求之前拦截统一处理，请求响应之后统一处理，那么业务处理回调还有必要去捕捉cache异常错误吗？

**Comment by mynetfan** [comment]
读代码要读全。
你截图里的errorMessageMode: 'message' 这个是默认配置，默认配置可以被每一次请求携带的配置所覆盖。
而login页面调用login接口的代码如下：
```
      const userInfo = await userStore.login(
        toRaw({
          password: data.password,
          username: data.account,
          mode: 'none', //不要默认的错误提示
        })
      );
```
其中`mode`参数为'none'，而在`src/store/modules/user.ts`中可以看到，实际上这个mode参数被继续传递给了loginApi：
```
const data = await loginApi(loginParams, mode);
```
继续跟进`src/api/sys/user.ts`看一下，会发现mode最终被传递给了defHttp的post方法中的options：
```
defHttp.post<LoginResultModel>(
    {
      url: Api.Login,
      params,
    },
    {
      errorMessageMode: mode,
    }
  )
```
这个参数会覆盖默认的errorMessageMode，所以你才会在console中看到errorMessageMode的值为none


这里本来就只是一个演示，一般接口的调用如果出错会直接使用默认的配置弹出提示（errorMessageMode: 'message'），而登录页面则演示了如何禁止默认的提示，然后自己catch这个错误来给出自定义的提示。当然，此处也可以添加更多的逻辑，比如在catch中判断登录异常的具体类型以及服务器返回的错误代码（如果有的话），来决定是否需要显示验证码或者要求手机短信验证等等
