### ISSUE TITLE
点击登录出现 "服务不可用，服务器暂时过载或维护!" 提示

### ISSUE THREAD

**Issue by sbcdyb123** [anncwb/vue-vben-admin#112]
在公司里的电脑拉去代码后,启动项目,然后点击登录是可以进入主界面的,但是在家里尝试的时候就报了这个提示 , 不是用的mock吗?是mockserver出问题了吗🤔

**Comment by sbcdyb123** [comment]
![9 1}MF`MAVQGBC63XP(~T3L](https://user-images.githubusercontent.com/34590929/100733418-1c5ae100-3409-11eb-8e95-3579b328fd40.png)

**Comment by sbcdyb123** [comment]
![9 1}MF`MAVQGBC63XP(~T3L](https://user-images.githubusercontent.com/34590929/100733672-7cea1e00-3409-11eb-8007-d1ae29fec1a7.png)

**Comment by sbcdyb123** [comment]
![$4W51 5C~57W%YQ%JU%ZKB4](https://user-images.githubusercontent.com/34590929/100739726-7dd37d80-3412-11eb-8350-cd94fe1287ab.png)

**Comment by anncwb** [comment]
能给个复现步骤？没遇到这个

**Comment by sbcdyb123** [comment]
啥代码都没动 , 就是yarn serve以后就是这个 @anncwb

**Comment by anncwb** [comment]
可能是依赖没装好，尝试删除依赖和lock文件重装试试

**Comment by sbcdyb123** [comment]
好的,我去试试,谢谢
