### ISSUE TITLE
浏览器打开两个登录页，一个登录成功后，另外一个还在登录页

### ISSUE THREAD

**Issue by FollowTrend** [anncwb/vue-vben-admin#1124]
![}4~5O GAZO CJBCA)7@5M56](https://user-images.githubusercontent.com/40554571/130766877-4b9a9a45-99b5-499b-a671-c16e9c12e25a.png)
![G)% `SPN19MQDEVTRWM`1F6](https://user-images.githubusercontent.com/40554571/130766930-d25724bb-6f2d-456d-88c4-b30aebe20d7f.png)

希望尽快修改更新

**Comment by FollowTrend** [comment]
框架的配置也没有同步

**Comment by mynetfan** [comment]
最新代码已处理，按F5刷新页面即可同步状态
