### ISSUE TITLE
上传组件打包后 上传失败

### ISSUE THREAD

**Issue by sunnylearn** [anncwb/vue-vben-admin#1139]

**Comment by liyaxu123** [comment]
我也遇到这个问题了，请问有解决方案吗？

**Comment by anncwb** [comment]
关闭mock后在尝试

**Comment by mynetfan** [comment]
未能提供更多信息，此Issue关闭。如有进一步的反馈，请重新打开此Issue

**Comment by zhuoshengjie** [comment]
同样的错误，dev下可以上传接口可以，打包后上传组件报错TypeError: l.upload.addEventListener is not a function
    at :5000/assets/vendor.190487bc.js:56
    at new Promise (<anonymous>)
    at xhr (:5000/assets/vendor.190487bc.js:56)
    at dispatchRequest$1

**Comment by zhuoshengjie** [comment]
有没有不关闭 mock的方法

**Comment by lorry0508** [comment]
Uncaught (in promise) TypeError: a.upload.addEventListener is not a function我也遇到这个问题了

**Comment by hqzxjczx** [comment]
> 
有的；
在 node_modules/mockjs/dist/mock.js 第 8312 行 和 node_modules/mockjs/src/mock/xhr/xhr.js 第 216 行;this.custom.xhr = xhr 的后面添加如下代码
 MockXMLHttpRequest.prototype.upload = xhr.upload;
