### ISSUE TITLE
是否考虑把moment替换为dayjs

### ISSUE THREAD

**Issue by PineSongCN** [anncwb/vue-vben-admin#114]
现在moment作者也推荐替换为dayjs，体积更小，使用基本一样。

**Comment by anncwb** [comment]
使用momentjs的原因是ant-design-vue内已经有了。所以就没换。就算换了dayjs，moment打包还是会在。这个会等antdv更换呢dayjs或者vite有相应的插件出来后替换

**Comment by yanjiFan1** [comment]
antd2升级得到antdv3 dayjs怎么兼容
