### ISSUE TITLE
JsonPreview 组件使用报错

### ISSUE THREAD

**Issue by fengbindev** [anncwb/vue-vben-admin#1146]
![image](https://user-images.githubusercontent.com/28595220/131247933-3bc735a1-caae-4314-8ad5-e264f96fac57.png)
![image](https://user-images.githubusercontent.com/28595220/131248005-a3143fe3-df93-4978-ae32-5c20b73bd1a6.png)

**Comment by mynetfan** [comment]
测试正常。https://vvbin.cn/next/#/comp/editor/json
选中“JSON数据”按钮后点击“获取数据”
