### ISSUE TITLE
我自定义了一个Form组件，功能是一个用户选择框，但是提示ReferenceError: Cannot access 'BasicTable' before initialization

### ISSUE THREAD

**Issue by accpman** [anncwb/vue-vben-admin#1149]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

我自定义了一个Form组件，功能是一个用户选择框，但是提示ReferenceError: Cannot access 'BasicTable' before initialization
![image](https://user-images.githubusercontent.com/4446237/131466068-bee23f0f-cf9f-4b4a-a979-76dd8fa402a5.png)

### 复现 Bug
<template>
    <div>
        <a-row class="j-select-row" type="flex" :gutter="8">
            <a-col class="left" :class="{'full': !buttons}">
                <a-select ref="select" :options="selectOptions" style="width: 100%;">

                </a-select>
            </a-col>
            <a-col v-if="buttons" class="right">
                <a-button type="primary" @click="handSelect">选择</a-button>
            </a-col>
        </a-row>
        <BasicModal v-bind="$attrs" @register="registerModal" title="职务选择" width="40%" :height="500" :minHeight="500">
            <BasicTable @register="registerTable" :rowSelection="rowSelection"></BasicTable>
        </BasicModal>
    </div>
</template>
<script lang="ts">
    import {defineComponent, ref, reactive} from 'vue';
    import {BasicTable, useTable} from '/@/components/Table';
    import {BasicModal, useModalInner} from '/@/components/Modal';
    import {getPositionList} from '/@/api/common/api';
    import {propTypes} from "/@/utils/propTypes";
    import {useRuleFormItem} from "/@/hooks/component/useFormItem";
    import {useAttrs} from "/@/hooks/core/useAttrs";

    export default defineComponent({
        name: 'JSelectPosition',
        components: {
            BasicModal,BasicTable
        },
        inheritAttrs: false,
        props: {
            value: propTypes.oneOfType([
                propTypes.object,
                propTypes.array
            ]),
            buttons: propTypes.bool.def(true),
        },
        emits: ['options-change', 'change'],
        setup(props, {emit, refs}) {
            const [registerModal, {setModalProps, closeModal}] = useModalInner();
            const emitData = ref<any[]>([]);
            const checkedKeys = ref<Array<string | number>>([]);
            let selectOptions = reactive([]);
            const attrs = useAttrs();
            const [state] = useRuleFormItem(props, 'value', 'change', emitData);
            const columns = [
                {
                    title: '职务编码',
                    dataIndex: 'code',
                    width: 40,
                    align: 'left',
                },
                {
                    title: '职务名称',
                    dataIndex: 'name',
                    width: 40,
                },
                {
                    title: '职务等级',
                    dataIndex: 'postRank_dictText',
                    width: 40
                }
            ];
            /**
             * 选择列配置
             */
            const rowSelection = {
                type: 'checkbox',
                columnWidth: 20,
                selectedRowKeys: checkedKeys,
                onChange: onSelectChange
            }
            //注册table数据
            const [registerTable, {reload}] = useTable({
                api: getPositionList,
                columns,
                useSearchForm: false,
                showTableSetting: false,
                bordered: true,
                showIndexColumn: false,
                pagination: true,
                maxHeight: 200
            });

            /**
             * 列表选择事件
             */
            function onSelectChange(selectedRowKeys: (string | number)[]) {
                checkedKeys.value = selectedRowKeys;
            }

            function handSelect() {
                setModalProps({
                    visible: true
                })
            }
            return {
                state,
                attrs,
                selectOptions,
                rowSelection,
                handSelect,
                registerTable,
                registerModal
            };
        },
    });
</script>
<style lang="less" scoped>
    .j-select-row {
        @width: 82px;

        .left {
            width: calc(100% - @width - 8px);
        }

        .right {
            width: @width;
        }

        .full {
            width: 100%;
        }

        ::v-deep(.ant-select-search__field) {
            display: none !important;
        }
    }
</style>

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by mynetfan** [comment]
Modal内部组件只会在显示Modal时才会渲染

**Comment by i7eo** [comment]
> Modal内部组件只会在显示Modal时才会渲染

所以modal内使用form，应该怎么样避免这个报错呢？
