### ISSUE TITLE
表单FormSchema的ifShow隐藏字段后，getFieldsValue依然能获取其表单的值

### ISSUE THREAD

**Issue by xiyanglove** [anncwb/vue-vben-admin#1157]
### 表单FormSchema的ifShow问题

动态表单使用Switch 用ifShow隐藏了字段后，调用getFieldsValue方法依然能获取到隐藏后字段的值，
这里如果是用的ifShow，在删除了dom后是否应该删除对应表单字段的值？

**Comment by mynetfan** [comment]
ifShow只是不渲染FormItem，不会影响FieldsValue
