### ISSUE TITLE
Description 是不是也可以搞成可编辑？

### ISSUE THREAD

**Issue by emxxjnm** [anncwb/vue-vben-admin#1158]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by mynetfan** [comment]
没有这个计划
