### ISSUE TITLE
路由还存在几个问题。

### ISSUE THREAD

**Issue by kailong321200875** [anncwb/vue-vben-admin#116]
1. 现在 所有路由 右键刷新的时候都会到404去，没有重定向。
2. 以 多级菜单 栏目为例，Menu2 栏目不管如何关闭，缓存依旧存在。

**Comment by anncwb** [comment]
b884654761f93455014fd1dcb0e40c030d8fb360. 这个提交应该已经修复了该问题。你代码可能不是最新的

**Comment by kailong321200875** [comment]
我是今天早上看的在线预览地址的。。现在刷新是没问题，但是第二个问题依然存在。。

**Comment by kailong321200875** [comment]
> [b884654](https://github.com/anncwb/vue-vben-admin/commit/b884654761f93455014fd1dcb0e40c030d8fb360). 这个提交应该已经修复了该问题。你代码可能不是最新的

我是今天早上看的在线预览地址的。。现在刷新是没问题，但是第二个问题依然存在。。

**Comment by anncwb** [comment]
预览可能不是最新的，我后面在更新下预览

**Comment by kailong321200875** [comment]
> 预览可能不是最新的，我后面在更新下预览

顺便问个技术问题：
![image](https://user-images.githubusercontent.com/32283845/101300251-ee91f400-386f-11eb-8530-a95f06485c81.png)
antdv 的 table 是不支持tsx这种插槽写法吗。用模版语法好好的，可是换成tsx就不行了。是我哪里写错了还是。。

**Comment by anncwb** [comment]
vite 是可以支持这种写法

**Comment by kailong321200875** [comment]
> vite 是可以支持这种写法

哦，我懂了，是我的问题。脑子一直没转过来。
