### ISSUE TITLE
本项目中下载依赖如果有assets文件，编译后会被删掉，导致项目引入css文件提示找不到

### ISSUE THREAD

**Issue by zxiaozhou** [anncwb/vue-vben-admin#1165]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ✅] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug
1. bpmn js有部分css文件需要单独引入，文件在bpmn-js/dist/assets下，但本项目下载依赖编译后文件被删掉，，css文件也找不到了。。引入也提示找不到文件
```
import "bpmn-js/dist/assets/diagram-js.css";
import "bpmn-js/dist/assets/bpmn-font/css/bpmn.css";
```

### Reproduction
1. 使用yarn添加依赖bpmn-js；
2. 下载成功开始编译时查看文件发现bpmn-js/dist/assets中css文件存在
3. 编译后再次查看，assets文件夹被删除，同时启动时vue提示bpmn-js/dist/assets/diagram-js.css样式文件找不到

## System Info

- Operating System: mac 11.5.2
- Node version: v14.17.5
- Package manager (npm/yarn/pnpm) and version: yarn 1.22.11

**Comment by mynetfan** [comment]
assets  目录下均为自动生成的文件，不会保留自定义文件。如果需要额外打包一些固定的文件，请将文件复制到public目录下。
参考[vite文档相关说明](https://cn.vitejs.dev/guide/assets.html#the-public-directory)
