### ISSUE TITLE
本项目中下载依赖如果有assets文件，编译后会被删掉，导致项目引入css文件提示找不到(声明下是node_modules里面依赖的目录)

### ISSUE THREAD

**Issue by zxiaozhou** [anncwb/vue-vben-admin#1169]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ✅] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug
1. 首先说明下，，我说的assets是依赖里面自己的目录，非自己创建，非自己创建
![image](https://user-images.githubusercontent.com/62740686/132278996-d7ee49bb-d584-441a-a385-b388b6474f2f.png)

2. bpmn js有部分css文件需要单独引入，文件在bpmn-js/dist/assets下，但本项目下载依赖编译后文件被删掉，，css文件也找不到了。。引入也提示找不到文件
```
import "bpmn-js/dist/assets/diagram-js.css";
import "bpmn-js/dist/assets/bpmn-font/css/bpmn.css";
```

### Reproduction
1. 使用yarn添加依赖bpmn-js；
2. 下载成功开始编译时查看文件发现bpmn-js/dist/assets中css文件存在
3. 编译后再次查看，assets文件夹被删除，同时启动时vue提示bpmn-js/dist/assets/diagram-js.css样式文件找不到

## System Info

- Operating System: mac 11.5.2
- Node version: v14.17.5
- Package manager (npm/yarn/pnpm) and version: yarn 1.22.11

**Comment by mynetfan** [comment]
你添加的bpmn-js什么版本？我测试添加的8.7.3dist目录下没有assets

**Comment by zxiaozhou** [comment]
@mynetfan 
1. 我的就是8.7.3..
2. 有目录的，，没目录的原因是添加依赖后有个编译过程，，编译后就被删掉了，，
3. 你可以删掉项目yarn.lock文件和node_modules目录，全量下载一次(此时编译时间会很长，有空闲去看见没编译时是有文件的)
4. 下面截图是我在桌面上直接运行yarn add bpmn-js下载依赖的截图
![image](https://user-images.githubusercontent.com/62740686/132382394-cef291a8-ed0c-426c-aca5-0ec944f7eb20.png)

**Comment by mynetfan** [comment]
yarn remove，搜索`.yarnclean`文件中的assets（大概在第12行），删掉它，然后重新yarn add

**Comment by VVGR** [comment]
.yarnclean这个文件完全没有必要
