### ISSUE TITLE
希望可以实现可拖拽排序的表格

### ISSUE THREAD

**Issue by luger1990** [anncwb/vue-vben-admin#1173]
希望可以增加可拖拽排序的表格，因为业务经常用，比如焦点图拖拽排序。功能类似于:
https://ant.design/components/table-cn/#components-table-demo-drag-sorting-handler

**Comment by luger1990** [comment]
请问有计划加入该功能吗

**Comment by mynetfan** [comment]
已有类似Issue: #1005
