### ISSUE TITLE
使用ApiSelect 报TypeError: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by huoxiangdong** [anncwb/vue-vben-admin#1175]
![image](https://user-images.githubusercontent.com/18095882/132613159-fa1ec7af-64a2-4c57-80b5-97858901d2ca.png)
使用ApiSelect组件,选择值后,报以下错误
![image](https://user-images.githubusercontent.com/18095882/132613340-cb5fc6f4-fd14-4716-97eb-255a19549b42.png)
![image](https://user-images.githubusercontent.com/18095882/132613353-b6caa5f2-159d-4643-a81c-bb54677a3c90.png)

发现ApiSelect组件修改props.value类型, 就不报错了
![image](https://user-images.githubusercontent.com/18095882/132617095-4cd52a5b-c9bd-4d4c-8af1-9df417d6a5df.png)

**Comment by xqfz** [comment]
我在测试可编辑行（/#/comp/table/editRowTable）时也发现这个问题，跟踪发现开发模式下校验value的type出错（assertType中valid = value instanceof type出错），production下不做这个检查所以不出错。（value值是字符串，但与propTypes.object比较时出错）

**Comment by hirelev** [comment]
vue-types版本的问题   4.0.2版本是OK的
