### ISSUE TITLE
打包后, CardGrid组件不显示

### ISSUE THREAD

**Issue by huoxiangdong** [anncwb/vue-vben-admin#1176]
如图，打包后会消失，开发模式下是正常的
![image](https://user-images.githubusercontent.com/18095882/132626681-4f2c0e5d-7c2a-4024-bc03-acf7cc9ab371.png)

**Comment by huoxiangdong** [comment]
打包好像没有转译
![image](https://user-images.githubusercontent.com/18095882/132636191-cd1b87e7-b9a6-4e72-8c12-78e1b69e9ed6.png)

**Comment by mynetfan** [comment]
未能重现。请尝试在Demo中重现此问题，然后告诉我们具体的重现方法

**Comment by fengshengchang** [comment]
@huoxiangdong 这个问题最后是怎么解决的？我也遇到了
