### ISSUE TITLE
table绑定expandedRowKeys属性操作无效

### ISSUE THREAD

**Issue by lsqGitHub716** [anncwb/vue-vben-admin#1188]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

![image](https://user-images.githubusercontent.com/65587928/132827707-a96d2050-9482-4549-843a-498bb71e4e09.png)

table表格绑定的expandedRowKeys会被封装的替换掉，导致不能手工处理expandedRowKeys的属性值

### 复现 Bug
1.创建table表格，绑定```:expandedRowKeys="expandedRowKeys" ```
2.操作expandedRowKeys的值，表格没有变化

## 系统信息

- 操作系统:window
- Node 版本:.14.8
- 包管理器 (npm/yarn/pnpm) 及其版本:1.22.11

**Comment by mynetfan** [comment]
要使用这个属性，必须将isTreeTable设为false。isTreeTable如果为true，内部会接管这个属性以便控制展开
