### ISSUE TITLE
官网文档和实际组件使用不符合问题反馈！

### ISSUE THREAD

**Issue by vipv21** [anncwb/vue-vben-admin#1189]
vben官网文档和实际项目中组件不符合之处：

以下是目前使用中发现文档和使用组件不符合的几个反馈：

### 1、TableAction组件

- actions
```
  // 是否显示分隔线，v2.0.0+
  divider?: boolean;
```
反馈： divider 设置不生效，并且actions内同时设置2个button导致按钮之间无间距

### 2、PageWrapper组件

- slots无效
```
leftFooter	PageFooter 左侧区域
rightFooter	PageFooter 右侧区域
```
反馈：以上name设置无效，查看官网源码得知组件本身不支持该名称使用,源码中支持：extra使用。

### 3、 Upload组件

- props-accept属性有问题
```
accept	string[]	-	-	限制上传格式 ['.doc,','.docx','.xlsx']
```
反馈：accept的格式设置无效。按照文档格式使用有误，正确格式为['doc,','docx','xlsx']则正常

---
最后建议： 

1、增加文档的同步更新和文档反馈功能保持和官网组件同步更新。

2、增加文档搜索功能、文档顶部不要强制吸顶导致使用浏览器自带页面查找功能(ctrl+F)输入框被遮挡无法使用。

**Comment by glorydreamtop** [comment]
ctrl+F还能被dom节点遮挡？？？？

**Comment by mynetfan** [comment]
1、这是一个BUG，之前某一次commit造成了divider无效的问题，不属于文档不同步；现已修复
2、没有问题，Demo例子：src/views/demo/page/form/high/index.vue
3、这个确实是Bug。已修复，并更新了文档

**Comment by vipv21** [comment]
> ctrl+F还能被dom节点遮挡？？？？

试了一下360浏览器会存在这个问题，属于浏览器问题。可以忽略额忽略   :joy:
