### ISSUE TITLE
vue-vben-admin20210911版run dev提示缺少依赖@vueuse/shared

### ISSUE THREAD

**Issue by xqfz** [anncwb/vue-vben-admin#1190]
vue-vben-admin20210911 11:08:34版run dev时提示缺少依赖@vueuse/shared：

Cropper.vue中import { useDebounceFn } from '@vueuse/shared';

1）改成import { useDebounceFn } from '@vueuse/code';
2）package.json中引入"@vueuse/shared": "^6.3.2",
均可解决问题

**Comment by mynetfan** [comment]
package.json中的@vueuse/core在安装时也会带上@vueuse/shared，无需额外添加@vueuse/shared依赖。
你的IDE提示缺少依赖，请先运行yarn install安装所有依赖后再试

**Comment by xqfz** [comment]
我用的是npm，没用yarn 。试了下，确实会自动引入。
![image](https://user-images.githubusercontent.com/19511579/132949075-eaefa8a1-f857-4df1-bee7-a3ba563987bb.png)

我再试试npm看看。

**Comment by xqfz** [comment]
npm不行，node_modules全部删除了，package-lock.json没有的情况下npm install（开了VPN）。
npm run dev出现@vueuse/shared找不到错误
![image](https://user-images.githubusercontent.com/19511579/132952955-59310046-17b2-4432-9ce3-145ec773aad6.png)

奇怪，生成的package-lock.json中有@vueuse/shared，不知道哪里不对。

packages部分如下图：
![image](https://user-images.githubusercontent.com/19511579/132953173-5a1aa59f-eade-41cb-afd6-78e6cd6921fc.png)

dependencies部分如下图：
![image](https://user-images.githubusercontent.com/19511579/132953192-f86e1cc2-0359-4073-86ab-21b41969ec8d.png)

**Comment by mynetfan** [comment]
那就换成@vueuse/core
