### ISSUE TITLE
能全局配置ant组件的属性么？

### ISSUE THREAD

**Issue by nirvana72** [anncwb/vue-vben-admin#1192]
有时候比较喜欢直接用ant的组件， 而不是用vben封装好的

比如我喜欢 a-table size="small",  有没有办法在某个地方全局地配置这个属性， 而不用每个table标签上写size

**Comment by mynetfan** [comment]
这种问题不应当查看antdv的文档吗？

**Comment by nirvana72** [comment]
看了， 可能是水平一般，没找到方法， ant 有一个ConfigProvider 的组件， 但好像不支持我需要的功能， 所以在这里找找帮助

**Comment by agileago** [comment]
@nirvana72 ant没有全局配置的，你可以封装一个高阶组件
