### ISSUE TITLE
页面有icon组件时，热更新 出现 Cannot access 'Icon' before initialization错误

### ISSUE THREAD

**Issue by Corgis** [anncwb/vue-vben-admin#1194]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ✔] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ✔] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

当组件中有引入 <Icon icon="xxx" :size="30" /> 组件，修改页面中的随意内容 热跟新会报错
Cannot access 'Icon' before initialization 且热更新失败 要重新刷新页面

### 复现 Bug

随便找个有引入Icon的页面 然后修改内容保存，控制台可见错误

## 系统信息

- 操作系统: win10家庭版
- Node 版本: v14.15.0
- 包管理器 (npm/yarn/pnpm) 及其版本: yarn  1.22.10

**Comment by glorydreamtop** [comment]
#480 
有人问过这个问题，但凡你先搜搜历史issue

**Comment by Corgis** [comment]
> #480
> 有人问过这个问题，但凡你先搜搜历史issue

本人搜过也看到了一样的issue 是四月份被关闭的，那正常最新版本应该已经是合并了修复代码的，可这个问题还在复现
![image](https://user-images.githubusercontent.com/13865529/133034643-09151059-31ac-4be2-8a20-8073af4b51bb.png)
而且 如果你说的是这个解决方法的话 那是有问题的

**Comment by anncwb** [comment]
我在跟踪下，有复现步骤可以发给我下

**Comment by Corgis** [comment]
> 我在跟踪下，有复现步骤可以发给我下

Vben Admin下  功能 -->图标菜单， src\views\demo\feat\icon\index.vue文件随便改个内容再保存就会报错 热更新失效
报错如下：
![image](https://user-images.githubusercontent.com/13865529/133181090-7aef2f10-1fa5-451f-853c-52c61dacafb9.png)

**Comment by t596502** [comment]
更新最新版后我这边也出现了这个问题

**Comment by mynetfan** [comment]
请各位测试一下此commit：https://github.com/anncwb/vue-vben-admin/commit/5af452754b0567539e6ba6899ce91fa2914a4829

如果已解决，请帮忙主动关闭此Issue反馈

**Comment by mynetfan** [comment]
请各位测试一下此commit：https://github.com/anncwb/vue-vben-admin/commit/5af452754b0567539e6ba6899ce91fa2914a4829
如果已解决，请帮忙主动关闭此Issue反馈
@t596502 @Corgis @glorydreamtop @ujn-bin

**Comment by Corgis** [comment]
感谢反馈，经测试已修复，关闭

**Comment by 1668535323** [comment]
能说下解决思路吗？精简版这个问题还在

**Comment by 1668535323** [comment]
> 感谢反馈，经测试已修复，关闭

能说下解决思路吗？精简版这个问题还在

**Comment by doraemonxxx** [comment]
The bug still occurred on my end when I saved BaseSetting.vue

Is there a workaround to fix the issue?

![image](https://user-images.githubusercontent.com/88119911/168670278-a50bbcee-d5a2-4c88-b885-7691a8bb80e4.png)

**Comment by doraemonxxx** [comment]
> > Thanks for the feedback, it has been fixed after testing, close
> 
> Can you tell me a solution? Lite version this problem still exists

I already fixed my issue. Pls, refer to the fix in #376 . If you found some abnormal behaviour after using the code. then remove it

**Comment by zam157** [comment]
我在更新后还是会有HMR问题. 仔细研究了一下发现作者在`/@/components/Icon/index.ts`中做了统一导出处理, 也就是把三个.vue文件引入到一个ts文件下统一导出. 

```js
import Icon from './src/Icon.vue';
import SvgIcon from './src/SvgIcon.vue';
import IconPicker from './src/IconPicker.vue';

export { Icon, IconPicker, SvgIcon };

export default Icon;
```

这样做可能可以提升一些DX, 但是也导致了这个bug. 粗略看下来至少在我所使用的vite版本(2.5.10)下.vue文件还不能这样统一导出

解决办法也很简单, 找到所有import了这个ts导出的语句, 统一改成对.vue文件单独引入

例如:

`import { Icon } from '/@/components/Icon';` 改为 `import Icon from '/@/components/Icon/src/Icon.vue';`

**Comment by LiconaMoyi** [comment]
> 我在更新后还是会有HMR问题. 仔细研究了一下发现作者在`/@/components/Icon/index.ts`中做了统一导出处理, 也就是把三个.vue文件引入到一个ts文件下统一导出.
> 
> ```js
> import Icon from './src/Icon.vue';
> import SvgIcon from './src/SvgIcon.vue';
> import IconPicker from './src/IconPicker.vue';
> 
> export { Icon, IconPicker, SvgIcon };
> 
> export default Icon;
> ```
> 
> 这样做可能可以提升一些DX, 但是也导致了这个bug. 粗略看下来至少在我所使用的vite版本(2.5.10)下.vue文件还不能这样统一导出
> 
> 解决办法也很简单, 找到所有import了这个ts导出的语句, 统一改成对.vue文件单独引入
> 
> 例如:
> 
> `import { Icon } from '/@/components/Icon';` 改为 `import Icon from '/@/components/Icon/src/Icon.vue';`
  you are right
