### ISSUE TITLE
没有类似 ElementUI 的prompt 的组件吗

### ISSUE THREAD

**Issue by Binaryify** [anncwb/vue-vben-admin#1195]
自己用模态框实现成本比较高，有 prompt 组件会比较方便

**Comment by anncwb** [comment]
popcomfirm

**Comment by Binaryify** [comment]
我指的是以方法调用，弹出一个输入框并用promise返回用户输入内容的prompt, 
类似原生的这个
![image](https://user-images.githubusercontent.com/12221718/133180293-9d22cf4e-ef88-4963-827c-7fa3a5b161cb.png)

popcomfirm并没有这种效果
