### ISSUE TITLE
setDrawerProps设置showFooter属性

### ISSUE THREAD

**Issue by lsqGitHub716** [anncwb/vue-vben-admin#1197]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

``` setDrawerProps({showFooter:true});```

### 复现 Bug
1.配置表格
2.配置抽屉表单
3.通过上面方式设置showFooter属性后，表格操作
4.点击新增，再点击某个数据的编辑，点击打开抽屉，再关闭，再点击编辑打开抽屉后，按钮没有了

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by mynetfan** [comment]
提供具体代码。没能理解所描述的情况

**Comment by lsqGitHub716** [comment]
1.配置```setDrawerProps({showFooter:true})```;
![image](https://user-images.githubusercontent.com/65587928/133179510-b493bc53-8c9d-48c4-9813-f95bc920883d.png)
2.新增/编辑打开方法
![image](https://user-images.githubusercontent.com/65587928/133179706-1fb2f891-8d18-47a9-9007-7894efa06748.png)
3.点击新增，打开抽屉，右下角显示按钮，关闭抽屉；
4.再点击编辑，打开抽屉，右下角显示按钮，关闭抽屉；
![image](https://user-images.githubusercontent.com/65587928/133179553-be2b1821-fce8-49d3-b648-07df698668fe.png)
5.再次点击编辑，打开抽屉，右下角按钮没有了；
![image](https://user-images.githubusercontent.com/65587928/133179661-60c1cfa7-648d-4840-ae65-90d84d508b7b.png)

**Comment by mynetfan** [comment]
同样代码未能重现

**Comment by mynetfan** [comment]
未能重现且没有提供更多信息，此Issue关闭。如需进一步处理，请重新打开此Issue

**Comment by hejingzhou** [comment]
我也遇到这个问题了
