### ISSUE TITLE
表单配置建议增加一个数组转字符串配置

### ISSUE THREAD

**Issue by accpman** [anncwb/vue-vben-admin#1198]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

### 描述 Bug
例如表单中有一个多选下拉框，默认返回是数组，有时候后台习惯已字符串接收，能否在form配置里添加一个属性，提交的时候对数组进行转换

**Comment by mynetfan** [comment]
不会这样处理。你完全可以自行在提交之前对表单数据做进一步的转换

**Comment by accpman** [comment]
> 不会这样处理。你完全可以自行在提交之前对表单数据做进一步的转换

按你的逻辑封装fieldMapToTime也是不必要的，我也可以对表单进行处理提交2个字段，封装就是为了方便，减少不必要的代码

**Comment by mynetfan** [comment]
你说的没错，fieldMapToTime本来就不是必要的。项目有些功能是大家贡献的PR，并不全是一开始就有计划。你说的这个数组转字符串配置，目前只有你一个人反馈，并且后端接受json数据中的数组也很常见，以目前开发组的时间安排来看，不会花时间在这个问题上，所以才关闭了这个Issue。如果你觉得有必要而且愿意分享你的代码，你也可以提交PR，vben感谢任何人的贡献。
