### ISSUE TITLE
proxy代理失败，请帮助我看看哪里错误

### ISSUE THREAD

**Issue by EasonQwQ** [anncwb/vue-vben-admin#1204]
这是我的 .env.development 文件，我已经设置了对baseUrl 转发
```
# Whether to open mock
VITE_USE_MOCK = true
# public path
VITE_PUBLIC_PATH = /

# Cross-domain proxy, you can configure multiple
# Please note that no line breaks
# ["/basic-api","http://localhost:3000"]
VITE_PROXY = [["/basic-api","http://localhost:3000"],['/baseUrl','http://124.70.183.169:3089'],["/upload","http://localhost:3300/upload"]]
# VITE_PROXY=[["/api","https://vvbin.cn/test"]]

# Delete console
VITE_DROP_CONSOLE = false

# Basic interface address SPA
VITE_GLOB_API_URL=/basic-api

# File upload address， optional
VITE_GLOB_UPLOAD_URL=/upload

# Interface prefix
VITE_GLOB_API_URL_PREFIX=

```

这是我的axios配置
```
export const realHttp = createAxios({
  requestOptions: {
    apiUrl: '/baseUrl',
  },
});
```

这是我的请求
```
enum Api {
  GetShares = '/shares',
}

/**
 * @description: Get user menu based on id
 */

export const getShares = (str = '') => {
  return realHttp.get({
    url: Api.GetShares,
    params: str,
  });
};
```

这是console控制台的请求
![image](https://user-images.githubusercontent.com/22360580/133303900-12673011-3701-4697-91da-f4bf6d4daf12.png)

可是请求并没有转发出去，我找了好久并没有原因，请帮助我看看呢

**Comment by MarLion** [comment]
求助 我也一样
我是没有跨域不需要代理

VITE_GLOB_API_URL = http://192.168.1.17:59527

打印出来url也是正确的 但是就是访问本地的

![1631786282(1)](https://user-images.githubusercontent.com/22169300/133592456-93be4fa8-f70b-436c-ab77-ea11a0f90eba.jpg)

@ @

**Comment by chorin959** [comment]
不是代理失败。
而是在vite.config里VITE_PROXY变量获取出来是空字符串。并没有正确读出这个配置。

**Comment by EasonQwQ** [comment]
> 不是代理失败。
> 而是在vite.config里VITE_PROXY变量获取出来是空字符串。并没有正确读出这个配置。

请问怎么修改呢

**Comment by MarLion** [comment]
> 不是代理失败。
> 而是在vite.config里VITE_PROXY变量获取出来是空字符串。并没有正确读出这个配置。

同问求助

**Comment by mynetfan** [comment]
你用浏览器访问  http://124.70.183.169:3089/shares  是否正常？

**Comment by EasonQwQ** [comment]
正常的，上一个回复我的说是vite config没有加载proxy，我在proxy这个函数里面打印了一下，确实，是空的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Netfan ***@***.***&gt;
发送时间: 2021年9月16日 19:56
收件人: anncwb/vue-vben-admin ***@***.***&gt;
抄送: xwk ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[anncwb/vue-vben-admin] proxy代理失败，请帮助我看看哪里错误 (#1204)





 
你用浏览器访问  http://124.70.183.169:3089/shares  是否正常？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EasonQwQ** [comment]
那个服务现在我还没起，马上我回去启动一下，但是我测试的时候这个服务是开启的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Netfan ***@***.***&gt;
发送时间: 2021年9月16日 19:56
收件人: anncwb/vue-vben-admin ***@***.***&gt;
抄送: xwk ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[anncwb/vue-vben-admin] proxy代理失败，请帮助我看看哪里错误 (#1204)





 
你用浏览器访问  http://124.70.183.169:3089/shares  是否正常？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chorin959** [comment]
全部用双引号，用单引号就会出问题。 对于这种JS/TS 工程来说，不识别单引号包裹字符串应该是一种缺陷。

**Comment by EasonQwQ** [comment]
> > 不是代理失败。
> > 而是在vite.config里VITE_PROXY变量获取出来是空字符串。并没有正确读出这个配置。
> 
> 同问求助

用双引号而不是单引号 我的起作用了。

**Comment by EasonQwQ** [comment]
我也认为这应该算一个bug

**Comment by MarLion** [comment]
> > > 不是代理失败。
> > > 而是在vite.config里VITE_PROXY变量获取出来是空字符串。并没有正确读出这个配置。
> > 
> > 
> > 同问求助
> 
> 用双引号而不是单引号 我的起作用了。

请问是只需要将env文件里换成双引号还是要全部换掉啊

**Comment by mynetfan** [comment]
本来，VITE_PROXY的配置只支持双引号，因为会经过JSON.parse转换。但因为没有在文档中提及，且不看源代码的话很可能会像此Issue一样难以找到问题的原因，所以现在已经作了处理，VITE_PROXY的配置支持了单引号：https://github.com/anncwb/vue-vben-admin/commit/067753d490abc1b92eac4783296daec6d4ec3d28
