### ISSUE TITLE
提交表单验证未通过时发生 Uncaught (in promise) 异常

### ISSUE THREAD

**Issue by 2501272126** [anncwb/vue-vben-admin#1206]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ √ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [  √ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ √  ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

开发时提交任何带验证的表单, 在验证未通过时都会触发Uncaught (in promise) 异常

Uncaught (in promise) {values: {…}, errorFields: Array(3), outOfDate: false}
Promise.catch(异步)
callWithAsyncErrorHandling  @ runtime-core.esm-bundler.js:6998
emit                                       @ runtime-core.esm-bundler.js:581
(匿名)                                     @ runtime-core.esm-bundler.js:6772
handleOk                               @ BasicModal.vue:204
callWithErrorHandling           @ runtime-core.esm-bundler.js:6987
callWithAsyncErrorHandling  @ runtime-core.esm-bundler.js:6996
emit                                      @ runtime-core.esm-bundler.js:581
(匿名)                                   @ runtime-core.esm-bundler.js:6772
handleOk                             @ ModalFooter.vue:30
callWithErrorHandling         @ runtime-core.esm-bundler.js:6987
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6996
emit                                       @ runtime-core.esm-bundler.js:581
(匿名)                                     @ runtime-core.esm-bundler.js:6772
handleClick6                         @ button.js:119
callWithErrorHandling           @ runtime-core.esm-bundler.js:6987
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:6996
invoker                                  @ runtime-dom.esm-bundler.js:347

### 复现 Bug

克隆2.7.2完整版源码, 安装依赖并启动运行,
系统管理 >> 部门管理 >> 新增部门 >> 确认 浏览器控制台显示error

所有的表单提交验证未通过时都会触发该异常.

## 系统信息

- 操作系统: windows 10 家庭版
- Node 版本: 16.8.0
- 包管理器 (npm/yarn/pnpm) 及其版本: yarn 1.22.11

**Comment by mynetfan** [comment]
这不是Bug，Demo只是为了演示用法没有写catch块，只写了finally。实际使用时如果需要在验证不通过时做额外的提示或处理，请自行catch
