### ISSUE TITLE
BasicTree组件不支持antv tree中slots属性

### ISSUE THREAD

**Issue by codefarming** [anncwb/vue-vben-admin#1208]
### 当前测试的vben版本为2.7.2
依照antv tree官方tree样例中slots属性自定义配置title后发现该属性无效，使用同组数据在antv tree中生效。
![1](https://user-images.githubusercontent.com/63433244/133416829-c611f3f1-7555-4912-b1de-7f9063663c2e.png)
![2](https://user-images.githubusercontent.com/63433244/133416847-cc1b5058-dbca-4579-86a9-ba6e170e1bb2.png)
![3](https://user-images.githubusercontent.com/63433244/133416855-91ab528f-f5dd-4539-a029-24bc4bf67240.png)
![4](https://user-images.githubusercontent.com/63433244/133416867-c29ee115-efda-4076-9328-91a55fc48ebd.png)

**Comment by mynetfan** [comment]
via. https://github.com/anncwb/vue-vben-admin/commit/15ea0d2f53b76643605ceba0edd4014c77fa5a40
