### ISSUE TITLE
左侧菜单动画不流畅

### ISSUE THREAD

**Issue by rumunanfeng** [anncwb/vue-vben-admin#121]
### Subject of the feature

优化建议

### Problem

左侧菜单在切换时，动画的顺序是先收起上一个选择菜单，再展开选中菜单，动画就会有一个不流畅体验

### Expected behaviour

Ant design vue的menu组件切换时动画是同步的

**Comment by anncwb** [comment]
菜单多的原因。ant-design-vue上面有相关的issue
