### ISSUE TITLE
权限使用了ROLE，菜单没有显示出来

### ISSUE THREAD

**Issue by meixian** [anncwb/vue-vben-admin#1214]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

请清晰地描述此 Bug 的具体表现。

### 复现 Bug

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统:
- Node 版本:
- 包管理器 (npm/yarn/pnpm) 及其版本:

**Comment by mynetfan** [comment]
请查阅文档

**Comment by itDjango** [comment]
> 16 Sep

我也同样的问题，找不到原因

**Comment by itDjango** [comment]
> 请查阅文档

我也同样的问题，找不到原因

**Comment by itDjango** [comment]
我发现继续使用ROUTE_MAPPING模式，在路由里面加 roles 竟然好用了

**Comment by GuoJieLun** [comment]
我的解决方案：
`
1. src/router/menus/index.ts  const menuModules: MenuModule[] ==》   const menuModules: Menu[] 
2. src/router/helper/menuHelper.ts 的 transformMenuModule方法修改为如下：
export function transformMenuModule(menuModule: Menu): Menu {
  const menuList = [menuModule];
  joinParentPath(menuList);
  return menuList[0];
}
`
3. 在menu/modules文件夹下加入对应的路由即可

**Comment by meixian** [comment]
这是一份自动回复邮件。
 
无法亲自回复您的邮件。会尽快给您回复。

**Comment by xiooong** [comment]
> 我的解决方案： `
> 
> 1. src/router/menus/index.ts  const menuModules: MenuModule[] ==》   const menuModules: Menu[]
> 2. src/router/helper/menuHelper.ts 的 transformMenuModule方法修改为如下：
>    export function transformMenuModule(menuModule: Menu): Menu {
>    const menuList = [menuModule];
>    joinParentPath(menuList);
>    return menuList[0];
>    }
>    `
> 3. 在menu/modules文件夹下加入对应的路由即可

我这样改了之后会跳到404页面是咋回事

**Comment by meixian** [comment]
这是一份自动回复邮件。
 
无法亲自回复您的邮件。会尽快给您回复。
