### ISSUE TITLE
路由设置base后文件并没走base的路径

### ISSUE THREAD

**Issue by bihell** [anncwb/vue-vben-admin#122]
### Subject of the issue

我在`src/router/index.ts`更改了路由配置，设定了`createWebHistory`方式访问，且指定`base`为admin。代码如下：

```js
// app router
const router = createRouter({
  history: createWebHistory('admin'),
  routes: basicRoutes as RouteRecordRaw[],
  strict: true,
  scrollBehavior: scrollBehavior,
});
```

### Your environment

- **OS**: macOS Big Sur Version 11.0.1
- **Packages**: vben-admin-2.0 2.0.0-rc.13
- **Env**: node v15.3.0 npm 7.0.14 yarn 1.22.10  chorme Version 87.0.4280.88 (Official Build) (x86_64)

### Steps to reproduce

随意访问一个页面，例如`http://localhost:3100/admin/login`

查看请求信息

### Expected behaviour

理论上我设置base之后 所有访问都应该走base

### Actual behaviour

实际的情况是只有域名走的base，其他请求都没走。 是否需要做特殊设定。

![image](https://user-images.githubusercontent.com/19926035/101719797-04592080-3adf-11eb-8d52-dad948c262e0.png)

**Comment by anncwb** [comment]
不需要 vite就是这样

**Comment by anncwb** [comment]
不设置这个，直接通过nginx来配置转发就可以
