### ISSUE TITLE
ant-design-vue升级版本后，useMessage提示错误

### ISSUE THREAD

**Issue by Ruio9244** [anncwb/vue-vben-admin#1220]
"ant-design-vue": "2.2.7",
hooks/web/useMessage.tsx 
报错
![image](https://user-images.githubusercontent.com/9160957/133871729-094e2d4c-350b-470a-bab0-272cc3e6f33d.png)

**Comment by mynetfan** [comment]
继续升级到2.2.8。antdv2.2.7的类型声明有问题
