### ISSUE TITLE
为什么收起和展开侧边栏会肉眼可见的卡顿

### ISSUE THREAD

**Issue by Mount-Ta1** [anncwb/vue-vben-admin#1222]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by anncwb** [comment]
Hello @Mount-Ta1. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.
