### ISSUE TITLE
Use Component `CodeEditor` will trigger: ReferenceError: MODE is not defined

### ISSUE THREAD

**Issue by HaceraI** [anncwb/vue-vben-admin#1224]
Pull 最新代码之后，我发现我的项目不能正常运行，当我尝试访问依赖组件 `CodeEditor` 的页面时，它会卡死在 Loading....
![image](https://user-images.githubusercontent.com/48341368/133887600-26e6d32e-d802-4c82-919f-61ccf7381fec.png)

我查看了线上演示的效果，同样卡死在 Loading.... 
线上演示地址：https://vvbin.cn/next/#/comp/editor/markdown/index
 ->  点击 `Json编辑器`

我尝试本地将 `import type { MODE } from './typing';` 更改为 `import { MODE } from './typing';`  这能使它恢复正常;

受影响的Code: 
https://github.com/HaceraI/vue-vben-admin/blob/main/src/components/CodeEditor/src/CodeEditor.vue#L15

**Comment by mynetfan** [comment]
感谢反馈。这里确实有问题需要修复。

**Comment by mynetfan** [comment]
https://github.com/anncwb/vue-vben-admin/commit/853bde9275584fb3ad2cceb03e59f981b8ebbd9a

这里已修复
