### ISSUE TITLE
BasicTree 半选状态

### ISSUE THREAD

**Issue by mypeng1985** [anncwb/vue-vben-admin#1232]
![image](https://user-images.githubusercontent.com/22997469/134349081-9eb904b8-6512-4aa9-b121-6f9542248a49.png)
请问下，如图所示，BasicTree 有没有属性可以设置 获取值的时候 把半选状态的一起获取到看文档没有说明，
 还是说只能自己扩展。
 谢谢。

**Comment by mynetfan** [comment]
只能通过事件获取，没有属性提供此数据，具体请查阅antdv的文档
