### ISSUE TITLE
请问支持动态设置Tab标签页title功能吗？

### ISSUE THREAD

**Issue by cometlj** [anncwb/vue-vben-admin#1239]
### 动态设置Tab标签页title标题

目前需要点击详情页路由，动态改变标签页的title，看了API文档里好像没有地方可以设置的，麻烦解答下，谢谢

**Comment by cometlj** [comment]
找到了之前的解决方案，感谢，已经关闭

**Comment by DOVE-PH** [comment]
请问如何解决的

**Comment by kangweiming1996** [comment]
@cometlj 请教下怎么解决的，遇到和这个相同的需求

**Comment by cometlj** [comment]
https://github.com/vbenjs/vue-vben-admin/issues/571
