### ISSUE TITLE
Upload组件的accept属性依旧存在问题

### ISSUE THREAD

**Issue by erniu** [anncwb/vue-vben-admin#1245]
### 描述 Bug

Version: 2.7.2

Upload组件的accept属性依旧存在问题，文档中有说明支持文件后缀验证和MIME字符串，实际代码中`checkFileType`函数并没有针对MIME做处理。

![image](https://user-images.githubusercontent.com/2314150/134874660-d8450455-476f-405f-84b8-e6ba444fc778.png)

### 复现 Bug

![image](https://user-images.githubusercontent.com/2314150/134875838-9319265c-6023-4483-af08-9fbcebbc124f.png)

![image](https://user-images.githubusercontent.com/2314150/134875933-6371ab8d-0168-41d2-84c1-46fadb325d1d.png)

**Comment by cnannerl** [comment]
同求 一样遇到问题了
