### ISSUE TITLE
请问如何实现 ApiSelect 的多层级联动？

### ISSUE THREAD

**Issue by flyingfishzxf** [anncwb/vue-vben-admin#1246]
### Subject of the feature

Describe your issue here.

### Problem

我后台项目有个需求，就是表格的过滤器有多级联动的需求，根据第一个下拉框选择的值，动态改变后一个下拉框的值，目前是3级，困扰很久，目前用一种不够优雅的代码实现，看截图，总共3级的过滤器，第1级的 `company_id` 的 `onChange` 事件的代码太长了，需要把下级的 `restaurant_id` 的完整 `componentProps` 包裹进来，而我其实只需要修改其 `params` 而已，这个 `issue` #229 问的是跟我相同的问题，却没有答案
![code-snapshot](https://user-images.githubusercontent.com/8775528/134878000-3cc24ed6-82af-4f36-b662-b75e9125fd3c.png)

### Expected behaviour

希望可以有一种优雅的方式实现独立 `ApiSelect` 的多级联动方式

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by anncwb** [comment]
参考ApiSelect，封装自己的多级联动组件，并嵌入Form内部。
