### ISSUE TITLE
BasicTable 列设置，上下拖拽位置错乱，拖拽到指定位置后未生效。

### ISSUE THREAD

**Issue by think-gem** [anncwb/vue-vben-admin#1250]
1、BasicTable 列设置，上下拖拽位置错乱，拖拽到指定位置后，未在指定位置。
2、拖拽列顺序后， 列设置里的重置、显示隐藏列，错乱。下图（版本：2.7.2）
3、重置按钮不能重置“固定列”

![image](https://user-images.githubusercontent.com/4160972/135073705-e7feec89-a389-4112-9ae8-f51837b485db.png)

**Comment by meixian** [comment]
请问解决了吗，我也遇到这个问题
