### ISSUE TITLE
网站标题会被遮挡

### ISSUE THREAD

**Issue by fengbindev** [anncwb/vue-vben-admin#1251]
![image](https://user-images.githubusercontent.com/28595220/135078143-48c6906e-e638-4c72-a3a2-ada8ccb2f7ac.png)
该部分，一些英文和文字会被遮挡。

**Comment by fengbindev** [comment]
![image](https://user-images.githubusercontent.com/28595220/135078325-509b5489-03f9-4454-a59d-55f1479e1269.png)
如果这里放开就没问题。

**Comment by fengbindev** [comment]
测试如下：
![image](https://user-images.githubusercontent.com/28595220/135078565-89b2e0f8-065b-4c92-be94-a98c45593b1d.png)
单词‘g’下面的部分被遮挡了

**Comment by niesk** [comment]
给标题样式`.vben-app-logo__title`增加`line-height: normal;`
