### ISSUE TITLE
建议页签切换时，保留切换页面之前的状态，而不是替换

### ISSUE THREAD

**Issue by think-gem** [anncwb/vue-vben-admin#1258]
建议页签切换时，保留切换页面之前的状态，而不是替换，如：

下图展开了两个节点，然后：点击页签 “基础表格”、“树形表格” 切换下，展开的节点及数据被还原页面初始状态。

![image](https://user-images.githubusercontent.com/4160972/135397905-a76373a3-cb5e-422f-81fe-67e2f8ce2e9a.png)

尝试过 BACK 路由 设置  没有起效：

meta: {
    ignoreKeepAlive: false,
    keepAlive: true,
}

projectSetting.ts

openKeepAlive: true

**Comment by linrencai** [comment]
打开页面缓存就可以了

**Comment by think-gem** [comment]
> 打开页面缓存就可以了

谢谢你的回复，除了我上面的 KeepAlive 还需要开启哪些参数？

**Comment by linrencai** [comment]
https://vvbin.cn/doc-next/guide/router.html  看下文档最后2点就懂了；需要defineComponets  的name属性和路由的name一样

**Comment by think-gem** [comment]
非常感谢，确实是 组件名和路由名不一致的问题，但我目前使用的是 <script lang="ts" setup> 语法，如何指定或获取组件名 name？
