### ISSUE TITLE
updateSchema 无效

### ISSUE THREAD

**Issue by martinou** [anncwb/vue-vben-admin#1261]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ok ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ok] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ok] 已在 Issues 中搜索了相关的关键词
- [ok ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

通过选择父节点的值，更新TreeSelect的数据，更新无效。

### 复现 Bug

1、选择父节点
2、通过Http获取所属信息
3、调用updateSchema
4、TreeSelect不能更新

关键代码：

async function handlePlatformChange(platId) {
        console.info(platId);
        const menuTreeData = await resourceSimpleTree(platId);
        console.info(menuTreeData);
        await updateSchema([
          {
            field: 'menuParentId',
            componentProps: { menuTreeData },
          },
        ]);
      }

menuTreeData：数据可以获取到，也满足树形数据的格式要求。格式如下：
[
    {
      "id": 12,
      "name": "系统管理",
      "updatedUser": null,
      "createdUser": null,
      "updatedUserId": null,
      "createdUserId": null,
      "updatedTime": "2021-09-17 15:46:42.918486",
      "createdTime": "2021-09-17 15:46:42.918486",
      "sorted": 0,
      "icon": "ant-design:appstore-outlined",
      "path": "/system",
      "enabled": true,
      "subCnt": 3,
      "title": "系统管理",
      "hidden": false,
      "parentId": null,
      "typeId": 6,
      "typeName": "目录",
      "permission": "",
      "children": [
        {
          "id": 15,
          "name": "组织架构",
          "updatedUser": null,
          "createdUser": null,
          "updatedUserId": null,
          "createdUserId": null,
          "updatedTime": "2021-09-27 19:12:08.387504",
          "createdTime": "2021-09-27 19:12:08.387504",
          "sorted": 0,
          "icon": "ant-design:windows-outlined",
          "path": "/system/organization/index",
          "enabled": true,
          "subCnt": 0,
          "title": "组织架构",
          "hidden": false,
          "parentId": 12,
          "typeId": 4,
          "typeName": "菜单",
          "permission": "org:index",
          "children": null,
          "hasChildren": null,
          "component": "/system/organization/index",
          "redirect": null,
          "alwaysShow": null,
          "meta": null,
          "iframe": false
        },
        {
          "id": 13,
          "name": "参数管理",
          "updatedUser": null,
          "createdUser": null,
          "updatedUserId": null,
          "createdUserId": null,
          "updatedTime": "2021-09-17 15:50:05.17469",
          "createdTime": "2021-09-17 15:50:05.17469",
          "sorted": 0,
          "icon": "ant-design:read-outlined",
          "path": "/system/parameter/index",
          "enabled": true,
          "subCnt": 0,
          "title": "参数管理",
          "hidden": false,
          "parentId": 12,
          "typeId": 4,
          "typeName": "菜单",
          "permission": "param:index",
          "children": null,
          "hasChildren": null,
          "component": "/system/parameter/index",
          "redirect": null,
          "alwaysShow": null,
          "meta": null,
          "iframe": false
        },
        {
          "id": 14,
          "name": "资源管理",
          "updatedUser": null,
          "createdUser": null,
          "updatedUserId": null,
          "createdUserId": null,
          "updatedTime": "2021-09-17 15:50:05.17469",
          "createdTime": "2021-09-17 15:50:05.17469",
          "sorted": 0,
          "icon": "ant-design:menu-unfold-outlined",
          "path": "/system/resource/index",
          "enabled": true,
          "subCnt": 0,
          "title": "资源管理",
          "hidden": false,
          "parentId": 12,
          "typeId": 4,
          "typeName": "菜单",
          "permission": "res:index",
          "children": null,
          "hasChildren": null,
          "component": "/system/resource/index",
          "redirect": null,
          "alwaysShow": null,
          "meta": null,
          "iframe": false
        }
      ],
      "hasChildren": null,
      "component": "Layout",
      "redirect": null,
      "alwaysShow": null,
      "meta": null,
      "iframe": false
    },
    {
      "id": 9999,
      "name": "工作台",
      "updatedUser": null,
      "createdUser": null,
      "updatedUserId": null,
      "createdUserId": null,
      "updatedTime": "2021-09-24 18:20:19.106564",
      "createdTime": "2021-09-24 18:20:19.106564",
      "sorted": 0,
      "icon": "ant-design:windows-outlined",
      "path": "/dashboard",
      "enabled": false,
      "subCnt": 1,
      "title": "工作台",
      "hidden": false,
      "parentId": null,
      "typeId": 6,
      "typeName": "目录",
      "permission": null,
      "children": [
        {
          "id": 99,
          "name": "分析页",
          "updatedUser": null,
          "createdUser": null,
          "updatedUserId": null,
          "createdUserId": null,
          "updatedTime": "2021-09-24 18:24:15.731318",
          "createdTime": "2021-09-24 18:24:15.731318",
          "sorted": 0,
          "icon": "ant-design:rise-outlined",
          "path": "/dashboard",
          "enabled": false,
          "subCnt": 0,
          "title": "分析页",
          "hidden": false,
          "parentId": 9999,
          "typeId": 4,
          "typeName": "菜单",
          "permission": "anaylis:index",
          "children": null,
          "hasChildren": null,
          "component": "/dashboard/analysis/index",
          "redirect": null,
          "alwaysShow": null,
          "meta": null,
          "iframe": false
        }
      ],
      "hasChildren": null,
      "component": null,
      "redirect": null,
      "alwaysShow": null,
      "meta": null,
      "iframe": false
    }
  ]

控制台没有任何错误。

请描述在演示页面中复现 Bug 的详细步骤，以确保我们可以理解并定位问题。部分 Bug 如果未在 Demo 中涉及，请务必提供关键代码

## 系统信息

- 操作系统: Window 10
- Node 版本: 14
- 包管理器 (npm/yarn/pnpm) 及其版本: yarn  1.22.11

**Comment by martinou** [comment]
重启既然好了。无语

**Comment by mynetfan** [comment]
componentProps: { treeData: menuTreeData }
