### ISSUE TITLE
组件里面的useSearchForm 能否加个属性，让标签的文字显示在占位符里面

### ISSUE THREAD

**Issue by bihell** [anncwb/vue-vben-admin#128]
如下面截图这样，文章状态在占位符这边

![image](https://user-images.githubusercontent.com/19926035/102333609-9e7e0480-3fc8-11eb-9eec-49573b9af431.png)

**Comment by anncwb** [comment]
可以尝试不传label只写placeholder。不行的话我后续在加

**Comment by bihell** [comment]
并没有placeHolder这个属性，等你后续加吧
![image](https://user-images.githubusercontent.com/19926035/102364500-7a82e900-3ff1-11eb-99d9-d460e36df036.png)

**Comment by anncwb** [comment]
placeholder属性肯定可以配置的啊  参考form文档

**Comment by bihell** [comment]
> placeholder属性肯定可以配置的啊 参考form文档

不是啊，我用的你分装的useSearchForm ，FormSchema里面的确没这个属性的。

**Comment by anncwb** [comment]
componentProps

**Comment by bihell** [comment]
> componentProps

搞定了，不容易
