### ISSUE TITLE
脚手架代码太乱

### ISSUE THREAD

**Issue by lichnow** [anncwb/vue-vben-admin#129]
可能由于`vite`本身生态不是很完善，整体程序非常清晰可控，但是`build`目录的脚手架代码心智负担实在太大,做任何一点修改都要去点到各种地方改代码，建议或者可以考虑使用`vue-cli`,或者`yargs`再封装一个轮子? 尤其类似`preserve.ts`这种检查目录名称，依赖更新或者`changelog.ts`什么的感觉写着没多大意义

**Comment by anncwb** [comment]
1.目前这个阶段vite确实不是很完善。所以没去整理
2. vite2.0即将出来，等这些出来会将大部分脚本独立成插件。
3. 有一些脚本是因为太多人遇到同样的问题了。所以才会去单独写一个去提示。后续生态完善这些都会优化的
