### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by anncwb** [anncwb/vue-vben-admin#13]
If the system does not have the function you want, you can put it here, and we will develop it according to the situation!

Function proposal format
```
Name: Add xxx function
Role: Business scenario description
Online reference example (if available): https://xxxx
```

如果系统没有您想要的功能，可以在这里提出，我们将视情况进行开发！

功能提出格式
```
名称：添加xxx功能
作用：业务场景说明
在线参考示例(如果有): https://xxxx
```

**Comment by Layczm** [comment]
名称：添加流程图功能
作用：绘制流程图，（键盘快捷键，自定义属性，自定义格式，喜欢颜值高的！）
在线参考示例: https://app.diagrams.net/（列子是用mxgraph实现的！）

**Comment by zss1004504439** [comment]
本地运行时，感觉好卡呀？

**Comment by anncwb** [comment]
@zss1004504439 我这边不会，是指页面卡顿吗？ 具体是哪里呢，

**Comment by anncwb** [comment]
@zss1004504439 以优化，可以看1.3.0版本

**Comment by superlbr** [comment]
考虑支持ts4.0？

**Comment by anncwb** [comment]
> 考虑支持ts4.0？

2.0版本会支持 不久后将会发布. vite+ts4+vue3

**Comment by whenTheMorningDark** [comment]
> 名称：添加流程图功能
> 作用：绘制流程图，（键盘快捷键，自定义属性，自定义格式，喜欢颜值高的！列子是用mxgraph实现的！）
> 在线参考示例: https://app.diagrams.net/

兄弟我有一个mxgraph组件的demo有兴趣可以看下,利用vue实现的

**Comment by Layczm** [comment]
> > 名称：添加流程图功能
> > 作用：布局流程图，（键盘快捷键，自定义属性，自定义格式，喜欢颜值高的！列子是用mxgraph实现的！）
> > 在线参考示例：[https：//app.diagrams 。净/](https://app.diagrams.net/)
> 
> 兄弟我有一个mxgraph组件的demo有兴趣可以看下，利用vue实现的

你的登陆问题还没解决，不会忘了我了吧！

**Comment by pumpkingsun** [comment]
名称：顶部菜单自适应
作用：目前的顶部菜单数量多了，会无法显示完整，希望当顶部菜单数量过多时，支持自适应显示，超出的菜单部分显示为”更多“。
参考示例：
![image](https://user-images.githubusercontent.com/11347174/96423240-a40ad880-122b-11eb-829d-708c79513816.png)

**Comment by anncwb** [comment]
@pumpkingsun  这个是bug。本来有的。应该是我改动到了，后续修复

**Comment by anncwb** [comment]
@pumpkingsun  fix (#6bab0b1)

**Comment by tgly307** [comment]
请问菜单拖拽和侧边栏拖拽是什么功能？在示例中没有找到怎么用

**Comment by anncwb** [comment]
@tgly307 鼠标移动到左侧菜单右侧 。会出现拖拽宽度的线。

**Comment by anncwb** [comment]
@West121 简单做了一个。功能不全。下版rc4加上去

**Comment by anncwb** [comment]
@West121 https://vvbin.cn/next/#/table/formTable

**Comment by West121** [comment]
> @West121 https://vvbin.cn/next/#/table/formTable

全屏有问题
![image](https://user-images.githubusercontent.com/29170680/97123260-e2415400-1765-11eb-8631-d3a6f55b8e66.png)

**Comment by anncwb** [comment]
@West121  新的问题建议另外开一个issue来提问。这个issue主要是提功能需求的

**Comment by anncwb** [comment]
@West121 因为全屏是对这个dom的。这个dom可视化区域就这么大。全屏就这样

**Comment by superlbr** [comment]
能不能加个权限管理的页面，对用户分配权限，分配页面、角色啥的

**Comment by nangongmo** [comment]
添加一个个人中心页面比较好

**Comment by anncwb** [comment]
> 能不能加个权限管理的页面，对用户分配权限，分配页面、角色啥的

有计划.要等一段时间

**Comment by anncwb** [comment]
> 添加一个个人中心页面和用户设置页面比较好，可以直接把vue antd pro的搬过来放进去

这个已经在写,antvpro的页面打算弄一些过来做例子

**Comment by anncwb** [comment]
> > @West121 https://vvbin.cn/next/#/table/formTable
> 
> 全屏有问题
> ![image](https://user-images.githubusercontent.com/29170680/97123260-e2415400-1765-11eb-8631-d3a6f55b8e66.png)

已修复

**Comment by TothingWay** [comment]
名称：添加树组件点击文字展开功能
作用：点击箭头展开不是很方便，想点击文字展开的同时又可以在最右侧添加按钮
在线参考示例：https://element.eleme.cn/#/zh-CN/component/tree，类似elementUI

**Comment by anncwb** [comment]
> 名称：添加树组件点击文字展开功能
> 作用：点击箭头展开不是很方便，想点击文字展开的同时又可以在最右侧添加按钮
> 在线参考示例：https://element.eleme.cn/#/zh-CN/component/tree

1

**Comment by nhdeng** [comment]
不支持IE11，实际开发过程中主线项目还是需要考虑兼容IE11的，这个大佬有兼容IE11的计划吗？

**Comment by superlbr** [comment]
还有一个请教下，左侧menu想隐藏起来怎么办，比如详情页这样。不传入menu，渲染会找不到页面吧

**Comment by zhenzhenChange** [comment]
名称：添加 穿梭框 + 树形控件 功能
作用：流程管理，按级别分层，选择层级或部分人员来下发通知等等
在线参考示例(如果有): https://blog.csdn.net/wangweiren_get/article/details/88118337

**Comment by anncwb** [comment]
> 名称：添加 穿梭框 + 树形控件 功能
> 作用：流程管理，按级别分层，选择层级或部分人员来下发通知等等
> 在线参考示例(如果有): https://blog.csdn.net/wangweiren_get/article/details/88118337
> PS：官方的示例有个简易版的，不过穿梭到右边树形结构没有维持，感觉两边的处理挺麻烦的。https://2x.antdv.com/components/transfer-cn/

可以  等我开始做系统管理模块的时候加

**Comment by mynetfan** [comment]
名称：记录build的时间
作用：可以在页面中显示项目的打包时间，以便可以查看前端页面的更新时间。

**Comment by anncwb** [comment]
> 名称：记录build的时间
> 作用：可以在页面中显示项目的打包时间，以便可以查看前端页面的更新时间。

没明白你的意思。在页面显示时间？

**Comment by mynetfan** [comment]
> > 名称：记录build的时间
> > 作用：可以在页面中显示项目的打包时间，以便可以查看前端页面的更新时间。
> 
> 没明白你的意思。在页面显示时间？

我想在某些页面显示前端项目的打包时间（运行yarn build的时间），希望每次打包都自动更新这个时间常量。

**Comment by superlbr** [comment]
支持vite2

**Comment by anncwb** [comment]
> 支持vite2
已支持

**Comment by tomasky** [comment]
table加载模拟数据很慢，即使修改了timeout=0, 还有点击列表全选的反应也很慢，要１秒，最新版本本地测试

**Comment by anncwb** [comment]
> table加载模拟数据很慢，即使修改了timeout=0, 还有点击列表全选的反应也很慢，要１秒，最新版本本地测试

我在排查看看

**Comment by leavest** [comment]
名称：添加代码编辑器
作用：在线修改json、yaml等配置文件，支持高亮、格式化、错误检测等功能
在线参考示例(如果有):

**Comment by anncwb** [comment]
The discussion has moved to https://github.com/anncwb/vue-vben-admin/discussions/251
