### ISSUE TITLE
Table setColumns defaultSorderOrder无效

### ISSUE THREAD

**Issue by enjkvbej** [anncwb/vue-vben-admin#130]
setColumns：其中columns设置defaultSorderOrder属性 但是并没有默认排序

**Comment by anncwb** [comment]
近期会重构下表格和表单。目前表格表单问题会在重构后解决

**Comment by enjkvbej** [comment]
> 近期会重构下表格和表单。目前表格表单问题会在重构后解决

那有什么hack方法来解决吗 调试时setColumns 确实把columns的值更新了（带defaultSorderOrder） 但是为啥不显示呢？

**Comment by anncwb** [comment]
setColumns我测试可以了
