### ISSUE TITLE
首页加载vendor.*.js  TTFB 时间过长 

### ISSUE THREAD

**Issue by TML4140** [anncwb/vue-vben-admin#1320]
![Image_20211027220236](https://user-images.githubusercontent.com/20573004/139082487-80fce9ff-8e9c-4588-b2e6-d432b075ef30.jpg)

请问有处理方式么？

**Comment by TML4140** [comment]
已经解决了， 跟 vue-vben-admin 没有关系

**Comment by mamba-in** [comment]
> 已经解决了， 跟 vue-vben-admin 没有关系

请问怎么解决的，我也遇到同样问题，main.ts加载很久
![WX20220613-144644](https://user-images.githubusercontent.com/21197600/173295487-106f73fb-3804-4bdd-aae5-978ce2e7da58.png)
