### ISSUE TITLE
切换标签页会重新加载页面内容，怎么让它不重新加载呢

### ISSUE THREAD

**Issue by cxxwl96** [anncwb/vue-vben-admin#1329]
切换标签页会重新加载页面内容，怎么让它不重新加载呢

**Comment by Joyboo** [comment]
参考:  路由 -> 多标签页缓存
https://vvbin.cn/doc-next/guide/router.html

**Comment by cdxxiaomao** [comment]
主要就是路由name必须要与页面文件中的name保持一致。然后在路由配置meta中配置好ignoreKeepAlive。
记住这三点就是。

**Comment by dzvane** [comment]
> 主要就是路由name必须要与页面文件中的name保持一致。然后在路由配置meta中配置好ignoreKeepAlive。 记住这三点就是。

看了预览里面的系统管理模块，ignoreKeepAlive=true，但是只有账号管理生效了~~，看了路由name必须要与页面文件中的name也一致的啊
