### ISSUE TITLE
混合模式下左侧菜单没有滚动条，顶部模式下鼠标悬浮到菜单上显示空白子菜单

### ISSUE THREAD

**Issue by LingJunZhu** [anncwb/vue-vben-admin#133]
![image](https://user-images.githubusercontent.com/39548095/102568998-9edce380-411f-11eb-8b06-38e13c1924f4.png)
![image](https://user-images.githubusercontent.com/39548095/102569132-d9468080-411f-11eb-8cba-1b17f49f787e.png)

**Comment by anncwb** [comment]
最新的代码应该改了。只是示例没改
