### ISSUE TITLE
官网demo中完整版在QQ浏览器（Chromium 70.0.3538.25）中不能进入登录页。显示“globalThis is not defined”

### ISSUE THREAD

**Issue by zhaohuiyingxue** [anncwb/vue-vben-admin#1331]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

官网demo中完整版在QQ浏览器（Chromium 70.0.3538.25）中不能进入登录页。显示“globalThis is not defined”

### 复现 Bug

1、官网demo中完整版打开不正常，显示Logo不进入登录页。console中显示“Uncaught ReferenceError: globalThis is not defined at vendor.e7c0f2cb.js:14”。但是精简版是正常的。
2、分别下载完整版源码的 master分支 和 v2.7.2。不做任何更改，进行编译直接生成dist进行浏览。master分支表现和上面一样都无法进入登录页，提示“globalThis is not defined”，但是v2.7.2正常。
3、以上所有在谷歌浏览器（Chromium 95）以及360极速浏览器（Chromium 86）中均正常。
4、以上浏览器均为最新版。

## 系统信息

- 操作系统: WIN10
- 浏览器：QQ浏览器（Chromium 70.0.3538.25）
- Node 版本:v14.18.1
- 包管理器 (npm/yarn/pnpm) 及其版本:yarn v1.22.17 vite v2.6.11(master分支)/vite v2.5.7（vben v2.7.2）

**Comment by anncwb** [comment]
尽量使用高版本浏览器，这个项目不对历史老版本浏览器做太多的兼容，最好是chrome80+以上
