### ISSUE TITLE
[vite:mock] mock reload error No loader is configured for ".vue"

### ISSUE THREAD

**Issue by lixinlin** [anncwb/vue-vben-admin#1334]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [ ] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [ ] 已在 Issues 中搜索了相关的关键词
- [ ] 不是 ant design vue 组件库的 Bug

### 描述 Bug

克隆了项目，增加了一个列表页面之后，莫名其妙的编译报错，本身可以编译，只是突然之间不能编译了

### 复现 Bug

上午12:23:38 [vite:mock] mock reload error Error: Build failed with 3 errors:
src/router/constant.ts:7:48: error: No loader is configured for ".vue" files: src/views/sys/exception/Exception.vue
src/router/constant.ts:12:35: error: No loader is configured for ".vue" files: src/layouts/default/index.vue
src/router/helper/routeHelper.ts:10:28: error: No loader is configured for ".vue" files: src/views/sys/iframe/FrameBlank.vue

## 系统信息

- 操作系统: win10、win11
- Node 版本: 16
- 包管理器 (npm/yarn/pnpm) 及其版本:yarn、npm，都是最新版

**Comment by lixinlin** [comment]
这个是报错的行
 > src/router/helper/routeHelper.ts:21:47: warning: "import.meta" is not available in the configured target environment ("es2015") and will be empty
    21 │   dynamicViewsModules = dynamicViewsModules || import.meta.glob('../../views/**/*.{vue,tsx}');
       ╵                                                ~~~~~~~~~~~

 > src/router/helper/routeHelper.ts:72:47: warning: "import.meta" is not available in the configured target environment ("es2015") and will be empty
    72 │   dynamicViewsModules = dynamicViewsModules || import.meta.glob('../../views/**/*.{vue,tsx}');
       ╵                                                ~~~~~~~~~~~

 > src/router/helper/routeHelper.ts:10:28: error: No loader is configured for ".vue" files: src/views/sys/iframe/FrameBlank.vue
    10 │ const IFRAME = () => import('/@/views/sys/iframe/FrameBlank.vue');
       ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 > src/utils/log.ts:1:20: warning: "import.meta" is not available in the configured target environment ("es2015") and will be empty
    1 │ const projectName = import.meta.env.VITE_GLOB_APP_TITLE;
      ╵                     ~~~~~~~~~~~

 > src/router/constant.ts:7:48: error: No loader is configured for ".vue" files: src/views/sys/exception/Exception.vue
    7 │ export const EXCEPTION_COMPONENT = () => import('/@/views/sys/exception/Exception.vue');
      ╵                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 > src/router/constant.ts:12:35: error: No loader is configured for ".vue" files: src/layouts/default/index.vue
    12 │ export const LAYOUT = () => import('/@/layouts/default/index.vue');
       ╵                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by lixinlin** [comment]
问题找到了，mock里面import vue文件导致的，将相关代码分离出来以后好了

**Comment by suka233** [comment]
同样出现了这个问题,也是报错mock reload error No loader is configured for ".vue"
但是并没有引入vue文件,而是在mock中引入了tsx文件,导致报错(ts文件不会报错)

解决办法是,不要在mock里面导入tsx文件即可
