### ISSUE TITLE
请问能否适配vue-cli5?

### ISSUE THREAD

**Issue by nangongmo** [anncwb/vue-vben-admin#137]
经过一段时间的尝试，打算放弃antd pro而使用vben，目前唯一的问题是生产环境使用vite不是很好，请问有计划适配vue-cli吗？

**Comment by anncwb** [comment]
目前代码和cli是不兼容的。所以不会去适配vue-cli

**Comment by nangongmo** [comment]
@anncwb 那么目前就是等vite生态完善才能用于生成环境吗？

**Comment by anncwb** [comment]
等下vite2.0
