### ISSUE TITLE
项目升级到antdv3.x后，中文环境下，日期选择框月份出现英文

### ISSUE THREAD

**Issue by dearmark** [anncwb/vue-vben-admin#1406]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

项目升级到antdv3.x后，中文环境下，日期选择框月份出现英文，年份正常

### 复现 Bug

![image](https://user-images.githubusercontent.com/3938942/143341174-3383fce2-b724-4698-bf6f-a43d86c7b240.png)

## 系统信息

- 操作系统: Windows 11 专业版 Insider Preview [64 位]
- Node 版本:v16.13.0
- 包管理器 (npm/yarn/pnpm) 及其版本:pnpm

**Comment by waney** [comment]
+1

**Comment by waney** [comment]
**注意：**Calendar 部分 locale 是从 value 中读取，所以请先正确设置 dayjs 的 locale。

// 默认语言为 en-US，所以如果需要使用其他语言，推荐在入口文件全局设置 locale
// import dayjs from 'dayjs';
// import 'dayjs/locale/zh-cn';
// dayjs.locale('zh-cn');

**Comment by dearmark** [comment]
fix: Fix multi-language errors and installation errors 
https://github.com/anncwb/vue-vben-admin/commit/2aabbc788ab05d06f4dcc2a01b25585ecf8f690b
已修复

**Comment by shuperry** [comment]
@dearmark 没有修复哦，对比你提交记录里的代码都有，但是日期选择组件就是有英文

**Comment by shuperry** [comment]
@waney 诡异的是，在 App.vue 里面全部都参照 antdv3.x 官网写法之后居然还是不行，日期选择组件就还是有英文

**Comment by Linjiande** [comment]
你好，antv 3.2.31 还是有这个问题
