### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by snihwxf** [anncwb/vue-vben-admin#141]
直接
git clone https://github.com/anncwb/vue-vben-admin
yarn install
yarn serve
运行就报错
版本 2.0.0-rc.14

client:19 [vite] connecting...
client:46 [vite] connected.
persistent.ts:16 Uncaught SyntaxError: Unexpected token

**Comment by anncwb** [comment]
本地开发使用了可选链语法。请使用最新版的谷歌浏览器开发。
