### ISSUE TITLE
vscode编辑器中，在 .vue文件中代码提示很慢很慢，大约要等3秒钟提示出来，.ts文件中很快

### ISSUE THREAD

**Issue by Miboweixin** [anncwb/vue-vben-admin#1418]
### 描述 Bug

在 .vue文件中代码提示很慢很慢，大约要等3秒钟提示出来，.ts文件中很快

### 复现 Bug

打开.vue文件 输入的语法提示太慢！
## 系统信息

- 操作系统: Mac OS 11.6
- node v12.18.3
- npm v6.14.6

**Comment by Miboweixin** [comment]
我目前能够确定的是 问题出在 package.json中某个依赖导致代码提示很慢

**Comment by wangz-code** [comment]
同求,

**Comment by M69W** [comment]
> 我目前能够确定的是 问题出在 package.json中某个依赖导致代码提示很慢

也可能是vscode 插件的问题。


```
ant-design-vue.vscode-ant-design-vue-helper
formulahendry.auto-close-tag
hookyqr.beautify
ms-ceintl.vscode-language-pack-zh-hans
intellsmi.comment-translate
mikestead.dotenv
editorconfig.editorconfig
dbaeumer.vscode-eslint
donjayamanne.githistory
eamodio.gitlens
ecmel.vscode-html-css
abusaidm.html-snippets
lokalise.i18n-ally
gregorbiswanger.json2ts
zignd.html-css-class-completion
xabikos.javascriptsnippets
ritwickdey.liveserver
esbenp.prettier-vscode
mohsen1.prettify-json
ryanolsonx.solarized
stylelint.vscode-stylelint
octref.vetur
voorjaar.windicss-intellisense
```

**Comment by Miboweixin** [comment]
我全局安装了 ts 就不卡了， npm i typescript -g，希望能够帮助大家

**Comment by Miboweixin** [comment]
> 我也是，ts文件就快，vue巨慢，不能接受，等它提示我都打完一个单词了

**Comment by Miboweixin** [comment]
> 同求，

我全局安装了 ts 就不卡了， npm i typescript -g，希望能够帮助大家

**Comment by Miboweixin** [comment]
> 我也是，ts文件就快，vue巨慢，不能接受，等它提示我都打完一个单词了

我全局安装了 ts 就不卡了， npm i typescript -g，希望能够帮助大家

**Comment by Miboweixin** [comment]
> > 我当前能够确定问题在package.json中是某个依赖导致代码提示很慢
> 
> 也可能是vscode插件的问题。
> 
> ```
> ant-design-vue.vscode-ant-design-vue-helper
> formulahendry.auto-close-tag
> hookyqr.beautify
> ms-ceintl.vscode-language-pack-zh-hans
> intellsmi.comment-translate
> mikestead.dotenv
> editorconfig.editorconfig
> dbaeumer.vscode-eslint
> donjayamanne.githistory
> eamodio.gitlens
> ecmel.vscode-html-css
> abusaidm.html-snippets
> lokalise.i18n-ally
> gregorbiswanger.json2ts
> zignd.html-css-class-completion
> xabikos.javascriptsnippets
> ritwickdey.liveserver
> esbenp.prettier-vscode
> mohsen1.prettify-json
> ryanolsonx.solarized
> stylelint.vscode-stylelint
> octref.vetur
> voorjaar.windicss-intellisense
> ```
> 
> ![20211202085538](https://user-images.githubusercontent.com/15809201/144338298-454d51d7-41a4-4b45-be42-7b60b5b7caf1.png)

我全局安装了 ts 就不卡了， npm i typescript -g，希望能够帮助大家

**Comment by Miboweixin** [comment]
谢谢大家的帮助，已解决问题。不是官网问题，我将关闭此问题
