### ISSUE TITLE
我运行起来后，国际化没成功，全是显示的代码，是哪里没配置对呢

### ISSUE THREAD

**Issue by shansheng** [anncwb/vue-vben-admin#142]
显示如下：
vue-i18n.js:54 [intlify] The message format compilation is not supported in this build. Because message compiler isn't included. You need to pre-compilation all message format. So translate function return 'routes.demo.table.table'.

**Comment by anncwb** [comment]
可以先把package.json内的vue-i18n固定为beta .14  去掉前面的　`^`重新安装即可
