### ISSUE TITLE
clone了源码，pnpm install 后，运行程序，出现@id/purge-icons/generated 500错误

### ISSUE THREAD

**Issue by GitACDreamer** [anncwb/vue-vben-admin#1435]
在上述的issue里查找，和网上查询未找到合适的解决办法，

### Describe the bug

A clear and concise description of what the bug is..
编译运行程序后，一直卡在加载主页面，显示不了登录页面，按F12调试发现是请求图标库icon  `purge-icons/generated`出现500错误。
目前，我只有注释掉使用此图标库，才能正常使用，但是系统里ant-design图标都不会显示，求教，此问题如何解决？
![image](https://user-images.githubusercontent.com/19402747/144348889-195cca16-cc2d-4096-8d6a-a0d586dcfe95.png)

### Reproduction

![image](https://user-images.githubusercontent.com/19402747/144348394-38401b55-fe05-481a-8790-e84cd716b717.png)

## System Info

- Operating System: Windows10
- Node version:  v12.17.0
- Package manager (npm/yarn/pnpm) and version: pnpm 6.23.2
- Browser： Google  94.0.4606.81

**Comment by 1sm23** [comment]
更新 `nodejs` 到 16.13.0 再 install 试试

**Comment by GitACDreamer** [comment]
@1sm23 感谢目前nodejs更新到最新版是OK了的，这个需要你们做兼容或者提示后续的使用者。
