### ISSUE TITLE
建议增加:: 在BasicForm中获取input方法,  应用场景是控制input聚焦

### ISSUE THREAD

**Issue by zn98com** [anncwb/vue-vben-admin#146]
![Snipaste_2020-12-26_10-47-06](https://user-images.githubusercontent.com/10260081/103144657-35388700-4768-11eb-9ea3-33e6df43eb18.png)

在表单打开时,实现聚焦,
如上,为了给input聚焦,采用slot可以,但把原来的结构全部破坏了,又显得不伦不类,代码不好维护. 
请老大给一个解决方法或者实现方法, 帮实现一下,太谢谢您了!

**Comment by anncwb** [comment]
下次发版本加
