### ISSUE TITLE
地址栏重定向问题或者优化

### ISSUE THREAD

**Issue by Alarikshaw** [anncwb/vue-vben-admin#147]
### Subject of the issue
直接输入url，没有做拦截
Describe your issue here.
已登录的情况，直接输入url ，‘/login’ 进入登录页面。
此时用户的信息依然保存在浏览器，但已无法跳转回去。
或者从另一个角度说用户的信息没有被清除掉，但依然无法解释：用户并没有退出这个场景。
只能再次登录。
### Your environment
本地开发环境
Env、yarn(1.21.1)、Chrome(87.0.4280.88)正式版
- **OS**: 
- **Packages**: 
- **Env**: 

### Steps to reproduce
请按照问题描述执行即可
Tell us how to reproduce this issue. Please provide a working and simplified example.
在src/router/guard/permissionGuard.ts文件下，对router.afterEach执行方法进行修改。
目前本地做的是禁止在已登录的情况禁止跳转至登录页，或者说无法跳转
![image](https://user-images.githubusercontent.com/46787751/103153045-7fe9eb80-47c8-11eb-9977-7de4a82ac76a.png)

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub. This will get you the fastest support. 🎉

### Expected behaviour

What should happen?

### Actual behaviour

What happens instead?

**Comment by Alarikshaw** [comment]
抱歉，上面的解决方案不行。

**Comment by anncwb** [comment]
现在跳转登录页视为退出登录

**Comment by Alarikshaw** [comment]
明白
