### ISSUE TITLE
ant-design-vue 3.x resizable collumns & multisort

### ISSUE THREAD

**Issue by chasie** [anncwb/vue-vben-admin#1470]
### Resizable and Multisort in Table

Hello, guys, i realy like your project(template), But I would like you to add some features (Table) from ant-design-vue 3.x like resizable collumns and multisort. Thanks, I'll be waiting.

**Comment by Carnia** [comment]
look here
https://github.com/vbenjs/vue-vben-admin/issues/1367#issuecomment-1107683378
