### ISSUE TITLE
modal弹窗在手机上不能打开

### ISSUE THREAD

**Issue by liuzhongyi1988** [anncwb/vue-vben-admin#1502]
浏览器是 ios14.2 safari和 ios chrome 86.04240.93,

1. modal弹窗不能打开
2. 不能退出系统

 https://vvbin.cn/next/#/comp/modal

**Comment by liuzhongyi1988** [comment]
最新版解决

**Comment by shencong12** [comment]
你是把项目src/components所有的组件全更新了吗
