### ISSUE TITLE
On form reset,Input not cleared,But the value is cleared

### ISSUE THREAD

**Issue by SheenaghF** [anncwb/vue-vben-admin#1519]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

On form reset,Input not cleared,But the value is cleared

### Reproduction

On form reset,Input not cleared,But the value is cleared

## System Info

- Operating System: win64
- Node version:14
- Package manager (npm/yarn/pnpm) and version:pnpm

**Comment by dearmark** [comment]
Some problem
