### ISSUE TITLE
请问vite打包后，出现VITE_GLOB_APP_TITLE' of 't' as it is undefined是什么原因？

### ISSUE THREAD

**Issue by AndroidMilk** [anncwb/vue-vben-admin#1522]
**⚠️ 重要 ⚠️ 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭**

- [x] 已阅读 [文档](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] 确保您的代码已是最新或者所报告的 Bug 在最新版本中可以重现. (部分 Bug 可能已经在最近的代码中修复)
- [x] 已在 Issues 中搜索了相关的关键词
- [x] 不是 ant design vue 组件库的 Bug

### 描述 Bug

打包后访问出现
Cannot destructure property 'VITE_GLOB_APP_TITLE' of 't' as it is undefined.
![image](https://user-images.githubusercontent.com/13392610/147185327-007821dd-664d-4a61-9be8-23e1220cebd9.png)

**Comment by AndroidMilk** [comment]
已解决

**Comment by 21stc-09** [comment]
> 已解决

请问怎么解决的？

**Comment by cnguu** [comment]
> 已解决

请问下是如何解决的？

**Comment by 21stc-09** [comment]
> 



> > 已解决
> 
> 请问下是如何解决的？

你的项目全局变量配置有问题，会导致这个报错。自己检查一下

**Comment by cnguu** [comment]
@21stc-09 谢谢答复，可能我和你的问题不太一样，我是通过降低vite-plugin-html版本解决的，3.0.6会出错，2.1.2是正常的

**Comment by 21stc-09** [comment]
> @21stc-09 谢谢答复，可能我和你的问题不太一样，我是通过降低vite-plugin-html版本解决的，3.0.6会出错，2.1.2是正常的

好的，我是根据vben结合公司项目自己改的一套，没有用这个插件。我当时是环境变量相关配置出现了问题，没有正确引用。希望对你有点帮助

**Comment by wubin1989** [comment]
@cnguu VITE_GLOB_APP_TITLE 这个环境变量可以随便设置，但是VITE_GLOB_APP_SHORT_NAME不可以带中横线”-“，把VITE_GLOB_APP_SHORT_NAME的值修改一下就好了。

**Comment by MrLucy** [comment]
> > @21stc-09 谢谢答复，可能我和你的问题不太一样，我是通过降低vite-plugin-html版本解决的，3.0.6会出错，2.1.2是正常的
> 
> 好的，我是根据vben结合公司项目自己改的一套，没有用这个插件。我当时是环境变量相关配置出现了问题，没有正确引用。希望对你有点帮助

遇见和你一样的问题，请问当时您是怎么解决的呢？

**Comment by 21stc-09** [comment]
> > > @21stc-09 谢谢答复，可能我和你的问题不太一样，我是通过降低vite-plugin-html版本解决的，3.0.6会出错，2.1.2是正常的
> > 
> > 
> > 好的，我是根据vben结合公司项目自己改的一套，没有用这个插件。我当时是环境变量相关配置出现了问题，没有正确引用。希望对你有点帮助
> 
> 遇见和你一样的问题，请问当时您是怎么解决的呢？

全局查找相关引用文件，修改相关的对应代码。我当时是环境变量没有配置该字段

**Comment by codeinfo** [comment]
学习了一下源码，根据当前的源码，production环境打宝时会生产对应的app.config文件
`  esno ./build/script/postBuild.ts  `
这个有没有比较好的替代方法？

**Comment by coderwyd** [comment]
> 学习了一下源码，根据当前的源码，production环境打包时会生产对应的app.config文件 ` esno ./build/script/postBuild.ts ` 这个有没有比较好的替代方法？

+1

**Comment by hulong-prong** [comment]
> 已解决

请问是如何解决的，遇到了同样的问题
