### ISSUE TITLE
表格开启搜索Form表单后，重置按钮重置功能无法清空Input输入框

### ISSUE THREAD

**Issue by Wang-Yumin** [anncwb/vue-vben-admin#1540]
演示页面中，存在开启Form搜索表单的表格，点击重置按钮后Input输入框未清空，实际搜索条件清空了（如：账号管理、角色管理），浏览器：Microsoft Edge 版本 96.0.1054.62 (官方内部版本) (64 位)
![image](https://user-images.githubusercontent.com/20619401/147403348-116c10a2-c35d-482b-9344-db4e96735632.png)

**Comment by wangxiaoer5200** [comment]
楼主可以用最新代码试试，这个问题同issues#1519，pr#1526已经解决这样的重置问题，这个issues可以关闭

**Comment by Wang-Yumin** [comment]
@wangxiaoer5200 是的，已经拉取了最新的代码验证，问题已解决
