### ISSUE TITLE
多开几个页面就卡死了

### ISSUE THREAD

**Issue by a0953245782** [anncwb/vue-vben-admin#159]
多开几个页面就卡死了

**Comment by anncwb** [comment]
请给具体复现步骤

**Comment by a0953245782** [comment]
多打开几个页签啊,打开到高级表单就卡死了
![image](https://user-images.githubusercontent.com/3320932/103507020-1d17e480-4e99-11eb-8edd-05a02dcf4669.png)

**Comment by mynetfan** [comment]
附议。
测试的浏览器有：edge v87.0.664.66（X64）、Chrome v84.0.4147.89(X86)、Firefox v82.0b2(X64)。系统是WIN10 X64 V10.0.19042.685
步骤：打开高级表单页→打开【页面】菜单下的其它任意页面（除【表单页】下的以外）→通过页面标签或左侧菜单切回到高级表单页面→假死。


![image](https://user-images.githubusercontent.com/17241274/103516214-172aff00-4eab-11eb-996e-f4bb3468d9d8.png)
![image](https://user-images.githubusercontent.com/17241274/103516394-6e30d400-4eab-11eb-8bc4-55f798492b12.png)

**Comment by mynetfan** [comment]
在Firefox中打断点，最终在src\components\Menu\src\components\BasicSubMenuItem.vue和src\components\Menu\src\components\BasicSubMenuItem.vue两个文件中的代码中陷入了死循环。

**Comment by anncwb** [comment]
已经定位了，晚点会修复

**Comment by anncwb** [comment]
close 7a07b703d11af

**Comment by xin7c** [comment]
> 在Firefox中打断点，最终在src\components\Menu\src\components\BasicSubMenuItem.vue和src\components\Menu\src\components\BasicSubMenuItem.vue两个文件中的代码中陷入了死循环。

这俩不是一个么···？

**Comment by mynetfan** [comment]
> > 在Firefox中打断点，最终在src\components\Menu\src\components\BasicSubMenuItem.vue和src\components\Menu\src\components\BasicSubMenuItem.vue两个文件中的代码中陷入了死循环。
> 
> 这俩不是一个么···？

是一个，我复制错了。我以为closed没人看，所以就没改
