### ISSUE TITLE
modal will be covered by table

### ISSUE THREAD

**Issue by everstarmy** [anncwb/vue-vben-admin#160]
When the table is maximized, the modal will be out of sight behind the table

**Comment by anncwb** [comment]
Please give steps to reproduce, otherwise I cannot locate your problem

**Comment by mynetfan** [comment]
基础表格页面，在表格的标题“基础示例”的右边有一个icon，鼠标移上去会弹出一个tooltip，内容为“温馨提醒”。但是，当开启表格的全屏模式时（点击表格右上角的全屏按钮），鼠标移到这个icon上就看不到弹出的tooltip了。@everstarmy说的大概也是类似这种情况，比如：在表格右侧有一个操作列，每行都有一个button，点击后可以以modal的形式弹出行内容的表单以便修改。但是全屏模式下的表格点击这个按钮就看不到modal了。

**Comment by everstarmy** [comment]
@mynetfan Yes, that's what I mean.

**Comment by mynetfan** [comment]
@everstarmy You can try the getContainer property of Table。See:  https://2x.antdv.com/components/modal/#API

**Comment by anncwb** [comment]
Someone has already answered, you can try his method to solve it
