### ISSUE TITLE
modal组件高度问题

### ISSUE THREAD

**Issue by bangxingni** [anncwb/vue-vben-admin#161]
反复打开关闭后高度会慢慢增大

**Comment by anncwb** [comment]
请给复现步骤，否则这样我无法定位你的问题

**Comment by bangxingni** [comment]
禁用useWrapper 时
![image](https://user-images.githubusercontent.com/20875524/103594369-76345680-4f33-11eb-8889-7753f33ee65c.png)弹窗正常显示，内容过多默认会出现滚动条(正常), 采用默认配置时(useWrapper=true)，若内容不够撑开当前屏幕,不停的打开，关闭弹窗，弹窗会逐渐变大
![image](https://user-images.githubusercontent.com/20875524/103594499-cf03ef00-4f33-11eb-9969-6bc8b13c78d9.png)  ，内容足过多出现滚动条时弹窗正常

**Comment by anncwb** [comment]
closed 8d7d083
