### ISSUE TITLE
表格组件关于列设置的问题

### ISSUE THREAD

**Issue by jenifly** [anncwb/vue-vben-admin#162]
# 2.0.0-rc.15
1.表格首次加载的时候没有正确加载basiccolumn中的width属性，需要调用setcolumns或者在tablesetting里头点击显示/隐藏列才会生效
2.点击fixed时候出现空白列
![1b62db986058087188da7f5cfa5d2d5](https://user-images.githubusercontent.com/22962492/103521044-14cca300-4eb3-11eb-949d-684dd776cc57.png)
3.设置完fixed后，再点击显示/隐藏列，fixed会失效，tablesetting里头fixed未同步

希望添加一个方法控制Pagination的显示与隐藏

**Comment by anncwb** [comment]
1.给复现步骤或者截图
2. 需要设置宽度。留一列不设置
3.  a2c89d2e842beb9

控制Pagination的显示 `setShowPagination` |`getShowPagination`

另外。多个问题请分开提

**Comment by jenifly** [comment]
创建列：
```
<BasicTable @register="registerTable">

function getTestColumns(): BasicColumn[] {
  let columns = []
  for (let i = 0; i < 20; i++) {
    columns.push({
      title: 't' + i,
      width: 40,
      dataIndex: 'test' + i,
      defaultHidden: i % 2 === 0,
    })
  }
  return columns
}
const [registerTable] = useTable({
  api: pandectApi,
  columns: getTestColumns(),
  bordered: true,
 })
```
首次显示，有横向进度条
![微信截图_20210106192751](https://user-images.githubusercontent.com/22962492/103763791-4f6e4100-5055-11eb-9163-e0fc7247f8cb.png)
勾选t0后，列宽重新计算
![微信截图_20210106193149](https://user-images.githubusercontent.com/22962492/103764153-e76c2a80-5055-11eb-9e11-6c9f0dcd8922.png)
将t3，t5左fixed，这种情况下无论如何操作都出现空列
![微信截图_20210106193752](https://user-images.githubusercontent.com/22962492/103764623-c0622880-5056-11eb-968b-4e045e004672.png)
留一列不设置宽度
```
function getTestColumns(): BasicColumn[] {
  let columns = []
  columns.push({
    title: 't',
    dataIndex: 'test',
  })
  for (let i = 0; i < 20; i++) {
    columns.push({
      title: 't' + i,
      width: Math.max(40, i * 10),
      dataIndex: 'test' + i,
      defaultHidden: i % 2 === 0,
    })
  }
  return columns
}
```
首次显示，t列宽度占满表格
![微信截图_20210106194530](https://user-images.githubusercontent.com/22962492/103765282-e76d2a00-5057-11eb-97a3-b45fb89d31a6.png)
勾选t0后列表显示正常，fixed功能也正常
![微信截图_20210106195115](https://user-images.githubusercontent.com/22962492/103765691-8e51c600-5058-11eb-8540-6698d44254a7.png)
