### ISSUE TITLE
表格页尾合计

### ISSUE THREAD

**Issue by zn98com** [anncwb/vue-vben-admin#163]
表格页尾合计：
表格组件采用的是前端合计的方法，这对不分页表格适用。
但实际使用场景中，99%都是分页表格，更多的是后台把多页合计算出来，返给前台，前台直接显示，现表格合计无法实现直接显示后台合计。建议表格组件增加一个直接显示合计的方法。谢谢！

**Comment by anncwb** [comment]
summaryData
