### ISSUE TITLE
useI18n t function typing any

### ISSUE THREAD

**Issue by ac88** [anncwb/vue-vben-admin#164]
### environment

- **Packages**: vben-admin-2.0
- **Env**: tsc v4.1.2

### Steps to reproduce
```ts
import { useI18n } from '/@/hooks/web/useI18n';
import { getI18n } from '/@/setup/i18n';

const { t } = useI18n();
const i18n = getI18n();

//type error,Expected 1-3 arguments, but got 5.
i18n.global.t('component.form.input', 1, 2, 3, 4)
//no type error
t('component.form.input', 1, 2, 3, 4)
```

### Expected behaviour

useI18n的t 类型和i18n.global.t一样支持多参数重载

### Actual behaviour
useI18n的t实现最终成了 
```ts
const t: (key: string, ...arg: any) => string
```

### my solution

```ts
type I18nGlobalTranslation = {
  (key: string): string;
  (key: string, locale: string): string;
  (key: string, locale: string, list: unknown[]): string;
  (key: string, locale: string, named: Record<string, unknown>): string;
  (key: string, list: unknown[]): string;
  (key: string, named: Record<string, unknown>): string;
};

type I18nTranslationRestParameters = [string, any]

const tg: I18nGlobalTranslation = (key: string, ...arg: any[]) =>
  i18n.global.t(key, ...(arg as I18nTranslationRestParameters))
```

想讨论下看看有没有更好的解决方式

`Parameters`拿到的是overloads最后的一个参数类型，我只好复制了1份`i18n.global.t`的完整overloads类型

**Comment by anncwb** [comment]
Previously changed to `any` because vue-i18n-next broke the type. The reason why it hasn't changed is because the higher version requires vite plugin support. But the plug-in only supports vite2.0, the project has not been upgraded to vite2.0, so it has not been changed yet
