### ISSUE TITLE
表格组件列宽问题

### ISSUE THREAD

**Issue by jenifly** [anncwb/vue-vben-admin#165]
创建列：
```
<BasicTable @register="registerTable">

function getTestColumns(): BasicColumn[] {
  let columns = []
  for (let i = 0; i < 20; i++) {
    columns.push({
      title: 't' + i,
      width: 40,
      dataIndex: 'test' + i,
      defaultHidden: i % 2 === 0,
    })
  }
  return columns
}
const [registerTable] = useTable({
  api: pandectApi,
  columns: getTestColumns(),
  bordered: true,
 })
```
首次显示，有横向进度条
![微信截图_20210106192751](https://user-images.githubusercontent.com/22962492/103763791-4f6e4100-5055-11eb-9163-e0fc7247f8cb.png)
勾选t0后，列宽重新计算
![微信截图_20210106193149](https://user-images.githubusercontent.com/22962492/103764153-e76c2a80-5055-11eb-9e11-6c9f0dcd8922.png)
将t3，t5左fixed，这种情况下无论如何操作都出现空列
![微信截图_20210106193752](https://user-images.githubusercontent.com/22962492/103764623-c0622880-5056-11eb-968b-4e045e004672.png)
留一列不设置宽度
```
function getTestColumns(): BasicColumn[] {
  let columns = []
  columns.push({
    title: 't',
    dataIndex: 'test',
  })
  for (let i = 0; i < 20; i++) {
    columns.push({
      title: 't' + i,
      width: Math.max(40, i * 10),
      dataIndex: 'test' + i,
      defaultHidden: i % 2 === 0,
    })
  }
  return columns
}
```
首次显示，t列宽度占满表格
![微信截图_20210106194530](https://user-images.githubusercontent.com/22962492/103765282-e76d2a00-5057-11eb-97a3-b45fb89d31a6.png)
勾选t0后列表显示正常，fixed功能也正常
![微信截图_20210106195115](https://user-images.githubusercontent.com/22962492/103765691-8e51c600-5058-11eb-8540-6698d44254a7.png)
在设置fixed后希望重新点击显示/隐藏列还能保留设置的fixed状态
大佬辛苦~

**Comment by anncwb** [comment]
出现空列留一列不计算即可。 那一列很长是因为你的电脑屏幕可能太宽，把其他的列从40设置到100+应该就可以了。其他问题已修复
