### ISSUE TITLE
a bug of ApiSelect in FormSchema

### ISSUE THREAD

**Issue by cugliang** [anncwb/vue-vben-admin#167]
### Subject of the issue
a bug of ApiSelect in FormSchema
Describe your issue here.
use two apiselect in formschema,then it will cancel another api request.
{
    field: "field30",
    component: "ApiSelect",
    label: "远程下拉",
    required: true,
    componentProps: {
      api: optionsListApi,
    },
    colProps: {
      span: 8,
    },
    defaultValue: "0",
  },
  {
    field: "field31",
    component: "ApiSelect",
    label: "远程下拉1",
    required: true,
    componentProps: {
      api: optionsListApi1,
    },
    colProps: {
      span: 8,
    },
    defaultValue: "0",
  }

this is the message in console,and optionsListApi will be cancel.
\vue-vben-admin-2.0\src\components\Form\src\components\ApiSelect.vue:98 
### Your environment

- **Packages**: 
- **Env**: nodejs 12

### Steps to reproduce

Tell us how to reproduce this issue. Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub. This will get you the fastest support. 🎉

### Expected behaviour

What should happen?

### Actual behaviour

What happens instead?

**Comment by anncwb** [comment]
You can set removeAllHttpPending to false in projectSetting. Or add {headers:{ignoreCancelToken:false}} to the corresponding interface of ApiSelect
