### ISSUE TITLE
a bug in transformRequestData

### ISSUE THREAD

**Issue by cugliang** [anncwb/vue-vben-admin#168]
### Subject of the issue
a bug in transformRequestData
Describe your issue here.
if code ne ResultEnum.SUCCESS,eq ResultEnum.ERROR,the hasSuccess eq false,it can't go to execute if (code === ResultEnum.ERROR).
    const hasSuccess = data && Reflect.has(data, 'code') && code === ResultEnum.SUCCESS;
    if (!hasSuccess) {
      if (message) {
        // errorMessageMode=‘modal’的时候会显示modal错误弹窗，而不是消息提示，用于一些比较重要的错误
        if (options.errorMessageMode === 'modal') {
          createErrorModal({ title: t('sys.api.errorTip'), content: message });
        } else if (options.errorMessageMode === 'message') {
          createMessage.error(message);
        }
      }
      Promise.reject(new Error(message));
      return errorResult;
    }

    // 接口请求成功，直接返回结果
    if (code === ResultEnum.SUCCESS) {
      return result;
    }
    // 接口请求错误，统一提示错误信息
    if (code === ResultEnum.ERROR) {
      return errorResult;
    }
    // 登录超时
    if (code === ResultEnum.TIMEOUT) {
### Your environment

- **OS**: 
- **Packages**: 
- **Env**: 

### Steps to reproduce

Tell us how to reproduce this issue. Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub. This will get you the fastest support. 🎉

### Expected behaviour

What should happen?

### Actual behaviour

What happens instead?

**Comment by anncwb** [comment]
The logic of this file needs to be changed according to your own background. Here is just an example
