### ISSUE TITLE
\src\components\Table\src\components\TableAction.vue:74 Uncaught (in promise) TypeError: Cannot read property 'getColumns' of undefined

### ISSUE THREAD

**Issue by wanghongyan** [anncwb/vue-vben-admin#169]
### Subject of the issue

文件上传组件，选择文件后报错：
C:\Users\edz\Desktop\vue-vben-admin-2.0.0-rc.15\src\components\Table\src\components\TableAction.vue:74 Uncaught (in promise) TypeError: Cannot read property 'getColumns' of undefined

**Comment by anncwb** [comment]
已经修复,目前vite2在上传接口地址不能访问的时候会导致服务崩溃。所以测试需要保证上传接口存在
