### ISSUE TITLE
Homepage beautification

### ISSUE THREAD

**Issue by anncwb** [anncwb/vue-vben-admin#173]
Welcome to pr's beautiful and atmospheric homepage design interface.

The pages involved are:

- Dashboard
- Workbench Page
- Analysis page

Of course, you can also submit beautification codes for other pages.

**Comment by anncwb** [comment]
You can reply to the interface you want to submit below. So as not to repeat with others

**Comment by jenifly** [comment]
![微信截图_20210112151419](https://user-images.githubusercontent.com/22962492/104281811-08ff6300-54e9-11eb-82b6-23c2fca378a5.png)
滚动条可以微调一下哈，原版的被header盖住一截，强迫症不友好...
header固定的情况下设置按钮放右上角？全屏内容或其它情况固定在右中？
