### ISSUE TITLE
表格列设置和customRender 的问题

### ISSUE THREAD

**Issue by joeescn** [anncwb/vue-vben-admin#174]
### Subject of the issue

当表格列使用的是 customRender,打开showTableSetting之后,点击隐藏列后,将无法通过再次点击显示.

### Steps to reproduce
![image](https://user-images.githubusercontent.com/45593216/104184987-49aa9e00-544f-11eb-9c89-b2803436e9c9.png)
![image](https://user-images.githubusercontent.com/45593216/104185161-8d9da300-544f-11eb-8e4c-c0c346ccb26a.png)

### Expected behaviour && Actual behaviour

问题一:  列展示中,更新时间是否勾选,可以自由控制字段的显示和隐藏,当时用 customRender 渲染的取消勾选之后,无法重新勾选,只能提供重置恢复

问题二: 更新之后的这个时间戳方法(createNow),当 params 为空时,get 请求依然不会携带时间戳,当get 请求随意添加一个参数时,可以成功携带时间戳,这个是 bug 还是正常的?

```
export function getMenuListById() {
  return defHttp.request<getMenuListByIdParamsResultModel>({
    url: Api.GetMenu,
    method: 'GET',
    params: { id: '1' },
  });
}
export function getMenuListById() {
  return defHttp.request<getMenuListByIdParamsResultModel>({
    url: Api.GetMenu,
    method: 'GET',
  });
}

```

**Comment by anncwb** [comment]
问题1是最新的代码吗。

**Comment by anncwb** [comment]
问题1我这边测试没问题

**Comment by joeescn** [comment]
使用的是都是精简版的最新代码
https://github.com/anncwb/vben-admin-thin-next

**Comment by anncwb** [comment]
精简版还没同步。等请等待同步。还有多个问题分开提
