### ISSUE TITLE
表格添加行Demo

### ISSUE THREAD

**Issue by snihwxf** [anncwb/vue-vben-admin#175]
Table 编辑的行时可以添加行，添加后默认编辑状态，希望出一个Demo，现在的Demo里只有编辑，没有添加

**Comment by anncwb** [comment]
多点点demo。页面->表单->高级表单

**Comment by snihwxf** [comment]
有一个问题，如果 我在 初始化的时候 const data: any[] = []; 是个这样的空值，那么添加行的时候就没有反应，如果 const data: any[] = [
        {
          Id: snowUuid(),
          Name: '',
          Value: '',
          Type: 2,
        },
      ];初始化的时候是这样，就没有问题，但是一般情况在 新做的时候 这个data肯定是 []这样的吧
