### ISSUE TITLE
表格选择建议

### ISSUE THREAD

**Issue by snihwxf** [anncwb/vue-vben-admin#177]
当table左边有 checkbox 的时候，那么能不能只有勾选 checkbox的时候才可以多选，选择行的时候不要选择中 checkbox, 不然选择有 
![image](https://user-images.githubusercontent.com/31719079/104265641-02f98a00-54c9-11eb-86e9-53e0ece065ac.png)编辑的时候，这样我编辑多行的，全都选择中了，我要操作删除多行的时候，我要先把选中的行去掉再勾选要删除的行， 这样操作肯定不行，还有一个问题就是 当有选择行的时候 用刷新，选择的行不会去掉

**Comment by anncwb** [comment]
建议你好好看文档示例。这些都是有属性控制的
