### ISSUE TITLE
Tree table indentSize error

### ISSUE THREAD

**Issue by bangxingni** [anncwb/vue-vben-admin#178]
![image](https://user-images.githubusercontent.com/20875524/104275870-a43f0b00-54de-11eb-912c-d6e1df48ba3a.png)
新版修改了样式,block覆盖了原本的inline，table为树结构时indentSize 不生效
before
![image](https://user-images.githubusercontent.com/20875524/104276198-5bd41d00-54df-11eb-88b8-6188ad8c8220.png) 
after
![image](https://user-images.githubusercontent.com/20875524/104276391-b66d7900-54df-11eb-8f57-41250de01bb8.png)

**Comment by anncwb** [comment]
close cdf0a60
