### ISSUE TITLE
表格组件发起额外的错误请求与组件高度问题

### ISSUE THREAD

**Issue by jenifly** [anncwb/vue-vben-admin#179]
2021-01-11提交之后，使用表格远程排序、pagination翻页、切换pageSize等需要请求api的操作时，会额外发起一次page=0的错误请求，使用SearchForm的查询按钮正常，如下：
- 使用SearchForm的查询按钮，高度正常
![微信截图_20210112145503](https://user-images.githubusercontent.com/22962492/104280128-6645e500-54e6-11eb-9ad1-70a01953fe7a.png)

- 跳转第二页，额外发起page=0的错误请求，导致表格重置，422错误是做了校验，page需为大于0的整数
![微信截图_20210112145604](https://user-images.githubusercontent.com/22962492/104280137-69d96c00-54e6-11eb-9689-9aa24d496b79.png)

- 再次查询按钮，高度出错
![微信截图_20210112145629](https://user-images.githubusercontent.com/22962492/104280144-6cd45c80-54e6-11eb-9d99-0c9db83b9fa8.png)

平台：win10x64
vite：2.0.0-beta.23
表格配置：
```
const testColumns: BasicColumn[] = [
  {
    title: '日期',
    dataIndex: 'date',
    width: 106,
    sorter: true,
  },
  ...
]
const [registerTable] = useTable({
  api: getTestDatatApi,
  size: 'small',
  columns: testColumns(),
  bordered: true,
  useSearchForm: true,
  beforeFetch: (query) => {
    query.total = true,
    query.start = '2020-11-11'
    query.end = '2020-11-22'
    if (query.order) query.order = query.order.replace('end', '')
  },
  immediate: false,
  showTableSetting: true,
})

```
建议
1.如果发起了错误的请求，表格不再往下执行渲染。具体表现为：已经加载了一页数据，不会因为发起了错误的api请求而导致表格清空。
2.在分页组件已正确加载后，执行分页跳转、排序等不改变分页组件total的情况下，api结果中的total参数可以忽略。也就是说，api结果中的total用于初始化分页组件，当分页组件加载完成后total便为非必要参数，当新的total传来且和当前分页组件中的total不同时，再重新渲染，相同时忽略。这样便不需要每次都在数据库中查询总条数。

**Comment by anncwb** [comment]
1. 错误的api请求是要清空的。这点不会改变。你得改变后台，不能因为后台的错误来让前台兼容。
2. total这个后台可以做缓存，不会因为这个增加这块的复杂性。翻到会引起其他的不必要问题。
3. page=0我实在想不到你是什么样的情况下出现的。按照示例我没复现出这个问题

**Comment by jenifly** [comment]
谢谢建议哈，受教了。
page=0是因为我开启了pagination，但是api返回值中没有total，-_-||

**Comment by jenifly** [comment]
谢谢建议哈，受教了
page=0是因为我开启了pagination，但api返回值中没有total...-_-||。这也不应该额外发起一次page=0的请求啊
目标：useDataSource.ts
![微信截图_20210113112008](https://user-images.githubusercontent.com/22962492/104402488-5d5e1d80-5591-11eb-8a47-a164f725a846.png)
