### ISSUE TITLE
如何通过表格的 formConfig 向表单中加入 #resetBefore 插槽

### ISSUE THREAD

**Issue by rungroo** [anncwb/vue-vben-admin#185]
table 自带的表单（formConfig）功能非常好用，但表单的按钮只限定了submit和reset，如何自定义加入按钮呢？
页面 template 中只写了table，表单是通过 formConfig 注入的，没法在 template 中加入 #resetBefore 插槽。

**Comment by anncwb** [comment]
使用 form-resetBefore插槽  文档有

**Comment by rungroo** [comment]
> 使用 form-resetBefore插槽 文档有

 form 的 resetBefore 需要在 template 中使用，table只能通过 formConfig 配置内置表单的属性，没法重写slot。或者有没有其他的办法改写代码？

**Comment by anncwb** [comment]
不是说了吗  form-resetBefore  这个插槽  哪里没有template  不然你表格怎么写的

**Comment by anncwb** [comment]
好好看下表格的插槽文档

**Comment by rungroo** [comment]
找到了，翻了半天没看到是我大意了，多谢！
