### ISSUE TITLE
BasicModal 生产环境下Bug

### ISSUE THREAD

**Issue by sjhsww** [anncwb/vue-vben-admin#186]
### Subject of the issue

Describe your issue here.
 BasicModal 生产环境下confirm-loading 属性无效  不会有loading状态,开发环境正常
### Your environment

- **OS**: 
- **Packages**: 
- **Env**: 

### Steps to reproduce

Tell us how to reproduce this issue. Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub. This will get you the fastest support. 🎉

### Expected behaviour

What should happen?

### Actual behaviour

What happens instead?

**Comment by anncwb** [comment]
我测试了下可以正常使用

**Comment by anncwb** [comment]
没有提供更详细的信息，我先关闭了。你有更详细的信息可以重新打开
