### ISSUE TITLE
表单 setFieldsValue 函数为空

### ISSUE THREAD

**Issue by rungroo** [anncwb/vue-vben-admin#192]
场景是希望在table内置form中，提交数据前改写某个field的值。

所以我将 submitFunc() 改写为 submitFunc(Ref<FormActionType>)：
```
submitFunc?: (formRef: Ref<FormActionType>) => Promise<void>;
```
useFormEvents.ts
```
  async function handleSubmit(e?: Event): Promise<void> {
    e && e.preventDefault();
    const { submitFunc } = unref(getProps);
    if (submitFunc && isFunction(submitFunc)) {
      await submitFunc(formElRef);
      return;
    }
    // ...
  }
```

在view中自定义 submitFunc，从参数里拿到 form 实体，但这个实体只有 getFieldsValue 没有 setFieldsValue，无法改写表单值。

请问这是什么原因，或者有没有其他办法。

**Comment by anncwb** [comment]
const [register,{getForm}]=useTable()  用这个getForm操作表单就可以

**Comment by snihwxf** [comment]
![image](https://user-images.githubusercontent.com/31719079/104989709-fab7c680-5a55-11eb-8ae4-83251616a5ef.png)
这个需要引用那个呢
