### ISSUE TITLE
表格搜索,若没有搜索到记录后, 序号变负数

### ISSUE THREAD

**Issue by zn98com** [anncwb/vue-vben-admin#198]
https://user-images.githubusercontent.com/10260081/104833644-22335580-58d5-11eb-8c8a-6c43c1b43a4e.mp4

**Comment by anncwb** [comment]
这个是最新代码？

**Comment by zn98com** [comment]
最新代码，找到原因了，是谷歌解译软件问题。



成都赛珂琪科技有限公司

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "anncwb/vue-vben-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月17日(星期天) 晚上11:08
收件人:&nbsp;"anncwb/vue-vben-admin"<vue-vben-admin@noreply.github.com&gt;;
抄送:&nbsp;"智能软件"<zn98@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [anncwb/vue-vben-admin] 表格搜索,若没有搜索到记录后, 序号变负数 (#198)





 
这个是最新代码？

**Comment by zn98com** [comment]
刚才又发现，最新版还是有这问题。序号变负



成都赛珂琪科技有限公司

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "anncwb/vue-vben-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月18日(星期一) 上午9:22
收件人:&nbsp;"anncwb/vue-vben-admin"<vue-vben-admin@noreply.github.com&gt;;
抄送:&nbsp;"智能软件"<zn98@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [anncwb/vue-vben-admin] 表格搜索,若没有搜索到记录后, 序号变负数 (#198)





 
Closed #198.

**Comment by anncwb** [comment]
我在最新的代码没有复现出这个问题。可以提供下更具体的步骤或者配置？

**Comment by zn98com** [comment]
成都赛珂琪科技有限公司






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "anncwb/vue-vben-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月18日(星期一) 上午10:56
收件人:&nbsp;"anncwb/vue-vben-admin"<vue-vben-admin@noreply.github.com&gt;;
抄送:&nbsp;"智能软件"<zn98@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [anncwb/vue-vben-admin] 表格搜索,若没有搜索到记录后, 序号变负数 (#198)





 
我在最新的代码没有复现出这个问题。可以提供下更具体的步骤或者配置？

**Comment by morning-reading** [comment]
其实我的也出现这种序号为负数情况！

**Comment by morning-reading** [comment]
![image](https://user-images.githubusercontent.com/19794192/104976294-d77e1e80-5a37-11eb-82a8-ca5ce6b5b79f.png)

**Comment by anncwb** [comment]
先升级最新版。然后给复现步骤。你们这个不是最新的。

**Comment by anncwb** [comment]
前面应该是在这次提交修复了056fc131168c4e900e9257c3e03257a390c3d3ba
