### ISSUE TITLE
antdesign 按需加载总是不生效 会不会是vite 项目有专门的设置方法

### ISSUE THREAD

**Issue by zg08** [anncwb/vue-vben-admin#205]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by anncwb** [comment]
没明白你的意思。项目不是可以
