### ISSUE TITLE
支持多系统集成-url单独显示标签页内容

### ISSUE THREAD

**Issue by worldofchu** [anncwb/vue-vben-admin#209]
例如 ABC三个独立vue系统，A 没啥业务功能，但是菜单挂载 B 和C的 业务标签内容。
A B  C 分别独立部署在三个服务器。
A配置菜单
B1  http://www.b.com/B1?onlytab=1
B2http://www.b.com/B2?onlytab=1
C1 http://www.b.com/C1?onlytab=1
本身 http://www.b.com/B1  对应B系统的 页码，但是此时肯定把菜单栏啊 顶部栏 侧边栏 都显示了。我想加上参数例如onlytab=1 让B1对应页面 只展示本身标签页里面的内容，这样在A系统挂菜单时候 直接加载这个页面。

**Comment by anncwb** [comment]
https://github.com/anncwb/vue-vben-admin/blob/0cc9f61f6a5ccad48224022f464aa4a5e2838083/src/settings/projectSetting.ts#L31

设置为true

**Comment by worldofchu** [comment]
这个参数设置之后 ，是不是 独立部署的B系统就 无法使用自身菜单单独展示了是吧？其实我是想 A 挂几个B的页面，但是B系统也可以同时 用自身的菜单来独立展示。。。

**Comment by worldofchu** [comment]
谢谢！额外问个基本语法 我看html 文件  <title><%= title %></title>
 这个 <%=  是属于哪个组件 或者插件的？虽然和aspx语法一样，但是这个肯定不是aspx了。这个也不是vue啊

**Comment by anncwb** [comment]
vite-plugin-html. ejs语法

**Comment by worldofchu** [comment]
谢谢！
