### ISSUE TITLE
关于表单自适应

### ISSUE THREAD

**Issue by hjleochen** [anncwb/vue-vben-admin#212]
首先感谢您精彩的工作。

请教一下，在小屏的情况下能否有参数把表单变成纵向呢？就是label和input各自单独一行。如下图字段0

(目前label 和input各自有： width: 100px 和 width: calc(100% - 100px);）

多谢。

![image](https://user-images.githubusercontent.com/21806/105465534-feee1900-5ccd-11eb-8f87-ca00f4a06172.png)

**Comment by hjleochen** [comment]
oo，其实自己写css控制一下应该就可以了。

**Comment by shuperry** [comment]
表单自适应两种方案，一种是 css 控制，一种是表单使用栅格式布局，然后配置参数实现，这两个方法哪个比较好些?

**Comment by anncwb** [comment]
目前表单都是用span来控制的。可以改成 对应的响应式断点来设置即可。参考这个https://2x.antdv.com/components/grid-cn#API
例：

当前的表单schma:
```ts
{
   colProps:{span:12} 
}
```

改为:
```ts
{
   colProps:{lg:12,sm:24} 
}
```
