### ISSUE TITLE
三级菜单切换，页面内setup执行两次

### ISSUE THREAD

**Issue by cdxxiaomao** [anncwb/vue-vben-admin#215]
版本：’2.0.0-rc.17‘
问题：当在三级菜单下，切换到另外的三级菜单。会出现setup执行两次的情况。
操作步骤：进入基础表格，点击进入基础表单。再次点击进入基础表格，这个时候就会发现，基础表格下的setup就执行了两次，有两次打印输出。其实这个时候，任何一个三级菜单下的页面都会执行两次。

**Comment by anncwb** [comment]
https://github.com/vuejs/vue-router-next/issues/626 可能需要等这个问题被修复才能使用

**Comment by anncwb** [comment]
目前不报错的方式：
1. 尽量不用3级菜单
2. 如果需要3级菜单，可以将路由设置两级，菜单3级
3. 关闭keepAlive
4. 3级菜单全部开启keepalive

**Comment by shuperry** [comment]
@anncwb  vue-router 已有升级版本，感觉可以升级试试看了.
