### ISSUE TITLE
table使用fixed会导致列表布局错乱

### ISSUE THREAD

**Issue by sjhsww** [anncwb/vue-vben-admin#216]
### Subject of the issue

Describe your issue here.
![image](https://user-images.githubusercontent.com/30516589/105794066-378b3c80-5fc5-11eb-8b2f-06aa547894e3.png)

### Your environment

- **OS**: 
- **Packages**: 
- **Env**: 

### Steps to reproduce

Tell us how to reproduce this issue. Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub. This will get you the fastest support. 🎉

### Expected behaviour

What should happen?

### Actual behaviour

What happens instead?

**Comment by anncwb** [comment]
请提供复现代码，否则我帮不到你
