### ISSUE TITLE
关于弹窗Modal的数据传输问题

### ISSUE THREAD

**Issue by CannotTell** [anncwb/vue-vben-admin#220]
>内外数据交互,外部通过 transferModalData 发送，内部通过 receiveDrawerDataRef 接收。该数据具有响应式
```js
useModal((data: any) => {
  consoloe.log(data);
});
```

你好，我看文档上Modal能接收外部传过来的数据，请问一下有将数据回传外部的方法吗？

**Comment by mynetfan** [comment]
查阅Vue的组件事件章节。
https://vue3js.cn/docs/zh/guide/component-custom-events.html#%E4%BA%8B%E4%BB%B6%E5%90%8D
