### ISSUE TITLE
关于上传的问题

### ISSUE THREAD

**Issue by snihwxf** [anncwb/vue-vben-admin#221]
现在的上传是用的这一个接口
VITE_PROXY=[["/upload","http://localhost:3001/upload"]]
如果 我上传要用到不同的接口，处理不同的数据的时候，应该怎么处理？

**Comment by anncwb** [comment]
这个只是示例，你可以把多个接口都写这里。也可以直接传入上传组件

**Comment by erniu** [comment]
> 这个只是示例，你可以把多个接口都写这里。也可以直接传入上传组件

理论上来讲，配置文件用来存储一些不变的可能会复用的一些东西，实际在业务中肯定会遇到多套不同的上传功能，比如图片上传、文件上传、视频上传，服务端可能会按业务拆开成不同的接口。

基于以上这种情形，如果都写在配置文件里面是不是不太合理啊？毕竟一个是具体的业务，一个是配置
