### ISSUE TITLE
BasicTable关于TableAction问题

### ISSUE THREAD

**Issue by joeescn** [anncwb/vue-vben-admin#227]
![image](https://user-images.githubusercontent.com/45593216/106385840-2bf8a500-640d-11eb-927c-571515132622.png)

![image](https://user-images.githubusercontent.com/45593216/106385937-a1fd0c00-640d-11eb-9448-4d8e64410db7.png)

列设置隐藏任意列后,用TableAction设置的操作列会自动取消,且无法恢复

### Subject of the issue

BasicTable关于TableAction问题

### Your environment

- **OS**: 
- **Packages**: 最新 精简版代码
- **Env**: 

### Code
``` 
<BasicTable @register="registerTable">
    <template #action="{ record }">
      <TableAction :actions="actions(record)" :dropDownActions="dropDownActions(record)" />
    </template>
  </BasicTable>
```

**Comment by anncwb** [comment]
能提供具体错误截图吗，没明白你的错误

**Comment by joeescn** [comment]
我只是点了下更新时间的列复选框,但是操作列也被隐藏了,而且操作列前面的复选框无法再次选中

**Comment by anncwb** [comment]
操作列应该不会出现在列配置上面把，你自己加上去的？

**Comment by joeescn** [comment]
可以了 谢谢 我把操作列 放到columns里面了
