### ISSUE TITLE
Dynamic Api for ApiSelect

### ISSUE THREAD

**Issue by cugliang** [anncwb/vue-vben-admin#229]
### Subject of the feature

Describe your issue here.
we use two ApiSelect for two fields in FormSchema,
sometimes,we need change the api prop and params prop of ApiSelect for dynamic,just as we select one option of ApiSelect A,then ApiSelect B will clear all options then fetch data from server with the new param.
but we don't know how to solve it with the api and prop,try and try again,but nothing got.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by anncwb** [comment]
Can you post your code？

**Comment by cugliang** [comment]
var schema1: FormSchema = {
  field: "vsid",
  component: "ApiSelect",
  label: "VS",
  itemProps: {
    labelCol: { span: 14 },
    wrapperCol: { span: 10 },
  },
  colProps: {
    span: 12,
  },
  componentProps: {
    //api:selListApi1234,//set and dont set here is the same.
    labelField: "name",
    valueField: "id",
    placeholder: "选择VS",
  },
};

var schemas:FormSchema[]=[
{
      field: "typeid",
      component: "ApiSelect",
      label: "类型",
      componentProps: ({ formModel }) => {
        return {
          numberToString: false,
          api: dicTypeApi,
          labelField: "name",
          valueField: "id",
          placeholder: "选择项目类型",
          onChange: (e: number) => {
            schema1.componentProps = {
                api: selListApi,
                params: { id: e },
                resultField: "list",
                labelField: "name",
                valueField: "id",
                placeholder: "选择VS",
              };

	removeSchemaByFiled(schema1.field);//success
      	//updateSchema(schema1);    //fail to fetch,if change label,it will change the label of apiselect
      	appendSchemaByField(schema1, "typeid", false);//fail to fetch
            }
          },
        };
      },
    },
schema1,
]

**Comment by anncwb** [comment]
1. Don't mess with the code format
2. Make your question clear
3. What you expect

**Comment by anncwb** [comment]
I will close it first until you can clarify your question

**Comment by flyingfishzxf** [comment]
@cugliang 请问你这个问题解决了吗？我现在也遇到这个问题，在 issues 里面都找不到别人问这个问题，难道大家都会？找到你的发现也没有答案
