### ISSUE TITLE
<img src="/@/assets/images/dashboard/wokb/wokb.png" class="workbench__wokb-img mb-3" />

### ISSUE THREAD

**Issue by shijingyan** [anncwb/vue-vben-admin#231]
### Subject of the issue

Describe your issue here.

### Your environment

- **OS**: 
- **Packages**: 
- **Env**: 

### Steps to reproduce

Tell us how to reproduce this issue. Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub. This will get you the fastest support. 🎉

### Expected behaviour

What should happen?

### Actual behaviour

What happens instead?

**Comment by shijingyan** [comment]
在window上图片加载不出来，在mac上可以。希望解决一下哈。

**Comment by anncwb** [comment]
vite的问题，可以向vite提issue
