### ISSUE TITLE
【BasicTable】当设置为可编辑行或可编辑单元格的一些bug

### ISSUE THREAD

**Issue by quanzaiyu** [anncwb/vue-vben-admin#235]
## 问题一

描述：当设置为可编辑行时，取消编辑，获取的是编辑后的值，而不是编辑前的值

期望：取消编辑后，恢复编辑前的值

![GIF](https://user-images.githubusercontent.com/13745132/106723482-1d470380-6642-11eb-82ef-ab46c2302460.gif)

## 问题二

描述：当设置 `editRow: true` 时，无法使用自定义插槽进行渲染

期望：可编辑行与自定义插槽可以共存并生效

![image](https://user-images.githubusercontent.com/13745132/106724202-e3c2c800-6642-11eb-8679-cd56efb9e35a.png)

![image](https://user-images.githubusercontent.com/13745132/106724230-f0472080-6642-11eb-9220-c1439cab0a5f.png)

**Comment by anncwb** [comment]
问题二不支持
