### ISSUE TITLE
【BasicForm】当component设置为ImageUpload时无法渲染

### ISSUE THREAD

**Issue by quanzaiyu** [anncwb/vue-vben-admin#236]
问题：当component设置为ImageUpload时无法渲染

示例代码：

```typescript
const schemas: FormSchema[] = [
  {
    field: 'field1',
    component: 'ImageUpload',
    label: '字段1'
  },
];
```

结果：通过useForm注册后无法在视图中渲染此组件。

期望结果：注册后，视图中正常渲染图片上传组件。

**Comment by anncwb** [comment]
示例不是正常吗

**Comment by quanzaiyu** [comment]
就直接在示例里面修改，未能正常渲染此组件

**Comment by anncwb** [comment]
没有这个组件。忘记删了

**Comment by quanzaiyu** [comment]
建议提供此组件，可以进行拖拽上传、手动选择文件上传的功能。UI可以参考：

![image](https://user-images.githubusercontent.com/13745132/107134950-8627c780-6931-11eb-88d9-d9b58ef9d748.png)
