### ISSUE TITLE
【BasicForm】自定义resetFunc，事件无限触发造成页面假死

### ISSUE THREAD

**Issue by quanzaiyu** [anncwb/vue-vben-admin#239]
问题：当自定义resetFunc方法，此方法将无限被触发，造成页面假死

示例代码：

```typescript
    let icon = ref<string>('')

    const [registerForm, { getFieldsValue, resetFields, setFieldsValue }] = useForm({
      labelWidth: 120,
      schemas: categoryFormSchemas,
      actionColOptions: {
        span: 24,
      },
      submitButtonOptions: {
        text: '添加',
      },
      resetButtonOptions: {
        text: '清空数据',
      },
      resetFunc: async () => {
        icon.value = ''
        await resetFields()
        console.log(getFieldsValue())
        console.log(icon)
      },
    })
```

效果：

![GIF](https://user-images.githubusercontent.com/13745132/106978642-999f2b00-6797-11eb-9158-c4926a0509b1.gif)

从图中可以看到，控制台在无限打印，说明`resetFunc` 被无限调用。刷新浏览器，发现页面无响应，页面假死。

期望：事件只调用一次

**Comment by JohnNiang** [comment]
你的 resetFunc 中调用了 resetFields 方法导致的无限循环。

源码如下：

```ts
  async function resetFields(): Promise<void> {
    const { resetFunc, submitOnReset } = unref(getProps);
    resetFunc && isFunction(resetFunc) && (await resetFunc());

    const formEl = unref(formElRef);
    if (!formEl) return;

    Object.keys(formModel).forEach((key) => {
      formModel[key] = defaultValueRef.value[key];
    });
    clearValidate();
    emit('reset', toRaw(formModel));
    submitOnReset && handleSubmit();
  }
```

**Comment by quanzaiyu** [comment]
经试验，仅当在 `resetFunc` 中调用 `resetFields` 时会无限触发，换为 `setFieldsValue` 并不会触发此问题。

使用 `resetFields`，无限触发，页面假死：

```
      resetFunc: async () => {
        icon.value = ''
        await resetFields()
        console.log(getFieldsValue())
        console.log(icon)
      },
```

使用 `setFieldsValue` ，work well：

```typescript
        resetFunc: async () => {
          icon.value = ''
          await setFieldsValue({
            icon: '',
          })
          console.log(getFieldsValue())
          console.log(icon)
        },
```

但这样的话，比较麻烦，必须将所有字段全部加到参数中重置。

**Comment by JohnNiang** [comment]
你不必在 resetFunc 中调用 resetFields 方法，因为 resetFields 方法本身就为你重置好了 model 的操作。

**Comment by quanzaiyu** [comment]
> 你不必在 resetFunc 中调用 resetFields 方法，因为 resetFields 方法本身就为你重置好了 model 的操作。


如若不调用 `resetFields`，会发现数据并未清空

```typescript
        resetFunc: async () => {
          icon.value = ''
          console.log(getFieldsValue())
          console.log(icon)
        },
```

控制台打印结果如下：

![image](https://user-images.githubusercontent.com/13745132/106980104-8cd00680-679a-11eb-9871-cd0739778055.png)

**Comment by JohnNiang** [comment]
> > 你不必在 resetFunc 中调用 resetFields 方法，因为 resetFields 方法本身就为你重置好了 model 的操作。
> 
> 如若不调用 `resetFields`，会发现数据并未清空
> 
> ```ts
>         resetFunc: async () => {
>           icon.value = ''
>           console.log(getFieldsValue())
>           console.log(icon)
>         },
> ```
> 
> 控制台打印结果如下：
> 
> ![image](https://user-images.githubusercontent.com/13745132/106980104-8cd00680-679a-11eb-9871-cd0739778055.png)

请看我刚才发的源码，执行 resetFunc 的时候还没有真正清空 model，所以你在 resetFunc 中还能看到此前的数据。

**Comment by quanzaiyu** [comment]
> 你不必在 resetFunc 中调用 resetFields 方法，因为 resetFields 方法本身就为你重置好了 model 的操作。

搞明白了，自定义的 resetFunc 会在前面执行，然后才清空model数据。

非常感谢！

**Comment by quanzaiyu** [comment]
![image](https://user-images.githubusercontent.com/13745132/106980537-547cf800-679b-11eb-8a29-5f8c858fae3e.png)

点一下“添加”按钮就看得出来了，数据校验提示已经显现，说明数据已被清空。
