### ISSUE TITLE
【BasicForm】当组件设置为Upload的时候，multiple属性无效

### ISSUE THREAD

**Issue by quanzaiyu** [anncwb/vue-vben-admin#240]
问题描述：当组件设置为Upload的时候，multiple属性无效，设置为false仍然可以添加多个文件。

示例代码：

![Snipaste_2021-02-05_14-57-55](https://user-images.githubusercontent.com/13745132/107000513-f6fca180-67c2-11eb-8447-908450c39211.png)

结果：

![Snipaste_2021-02-05_14-58-34](https://user-images.githubusercontent.com/13745132/107000524-fcf28280-67c2-11eb-9273-a18b04c6b655.png)

![image](https://user-images.githubusercontent.com/13745132/107000665-388d4c80-67c3-11eb-9aeb-852a0bf230de.png)

从控制台打印可以看出，添加的是多个文件：

![image](https://user-images.githubusercontent.com/13745132/107000795-6ffbf900-67c3-11eb-950d-fcb77bc72b7d.png)

预期结果：将multiple设置为false时，只能上传并保存一个文件。

**Comment by quanzaiyu** [comment]
尝试使用 `maxNumber` 属性控制，只是单次选择的时候有效，最终仍然能够选择多个文件

```typescript
    componentProps: {
      multiple: false,
      emptyHidePreview: true,
      maxSize: 50,
      maxNumber: 1,
      api: async (file: any) => {
        const res = await uploadToOss(file.file, 'cover')
        return { data: res }
      },
    },
```

效果：

![GIF](https://user-images.githubusercontent.com/13745132/107007487-8eff8880-67cd-11eb-9098-57abc9536b8a.gif)

**Comment by anncwb** [comment]
multiple是选择文件的时候可以多选，如果要限制文件上传数量,应该用maxNumber,这个是bug，我等会修复

**Comment by Mr-LiuDC** [comment]
我如果多选文件，会多次调用上传接口，请问怎样才能在一次请求中同时上传多个文件？

**Comment by Darkingtail** [comment]
`
  {
    field: 'logoFileId',
    label: '模组图标',
    component: 'ImageUpload',
    componentProps: (props) => {
      return {
        api: uploadOrDownloadModule,
        maxSize: 2,
        maxCount: 1,
        resultField: 'result',
      };
    },
    rules: [
      {
        required: true,
        trigger: 'change',
        type: 'array',
        message: '请上传模组图标',
        validator(rule, value) {
          console.log(value);
          return !value ? Promise.reject() : Promise.resolve();
        },
      },
    ],
  },`

**Comment by Darkingtail** [comment]
{ field: 'logoFileId', label: '模组图标', component: 'ImageUpload', componentProps: (props) => { return { api: uploadOrDownloadModule, maxSize: 2, maxCount: 1, resultField: 'result', }; }, rules: [ { required: true, trigger: 'change', type: 'array', message: '请上传模组图标', validator(rule, value) { console.log(value); return !value ? Promise.reject() : Promise.resolve(); }, }, ], },


form这个字段一直校验没有的，应该怎么给他赋值啊
