### ISSUE TITLE
使用yarn安装依赖一直报错，项目无法运行

### ISSUE THREAD

**Issue by jin974319** [anncwb/vue-vben-admin#241]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vben-admin@2.0.0-rc.17 dev: `vite`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vben-admin@2.0.0-rc.17 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bang\AppData\Roaming\npm-cache\_logs\2021-02-05T07_04_03_466Z-debug.log

**Comment by quanzaiyu** [comment]
建议尝试删除 node_modules 目录，再尝试安装。或者尝试使用以下命令重新安装：

```
yarn reinstall
```

手动删除node_modules较慢，可以使用命令：

```
yarn clean:lib
```

**Comment by quanzaiyu** [comment]
如果是网络问题，建议换源
