### ISSUE TITLE
【BasicForm】当组件设置为Upload的时候，添加accept属性报错

### ISSUE THREAD

**Issue by quanzaiyu** [anncwb/vue-vben-admin#242]
问题描述：当组件设置为Upload的时候，添加accept属性，点击上传框，无响应，在控制台中报错。

示例代码如下：

![Snipaste_2021-02-05_15-59-24](https://user-images.githubusercontent.com/13745132/107005843-43e47600-67cb-11eb-94d7-d06a600a20b9.png)

参数设置参看的是官方文档：

![image](https://user-images.githubusercontent.com/13745132/107006267-d8e76f00-67cb-11eb-8dda-8c0acbb2009d.png)

即使按照MIME类型设置，依然报错：

![image](https://user-images.githubusercontent.com/13745132/107006344-f61c3d80-67cb-11eb-810a-2529ab50d0bb.png)

效果：点击“上传”框，控制台打印出错误：

![image](https://user-images.githubusercontent.com/13745132/107005825-3e872b80-67cb-11eb-9e08-57df2418a5a1.png)

期望结果：accept属性控制上传框的格式，并正确执行。

**Comment by anncwb** [comment]
文档写错,accept是个数组 ['.png','.jpeg']

**Comment by quanzaiyu** [comment]
> 文档写错,accept是个数组 ['.png','.jpeg']

自定义格式中多了一个 `.` ：

![image](https://user-images.githubusercontent.com/13745132/107135015-2b42a000-6932-11eb-906c-698131f53ed1.png)

注意看上图，有两个 `.` ，导致未找到文件。

就不开新的issue了，稍微修改下就行了

**Comment by quanzaiyu** [comment]
直接在参数中去掉 `.` 亦可：

![image](https://user-images.githubusercontent.com/13745132/107135103-ec611a00-6932-11eb-934e-231b82ae79ed.png)

**Comment by anncwb** [comment]
可以 我没注意到
