### ISSUE TITLE
BasicForm updateSchema操作更新Select引起validator一直通不过

### ISSUE THREAD

**Issue by CannotTell** [anncwb/vue-vben-admin#243]
BasicForm 里直接定义Select能正常使用，但是一旦updateSchema了字段后validator一直通不过。
版本：2.0.0-rc.17
![image](https://user-images.githubusercontent.com/9131290/107013227-0be23080-67d5-11eb-85ce-debb982759f1.png)
![image](https://user-images.githubusercontent.com/9131290/107013395-3df39280-67d5-11eb-9bf2-cf8ecb42c1da.png)
![image](https://user-images.githubusercontent.com/9131290/107013404-40ee8300-67d5-11eb-8679-c430eb3bc462.png)

**Comment by anncwb** [comment]
如果你想动态修改rule，可以尝试使用dynamicRules 这个配置。示例也有

**Comment by CannotTell** [comment]
其实并不只是修改rule，我主要是想更新option下拉列表

**Comment by anncwb** [comment]
我看着是可以的， defaultValue不能通过updateSchema来更新。它只作用一次。rule可以用dynamicRules。你更改options可以只写下面这样即可

```ts
updateSchema({
filed:"school",
components:{
options:[xxxx]
}
})

```

**Comment by CannotTell** [comment]
好的  感谢，我试上一试
