### ISSUE TITLE
updateSchema无效

### ISSUE THREAD

**Issue by zn98com** [anncwb/vue-vben-admin#244]
![image](https://user-images.githubusercontent.com/10260081/107023675-ec053980-67e1-11eb-8dd5-b8cedd6eb2a1.png)

    {
      field: 'ys',
      component: 'Select',
      label: '医师',
      colProps: { span: 4 },
      labelWidth: 50,
      componentProps: ({ formModel, schema }: any) => {
        return {
          allowClear: false,
          options: [],
          onSelect: (ys: string) => {
            setYsSelect(refForm, yss, ys);
          },
          onKeydown: (e: any) => {
            if (e.key === 'Enter') {
              nextTick(async () => {
                skqTableQuery.value.vxeInput.focus(); //聚焦检索框
              });
            }
          },
        };
      },
    },

动态加载方法：
async function setKsSelect(refForm: any, formModel: any, yss: any[], ks: any) {
//   const ksyss = yss[ks]; //当前科室医生
    const ksyss = [
      { label: '李四', value: '李四', ghf: 3 },
      { label: '张三', value: '张三', ghf: 4 },
    ];
  let ysSchema = refForm.value.getSchema.filter((f: any) => f.field === 'ys')[0];
  ysSchema.componentProps.options = ksyss;
  await refForm.value.updateSchema(ysSchema);
//   formModel.ys = ksyss[0].value;
//   formModel.ghf = ksyss[0].ghf;
//   setYsSelect(refForm, yss, formModel.ys);
}

**Comment by guojoa** [comment]
我也遇到这个问题，我用的是TreeSelect.
updateSchema({
          field: 'pid',
          componentProps: {
            treeData,
            value: defaultvalue,
            // defaultValue: defaultvalue,
            // treeCheckable: true,
            onSelect: (value, node, extra) => {
              console.log('value', value);
              console.log('node', node);
              console.log('extra', extra);
            },
          },
        });
传两个值，treeData和value。treeData有效果。但value一直不起作用

**Comment by anncwb** [comment]
> 我也遇到这个问题，我用的是TreeSelect.
> updateSchema({
> field: 'pid',
> componentProps: {
> treeData,
> value: defaultvalue,
> // defaultValue: defaultvalue,
> // treeCheckable: true,
> onSelect: (value, node, extra) => {
> console.log('value', value);
> console.log('node', node);
> console.log('extra', extra);
> },
> },
> });
> 传两个值，treeData和value。treeData有效果。但value一直不起作用

value是组件的值，不能通过props修改

**Comment by anncwb** [comment]
> ![image](https://user-images.githubusercontent.com/10260081/107023675-ec053980-67e1-11eb-8dd5-b8cedd6eb2a1.png)
> 
> ```
> {
>   field: 'ys',
>   component: 'Select',
>   label: '医师',
>   colProps: { span: 4 },
>   labelWidth: 50,
>   componentProps: ({ formModel, schema }: any) => {
>     return {
>       allowClear: false,
>       options: [],
>       onSelect: (ys: string) => {
>         setYsSelect(refForm, yss, ys);
>       },
>       onKeydown: (e: any) => {
>         if (e.key === 'Enter') {
>           nextTick(async () => {
>             skqTableQuery.value.vxeInput.focus(); //聚焦检索框
>           });
>         }
>       },
>     };
>   },
> },
> ```
> 
> 动态加载方法：
> async function setKsSelect(refForm: any, formModel: any, yss: any[], ks: any) {
> // const ksyss = yss[ks]; //当前科室医生
> const ksyss = [
> { label: '李四', value: '李四', ghf: 3 },
> { label: '张三', value: '张三', ghf: 4 },
> ];
> let ysSchema = refForm.value.getSchema.filter((f: any) => f.field === 'ys')[0];
> ysSchema.componentProps.options = ksyss;
> await refForm.value.updateSchema(ysSchema);
> // formModel.ys = ksyss[0].value;
> // formModel.ghf = ksyss[0].ghf;
> // setYsSelect(refForm, yss, formModel.ys);
> }

我这边尝试是可以修改的，你得检查你的代码跟动态表单的示例有什么区别。

**Comment by zn98com** [comment]
老师，第一种写法不能渲染，第二种写法可以正常渲染下拉框，但第二种方法又导入不了formModel,schema，烦请解决一下。谢谢



&nbsp;componentProps:&nbsp;({&nbsp;formModel,&nbsp;schema&nbsp;}:&nbsp;any)&nbsp;=&gt;&nbsp;{














成都赛珂琪科技有限公司




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "anncwb/vue-vben-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月5日(星期五) 晚上9:03
收件人:&nbsp;"anncwb/vue-vben-admin"<vue-vben-admin@noreply.github.com&gt;;
抄送:&nbsp;"智能软件"<zn98@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [anncwb/vue-vben-admin] updateSchema无效 (#244)





  

 {   field: 'ys',   component: 'Select',   label: '医师',   colProps: { span: 4 },   labelWidth: 50,   componentProps: ({ formModel, schema }: any) =&gt; {     return {       allowClear: false,       options: [],       onSelect: (ys: string) =&gt; {         setYsSelect(refForm, yss, ys);       },       onKeydown: (e: any) =&gt; {         if (e.key === 'Enter') {           nextTick(async () =&gt; {             skqTableQuery.value.vxeInput.focus(); //聚焦检索框           });         }       },     };   }, },  
动态加载方法：
 async function setKsSelect(refForm: any, formModel: any, yss: any[], ks: any) {
 // const ksyss = yss[ks]; //当前科室医生
 const ksyss = [
 { label: '李四', value: '李四', ghf: 3 },
 { label: '张三', value: '张三', ghf: 4 },
 ];
 let ysSchema = refForm.value.getSchema.filter((f: any) =&gt; f.field === 'ys')[0];
 ysSchema.componentProps.options = ksyss;
 await refForm.value.updateSchema(ysSchema);
 // formModel.ys = ksyss[0].value;
 // formModel.ghf = ksyss[0].ghf;
 // setYsSelect(refForm, yss, formModel.ys);
 }
  
我这边尝试是可以修改的，你得检查你的代码跟动态表单的示例有什么区别。

**Comment by anncwb** [comment]
我用你的写法是可以的。

**Comment by anncwb** [comment]
我先关闭的，直到你能提供完整的可复现示例。
