### ISSUE TITLE
自定义组件方法在BasicForm不能使用

### ISSUE THREAD

**Issue by zn98com** [anncwb/vue-vben-admin#245]
![image](https://user-images.githubusercontent.com/10260081/107024799-726e4b00-67e3-11eb-965a-1955fa70c13b.png)

比如：onBlur方法，
错误：runtime-core.esm-bundler.js:38 [Vue warn]: Invalid prop: type check failed for prop "onBlur". Expected Function, got Array  
  at <ASelect ref="sSelect" value=undefined onUpdate:value=fn  ... > 
  at <SSelectEdit allowClear=true getPopupContainer=fn<getPopupContainer> size="small"  ... >

**Comment by anncwb** [comment]
在自定义组件内加上 

```ts

  import { propTypes } from '/@/utils/propTypes';

  export default defineComponent({
    props: {
      onBlur: propTypes.func
    }
{

```
