### ISSUE TITLE
基于文件的路由

### ISSUE THREAD

**Issue by feitian124** [anncwb/vue-vben-admin#254]
目前 vue-vben-admin 实现一个页面，需要配置和编写：
- 目录
- 路由
- 页面组件

略感繁琐。

nextjs, [umi](https://v2.umijs.org/guide/router.html), nuxtjs 等都有基于文件的路由，感觉很方便。
同样基于 vite 和 vue3 的 [vitesse](https://github.com/antfu/vitesse)也实现了基于文件的路由，基于插件[vite-plugin-pages](https://github.com/hannoeru/vite-plugin-pages)似乎实现成本不高。

举个例子

能否考虑实现基于文件的路由？

**Comment by anncwb** [comment]
这个项目应该不会做基于文件的路由，我感觉那样失去了灵活性。这个属于模版项目，需要使用的话基本都需要对菜单进行改造以适配后台。如果需要，自行集成我感觉花不了太多时间

**Comment by feitian124** [comment]
感谢答复。
还有2个小想法。
1. 现在即使基于 thin 模板开始开发，感觉“公共和基础”的代码也挺多的，是否可以抽取到一个 core 包中？
2. 代码目录目前是按 route, components, view 分类存放的，在中等以上项目中，以功能分类感觉更方便，如 order, user, shop.
