### ISSUE TITLE
能否支持oidc单点登录，例如使用vuex-oidc和oidc-client

### ISSUE THREAD

**Issue by worldofchu** [anncwb/vue-vben-admin#257]
### Subject of the feature

1：能否支持oidc单点登录，例如使用vuex-oidc和oidc-client  ，谢谢！

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by anncwb** [comment]
我觉得这个是小众需求把。你可以自行集成，应该不是很难。按照以前项目逻辑搬过来应该很快

**Comment by worldofchu** [comment]
好吧，正在做，可是老是出错。guard 里面老是 执行不到next() ,应该是里面的oidcCheckAccess 有问题。

**Comment by worldofchu** [comment]
对于 多项目 集成 是比较有用的

**Comment by anncwb** [comment]
其实这个我也没用过。所以不好说

**Comment by worldofchu** [comment]
主要是 vuex-oidc这个 我看着做着挺完整的 ，所以想用这个。只是这个不是ts 的 也不是vue3 的。它自个的示例程序没问题。就是我想集成到我们的permissionGuard前面，结果它自个的中间件 vuexOidcCreateRouterMiddleware 在跳转ids4登录之后 回来之后 就不正常，始终无法执行到里面的next(),死循环了

**Comment by worldofchu** [comment]
问下 能发下 您的vscode的 launch.json 吗 我这默认配的 始终无法 vscode进入断点，只能console log

**Comment by anncwb** [comment]
代码内的.vscode就是我的配置。不过这些我一般都没用，直接用浏览器控制台了

**Comment by jinghun1999** [comment]
vue2里有现成的成熟方案，我在迁移到vben-admin里（不使用vuex）搞了好几天本来成功了，后来不知改了哪儿又不行了，我也是服了
