### ISSUE TITLE
关于本系统的用户RoleInfo

### ISSUE THREAD

**Issue by worldofchu** [anncwb/vue-vben-admin#259]
userId: '1',
      username: 'vben',
      realName: 'Vben Admin',
      desc: 'manager',
      password: '123456',
      token: 'fakeToken1',
      role: {
        roleName: 'Super Admin',
        value: 'super',
      },

这里 的role 字段 应该是个集合把 ，一个用户应该有多个角色的！！！  
### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by mynetfan** [comment]
我也觉得这里应该是roles:[{roleName:'Role1',value:'role1'},{roleName:'Role2',value:'role2'}]这样的

**Comment by anncwb** [comment]
这里只是模拟数据，到最后还是转成了数组。这个我可以调整下

```rs
 @Action
  async getUserInfoAction({ userId }: GetUserInfoByUserIdParams) {
    const userInfo = await getUserInfoById({ userId });
    const { role } = userInfo;
    const roleList = [role.value] as RoleEnum[];
    this.commitUserInfoState(userInfo);
    this.commitRoleListState(roleList);
    return userInfo;
  }
```
