### ISSUE TITLE
一个小疑问

### ISSUE THREAD

**Issue by RoneLeo** [anncwb/vue-vben-admin#260]
你这句代码是想表达默认值的意思吗

![image](https://user-images.githubusercontent.com/38026782/107336461-157cd880-6af4-11eb-9f82-f8bb2e59b3b1.png)

![image](https://user-images.githubusercontent.com/38026782/107336499-22013100-6af4-11eb-8d82-593879c3d083.png)

**Comment by anncwb** [comment]
一样的效果

**Comment by toesbieya** [comment]
前者给headers取默认值，后者给headers.ignoreCancelToken取默认值
