### ISSUE TITLE
axios封装的工具对像，在请求后台接口响应错误500，无法跳转登陆路由。

### ISSUE THREAD

**Issue by bhxf** [anncwb/vue-vben-admin#265]
调用后台接口响应500，错误消息token失效。需要重新登陆。所以在src/utils/http/axios/checkStatus.ts中的500处理代码快中加入
 case 500:
      error(t(msg));
      if (msg?.includes('Token失效')) {
        userStore.loginOut(true);
      }
      break;
浏览器地址路由已经跳转：http://localhost:3100/#/login。但是登陆组件也没未能显示。初步估计是同时抛出异常信息导致中断。

**Comment by anncwb** [comment]
我这边测试了下是可以跳转,你是否还做了别的操作
