### ISSUE TITLE
关于Table可编辑行的几个疑问

### ISSUE THREAD

**Issue by tky753** [anncwb/vue-vben-admin#267]
用的thin版本，不知道在这里发帖是否合适

1. column设置了**editRule** 后，单元格input控件每次输入字符都会触发**editRule**，是否有必要？
2. column设置了**editRule** 后，编辑行状态下，调用 `record.onEdit?.(false, true) `同一单元格的**editRule**会触发两次，而且不知道为什么第一次触发时值为空第二次正确，因为我**editRule**加了个验证空的话会返回'XX不能为空'，所以**onEdit**会返回false，以第一次触发为准。（不过在非thin版本虽然也触发两次，但第一次触发值不为空）
3. 在 `record.onEdit?.(false, true) `后，编辑控件值会写入record，那在此之前如何获取到控件的当前值？

**Comment by anncwb** [comment]
1. 每次输入类似于change事件触发表单校验。这在正常的表单校验也是正常的。
2，3. 可以提供下具体代码？

**Comment by tky753** [comment]
@anncwb 
第二个问题：
在**非thin**项目下的**src\views\demo\page\form\high\PersonTable.vue**文件中的大约27行处，加上
```
      editRule: async (text) => {
        console.log('成员姓名:'+text);
        if (!text) {
          return '不能为空';
        }
        return '';
      },
```
![image](https://user-images.githubusercontent.com/18205977/108328437-8cf2ec00-7207-11eb-89c2-5145804c625a.png)
对应界面（页面/表单页/高级表单）上，成员管理随便一条点编辑，再点保存：
![image](https://user-images.githubusercontent.com/18205977/108328766-f410a080-7207-11eb-93de-568435efd760.png)
控制台显示
![image](https://user-images.githubusercontent.com/18205977/108328925-0559ad00-7208-11eb-8294-40c6c852e0d2.png)
第三个问题：
也在**非thin**项目下的**src\views\demo\page\form\high\PersonTable.vue**文件中的大约96行处，加一句`console.log(JSON.stringify(record));`
![image](https://user-images.githubusercontent.com/18205977/108326686-82375780-7205-11eb-851c-d080e8e067a9.png)
对应界面（页面/表单页/高级表单）上，成员管理增加一条点保存
![image](https://user-images.githubusercontent.com/18205977/108327237-215c4f00-7206-11eb-8138-6b2cb3ac657d.png)
控制台会输出
![image](https://user-images.githubusercontent.com/18205977/108326782-9e3af900-7205-11eb-9f4b-08acbf7d8756.png)
可以看出，在调用**onEdit**前record里没有数据，所以想知道如何在此之前获取到控件值
PS：这里还有一个问题，点保存没有在绑定数据源增加一行，，考虑到这是demo，可能也没什么关系

**Comment by anncwb** [comment]
第二个问题已经修复,第三问题PersonTable最新的代码，增加了edit-change事件，可以在值改变后触发,然后保存到变量，这样就可以在保存前拿到

**Comment by tky753** [comment]
@anncwb  求教 第二个问题怎么修复的，我thin那边的项目还是会触发两次，第一次原始值

**Comment by tky753** [comment]
@anncwb 终于发现问题所在了，如果column加上 **fixed: 'left'**,就会触发第二个问题：
调用`record.onEdit?.(false, true);`时触发两次editRule，且第一次传入参数如果新行则为空，修改行则为修改前的值。
![image](https://user-images.githubusercontent.com/18205977/108648047-2adf0300-74f5-11eb-9811-0adec7f14da0.png)
