### ISSUE TITLE
删除 yarn.log 以后，重新 yarn install ，启动 serve 后 antd 样式无法加载

### ISSUE THREAD

**Issue by cnhuye** [anncwb/vue-vben-admin#269]
### Subject of the issue
删除 yarn.log 以后，重新 yarn install ，启动 serve 后 antd 样式无法加载.
使用 clone 下来的 yarn.lock 直接 yarn install 后，再启动 serve 一切正常。

![WX20210212-212141](https://user-images.githubusercontent.com/486552/107774183-a1536680-6d79-11eb-9502-9767d0792821.png)
![WX20210212-212224](https://user-images.githubusercontent.com/486552/107774199-a57f8400-6d79-11eb-94e7-bc98352cf7df.png)

### Your environment

- **OS**:  macOS Mojave
- **Packages**: 刚 clone 下来的项目
- **Env**: 
    - node  v15.7.0
    - yarn 1.22.10
    - npm 7.4.3

### Steps to reproduce
下载下来的项目，删除 yarn.lock， 执行 yarn install ,  yarn serve。

**Comment by anncwb** [comment]
我试了下不会出现。可以提供下你的 node_modules内的vite-plugin-style-import插件版本号吗

**Comment by cnhuye** [comment]
```
$ yarn list|grep vite
warning ../package.json: No license field                                                                                                              
├─ @vitejs/plugin-legacy@1.3.0
├─ @vitejs/plugin-vue-jsx@1.1.0
├─ @vitejs/plugin-vue@1.1.4
├─ vite-plugin-html@2.0.0
├─ vite-plugin-mock@2.1.4
├─ vite-plugin-purge-icons@0.6.0
├─ vite-plugin-pwa@0.4.6
├─ vite-plugin-style-import@0.5.8
├─ vite@2.0.0-beta.59
```

大年初一的，打扰了，抱歉～  祝新年快乐～ 牛年无八哥～ 

> 我试了下不会出现。可以提供下你的 node_modules内的vite-plugin-style-import插件版本号吗

**Comment by anncwb** [comment]
vite-plugin-style-import 这个在package.json的版本是0.5.8吗.现在最新的是0.7.2.检查是否用了淘宝源导致了版本一样不一致

**Comment by cnhuye** [comment]
谢谢，下载了最新的代码，现在没有问题了。 我的代码是10天前下载的，应该是版本的问题。

> vite-plugin-style-import 这个在package.json的版本是0.5.8吗.现在最新的是0.7.2.检查是否用了淘宝源导致了版本一样不一致
