### ISSUE TITLE
导航栏模式为顶部菜单混合模式出现左边菜单栏底部空白

### ISSUE THREAD

**Issue by wsxe9988** [anncwb/vue-vben-admin#273]
### Subject of the issue

导航栏模式为顶部菜单混合模式出现左边菜单栏底部空白
![image](https://user-images.githubusercontent.com/5828057/108204250-88bec400-715e-11eb-8406-d97dd16a881a.png)

### Your environment
https://vvbin.cn/next/#/home/welcome

### Steps to reproduce

Tell us how to reproduce this issue. Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub. This will get you the fastest support. 🎉

### Expected behaviour

What should happen?

### Actual behaviour

What happens instead?

**Comment by anncwb** [comment]
我测了下没出现。还有别的设置吗？

**Comment by wsxe9988** [comment]
我的电脑分辨率为1366*768  和这个有关系嘛

**Comment by wsxe9988** [comment]
![image](https://user-images.githubusercontent.com/5828057/108206000-c3c1f700-7160-11eb-98e4-fdca03ed66a7.png)
antdesign  vue  pro （基于vue3.0）有这种布局，希望后面能加入

**Comment by anncwb** [comment]
这种布局我这边有类似的，我觉得他的布局利用率不太好。所以我自己写了一个
![image](https://user-images.githubusercontent.com/28132598/108206253-24513400-7161-11eb-808d-2da589e7e31b.png)

**Comment by anncwb** [comment]
第一个问题还是没复现。有具体步骤在发给我下吧
![image](https://user-images.githubusercontent.com/28132598/108206325-3af78b00-7161-11eb-935c-be305fd9c22e.png)

**Comment by wsxe9988** [comment]
看到了。第一个问题 我的谷歌浏览器版本是版本 86.0.4240.75（正式版本） （64 位）

**Comment by wsxe9988** [comment]
后面的roadmap有嘛

**Comment by anncwb** [comment]
我准备列一个

**Comment by wsxe9988** [comment]
嗯好的，后面时间允许的话，可以参与开发下，

**Comment by anncwb** [comment]
https://github.com/anncwb/vue-vben-admin/issues/274 欢迎pr。那个问题你能保证确定在发给我看看

**Comment by wsxe9988** [comment]
您昨晚发的2.0版本，我看了这个问题没有了 ，谢谢
