### ISSUE TITLE
最新版本-设置按钮移动到了右上角按了esc也无法恢复

### ISSUE THREAD

**Issue by worldofchu** [anncwb/vue-vben-admin#275]
最新版本-设置按钮移动到了右上角。设置菜单里面 有个全屏内容，点击后直接全屏了，按了esc也无法恢复。但是由于一下子全屏，导致设置按钮也看不到了。

原来的情况是 设置按钮是 在右侧中间浮动的就不存在这个问题，建议解决！另外还是建议一个浮动设置按钮就行了，不能像其他admin后台似的 浮动菜单过多 都占用正常页面了

**Comment by anncwb** [comment]
这个我会加个配置，自己选择位置。因为浮动的会遮挡住页面内容
