### ISSUE TITLE
项目克隆后yarn下载依赖后，运行报错

### ISSUE THREAD

**Issue by jin974319** [anncwb/vue-vben-admin#279]
![image](https://user-images.githubusercontent.com/35279865/108333912-61263500-720c-11eb-8c33-53b1a7887194.png)

大佬，这是为什么呢，安装依赖一直失败

**Comment by anncwb** [comment]
尝试执行 yarn reinstall

**Comment by jin974319** [comment]
![image](https://user-images.githubusercontent.com/35279865/108443409-ac375b00-7293-11eb-93c6-3c656300cd82.png)
不行，这个命令也有报错

**Comment by anncwb** [comment]
那就删除yarn.lock和node_modules重新安装
