### ISSUE TITLE
登录失败无法继续登录

### ISSUE THREAD

**Issue by superlbr** [anncwb/vue-vben-admin#28]
重现步骤：
1. 登录vvbin.cn
2. 输入用户名、密码，安全校验
3. 提示密码错误，然后安全校验，卡住
4. 需重新刷新。。。

**Comment by anncwb** [comment]
下一个版本修复

**Comment by anncwb** [comment]
> 重现步骤：
> 
> 1. 登录vvbin.cn
> 2. 输入用户名、密码，安全校验
> 3. 提示密码错误，然后安全校验，卡住
> 4. 需重新刷新。。。

最新版已修复

**Comment by superlbr** [comment]
去掉mock，使用后端api还是有这个问题，api报个错就卡住了
另外还有几个问题，使用后端api：
1. [文档-后台动态获取菜单](https://vvbin.cn/docs/guide/perm/back.html#%E5%AE%9E%E7%8E%B0%E6%B5%81%E7%A8%8B)上getUserInfoById 接口返回值不是这个，而是GetMenuListByUserId的返回值
2. 切换后端模式，AuthModeEnum.BACK，并不会把整个views都引入进来，而是getLazyComponent，而且即使copy进来仍会提示找不到组件
```Cannot find module '@/views/dashboard/welcome/index.vue'```

**Comment by anncwb** [comment]
@superlbr 能否提供步骤或者错误信息

**Comment by superlbr** [comment]
以vue-vben-admin-thin为例:
1. 设置```authMode: AuthModeEnum.BACK```
2. 登录，后端无对应接口或者接口报错，则卡住
3. 构造后端api，使请求能访问到对应的数据。
4. 报错
![image](https://user-images.githubusercontent.com/8142164/93011108-e2c2c880-f5c5-11ea-9b85-d90b7a234cef.png)
注意：如果这时候去看，views并未被全部引入
![image](https://user-images.githubusercontent.com/8142164/93011180-9330cc80-f5c6-11ea-920e-bd24add3a0ba.png)

5. 如果将routeHelpers里的lazyComponent部分替换为```component === 'PAGE_LAYOUT' ? PAGE_LAYOUT_COMPONENT : import(`@/views/${component}.vue`)```，则可以进入首页，但是页面空白，且报错一样
![image](https://user-images.githubusercontent.com/8142164/93011163-75636780-f5c6-11ea-8cc1-d3e206d10c99.png)

**Comment by anncwb** [comment]
能否加下群 或者提供可以运行的代码仓库

**Comment by superlbr** [comment]
加群了@anncwb
