### ISSUE TITLE
多次加载页面

### ISSUE THREAD

**Issue by guojoa** [anncwb/vue-vben-admin#281]
### 多次加载页面
我用的是，精简版对接后台，刷新页面不会有问题。打开一个页面如menu，再次打开一个页面就会加载两次。并且两闪请求后台数据。如果注释掉LayoutMultipleHeader就不会有这种问题。
在vue-vben-admin中，切换后台权限模式，再切换回前台模式，打开页面table的请求mock数据就会请求两次数据
![image](https://user-images.githubusercontent.com/4997901/108477127-c9891b00-72cd-11eb-8e98-3a94cf80569f.png)

**Comment by anncwb** [comment]
这个是vue-router keepalive造成的。跟这个问题一样https://github.com/anncwb/vue-vben-admin/issues/215.
