### ISSUE TITLE
表格全屏之后无法显示 tooltip 的内容

### ISSUE THREAD

**Issue by JohnNiang** [anncwb/vue-vben-admin#283]
### Subject of the issue

表格全屏之后无法显示 tooltip 的内容。猜测全屏后的表格的 z-index 大于了 tooltip 的 z-index。

### Your environment

- **OS**: 
- **Packages**: 
- **Env**: 

### Steps to reproduce

在单元格中创建一个 tooltip，并设置好内容，点击表格工具的全屏按钮，无法正常显示 tooltip。

### Expected behaviour

表格全屏后依然能够看到 tooltip 的内容。

### Actual behaviour

表格全屏后无法看到 tooltip 的内容。

**Comment by JohnNiang** [comment]
Popover 同样不行。

**Comment by anncwb** [comment]
将tooltip挂在到表格

**Comment by JohnNiang** [comment]
Modal 也无法显示。

**Comment by JohnNiang** [comment]
> 将tooltip挂载到表格,默认是挂载在body

我尝试一下。

**Comment by anncwb** [comment]
这个问题我觉得没必要去解决，也没好的解决方法。因为不知道全屏后哪些组件需要展示,只能你手动去设置层级。我认为全屏后只适合预览。不适合操作。

**Comment by JohnNiang** [comment]
> 这个问题我觉得没必要去解决，也没好的解决方法。因为不知道全屏后哪些组件需要展示,只能你手动去设置层级。我认为全屏后只适合预览。不适合操作。

解决成本确实太高了。

**Comment by anncwb** [comment]
对的。我也在想准备吧表格的全屏功能移除了。这个功能可能会造成不必要的问题

**Comment by anncwb** [comment]
ant design pro是没有这个全屏功能的
