### ISSUE TITLE
新增多功能导航菜单

### ISSUE THREAD

**Issue by wsxe9988** [anncwb/vue-vben-admin#284]
### Subject of the feature

Describe your issue here.

类似阿里云多功能导航菜单组件，适用于菜单项居多的产品，支持展开，也可以搜索和快速定位分类

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

参考项目:https://pro.iviewui.com/store/item/1247108573981446144
![image](https://user-images.githubusercontent.com/5828057/108611576-b59eff80-741a-11eb-8a3b-449c6d30bc52.png)

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by anncwb** [comment]
这个没打算做。 有兴趣你可以提pr
