### ISSUE TITLE
请求新增GlobalFooter 全局页脚组件

### ISSUE THREAD

**Issue by wsxe9988** [anncwb/vue-vben-admin#287]
### Subject of the feature

Describe your issue here.

全局页脚常居中位于页面最底部，承载版权等信息。

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

参考项目:https://www.iviewui.com/components/pro/global-footer
![image](https://user-images.githubusercontent.com/5828057/108615023-be9fc900-743a-11eb-8fd2-682810f2a69b.png)

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by anncwb** [comment]
看文档，在配置中开启
