### ISSUE TITLE
新增Ellipsis 文本自动省略号功能

### ISSUE THREAD

**Issue by wsxe9988** [anncwb/vue-vben-admin#289]
### Subject of the feature

文本过长自动处理省略号，支持按照文本长度、最大行数、限制高度三种方式截取。

### Problem

文本过长自动处理省略号，支持按照文本长度、最大行数、限制高度三种方式截取。

### Expected behaviour

参考项目:https://www.iviewui.com/components/pro/ellipsis
![image](https://user-images.githubusercontent.com/5828057/108615095-5e5d5700-743b-11eb-90d5-b2f5571e067a.png)

![image](https://user-images.githubusercontent.com/5828057/108615088-57364900-743b-11eb-8a74-d19047167e45.png)
![image](https://user-images.githubusercontent.com/5828057/108615099-61f0de00-743b-11eb-94a5-d604f7034c8a.png)

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by xiaoxian521** [comment]
@wsxe9988 现在这个问题还存在吗

**Comment by wsxe9988** [comment]
不太确定，我现在在https://vvbin.cn/next没有看到相关示例
