### ISSUE TITLE
表格 TableSetting 切换列显示，设置了 customRender 的列勾选异常

### ISSUE THREAD

**Issue by LSYUN** [anncwb/vue-vben-admin#293]
### Subject of the issue
表格组件，在 TableSetting 切换列显示，设置了customRender 的列会同时取消勾选，并再也勾选不上。

### Steps to reproduce
异常场景1：
取消勾选一个（非customRender ）列，customRender 列也会随着取消勾选，并勾选不上；

异常场景2：
直接取消勾选 customRender 列后再也勾选不上；

![截图20210224113345](https://user-images.githubusercontent.com/20899078/108944741-577e5080-7696-11eb-8fe2-857dadff6b73.png)

**Comment by anncwb** [comment]
我在demo->自定义列那边并没有复现出该问题。你是不是改了什么。
