### ISSUE TITLE
热更新为什么不是预期效果？

### ISSUE THREAD

**Issue by doocal** [anncwb/vue-vben-admin#300]
试了一下 projectSetting.ts>showSettingButton 的按钮配置项目调整，界面虽然刷新了，但是按钮的显示不会随着配置变更。切换到另一个地址访问正常。

**Comment by anncwb** [comment]
可以看文档.配置文件修改需要清空缓存后在登录.

**Comment by doocal** [comment]
@anncwb  useContext.ts>createContext 方法随便加一个注释热更新后，左侧菜单全部丢失。
