### ISSUE TITLE
热更新后，左侧菜单全部丢失。

### ISSUE THREAD

**Issue by doocal** [anncwb/vue-vben-admin#301]
@anncwb  useContext.ts>createContext 方法随便加一个注释热更新后，左侧菜单全部丢失。

_Originally posted by @doocal in https://github.com/anncwb/vue-vben-admin/issues/300#issuecomment-785501617_

**Comment by anncwb** [comment]
vite升级后造成的热更新问题，还在跟踪。暂时还没找到原因

**Comment by anncwb** [comment]
可以先等等 https://github.com/vitejs/vite/issues/2308 这个问题的反馈。在确认下是哪个的问题
