### ISSUE TITLE
TableAction 组件bug

### ISSUE THREAD

**Issue by shijingyan** [anncwb/vue-vben-admin#302]

**Comment by shijingyan** [comment]
<TableAction :actions="[
            { label: t('sys.errorLog.tableActionDesc'), onClick: handleEdit.bind(null, record) },
          ]" />

例如：编辑某行数据中的用户名字段username:name1修改为name2,
编辑行数据之后并存并reload表格数据，刚才编辑的行数据中的username已更新为name2，
接着继续编辑刚才那一行的数据，此时，handleEdit回调中的record还是最开始初始化时的数据，username还是name1,
在不刷新页面的情况下，无论为编辑几次刚才那条行数据，record还是最开始初始化时的数据。

**Comment by anncwb** [comment]
vue 的问题,得等vue修复

**Comment by shijingyan** [comment]
印象你前一段时间重构了table组件（那个版本新增了table行内编辑form框），在这个版本之前是没有该问题的。应该不是vue的问题。

**Comment by anncwb** [comment]
看错问题了，以为是TableAction那个bug。编辑行我在确认看下

**Comment by anncwb** [comment]
贴下你的代码

**Comment by anncwb** [comment]
closed 7156e47c18
