### ISSUE TITLE
table在使用expandedRowRender后，列的fixed属性无法正常显示

### ISSUE THREAD

**Issue by jenifly** [anncwb/vue-vben-admin#303]
### 未设置fixed前
![微信截图_20210225123301](https://user-images.githubusercontent.com/22962492/109103521-faea6680-7765-11eb-9084-9829de123377.png)
### 设置`部门`左固定，`操作`右固定
![微信截图_20210225123340](https://user-images.githubusercontent.com/22962492/109103496-f160fe80-7765-11eb-8d62-4d3d49421aa3.png)

**Comment by anncwb** [comment]
ant-design-vue的问题。组件不支持这两个一起使用
