### ISSUE TITLE
src/utils/http/index.ts里面对返回处理有点问题呀

### ISSUE THREAD

**Issue by cengxw** [anncwb/vue-vben-admin#304]
// 这里逻辑可以根据项目进行修改
    const hasSuccess = data && Reflect.has(data, 'code') && code === ResultEnum.SUCCESS;
    if (!hasSuccess) {
      if (message) {
        // errorMessageMode=‘modal’的时候会显示modal错误弹窗，而不是消息提示，用于一些比较重要的错误
        if (options.errorMessageMode === 'modal') {
          createErrorModal({ title: t('sys.api.errorTip'), content: message });
        } else if (options.errorMessageMode === 'message') {
          createMessage.error(message);
        }
      }
      Promise.reject(new Error(message));
      return errorResult;
    }

上面这段代码中，如果后台返回的code是ResultEnum.ERROR或者ResultEnum.TIMEOUT，那在这代码之后对ERROR或TIMEOUT的处理片段就执行不到了。。

**Comment by anncwb** [comment]
能执行到这里代表的是请求成功了，哪里会出现timeout

**Comment by cengxw** [comment]
那第72行之后的代码岂不是一点作用都没有嘛，不管请求成功还是失败，都 不可能执行到那后面去了。

**Comment by anncwb** [comment]
自己断点调试吧，这块正常使用的

**Comment by cengxw** [comment]
const { code, result, message } = data;
请问这个data的值要是什么样子的才会走到72行之后啊。

**Comment by anncwb** [comment]
code 不等于SUCCESS不就执行了
