### ISSUE TITLE
个人中心用户头像在线裁剪

### ISSUE THREAD

**Issue by wsxe9988** [anncwb/vue-vben-admin#305]
### Subject of the feature

Describe your issue here.

### Problem

个人中心用户头像在线裁剪

### Expected behaviour

![image](https://user-images.githubusercontent.com/5828057/109171036-4f203580-77bc-11eb-89b7-c7fa7535a4f0.png)

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by xiaoxian521** [comment]
@wsxe9988 裁剪组件已完善，可根据裁剪组件自行进行图片裁剪 #463
