### ISSUE TITLE
当vxe-table 4.0(基于vue3 ) release后，是否可以将其引入，增强antdesignvue的表格功能

### ISSUE THREAD

**Issue by wsxe9988** [anncwb/vue-vben-admin#307]
### Subject of the feature

当vxe-table 4.0(基于vue3 ) release后，是否可以将其引入，增强antdesignvue的表格功能

### Problem

vxe-table-plugin-antd基于 vxe-table 表格的适配插件，用于兼容 ant-design-vue 组件库，能否在项目里提供个集成的例子供学习使用，谢谢

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by anncwb** [comment]
不会，这种可以自己引入
