### ISSUE TITLE
发现一个错误

### ISSUE THREAD

**Issue by flybyhorse** [anncwb/vue-vben-admin#31]
TypeError: str.matchAll is not a function
      at Object.extractor (H:\vue-vben-admin-main\node_modules\@purge-icons\core\dist\index.js:146:27)
      at Extract (H:\vue-vben-admin-main\node_modules\@purge-icons\core\dist\index.js:173:54)

**Comment by anncwb** [comment]
> TypeError: str.matchAll is not a function
> at Object.extractor (H:\vue-vben-admin-main\node_modules@purge-icons\core\dist\index.js:146:27)
> at Extract (H:\vue-vben-admin-main\node_modules@purge-icons\core\dist\index.js:173:54)

可以发下你的环境 node版本 和系统版本吗，或者复现方式。目前我们没遇到这个问题

**Comment by Guuuxu** [comment]
> > TypeError: str.matchAll is not a function
> > at Object.extractor (H:\vue-vben-admin-main\node_modules@purge-icons\core\dist\index.js:146:27)
> > at Extract (H:\vue-vben-admin-main\node_modules@purge-icons\core\dist\index.js:173:54)
> 
> 可以发下你的环境 node版本 和系统版本吗，或者复现方式。目前我们没遇到这个问题

node: v10.16.0 使用的npm工具 win7, 需要升级node?

**Comment by anncwb** [comment]
用vnm升级到node 试看看
