### ISSUE TITLE
打包体积为7MB，能否缩减

### ISSUE THREAD

**Issue by shuperry** [anncwb/vue-vben-admin#311]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by anncwb** [comment]
整个示例网站开启gzip 在2.4M左右。 开启Brotli压缩就1.9M. 对于后台系统已经算挺小了。虽然还有部分依赖没优化，比如 moment。但是这个是示例项目，包含了echart/xlsx这种比较大的插件，打包体积大是肯定的。

想要体积小可以看精简版 https://github.com/anncwb/vben-admin-thin-next。 2.5m左右，brotli后大概在1M左右

**Comment by shuperry** [comment]
@anncwb 好的，谢谢，vben-admin-thin-next 这个库是同步更新的么？

**Comment by anncwb** [comment]
一般2-3天同步一次

**Comment by shuperry** [comment]
Thanks.

**Comment by shuperry** [comment]
@anncwb 再问个问题哈，怎么配置打包之后不保留未经压缩的文件，我看打包之后的文件里有 .gz 文件，还有未经压缩的源文件并存

**Comment by shuperry** [comment]
@anncwb  我找到方法了，我来提个 PR 把这个支持配置吧

**Comment by anncwb** [comment]
![image](https://user-images.githubusercontent.com/28132598/111406736-c555ef00-870d-11eb-9d0d-edd64241aaad.png)

**Comment by shuperry** [comment]
嗯嗯，已经看到代码了
