### ISSUE TITLE
TableAction onClick事件record传值未更新

### ISSUE THREAD

**Issue by kenshinguan** [anncwb/vue-vben-admin#313]
使用TableAction组件，onClick:  事件名.bind(null, record), 其中record的值始终是初始表格数据，不是更改后表格的数据

**Comment by JohnNiang** [comment]
有可能你拿到的数据是 deepClone 之后的数据。

**Comment by anncwb** [comment]
@kenshinguan 能给下你的使用方式吗，这个我没有还原出来。可以正常使用

**Comment by kenshinguan** [comment]
附件 - 代码文件


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "anncwb/vue-vben-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 凌晨0:32
收件人:&nbsp;"anncwb/vue-vben-admin"<vue-vben-admin@noreply.github.com&gt;;
抄送:&nbsp;"管涧萧萧"<582936996@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [anncwb/vue-vben-admin] TableAction onClick事件record传值未更新 (#313)





 
@kenshinguan 能给下你的使用方式吗，这个我没有还原出来。可以正常使用

**Comment by kenshinguan** [comment]
@anncwb 代码文件已发送至您邮箱，谢谢！

**Comment by anncwb** [comment]
@kenshinguan 没收到。你贴下主要带啊庅就可以了

**Comment by anncwb** [comment]
或者尝试下系统管理模块，看看可不可以，我测试是可以的

**Comment by kenshinguan** [comment]
@anncwb 原因找到了，需要设置ignoreKeepAlive为true，TableAction才能获取更新数据，考虑到性能，可否优化TableAction，使得ignoreKeepAlive为false也能获取更新数据

**Comment by anncwb** [comment]
closed 7156e47c18
