### ISSUE TITLE
是否考虑，在提供一个js版本

### ISSUE THREAD

**Issue by jekip** [anncwb/vue-vben-admin#316]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by anncwb** [comment]
不会，没必要提供js版本。不过欢迎pr
