### ISSUE TITLE
TreeSelect 组件怎么回显数据

### ISSUE THREAD

**Issue by ZhangwenGmi** [anncwb/vue-vben-admin#319]

**Comment by ZhangwenGmi** [comment]
![image](https://user-images.githubusercontent.com/21217205/109924418-330c1f00-7cfb-11eb-9db3-08aa92dfc077.png)
这种方式无法设置选中的值

**Comment by liushiqian** [comment]
为啥tree组件没有TreeSelectProps这个搜索功能？没找到，你是怎么解决？
