### ISSUE TITLE
vite case files path wrong

### ISSUE THREAD

**Issue by yuyeqianxun** [anncwb/vue-vben-admin#32]
### Subject of the issue
有两处地方应用了包文件里面的内容，vite在路径前会自动加上@modules，但是不直接引用包名的话会导致它添加路径出错，具体如截图
![微信截图_20201010150946](https://user-images.githubusercontent.com/17348438/95648521-74aceb00-0b0a-11eb-980a-e3db3279b5e7.png)
```js
import 'ant-design-vue/dist/antd.css';
```
![微信截图_20201010150858](https://user-images.githubusercontent.com/17348438/95648512-619a1b00-0b0a-11eb-81b9-11398f611e7b.png)
```
[vite] Failed to resolve module import "ant-design-vue/dist/antd.css-vben-adminode_modulesant-design-vuedistantd.css". (imported by /@/setup/ant-design-vue/index.ts)
```
如上图引用包内部的文件时，会导致下图自动修改路径出问题，我不确定vite是否有针对这种情况的设置。改成相对路径项目才能正常打开。
### Your environment

- **OS**: windows 10;node v14.11;
- **Packages**: 2.0.0-beta.4
- **Env**: Production

### Steps to reproduce

Tell us how to reproduce this issue. Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub. This will get you the fastest support. 🎉

### Expected behaviour

What should happen?

### Actual behaviour

What happens instead?

**Comment by anncwb** [comment]
没还原出的你问题，能说下还原的步骤吗。

**Comment by yuyeqianxun** [comment]
> 没还原出的你问题，能说下还原的步骤吗。

没有啥特别步骤，git clone->cd->yarn install->yarn serve,然后就出现了，我有空排查排查node版本，vite全局安装这些吧

**Comment by anncwb** [comment]
@yuyeqianxun 你的文件目录有中文 空格 这些吗
