### ISSUE TITLE
package.json中的依赖能否尽量使用精确版本

### ISSUE THREAD

**Issue by tky753** [anncwb/vue-vben-admin#324]
### Subject of the feature

建议 package.json中的依赖尽量使用**精确版本**

### Problem

如果yarn.lock不去动它，那一般没有问题。
但是如果：
1. 不小心运行了yarn reinstall，就会把yarn.lock删除，再运行install后的依赖版本很可能会有微妙的不同，然后出现奇奇怪怪的问题；
2. 用户加了一些其他包，然后yarn install后，yarn.lock就变了，之后想要再拉取最新改动时，yarn.lock就会冲突，可能会陷入不得不手动merge yarn.lock的窘境，因为yarn.lock是自动生成的，所以手动改有一定难度。因而难以拉取最新改动。

### Expected behaviour

运行 yarn reinstall生成的yarn.lock和项目自带的yarn.lock总是完全一致。

**Comment by anncwb** [comment]
emm... yarn.lock合并并不需要合并冲突，直接合并然后重新执行yarn 即可
