### ISSUE TITLE
Consider Releasing vue-vben-admin as a self contained  npm library

### ISSUE THREAD

**Issue by uwascan** [anncwb/vue-vben-admin#325]
### Release as an npm Library
Describe your issue here.
After making a ton of customization to make this (wonderfully made) admin panel compatible with my backend (Asp.net Core Abp Framework [https://abp.io/]) and a new awesome version is released, you have to start the customization process all over again.

### Expected behaviour
IF released as an NPM library with well established and well documented extension points, all one has to do is update your version of vue-vben-admin in your package.json file and run npm install or yarn

For me, this is the best Vue Admin Panel on this planet.

**Comment by anncwb** [comment]
emm.. For this type of template project, it cannot be published to npm

**Comment by anncwb** [comment]
The document will be added slowly, time is limited, please forgive me
