### ISSUE TITLE
table的reload方法不生效

### ISSUE THREAD

**Issue by ZhangwenGmi** [anncwb/vue-vben-admin#326]
![image](https://user-images.githubusercontent.com/21217205/110197252-506cf480-7e85-11eb-9b63-9fb1a3615ad7.png)
![image](https://user-images.githubusercontent.com/21217205/110197253-5236b800-7e85-11eb-9111-9dc3dd5af374.png)
![image](https://user-images.githubusercontent.com/21217205/110197254-5367e500-7e85-11eb-9ab9-4f0c6fea4cce.png)

**Comment by anncwb** [comment]
没明白哪里不生效，这个都是正常使用，获取更新到最新代码试试

**Comment by anncwb** [comment]
等你提供更多的错误信息,再次开启这个问题
