### ISSUE TITLE
table组件useSearchForm在标签里面声明，点击查询无效

### ISSUE THREAD

**Issue by ZhangwenGmi** [anncwb/vue-vben-admin#327]
![image](https://user-images.githubusercontent.com/21217205/110197743-9a0b0e80-7e88-11eb-9445-4e0222f73632.png)
![image](https://user-images.githubusercontent.com/21217205/110197742-9a0b0e80-7e88-11eb-90e4-853709ad1b04.png)
useSearchForm在标签里面声明，点击查询无效

**Comment by anncwb** [comment]
你没有传api,所以搜索方法你要自己覆盖实现
