### ISSUE TITLE
每次刷新加载非常慢

### ISSUE THREAD

**Issue by carl-jin** [anncwb/vue-vben-admin#329]
如下图所示, 我的配置在下方, 我不知道这是不是正常情况, 但是对比了vue-cli的项目, 这个还是有点慢呢, vue-cli的项目是都压成了一个chunks, 一次性加载
[https://imgur.com/rxkSR85](https://imgur.com/rxkSR85)

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

## System Info

- Operating System:window10
- Node version:v14.15.0
- Package manager (npm/yarn/pnpm) and version:6.14.8
- "vite": "^2.0.5",
- "vue": "^3.0.7",
-  "ant-design-vue": "2.0.1",
-  "vite-plugin-compression": "^0.2.3",

**Comment by anncwb** [comment]
请求多这个问题是vite机制的问题，刷新慢这个我已经在跟踪了，后面会解决

**Comment by JieYueCoding** [comment]
请问这个问题最终解决了吗，我现在把最新代码拿下来，本地启动项目加载时还是感觉挺慢的 有六七秒

**Comment by carl-jin** [comment]
> 请问这个问题最终解决了吗，我现在把最新代码拿下来，本地启动项目加载时还是感觉挺慢的 有六七秒

没解决，你可以把浏览器的devtool里面的disable cache关掉会快很多，另外因为vite的机制，基本上开发时刷新页面的情况很少

**Comment by freedomdebug** [comment]
请问有解决么，不是一般的慢

**Comment by carl-jin** [comment]
> 请问有解决么，不是一般的慢

https://github.com/anncwb/vue-vben-admin/blob/e85649bde2378e8118099879392ff024da33e12b/build/vite/plugin/index.ts#L41
作者在最新的代码中已经暂时修复了这个问题

**Comment by carl-jin** [comment]
最近把老项目从 webpack 迁移到 vite 时又遇到这个问题了，记录了下优化的方法， 虽然没有从实质上解决问题，但是也加速不少，[https://carljin.com/vite-resolve-request-files-a-ton.html](https://carljin.com/vite-resolve-request-files-a-ton.html)
