### ISSUE TITLE
后台菜单时候，v-auth指令无效

### ISSUE THREAD

**Issue by 734839030** [anncwb/vue-vben-admin#330]
### Describe the bug

```
src/directives/permission.ts
const mounted = (el: Element, binding: DirectiveBinding<any>) => {
  if (isBackMode()) return;
  isAuth(el, binding);
};

```
if 逻辑错误了，应该改为如下
 if (isBackMode()) isAuth(el, binding);
 return;

**Comment by anncwb** [comment]
后台模式 mounted应该是不能被触发的。只能触发update，因为获取code这个是异步函数

**Comment by anncwb** [comment]
否则在update的时候，这个会显示不出来

**Comment by anncwb** [comment]
这个可能跟下面的初始化code时机相关，你的初始化时机可能比较早。我在看下

**Comment by 734839030** [comment]
文档说在登录时候放入，我改造时候觉得和加载的菜单一起处理比较好，放在下图这个地方，如果是不是通用问题，就不麻烦您定位了，我等您回复后自行关掉issue。
![image](https://user-images.githubusercontent.com/12107198/110481103-2c7a0f00-8122-11eb-98f4-dccb9c1871d1.png)

**Comment by anncwb** [comment]
我看了下是和加载时机有关。我示例demo是写在当前页，所以mounted不执行。你写在那里的话mounted会执行。你可以先按你的改
