### ISSUE TITLE
使用PermissionMode:Back, 和vue-router的createWebHistory() 模式, 刷新页面报错

### ISSUE THREAD

**Issue by carl-jin** [anncwb/vue-vben-admin#331]
(下面这一段是废话, 作者没时间的话, 直接请直接跳过)
首先感谢作者宝贵的时间, 能处理这个issue, 这个问题网上搜索不到, 我又拿了vue-vben-admin和ven-admin-thin-next俩项目反复测试, 捣鼓了一下午, 还是没解决, 瞅了一眼满地的头发, 我还是决定提个issue, 这个PermissionMode:Back模式, 只在文档中提到过, 但是并没有演示如何添加. 总而言之, 非常感谢作者能百忙之中看下这个issue👍

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug
在项目中配置
PermissionMode:Back, 和 vue-router的createWebHistory() 后, 在mock中添加的新路由, 进入后刷新页面, 报以下错误
刷新页面报这个错误, 直接页面卡死(就是页面一直转圈圈, 必须手动到地址栏删掉路径重新刷新)
``` shell script
4:13:06 PM [vite] http proxy error:
Error: connect ECONNREFUSED 127.0.0.1:3000
```

### Reproduction
我fork了一个项目[https://github.com/carl-jin/vben-admin-thin-next](https://github.com/carl-jin/vben-admin-thin-next)
复现步骤
1. 安装项目
2. yarn serve
3. 登入到后台
4. 点击左侧目录的`API权限`
5. 点击`API添加`
6. 刷新页面, 此时页面卡死, 一直显示加载, 并且可以在控制台中看到报错
``` shell script
4:32:27 PM [vite] http proxy error:
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

以下内容是这个fork项目修改的地方

我用的是vben-admin-thin-next进行开发, 是最新的项目, 2.0.3的版本(这个是作者刚刚从vue-vben-admin合并的)
```javascript
//  src/router/index.ts  14行, 使用history模式
const router = createRouter({
  //   修改了下面这一行
  history: createWebHistory(),
  routes: (basicRoutes as unknown) as RouteRecordRaw[],
  strict: true,
  scrollBehavior: () => ({ left: 0, top: 0 }),
});
```

使用permissionMode:PermissionModeEnum.BACK 模式 (这样会从mock里面读取数据生成menu)
```javascript
//  src/settings/projectSetting.ts   22行
  // Permission mode
  permissionMode: PermissionModeEnum.BACK,
```

然后在mockjs里面添加一个路由
``` javascript
//  mock/sys/menu.ts
const apiPermission = {
  path: '/api-permission',
  name: 'ApiPermission',
  component: 'LAYOUT',
  redirect: '/api-permission/list',

  meta: {
    title: 'API权限',
    icon: 'carbon:user-role',
  },

  children: [
    {
      path: 'list',
      name: 'ApiPermissionList',
      component: '/api-permission/list/index',
      meta: {
        title: 'API列表',
      },
    },
    {
      path: 'add',
      name: 'ApiPermissionAdd',
      component: '/api-permission/add/index',
      meta: {
        title: 'API添加',
      },
    },
  ],
};

export default [
  {
    url: '/api/getMenuListById',
    timeout: 0,
    method: 'get',
    response: ({ query }) => {
      const { id } = query;
      if (!id || id === '1') {
        // 从这里给他返回到前端去
        return resultSuccess([dashboardRoute, apiPermission]);
      }
      if (id === '2') {
        return resultSuccess([dashboardRoute, apiPermission]);
      }
    },
  },
] as MockMethod[];
```

在相同的代码下把
```javascript
  history: createWebHistory(),
```
还原成 `createHashWebHistory`就没这个问题, 不清楚是不是vite的问题? 但是我也尝试了`vue-vben-admin`这个项目mock里面模拟的路由, 没发现问题. 我觉得还是我少配置了什么, 这块也希望作者有空能在文档里面描述下, 该如何添加一个后台路由

## System Info

- Operating System:window10
- Node version:v14.15.0
- Package manager (npm/yarn/pnpm) and version:npm 6.14.8
- "vue-router": "^4.0.4"
- "vite": "^2.0.5"

**Comment by anncwb** [comment]
暂时先用createHashWebHistory, createWebHistory这个我排查看看

**Comment by carl-jin** [comment]
> 暂时先用createHashWebHistory, createWebHistory这个我排查看看

我只是很好奇, 为什么vue-vben-admin项目中模拟的mock数据, 动态生成的menu就正常, 我自己写的就不行, 即使我删掉 router and menus 里面的moduels文件夹, vue-vben-admin里面的动态menu, 刷新后也没问题, 就自己写的有问题. 
我现在只能使用 createWebHistory 了
谢谢你的回复

**Comment by anncwb** [comment]
我这边试了下你的项目，改成createWebHistory正常使用。你可以尝试清空缓存后看看

**Comment by anncwb** [comment]
![image](https://user-images.githubusercontent.com/28132598/110335226-95984e80-805e-11eb-9999-109deade3d37.png)
![image](https://user-images.githubusercontent.com/28132598/110335236-9af59900-805e-11eb-8626-e35eb93ca28b.png)

**Comment by anncwb** [comment]
@carl-jin 刚看了下 找到原因了

```ts
/api-permission // 这是你的路由地址
```


```bash
VITE_PROXY=[["/api","http://localhost:3000"],["/upload","http://localhost:3001/upload"]]

VITE_GLOB_API_URL=/api  # 这个是你本地开发的地址。
```
两个api冲突了，/api-permission被转换成了 http://localhost:3000-permission

只需改变下面的api名称即可

```bash
VITE_PROXY=[["/default-api","http://localhost:3000"],["/upload","http://localhost:3001/upload"]]

VITE_GLOB_API_URL=/default-api # 这个是你本地开发的地址。
```

**Comment by carl-jin** [comment]
> @carl-jin 刚看了下 找到原因了
> 
> ```ts
> /api-permission // 这是你的路由地址
> ```
> 
> ```shell
> VITE_PROXY=[["/api","http://localhost:3000"],["/upload","http://localhost:3001/upload"]]
> 
> VITE_GLOB_API_URL=/api  # 这个是你本地开发的地址。
> ```
> 
> 两个api冲突了，/api-permission被转换成了 http://localhost:3000-permission
> 
> 只需改变下面的api名称即可
> 
> ```shell
> VITE_PROXY=[["/default-api","http://localhost:3000"],["/upload","http://localhost:3001/upload"]]
> 
> VITE_GLOB_API_URL=/default-api # 这个是你本地开发的地址。
> ```

让我给你买杯咖啡吧
