### ISSUE TITLE
table的行单击事件和双事件可以区分下吗？

### ISSUE THREAD

**Issue by fkuepl** [anncwb/vue-vben-admin#332]
<template>
     <el-button
　　      @click="handleClick" 
　　      @dblclick.native="handleDb"
      >
       点击
      </el-button>
</template>
<script>
var time = null;  //  在这里定义time 为null 
export default {
  methods: {
　　// 单击事件函数
    handleClick() {
      clearTimeout(time);  //首先清除计时器
      time = setTimeout(() => {
          // to do something
      }, 300);   //大概时间300ms
    },
　　// 双击事件函数，清除计时器，直接处理逻辑
    handleDb() {
      clearTimeout(time);  //清除
      // to do something
    }
  }
};
</script>

**Comment by anncwb** [comment]
这个只能按你的方式处理，我不会全局加定时器，加了之后单击会有延时。一般有双击的行要把单击选中checkbox禁用掉。
