### ISSUE TITLE
可以提供一个简易版本吗？

### ISSUE THREAD

**Issue by cshenger** [anncwb/vue-vben-admin#34]
您好，就是可以提供一个不包含其他功能，只需要一个基础框架的空白版本吗？真正实际使用可能还是大多数的页面是用户自己开发。

**Comment by anncwb** [comment]
@cshenger 可以，这个在计划之内。因为现在还处于beta，在稍微稳定点很卡会提供出来。

**Comment by sun519** [comment]
+1，挺想要一个基础框架的空白版本的

**Comment by binnuo** [comment]
同感😋

**Comment by anncwb** [comment]
@cshenger @sun519 @binnuo  https://github.com/anncwb/vben-admin-thin-next

**Comment by tangjy2020** [comment]
求简版，现在这个里面东西太多了
