### ISSUE TITLE
操作栏放三个图标时，底部会多出一条线

### ISSUE THREAD

**Issue by fkuepl** [anncwb/vue-vben-admin#340]
![image](https://user-images.githubusercontent.com/2612446/110441257-8663e000-80f4-11eb-9457-7e928e2d57b0.png)

**Comment by anncwb** [comment]
复现不出来，请给能绝对复现的代码或者配置

**Comment by anncwb** [comment]
宽度需要给够

**Comment by anncwb** [comment]
3个最少给120

**Comment by fkuepl** [comment]
明白了，给成120是可以的
