### ISSUE TITLE
顶部菜单混合模式+折叠菜单  当菜单项特别多的时候 滚动菜单的时候，整个页面都在滚动，而不是仅仅是相应菜单那块

### ISSUE THREAD

**Issue by wsxe9988** [anncwb/vue-vben-admin#342]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

顶部菜单混合模式+折叠菜单  当菜单项特别多的时候 滚动菜单的时候，整个页面都在滚动，而不是仅仅是相应菜单那块

### Reproduction

https://vvbin.cn/thin/next/#/home/welcome 或 https://vvbin.cn/next/#/home/welcome

## System Info

- Operating System: Win10
- Brower Version:Google 88.0.4324.182
![image](https://user-images.githubusercontent.com/5828057/110470861-5cbbb080-8116-11eb-8200-46ed458ce7b7.png)
![image](https://user-images.githubusercontent.com/5828057/110470873-604f3780-8116-11eb-93f5-4c1386fc8cc0.png)

**Comment by anncwb** [comment]
这个不支持，考虑切换到左侧混和混和模式。那个模式其实跟这个是一样的

**Comment by toesbieya** [comment]
弹出菜单加个max-height和overflow，美观点再加个margin-top
