### ISSUE TITLE
npm ERR! Failed at the gifsicle@5.2.0 postinstall script.

### ISSUE THREAD

**Issue by M69W** [anncwb/vue-vben-admin#345]
`git clone https://github.com/anncwb/vue-vben-admin.git`
`npm install`

### Describe the bug

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gifsicle@5.2.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gifsicle@5.2.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging
```

### Reproduction
git clone https://github.com/anncwb/vue-vben-admin.git
npm install
show this error: `npm ERR! Failed at the gifsicle@5.2.0 postinstall script.`
use `npm install image-webpack-loader -D` to solve this error ftom [Error: Cannot find module 'gifsicle'问题解决](https://www.cnblogs.com/beileixinqing/p/14468794.html)

## System Info

- Operating System: `windwos`
- Node version: `v12.20.0`
- Package manager (npm/yarn/pnpm) and version: `npm`

**Comment by anncwb** [comment]
Please use yarn

**Comment by liuwave** [comment]
用yarn也报错，之前是用yarn成功安装了，今天用 yarn reinstall 就报错了。

试过更换

> error D:\project\huiyou\simple-crm\simple-admin\node_modules\gifsicle: Command failed.
> Exit code: 1
> Command: node lib/install.js
> Arguments:
> Directory: xxx\node_modules\gifsicle
> Output:
> Response code 404 (Not Found)
> compiling from source
> gifsicle pre-build test failed
> Error: Command failed: C:\Windows\system32\cmd.exe /s /c "autoreconf -ivf"
> 'autoreconf' 



>yarn --version
>1.22.11


>node --version
>v16.9.1

试过更换镜像:

> yarn config get registry
> https://registry.npm.taobao.org

还是不能成功安装。

@anncwb

**Comment by huguangju** [comment]
yarn 安装确实有问题，运行 `yarn` 安装 `gifsicle` 时失败

```bash
[5/5] 🔨  Building fresh packages...
[8/11] ⠐ pngquant-bin
[6/11] ⠐ mozjpeg
[7/11] ⠐ optipng-bin
[4/11] ⠐ gifsicle
error /Users/huguangju/Mine/vue-vben-admin/node_modules/gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments: 
Directory: /Users/huguangju/Mine/vue-vben-admin/node_modules/gifsicle
Output:
Response code 404 (Not Found)
gifsicle pre-build test failed
compiling from source
Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: autoreconf: command not found
```
**系统信息**

- MacOS: 10.13.6
- commit: bc18ecb2777c2080e3cef12932245edf05e7c9fe
- node -v: v16.13.0
- yarn -v: 1.22.17
- yarn 设置了 taobao registry: 'https://registry.npm.taobao.org/'

----

@liuwave 删除 node_modules，重新执行 `yarn bootstrap` 用 `pnpm` 安装，能正常安装
