### ISSUE TITLE
Menus配置：当子路由的hideMenu都为true时，菜单渲染错误

### ISSUE THREAD

**Issue by ZhongMingKun** [anncwb/vue-vben-admin#346]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

菜单渲染错误

### Reproduction
**router/menus/modules/xxx.ts**

```ts
import type { MenuModule } from '/@/router/types';
import { t } from '/@/hooks/web/useI18n';

const menu: MenuModule = {
  orderNo: 0,
  menu: {
    path: '/merchant',
    name: t('routes.merchant.manage'),
    children: [
      {
        path: 'list',
        name: t('routes.merchant.list'),
        hideMenu: true,
      },
      {
        path: 'add',
        name: t('routes.merchant.add'),
        hideMenu: true,
      },
      {
        path: 'bind_bankcard',
        name: t('routes.merchant.bindBankcard'),
        hideMenu: true,
      },
      {
        path: 'detail',
        name: t('routes.merchant.detail'),
        hideMenu: true,
      },
    ],
  },
};
export default menu;
```

**展示效果有问题：顶部菜单混合模式下不应该出现左侧空白菜单**

![image](https://user-images.githubusercontent.com/33282718/110563471-549b5980-8186-11eb-88d2-8cb1cff63394.png)

**顶部菜单模式不应该有下拉菜单**

![image](https://user-images.githubusercontent.com/33282718/110563324-21f16100-8186-11eb-932a-ddc6929b6291.png)

** 左侧菜单模式应该可以直接跳转而不是打开折叠菜单而里面却没内容**

![image](https://user-images.githubusercontent.com/33282718/110563402-3afa1200-8186-11eb-931b-3a90a1883951.png)

**左侧菜单混合模式不应该出现空白菜单**

![image](https://user-images.githubusercontent.com/33282718/110563224-eeaed200-8185-11eb-854a-a9206b8cfe9a.png)

## System Info

- Operating System: win10
- Node version: 14.5.0
- Package manager (npm/yarn/pnpm) and version: yarn 1.22.5

**Comment by carl-jin** [comment]
> bug之外的问题，你能说说你菜单为什么要都隐藏吗，为什么不直接隐藏父级

我印象中, 见过作者好像发过关于这个项目的一些功能实现原理, 作者有空能共享下吗, 我想补习补习, 学习下设计思路

**Comment by ZhongMingKun** [comment]
> bug之外的问题，你能说说你菜单为什么要都隐藏吗，为什么不直接隐藏父级

参考[ant-design-pro-layout](https://procomponents.ant.design/components/layout#menudataitem) 希望可以添加hideChildrenInMenu之类的属性去控制

**Comment by visualhu** [comment]
子菜单设置hideMenu: true时，访问该菜单父菜单失去高亮功能。
