### ISSUE TITLE
热更新后，菜单和标签全部丢失

### ISSUE THREAD

**Issue by hoozi** [anncwb/vue-vben-admin#347]
修改一个页面，vite hmr后菜单和标签全部丢失了T_T

**Comment by anncwb** [comment]
升级最新版本

**Comment by hoozi** [comment]
> 升级最新版本

升级vben吗？

**Comment by anncwb** [comment]
对

**Comment by carl-jin** [comment]
> 对

能更新到thin-next版本吗, 我也想更新

**Comment by anncwb** [comment]
> > 对
> 
> 能更新到thin-next版本吗, 我也想更新

thin昨天才更新。今天稍晚会更新

**Comment by hoozi** [comment]
> > > 对
> > 
> > 
> > 能更新到thin-next版本吗, 我也想更新
> 
> thin昨天才更新。今天稍晚会更新

我都不知道要怎么更新，因为我在里面加了很多自己的东西。更新会覆盖掉吗

**Comment by anncwb** [comment]
跟这个问题其实是一样https://github.com/anncwb/vue-vben-admin/issues/301

**Comment by anncwb** [comment]
这个问题可能还存在，我会在跟踪下

**Comment by hoozi** [comment]
> 这个问题可能还存在，我会在跟踪下

现在是报这个错了 parentComponent.ctx.deactivate is not a function.

**Comment by hoozi** [comment]
> 这个问题跟热更新没关闭吧，你可以提供复现步骤给我

这个确实是热更新出现的，我猜测是热更新的时候 哪个组件丢失了 找不到它的deactivate方法，我还在排查

**Comment by carl-jin** [comment]
> > > > 对
> 
> > > 
> 
> > > 
> 
> > > 能更新到thin-next版本吗, 我也想更新
> 
> > 
> 
> > thin昨天才更新。今天稍晚会更新
> 
> 
> 
> 我都不知道要怎么更新，因为我在里面加了很多自己的东西。更新会覆盖掉吗

把冲突处理下就行了。 这个叫“同步上游版本“你搜下很多教程的

**Comment by carl-jin** [comment]
> 修改一个页面，vite hmr后菜单和标签全部丢失了T_T

看看是不是跟我这个问题一样, https://github.com/anncwb/vue-vben-admin/issues/376 我折腾了一个下午也没整懂
