### ISSUE TITLE
在全屏模式下，F5刷新后菜单按钮丢失了

### ISSUE THREAD

**Issue by fkuepl** [anncwb/vue-vben-admin#359]
![image](https://user-images.githubusercontent.com/2612446/110887023-834f3680-8324-11eb-979d-c57d4fc5d224.png)
1：很大小型TB用户的显示器比较小，会使用该模式，但是一刷新，按钮就没了，能否刷新后不丢失；
2：右边的设置按钮是否可以不显示

**Comment by anncwb** [comment]
第一点不是很明白，哪个没了？  第二点配置文件内自己关闭就可以

**Comment by fkuepl** [comment]
全屏时打开了多个链接，一刷新只有当前页的标签存在，别的都没了，用户和公司客户都认为是BUG

**Comment by anncwb** [comment]
![image](https://user-images.githubusercontent.com/28132598/111122108-865a5900-85a8-11eb-850c-0d1bef3cd6f1.png)
刷新bia标签页 这个也可以阿

**Comment by anncwb** [comment]
虽然可以实现记住标签页,但是切换过去内容不会保持了(如果你开了缓存的话),所以没做.这样也会被当做bug

**Comment by fkuepl** [comment]
有些用户是习惯直接点F5的，是否可以全屏模式下刷新切换标签不是读缓存，这个应该是说的过去的

**Comment by xiaoxian521** [comment]
@fkuepl 这个可以将菜单存缓存，从缓存拿，包括增删tag都需要同时操作一下缓存

**Comment by fkuepl** [comment]
想系统会修复的话，自己就不去改了，毕竟这也挺尝规的，而且从体验上来看，有这功能比没有这功能要好很多，如果系统确定不会修复的话，就关掉吧。
