### ISSUE TITLE
Yarn Install 一直出错

### ISSUE THREAD

**Issue by samchenws** [anncwb/vue-vben-admin#360]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

 warning " > vuex-module-decorators@1.0.1" has incorrect peer dependency "vuex@3".
[5/6] Building fresh packages...
[1/10] ⠂ vue-demi
[2/10] ⠂ core-js
[3/10] ⠂ esbuild
[4/10] ⠂ gifsicle
error D:\project\vben-admin-thin-next-main\node_modules\pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by joel785454405** [comment]
node 版本多少

**Comment by samchenws** [comment]
> node 版本多少

  node -v
v14.15.1
  yarn -v
1.22.5

**Comment by anncwb** [comment]
文档有问题可以看看。不行的话执行`yarn reinstall`或者手动删除node_modules和yarn.lock重新安装依赖即可

**Comment by luckdolphin** [comment]
我不明白这个问题为何会关闭，这个问题目前依然很活跃

**Comment by samchenws** [comment]
yarn clean:lib
yarn clean:cache
yarn reinstall
yarn dev
搞定，老板说得对还是得多看看文档
