### ISSUE TITLE
关于登录后的地址跳转

### ISSUE THREAD

**Issue by fkuepl** [anncwb/vue-vben-admin#361]
登录成功时如果地址中没有redirect指向的页面，是否可以指向菜单栏的第一个有地址的页面？而不是固定在home页

**Comment by anncwb** [comment]
这个最好还是有个首页,不然很多地方都会出错.很多地方点击都是跳转首页

**Comment by fkuepl** [comment]
那现在首页有设置成全局的吗？比如我登录进自己将第一个菜单功能修改成默认的首页，这样所有地方的跳转也就不出错了

**Comment by anncwb** [comment]
修改 pageEnum 内的 BASE_HOME

**Comment by fanhoucheng** [comment]
如果用戶權限沒有BASE_HOME的那個router 那怎麽辦？
是不是可以動態改變？
