### ISSUE TITLE
增加特殊 下拉框组件- 

### ISSUE THREAD

**Issue by worldofchu** [anncwb/vue-vben-admin#364]
即 原本 下拉框 的，现在下拉框按钮替换为 某按钮 比如 默认按钮文本 ...    
这样点 按钮 弹出 模态窗体，里面可以是自行 查询条件+展示表格 ，选择一个或者多个后 返回主窗体，自动将选择的内容 显示到 下拉框，赋予到下拉框 value

**Comment by glorydreamtop** [comment]
好家伙，你家的需求指望别人白给你写了。
