### ISSUE TITLE
select 使用required:true时，value值为数字型时，可以显示lable，但是验证规则会提示验证不通过；如果value值为字符型，select选择框显示的是value的值，而不是lable的值

### ISSUE THREAD

**Issue by fkuepl** [anncwb/vue-vben-admin#367]
![image](https://user-images.githubusercontent.com/2612446/111033534-b260c780-844c-11eb-911b-d74be7e84453.png)
![image](https://user-images.githubusercontent.com/2612446/111033617-12f00480-844d-11eb-9938-2eb716e01c45.png)

**Comment by anncwb** [comment]
value值要和绑定的值一直  1和字符串`1`是匹配不了的

**Comment by fkuepl** [comment]
我想在框中默认显示的是“锁定”，但数据提交到后台时是数字2，并且要验证required:true，那options中要怎么写呢？

**Comment by anncwb** [comment]
[{required:true,type:"number"}]
