### ISSUE TITLE
建议给表格的column的format增加通过api异步翻译功能

### ISSUE THREAD

**Issue by XJH0415** [anncwb/vue-vben-admin#370]
### Subject of the feature

建议给表格的column的format增加通过api异步format功能

### Problem

在实际使用中，表格往往是给用户查阅的，某些column往往是要通过format把接口过来的原始数据翻译成想要的结果，比如性别通过用1表示男，2表示女，这个时候就需要用到format或者slot去把数字1，2转换成男，女。目前的功能能够支持该需求，但是当表格需要翻译的的column比较多，且可以支持后台配置化时，这种方案就不好了。

### Expected behaviour

建议加入apiFormat功能，这样可以结合后端数据字典接口，可配置化的自动format。

### Alternatives

类似于apiSelect组件一样，可以传入一个api  Promise和对应的params，再加入一个fetchSetting设置相应的取值字段

**Comment by anncwb** [comment]
表格内单元格我觉得不适合做异步,这种一般是后台返回，后台在返回 gener字段  时可以同时返回generText字段，表示对应的值。这些对于后台是很容易实现的。只需对枚举转换而已

**Comment by XJH0415** [comment]
不适合是在哪方面，我觉得是可以考虑的，结合数据字典，可以更好的实现配置化，虽然后台很容易实现，但是我觉得这些只是用于展示的generText而去增加后台查询语句复杂度（连接字典表）。上面举例的男女显示，可以用枚举实现，但是有一些复杂的往往会使用字典表，有利于改动调整。相应的，我们也实现了一套的字典功能，结合字典，有异步format的话更方便，后台也不用去关心翻译的问题，前端也只需要配置好api就可以了

**Comment by anncwb** [comment]
不会针对某个单元格做异步。字典表更新比较少。这种可以在登录后统一缓存所有字典或者项目内用到的字典到系统。然后所有组件通过包括表格，下拉这些通过缓存的数据来取值。但这些都是偏业务了，需要根据自己后台接口来。所以这个项目不会去做，只能用到自行去适配自己后台

**Comment by seamusic** [comment]
看到这个回复，真的非常失望。

**Comment by miaobowei** [comment]
建议column增加一个 字典表数据属性类 和 字典表url 以及全局字典表缓存
