### ISSUE TITLE
更新到v2.1.0 热更新报错, 必须刷新页面才行

### ISSUE THREAD

**Issue by carl-jin** [anncwb/vue-vben-admin#374]
![image](https://user-images.githubusercontent.com/24644246/111182129-fe168c80-8584-11eb-9cee-7d9ddd574f93.png)

**Comment by carl-jin** [comment]
我尝试把自己的代码注释掉, 但是热更新后, 还是报错, 应该是这个Icon有问题

**Comment by carl-jin** [comment]
https://github.com/carl-jin/vben-admin-thin-next
可以拉我的项目下来, 打开任意页面, 修改文件, 热更新 -> 报错

**Comment by anncwb** [comment]
直接全新的thin也会是吗

**Comment by carl-jin** [comment]
我试试

**Comment by carl-jin** [comment]
我看了下和issue里面的keepalive是一个问题
