### ISSUE TITLE
提个可能是插件bug的问题

### ISSUE THREAD

**Issue by mypublicuse** [anncwb/vue-vben-admin#378]
复现步骤：
1：例如 找到src\layouts\default\header\components\Breadcrumb.vue  文件 
在
export default defineComponent({
    name: 'LayoutBreadcrumb',
    components: { Icon, [Breadcrumb.name]: Breadcrumb, [Breadcrumb.Item.name]: Breadcrumb.Item },
 
这里  我追加了[Breadcrumb.Item.name]: Breadcrumb.Item  
然后 serve ，打开网页 控制台报错误
Uncaught ReferenceError: LoadingOutlined_default is not defined
    default LoadingOutlined.js:1
    <anonymous> FormItem.js:66 
文件指向 vite-plugin-theme 这个插件 ，请作者验证！谢谢！

**Comment by anncwb** [comment]
没复现.vite-plugin-theme这个只是针对css的提取,不会是这个的问题
