### ISSUE TITLE
表格出现问题，多列

### ISSUE THREAD

**Issue by samchenws** [anncwb/vue-vben-admin#380]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

 当表格的columns 数据
最后一列如下 
{
    title: '操作',
    key: 'action',
    width: '145px',
    fixed: 'right',
    slots: { customRender: 'action' },
  }
没有设置dataIndex会出现多列
我在antdv中一样写法没有遇到.

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by anncwb** [comment]
key改成 dataIndex
