### ISSUE TITLE
手机验证码组件，在BasicForm中使用无法重置input框

### ISSUE THREAD

**Issue by weilinliang** [anncwb/vue-vben-admin#381]
![Snipaste_2021-03-17_10-01-36](https://user-images.githubusercontent.com/51466251/111403384-d439a300-8707-11eb-9bec-634e614a6af9.png)
![image](https://user-images.githubusercontent.com/51466251/111403455-fc290680-8707-11eb-8a39-4625cc4f428a.png)
![image](https://user-images.githubusercontent.com/51466251/111403525-1367f400-8708-11eb-84ad-7f428ef9142d.png)
代码如上

**Comment by Jzow** [comment]
你好 你这个sendCodeApi函数是验证手机必填吗 如何写的呢
