### ISSUE TITLE
菜单主题为白色时，激活菜单的底色不会随主题色变化

### ISSUE THREAD

**Issue by HelKim** [anncwb/vue-vben-admin#382]
![image](https://user-images.githubusercontent.com/30397458/111439480-5f368f80-8740-11eb-83f2-8d430a924b2a.png)
换了橙色主题，激活菜单的底色还是白色，在开发时是正常的，打包之后就不行。

**Comment by anncwb** [comment]
![image](https://user-images.githubusercontent.com/28132598/111633063-13631380-8830-11eb-91ad-b5784f0f22c8.png)
不是可以吗,怎么弄的

**Comment by HelKim** [comment]
> ![image](https://user-images.githubusercontent.com/28132598/111633063-13631380-8830-11eb-91ad-b5784f0f22c8.png)
> 不是可以吗,怎么弄的

https://vvbin.cn/next/#/home/welcome
试试线上的，在dev启动是可以的，打包之后就不行了。
也有可能浏览器问题？我的是chrome 89.0.4389.90

**Comment by anncwb** [comment]
应该是插件的问题,我在跟踪下

**Comment by wsxe9988** [comment]
也发现了，https://vvbin.cn/next/#/ 也能看出这个问题 
![image](https://user-images.githubusercontent.com/5828057/111967437-00ec2100-8b33-11eb-8988-529aa46f02f0.png)  正常图标这个菜单的背景应该是橙色
