### ISSUE TITLE
Icon 雪碧图 无法显示

### ISSUE THREAD

**Issue by weilinliang** [anncwb/vue-vben-admin#383]
![{}I 93_84M7NEQ@GYTL)HYI](https://user-images.githubusercontent.com/51466251/111443888-cc4c2400-8744-11eb-86da-b474937c5134.png)
![5QV5$WAC$ {ZQE8YW9WPLM4](https://user-images.githubusercontent.com/51466251/111443922-d3733200-8744-11eb-96db-232f69dc8f36.png)
![Snipaste_2021-03-17_17-17-26](https://user-images.githubusercontent.com/51466251/111443938-d79f4f80-8744-11eb-8aea-85b043cd5a21.png)
![Snipaste_2021-03-17_17-18-23](https://user-images.githubusercontent.com/51466251/111443950-da9a4000-8744-11eb-9b37-b7729c3f7842.png)
代码如上

**Comment by anncwb** [comment]
提供你的svg图标给我把,我测试是可以的

**Comment by anncwb** [comment]
![image](https://user-images.githubusercontent.com/28132598/111579726-7aada300-87f1-11eb-9418-6a405cbeaf8c.png)
![image](https://user-images.githubusercontent.com/28132598/111579741-826d4780-87f1-11eb-8105-64a410c4c437.png)
好像是可以

**Comment by weilinliang** [comment]
我这边再测试下

**Comment by weilinliang** [comment]
谷歌浏览器版本的问题

**Comment by weilinliang** [comment]
![image](https://user-images.githubusercontent.com/51466251/111761974-6e057980-88db-11eb-9387-98bce7ce39ab.png)
这个不可以

**Comment by weilinliang** [comment]
![image](https://user-images.githubusercontent.com/51466251/111762108-968d7380-88db-11eb-8516-8b02154153a6.png)
我同事的89是可以的

**Comment by anncwb** [comment]
我感觉是svg图标的问题，你可以尝试换一个标准的svg图标来测试

**Comment by weilinliang** [comment]
好的，这个星期一 我再测试下

**Comment by weilinliang** [comment]
我用iconfont 的图标试了，的确是可以的，暂时没问题了
