### ISSUE TITLE
BasicModal嵌套出错

### ISSUE THREAD

**Issue by jenifly** [anncwb/vue-vben-admin#384]
在一个BasicModal中再嵌套BasicModal，在打开外层BasicModal后，再次调用根页面调用openModal时会直接打开内层BasicModal

**Comment by anncwb** [comment]
请给复现代码

**Comment by anncwb** [comment]
看你的描述应该是你的$attrs传递了外层register给内层，这个在$attrs内区分下即可

**Comment by jenifly** [comment]
确实，谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月20日(星期六) 晚上10:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [anncwb/vue-vben-admin] BasicModal嵌套出错 (#384)





 
看你的描述应该是你的$attrs传递了外层register给内层，这个在$attrs内区分下即可
 
&mdash;
