### ISSUE TITLE
最新 后端请求超时

### ISSUE THREAD

**Issue by weilinliang** [anncwb/vue-vben-admin#386]
![image](https://user-images.githubusercontent.com/51466251/111563171-66a67900-87d2-11eb-955d-40e47bdcac04.png)
![image](https://user-images.githubusercontent.com/51466251/111563333-bdac4e00-87d2-11eb-9098-30879cee7db7.png)
应该是vite插件的问题

**Comment by weilinliang** [comment]
![image](https://user-images.githubusercontent.com/51466251/111564055-103a3a00-87d4-11eb-9db6-506d1ef66a71.png)

**Comment by weilinliang** [comment]
用的真实接口，mock已经关闭

**Comment by weilinliang** [comment]
aixos文件也没改动

**Comment by anncwb** [comment]
生产和开发都会吗?

**Comment by weilinliang** [comment]
![image](https://user-images.githubusercontent.com/51466251/111564739-390eff00-87d5-11eb-92cd-565684329462.png)
生产请求是可以的，好像登录跳转也有问题，不过合并我有改到permission 文件，具体问题还不清楚

**Comment by guanguanchuangyu** [comment]
![image](https://user-images.githubusercontent.com/25916858/111718416-d8df9200-8894-11eb-8631-07359d6434d3.png)
试试调整一下，好像是logger的问题

**Comment by anncwb** [comment]
我这边一直没复现出这个问题

**Comment by anncwb** [comment]
"vite-plugin-windicss": "0.8.3", 将这个插件版本固定即可
