### ISSUE TITLE
useTable 中的 rowSelection参数, 设置onChange后, checkbox点击选中失效

### ISSUE THREAD

**Issue by carl-jin** [anncwb/vue-vben-admin#390]
# 问题描述
只要在`rowSelection`里面设置了`onChange`方法, 就会导致tables左边的checkbox无法点击
``` typescript
   const [registerTable, { reload, setLoading }] = useTable({
        ....
        rowSelection: {
          onChange: (selectedRowKeys, selectedRows) => {
          },
        },
        ...
      });
```

# 复现步骤
1. 随便弄个table, demo里面的也行
2.  设置
    ``` typescript
         rowSelection: {
          onChange: (selectedRowKeys, selectedRows) => {
          },
        },
    ```
3. 尝试点击 checkbox

**Comment by carl-jin** [comment]
如果无法复现, 如果有时间的话, [https://github.com/carl-jin/vben-admin-thin-next](https://github.com/carl-jin/vben-admin-thin-next)
1. 拉取项目
2. 访问 [http://localhost:3100/automation/flows](http://localhost:3100/automation/flows)

**Comment by carl-jin** [comment]
睡觉去了, 作者没时间弄的话, 明天我再捣鼓捣鼓, 我还没细看`useTable`

**Comment by carl-jin** [comment]
[https://github.com/anncwb/vue-vben-admin/blob/67962f1deea31d695d20ae0ea7fc39b39c1eea47/src/components/Table/src/hooks/useRowSelection.ts#L25](https://github.com/anncwb/vue-vben-admin/blob/67962f1deea31d695d20ae0ea7fc39b39c1eea47/src/components/Table/src/hooks/useRowSelection.ts#L25)
正确的使用方法应该是监听`selection-change`事件, 而不是传递onChange方法

**Comment by luger1990** [comment]
我看目前还是有问题

**Comment by mynetfan** [comment]
监听onChange后无法选中的问题，在好几个版本之前就已经解决了。请更新后再试
