### ISSUE TITLE
table样式需要优化

### ISSUE THREAD

**Issue by fkuepl** [anncwb/vue-vben-admin#395]
1：进入Demo的TreeTable.vue，去掉class="p-4"，可以发现没有撑满整屏
2：加上:pagination="false"属性，发现也会影响撑满整屏的高度

**Comment by anncwb** [comment]
第二个问题需要手动加上 :resizeHeightOffset=“-16”

**Comment by fkuepl** [comment]
第一个问题又出现了，我拉取的是最新版本
