### ISSUE TITLE
项目复杂度是否过高

### ISSUE THREAD

**Issue by JacBian** [anncwb/vue-vben-admin#399]
### Subject of the feature

首先项目的精致和完善水平大大超过鄙人的水平，所以肯定存在菜鸟看不到的地方太多。
config目录，src目录，router目录。下设层级和分类真的非常细，反而给我这种菜鸟的感觉是，是否设计过头了。
越是细致的设计，学习成本越高，降低设计的复杂度，在一个文件内是否也可以表达出分类的思想。
和项目的精细对比，这个吐槽有点鸡蛋里挑骨头，哈哈哈

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by anncwb** [comment]
一开始这个项目的目标就是为中大型项目提供的，中大型项目一般内容较多，需要细分比较好维护。我个人也习惯这种写法

**Comment by agileago** [comment]
@JacBian 不是你的问题，好的代码好的架构就是简单、清晰、易懂的
吐槽几个点
- 用好依赖注入，而不是过度包装，不要用 pinia，直接顶层注入服务
- 基础布局最好可以封装成库，`vben-layout` ?
- 去掉`windi.css`这玩意太黑盒，我在IDE里面点类竟找不到定义，还得去文档上找
- 有些代码真的没必要封装那么多层

全局服务使用类来书写
``` typescript

class UserService {
  static TOKEN: InjectionKey<UserService> = Symbol('UserService')
  constructor() {
    provide(UserService.TOKEN, this)
  }
  user = ref({
    name: ''
  })
}

const AppProvider = defineComponent({
  setup(props, ctx) {
    // 所有服务的初始化，或者可以用依赖注入的库，因为有可能不同服务之间有关联
    new UserService()
    return () => ctx.slots.default?.()
  }
})
```

**Comment by zhangzy56** [comment]
首先谢谢作者的开源精神
其次封装真的太过渡了  一层一层在套娃？看吐了  个人觉得单纯在炫技

**Comment by zhangzy56** [comment]
就是一个很简单的管理系统嘛  整的那么复杂  一层层的封装嵌套   实在忍不住了  来吐槽一手

**Comment by ClearFeng** [comment]
没必要封装这么多层的

**Comment by CODPHISH** [comment]
感觉封装太复杂了，一个table都看半天看不明白

**Comment by agileago** [comment]
@CODPHISH   https://github.com/agileago/oop-pro   看看这个

**Comment by C-racker** [comment]
确实，这种套娃编程，自己能快速定位吗？

**Comment by cMing1997** [comment]
> 确实，这种套娃编程，自己能快速定位吗？

代码定位，可以使用 code-inspector-plugin 这个插件
