### ISSUE TITLE
功能新增

### ISSUE THREAD

**Issue by wsxe9988** [anncwb/vue-vben-admin#402]
### Subject of the feature

Describe your issue here.

### Problem

![image](https://user-images.githubusercontent.com/5828057/111965086-4ce99680-8b30-11eb-8186-c869dd1310a6.png)
能否在红色圈出的地方把修改密码 个人中心 个人设置 移过去呢

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by anncwb** [comment]
bug之外的问题请到https://github.com/anncwb/vue-vben-admin/discussions/251提
