### ISSUE TITLE
刷新页面跳转到登录页

### ISSUE THREAD

**Issue by RuoFeng2015** [anncwb/vue-vben-admin#407]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:
- 精简版
刷新页面跳转到登录页

**Comment by hoozi** [comment]
> **⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**
> 
> * [ ]  Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
> * [ ]  Make sure the code is up to date. (Some bugs have been fixed in the latest code)
> * [ ]  This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.
> 
> ### Describe the bug
> A clear and concise description of what the bug is..
> 
> ### Reproduction
> Please describe the steps of the problem in detail to ensure that we can restore the correct problem
> 
> ## System Info
> * Operating System:
> * Node version:
> * Package manager (npm/yarn/pnpm) and version:
> * 精简版
>   刷新页面跳转到登录页
同样问题，token似乎没有持久化住

**Comment by anncwb** [comment]
fix fedd9ca
