### ISSUE TITLE
vue别名 怎么用。。。

### ISSUE THREAD

**Issue by zezhongmiao** [anncwb/vue-vben-admin#411]
// ['/vue/','2vue/dist/vue.esm-bundler.js'],

vite.config.js
   alias: createAlias([
     // ['/vue/','vue/dist/vue.esm-bundler.js'],
      // /@/xxxx => src/xxxx
      ['/@/', 'src'],
      // /#/xxxx => types/xxxx
      ['/#/', 'types'],
    ]),

**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by anncwb** [comment]
['vue','2vue/dist/vue.esm-bundler.js']
