### ISSUE TITLE
GitHub文档图中这两个是不是写反了？

### ISSUE THREAD

**Issue by bluesnn** [anncwb/vue-vben-admin#412]
![image](https://user-images.githubusercontent.com/19706348/112267535-906b0e80-8cb0-11eb-99a9-4d91e32369bb.png)
![image](https://user-images.githubusercontent.com/19706348/112268041-52221f00-8cb1-11eb-8eed-1be69236c51a.png)

**Comment by anncwb** [comment]
fix 24a3f90
