### ISSUE TITLE
更改主题色会导致分布表单步骤数字颜色异常

### ISSUE THREAD

**Issue by SimonFerrymen** [anncwb/vue-vben-admin#414]
![image](https://user-images.githubusercontent.com/51774255/112271837-6288c880-8cb6-11eb-98bb-62c55c927568.png)

**Comment by wozien** [comment]
在开发环境我发现自己写的样式变量有可能会覆盖组件库的，是不是有可能是这个原因？

**Comment by anncwb** [comment]
这个还没去看。后面跟主题有关的我统一改
