### ISSUE TITLE
本地运行工程，分析页面中图表未显示legend

### ISSUE THREAD

**Issue by kenshinguan** [anncwb/vue-vben-admin#415]
本地运行工程，分析页面中的图表没有显示legend

**Comment by anncwb** [comment]
自行添加参数即可

**Comment by kenshinguan** [comment]
@anncwb 已添加legend参数，使用工程封装的echarts图表未能显示，直接使用echarts时可以显示。通过昨天拉取的代码，本地运行时，系统分析页面案例图表是未能显示，但是通过访问线上https://vvbin.cn/next分析页面案例图表是能够显示
