### ISSUE TITLE
缓存问题

### ISSUE THREAD

**Issue by YYYlh** [anncwb/vue-vben-admin#416]
![image](https://user-images.githubusercontent.com/38207999/112291999-9cb09500-8ccb-11eb-97be-451cf9273874.png)
set方法中是不是应该传入 expire - now; 传入的expire太大导致定时器失效直接执行了remove方法

**Comment by anncwb** [comment]
你这个不是最新代码吧，最新代码应该是解决了

**Comment by YYYlh** [comment]
> 你这个不是最新代码吧，最新代码应该是解决了

最新的代码没有问题，谢谢作者大大
