### ISSUE TITLE
Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by 123303841** [anncwb/vue-vben-admin#418]
yarn install 后会报错。我是直接拉的代码

Uncaught SyntaxError: Unexpected token .

![image](https://user-images.githubusercontent.com/17061972/112413736-9f85a700-8d18-11eb-8e73-d4f229173c6e.png)
![image](https://user-images.githubusercontent.com/17061972/112413791-b3c9a400-8d18-11eb-9275-8f068d1c755e.png)
请问下，这个问题怎么解决

**Comment by anncwb** [comment]
本地开发浏览器换谷歌80+
