### ISSUE TITLE
I do not have YARN, can I use NPM?

### ISSUE THREAD

**Issue by Husky-Yellow** [anncwb/vue-vben-admin#42]
I wanted to use NPM to use your Vite-admin project, but an error was reported

**Comment by anncwb** [comment]
Can you provide the node.js version and error information?

**Comment by Husky-Yellow** [comment]
![image](https://user-images.githubusercontent.com/50540342/96406991-07d4d780-1213-11eb-96c0-ed1f7ab04d78.png)

**Comment by Husky-Yellow** [comment]
![image](https://user-images.githubusercontent.com/50540342/96407256-90ec0e80-1213-11eb-841d-d5a146bc626e.png)

**Comment by anncwb** [comment]
Try to lower the node.js version to 12. And delete the lock file. Then reinstall the dependencies

**Comment by anncwb** [comment]
Installing a yarn is actually very simple. Just npm i -g yarn

**Comment by Husky-Yellow** [comment]
Thanks,It's a great project
