### ISSUE TITLE
BasicTree组件的疑似bug

### ISSUE THREAD

**Issue by ChaosLcc** [anncwb/vue-vben-admin#420]
#### 1. 返回的数据问题，层级关联和层级独立返回的数据是不是弄反了？
<img width="591" alt="Xnip2021-03-25_14-50-56" src="https://user-images.githubusercontent.com/16434139/112431483-8e6d8200-8d7a-11eb-885b-7e5652863245.png">

<img width="609" alt="Xnip2021-03-25_14-53-45" src="https://user-images.githubusercontent.com/16434139/112431505-96c5bd00-8d7a-11eb-9852-a3899f2e77ce.png">

<img width="682" alt="Xnip2021-03-25_14-54-10" src="https://user-images.githubusercontent.com/16434139/112431547-a1805200-8d7a-11eb-8bb7-b86fb9b84719.png">

#### 2. 切换层级关联和层级独立的问题

- 切换层级关联和层级独立，不再做任何选择操作，直接提交，返回的menuIds格式不会改变（格式指的是上图的数组或者对象）
- 切换层级关联和层级独立，进行选择操作，提交，返回的menuIds格式会改变

**Comment by anncwb** [comment]
这个应该不是项目的问题，是组件库的问题，你可以用a-tree尝试看看。应该也会出错。
