### ISSUE TITLE
table工具栏的内容多过时，不会自动换行，造成搜索按钮都没法点了

### ISSUE THREAD

**Issue by fkuepl** [anncwb/vue-vben-admin#422]
![image](https://user-images.githubusercontent.com/2612446/112442772-296c5900-8d87-11eb-81f1-6740d7810480.png)
![image](https://user-images.githubusercontent.com/2612446/112442900-4c970880-8d87-11eb-8162-7ff58330e42f.png)

**Comment by fkuepl** [comment]
上面是二张图，第一张是没显示全的，第二张是大屏显示是全的

**Comment by anncwb** [comment]
这种是你自己控制的。或者改变布局，多的按钮放到下拉里面。
