### ISSUE TITLE
最新代码 菜单栏 Menu 下的 hideMenu 属性设置为true 失效

### ISSUE THREAD

**Issue by raylin666** [anncwb/vue-vben-admin#427]
![image](https://user-images.githubusercontent.com/10880431/112500258-30b15800-8dc3-11eb-8471-de2a4d08b4ee.png)
![image](https://user-images.githubusercontent.com/10880431/112500340-4161ce00-8dc3-11eb-9ca5-99c101e109c3.png)

如图sh所示，hideMenu 设置为 true, 依然展示在了菜单栏

**Comment by anncwb** [comment]
hiddenMenu应该是设置在路由的meta内
