### ISSUE TITLE
完整版 yarn install 报错  尝试各种解决办法无果

### ISSUE THREAD

**Issue by Mr-Vash** [anncwb/vue-vben-admin#428]
### yarn install 报错
`error E:\WWW\jl_desktop\node_modules\pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: E:\WWW\jl_desktop\node_modules\pngquant-bin
Output:
‼ unable to verify the first certificate
  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed`

**Comment by Mr-Vash** [comment]
`info yarn config
{
  'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-commit-hooks': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'bin-links': true,
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': false,
  'user-agent': 'yarn/1.22.10 npm/? node/v12.13.0 win32 x64',
  lastUpdateCheck: 1616661756509
}
info npm config
{
  'strict-ssl': false,
  registry: 'http://registry.npm.taobao.org/',
  ca: ''
}`

这是我的npm和yarn的配置信息

**Comment by Mr-Vash** [comment]
1.删除package.json中vite-plugin-imagemin依赖

2.删除build/vite/plugin/index.ts中  import { configImageminPlugin } from './imagemin'   以及VITE_USE_IMAGEMIN && vitePlugins.push(configImageminPlugin())

已解决

**Comment by ningrunting** [comment]
这个方案去掉了图片压缩，会对加载性能有影响吗？如果需要用到图片压缩，还有没有其他的解决方案？

**Comment by Realybig** [comment]
是因为imagemin不支持m1和m2芯片吗？
