### ISSUE TITLE
好奇去掉 Tailwind CSS 的原因

### ISSUE THREAD

**Issue by iiiyu** [anncwb/vue-vben-admin#43]
纯属个人好奇为什么要去掉 Tailwind CSS 。
基于什么样的考虑呢？

**Comment by iiiyu** [comment]
我看了看文档，因为用了Ant Design的原因吧。

**Comment by anncwb** [comment]
@iiiyu 跟vite配合很卡。可以看这个问题https://github.com/vitejs/vite/issues/890

**Comment by iiiyu** [comment]
> @iiiyu 跟vite配合很卡。可以看这个问题[vitejs/vite#890](https://github.com/vitejs/vite/issues/890)

嗯嗯 感谢回答。
