### ISSUE TITLE
建议优化下form中ApiSelect，可以添加参数控制点击后初次访问接口

### ISSUE THREAD

**Issue by fkuepl** [anncwb/vue-vben-admin#430]
![image](https://user-images.githubusercontent.com/2612446/112611044-4c1a7280-8e58-11eb-82cc-716638034aa8.png)
这个api的调用可以是点击后触？别一进页面就触发；  对比table页面，用户不一定会使用搜索，可以减少API的请求

**Comment by carl-jin** [comment]
https://github.com/anncwb/vue-vben-admin/issues/357

**Comment by sandiandian** [comment]
这个是可以设置的
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/38250151/187879942-695911c7-6ab3-49cf-8510-59e97b8c8570.png">
