### ISSUE TITLE
table 高度优化

### ISSUE THREAD

**Issue by fkuepl** [anncwb/vue-vben-admin#437]
![image](https://user-images.githubusercontent.com/2612446/112966084-79c72a80-917c-11eb-930a-3446b3d05aad.png)
想一次性把系统中所有table的滚动条去除，所以修改了BasicTable组件，在table中添加了:scroll="{x:null,y:null}"，
![image](https://user-images.githubusercontent.com/2612446/112966251-a1b68e00-917c-11eb-83fc-db880373ae16.png)
 

结果：高度不再是满屏了

问题2：找到DEMO中的basic基础table ,去除属性class="p-4"，table  也不是满屏的

**Comment by xiaoxian521** [comment]
@fkuepl 现在没有这个问题了吧

**Comment by fkuepl** [comment]
> @fkuepl 现在没有这个问题了吧

我还没更新，不知道修复了没有，想着等我提的几个问题都修复了再统一更新下

**Comment by xiaoxian521** [comment]
嗯嗯 你可以先更新 这个问题应该是修复了 可以关了这个issues

**Comment by fkuepl** [comment]
> @fkuepl 现在没有这个问题了吧

该问题还是存在的哟，我提了新的issues
