### ISSUE TITLE
useLoading方法导致onMounted无法async

### ISSUE THREAD

**Issue by PuiwahWai** [anncwb/vue-vben-admin#438]
### Describe the bug

useLoading方法导致onMounted无法async

### Reproduction

onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

**Comment by sandwichLili** [comment]
怎么修改全局loading图样呢，table和form里用的也是相同
