### ISSUE TITLE
浏览器 title 不会更新

### ISSUE THREAD

**Issue by weilinliang** [anncwb/vue-vben-admin#440]
![image](https://user-images.githubusercontent.com/51466251/113405884-21db2e80-93dd-11eb-8cba-1a72b4c10326.png)
真实接口的后端返回动态路由的模式下
点击退出登录 再登录 浏览器标题如上图表示
![image](https://user-images.githubusercontent.com/51466251/113406081-754d7c80-93dd-11eb-89a6-625b522905fd.png)

**Comment by anncwb** [comment]
这个获取最新代码，应该是修复了
