### ISSUE TITLE
组件=》Table =》 开启搜索区域 字段三下拉框不对；对不起，封装的是不是有点过头了，还是这就是新的typescript的项目编程思维

### ISSUE THREAD

**Issue by syifeng** [anncwb/vue-vben-admin#442]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### 组件=》Table =》 开启搜索区域 字段三下拉框不对
https://vvbin.cn/next/#/comp/table/formTable

下载下来看了下这个table，table封装了很多种类型，如果自己要写table的话看着确实是很简单，配置好就行，但是一层层往后去看代码才发现这个封装了好多层，相当于把原来的table加了一层层逻辑对外只给配置，这样看似对外很简单，但是一旦遇到问题，一层层找也确实是很头大啊

**Comment by anncwb** [comment]
这个只是个人习惯，代码现在页没去优化。其实很多组件可以自己写，没必要用现成的，不习惯反而加大难度
