### ISSUE TITLE
完整版-Table开启搜索区域页面，自定义select没有正确显示

### ISSUE THREAD

**Issue by Mr-Vash** [anncwb/vue-vben-admin#450]
![QQ图片20210407141751](https://user-images.githubusercontent.com/15337219/113819546-0b9deb80-97ac-11eb-9a54-ece0e2334d96.png)

去掉下图配置项后正确显示select
![QQ图片20210407141746](https://user-images.githubusercontent.com/15337219/113819729-4dc72d00-97ac-11eb-834a-8b004fe6ba2c.png)

**Comment by anncwb** [comment]
这是正确的。这个是为了演示slot用法

**Comment by holyrong** [comment]
@anncwb  搜索区域中 Select控件，如何异步加载数据库的数据源？
`componentProps: {
			options: await getOptions(),
		},`
这种写法，dev模式没问题，build的时候会报错：
`Top-level await is not available in the configured target environment ("es2015")`
