### ISSUE TITLE
Modal 设置confirmLoading 为true 后 关闭瞬间能触发点击事件

### ISSUE THREAD

**Issue by weilinliang** [anncwb/vue-vben-admin#451]
![image](https://user-images.githubusercontent.com/51466251/113849376-005ab800-97cc-11eb-9b83-28d241e3dfb8.png)
![image](https://user-images.githubusercontent.com/51466251/113849430-10729780-97cc-11eb-840b-32ae6d219a9c.png)
![image](https://user-images.githubusercontent.com/51466251/113849524-2d0ecf80-97cc-11eb-8638-5141e71eac52.png)
代码如上图，弹框关闭后再设置confirmLoading 为false，但是还是能触发事件，是我写法问题吗，我尝试过使用setTimeout是可以防止再次点击的

**Comment by anncwb** [comment]
可以给下更详细的代码吗，modelOk是在什么时候执行的

**Comment by xiaoxian521** [comment]
@weilinliang 提供个示例代码仓库吧

**Comment by weilinliang** [comment]
晚点给你们提供

**Comment by weilinliang** [comment]
晚点给你们提供

**Comment by weilinliang** [comment]
![image](https://user-images.githubusercontent.com/51466251/113990597-352a4600-9884-11eb-8232-e63ed1d686a9.png)
![image](https://user-images.githubusercontent.com/51466251/113990669-483d1600-9884-11eb-9a2d-9da7598ea6ee.png)
![image](https://user-images.githubusercontent.com/51466251/113990719-52f7ab00-9884-11eb-9803-01d4fdbc44b0.png)
![image](https://user-images.githubusercontent.com/51466251/113990926-8a665780-9884-11eb-9c30-fe349cdb4d2b.png)
![image](https://user-images.githubusercontent.com/51466251/113990950-9225fc00-9884-11eb-9d67-207fe623d621.png)

流程如上图

**Comment by anncwb** [comment]
没能复现。尝试排查下$attrs是否存在多次复用触发

**Comment by xiaoxian521** [comment]
@weilinliang 直接提供代码仓库吧 这样也好调试

**Comment by weilinliang** [comment]
![image](https://user-images.githubusercontent.com/51466251/114123086-2d21e300-9924-11eb-878a-2445b5c7a1a4.png)

![image](https://user-images.githubusercontent.com/51466251/114123051-1ed3c700-9924-11eb-973c-3cb8a9b8ab01.png)
我尽量还原了，我也没能用新的仓库代码复现出来，就很奇怪

**Comment by xiaoxian521** [comment]
嗯嗯 如果没问题 关了这个issues吧
