### ISSUE TITLE
给select控件(多选)通过 setFieldsValue 赋值 一个数组,  validate过不去. 需要手动重新选中后才能通过

### ISSUE THREAD

**Issue by qqllyy79** [anncwb/vue-vben-admin#462]
我定义了一个select 控件:
.....
  {
      field: 'childroleid',
      label: '副角色',
      component: 'Select',
      required: true,
      componentProps: {
        mode:'multiple',
        getPopupContainer: () => document.body,
      },
  },
.....

在useDrawerInner 的方法中 调用
........
setFieldsValue({
            ...data.record,
            mainroleid:userRole.mainroleid,
            childroleid:['15236725976482816'],
            maindeptid:userDept.maindeptid,
            childdeptid:userDept.childdeptids,
          });
.....
赋值, 我赋值了一个常量.  
界面中select 控件能将选择项选出来, 但是validate 会提示 不能为空.  

不清楚是使用方式存在问题, 还是其他的什么原因, 望指点一下

**Comment by anncwb** [comment]
见 #299

**Comment by qqllyy79** [comment]
谢谢
