### ISSUE TITLE
自定义组件Table的defaultExpandAllRows无效

### ISSUE THREAD

**Issue by gudufy** [anncwb/vue-vben-admin#469]
自定义组件Table的defaultExpandAllRows无效

**Comment by anncwb** [comment]
defaultExpandAllRows不能加在useTable，直接加标签上。或者可以使用函数在初次渲染的时候展开全部

**Comment by fengbindev** [comment]
> defaultExpandAllRows不能加在useTable，直接加标签上。或者可以使用函数在初次渲染的时候展开全部

我加在标签上也没用，或者怎么让表格数据加载完成后展开全部
