### ISSUE TITLE
[功能需求]带搜索表单和分页的列表组件

### ISSUE THREAD

**Issue by linjiacheng** [anncwb/vue-vben-admin#474]
### Subject of the feature

带搜索表单和分页的列表组件
1、支持开启搜索
2、支持定义数据源，支持自定义渲染，支持action操作项
3、支持翻页

**Comment by anncwb** [comment]
没明白你的意思，可以描述清楚一点？

**Comment by linjiacheng** [comment]
类似这样
![无标题2](https://user-images.githubusercontent.com/620626/114479032-2e0f8900-9c32-11eb-8825-db3fd161b5a1.png)
或者这样
![无标题](https://user-images.githubusercontent.com/620626/114479034-2f40b600-9c32-11eb-8769-b460310e5313.png)

**Comment by anncwb** [comment]
这种不是表格了，属于列表了

**Comment by linjiacheng** [comment]
是的，我觉得应该是叫BasicList.vue之类的，甚至可以是BasicTable的基类。

**Comment by xiaoxian521** [comment]
我感觉主题部分提供个插槽就行了

**Comment by leeweikung** [comment]
<img width="1678" alt="table select" src="https://user-images.githubusercontent.com/18099969/116383845-d2581900-a849-11eb-894a-36d07d530b5f.png">

请问大神们能否参考sapui5的table select组件封装一个
