### ISSUE TITLE
table滚动条太影响美观了，是否能优化下？

### ISSUE THREAD

**Issue by fkuepl** [anncwb/vue-vben-admin#478]
![image](https://user-images.githubusercontent.com/2612446/114494201-894f7480-9c4e-11eb-9638-bdb08505b284.png)
加上属性：:scroll="{x:null,y:null}"  时，会存在二个问题，目前使用的是2.3.0版本

1：当内容宽度或高度大于外宽时，滚动效果也没有了
2：自适应的高度会高于一大截

![image](https://user-images.githubusercontent.com/2612446/114494463-0844ad00-9c4f-11eb-92a7-096f520edf59.png)

**Comment by fkuepl** [comment]
如果滚动条在不未出现的情况下显示的是一像素宽度的线条，并且左边也有一像素的宽，效果效果到也会好很多

**Comment by mynetfan** [comment]
fixed in: https://github.com/anncwb/vue-vben-admin/commit/735028c43055e8e80ebc7344af0cd0f51c744f98

**Comment by transtone** [comment]
这些修复是否可以提交给 ant-design-vue 官方，让更多人享受到这些改进。
