### ISSUE TITLE
线上Mock 求助

### ISSUE THREAD

**Issue by tky753** [anncwb/vue-vben-admin#479]
thin项目，版本 2.3.0
照着[文档](https://vvbin.cn/doc-next/guide/basic/mock.html#%E7%BA%BF%E4%B8%8A-mock)设置了
1.   **.env.production**修改 `VITE_USE_MOCK = true`
2.  mock/_createProductionServer.ts 不用改，因为已经全部mock都加进去了
3. **/@/main.ts**引入
```ts
import { setupProdMockServer } from '../mock/_createProductionServer';
if (import.meta.env.PROD && import.meta.env.VITE_USE_MOCK) {
  setupProdMockServer();
}
```
4. 运行 yarn preview
5. 点登录，确实没有产生请求，但是报错：**RangeError: Maximum call stack size exceeded**
![image](https://user-images.githubusercontent.com/18205977/114522553-0fcb7c80-9c76-11eb-981b-2bceffb934e3.png)

**Comment by anncwb** [comment]
这个代码不需要自行注入，在插件那边注入了
```ts
if (import.meta.env.PROD && import.meta.env.VITE_USE_MOCK) {
  setupProdMockServer();
}
```

检查是否用了restful-api格式的mock接口，restful在线上会不行。参考项目，项目预览网站可以正常使用。

最后，线上最好不要开启mock，这个只针对于示例网站
