### ISSUE TITLE
使用icon组件时，出现 Cannot access 'Icon' before initialization错误

### ISSUE THREAD

**Issue by bhxf** [anncwb/vue-vben-admin#480]
（只针对本地开发）页面引入icon组件，随便修改某个数据（样式除外），就会出现 Cannot access 'Icon' before initialization。导致页面无法热更新成功。

**Comment by carl-jin** [comment]
[https://github.com/anncwb/vue-vben-admin/issues/376#issuecomment-799931968](https://github.com/anncwb/vue-vben-admin/issues/376#issuecomment-799931968)
试试这个, 这个问题我也遇到过

**Comment by bhxf** [comment]
好的，我试下。

**Comment by bhxf** [comment]
确实是可以了，多谢。后面这块是需要作者在进行更新优化对吧。😄
