### ISSUE TITLE
ant-design没有按需加载

### ISSUE THREAD

**Issue by may2472** [anncwb/vue-vben-admin#484]
You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size. Not support Vite !!!
打开浏览器开发者工具，一直存在上述的警告

**Comment by anncwb** [comment]
这个是ant-design 的问题。项目是按需引入的，babel-plugin-import这个是针对webpack的，vite不支持

**Comment by zzs89117920** [comment]
![image](https://user-images.githubusercontent.com/5515847/125243998-5e45f100-e321-11eb-9e68-efda539325ca.png)
antd-vue 提供了按需加载

**Comment by zzs89117920** [comment]
![image](https://user-images.githubusercontent.com/5515847/125243998-5e45f100-e321-11eb-9e68-efda539325ca.png)
antd-vue 提供了vite的按需加载

**Comment by zzs89117920** [comment]
![image](https://user-images.githubusercontent.com/5515847/125244164-93eada00-e321-11eb-8cb5-29174553e532.png)
