### ISSUE TITLE
合计的精度有问题

### ISSUE THREAD

**Issue by fkuepl** [anncwb/vue-vben-admin#486]
![image](https://user-images.githubusercontent.com/2612446/114978011-33333900-9ebb-11eb-99e2-c3b0fae1e052.png)

1：精度有问题
2：高度自适应时，比不带合计行的table要高出一截，应该减掉

**Comment by anncwb** [comment]
合计这个你要自行除了。js小数想加会丢失精度的。
高度我会统一在看看怎么优化

**Comment by fkuepl** [comment]
以前使用的layui，他的高度是对复杂表头，简单表头，分页栏，搜索等这几个项都设置了高度，然后根据要显示的表类型做了加减处理，可以借鉴下。
