### ISSUE TITLE
table高度和滚动条的问题能提速解决解决么？实在被逼的紧，设计要求不能有滚动条，不使用canResize这个的话，table 头又不能固定住

### ISSUE THREAD

**Issue by fkuepl** [anncwb/vue-vben-admin#494]
![image](https://user-images.githubusercontent.com/2612446/115137349-36aff700-a058-11eb-980b-2a8bac4870a1.png)

**Comment by anncwb** [comment]
这个问题不是看着这么好改，好改我早就取消了。ant design - table的scroll也有一些限制，还没找到取消的办法。这个问题跟#478一样，就先关了
