### ISSUE TITLE
downloadByUrl 函数 fileName参数 无效

### ISSUE THREAD

**Issue by weilinliang** [anncwb/vue-vben-admin#500]
![image](https://user-images.githubusercontent.com/51466251/115198492-b1464880-a124-11eb-8dfa-d8f8f5726950.png)

![image](https://user-images.githubusercontent.com/51466251/115215634-4867cc00-a136-11eb-870d-fbedb71fb6ba.png)

![image](https://user-images.githubusercontent.com/51466251/115198630-da66d900-a124-11eb-9a46-abdd588f4e25.png)

**Comment by anncwb** [comment]
文件名建议还是后台改，这个影响因素很多

**Comment by weilinliang** [comment]
这个用的是文件的url 下载，没调接口，改不了名字的话，就关了这个issue了

**Comment by anncwb** [comment]
要返回数据流格式才可以设置文件名，直接url会直接下载，改不了
