### ISSUE TITLE
primary ghost按钮hover时样式问题

### ISSUE THREAD

**Issue by Jaciky** [anncwb/vue-vben-admin#502]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

按钮样式问题

### Reproduction

![image](https://user-images.githubusercontent.com/29850423/115222829-bc59a280-a13d-11eb-89dc-9e9b0fcbfd64.png)

## System Info

- Operating System:win10
- Node version:^14
- Package manager (npm/yarn/pnpm) and version:yarn@1.22.5

**Comment by anncwb** [comment]
更新最新代码
