### ISSUE TITLE
design/index.less 中代码 会导致 a-affix 组件浮动效果失效

### ISSUE THREAD

**Issue by cnhuye** [anncwb/vue-vben-admin#506]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug
design/index.less 中代码:
html,body{height:100%}

会导致 antd 的 affix 失效。

### Reproduction

不太清楚为什么会限制 height:100%，但这个css会导致 antd 的 a-affix 组件失效，不再有浮动效果 。

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by anncwb** [comment]
能否给个示例，我这边测试没出现这个问题
