### ISSUE TITLE
内容全屏时，表格高度没有重新计算

### ISSUE THREAD

**Issue by jenifly** [anncwb/vue-vben-admin#508]
点击内容全屏：
![image](https://user-images.githubusercontent.com/22962492/115355315-21200600-a1ed-11eb-9e02-9833ead6207f.png)
表格高度没有重新计算，在改变数据或触发窗口大小改变后表格高度重新计算
取消内容全屏后，表格使用了内容全屏中的高度，也没有重新计算
![image](https://user-images.githubusercontent.com/22962492/115356283-1154f180-a1ee-11eb-9d78-c1c5d357f19b.png)

**Comment by fkuepl** [comment]
这个项目高度有多处问题，希望作者能做为首要任务进行修正下； 我的想法是可以只要监听全屏的高度，再将每处固定的高度，如顶部，搜索栏，标签栏，table的多级头表，合计栏等等这些高度定义到一个数组中，将这些显示了的高度加一起，当浏览器的高度监听到发生变化时，减掉及可，当时还有些内容块是用户自己定义的，现系统中有一个参数是可以让用户自己调整的，也需要保留。

**Comment by fkuepl** [comment]
这个项目高度有多处问题，希望作者能做为首要任务进行修正下； 我的想法是可以只要监听全屏的高度，再将每处固定的高度，如顶部，搜索栏，标签栏，table的多级头表，合计栏等等这些高度定义到一个数组中，将这些显示了的高度加一起，当浏览器的高度监听到发生变化时，减掉及可，当时还有些内容块是用户自己定义的，现系统中有一个参数是可以让用户自己调整的，也需要保留。
