### ISSUE TITLE
modal handleDrag

### ISSUE THREAD

**Issue by finalreturn** [anncwb/vue-vben-admin#51]
What happens?
modal拖拽，在打开1+N次后失效。

复现步骤，错误日志以及相关配置
传入modal prop , destroyOnClose = true (关闭时销毁 Modal 里的子元素)

<div tabindex="-1" class="ant-modal-wrap " role="dialog" aria-labelledby="rcDialogTitle1" data-drag="true" style="display: none;"></div>

相关环境信息
版本：2.0.0-rc.3

**Comment by anncwb** [comment]
已修复
