### ISSUE TITLE
token失效后第一次打开一直停留在加载页

### ISSUE THREAD

**Issue by bangxingni** [anncwb/vue-vben-admin#512]
![image](https://user-images.githubusercontent.com/20875524/115507157-55a7c680-a2ae-11eb-8ce9-8b954dbf022d.png) 这一段应该也包裹在try catch 代码块中，否则当请求状态码返回401  token失效时, 第一次进入会执行不下去,只有url返回了login,动画停留在加载页， 
![image](https://user-images.githubusercontent.com/20875524/115509246-ce0f8700-a2b0-11eb-82a1-5e5ceb50c3c2.png)

**Comment by liyao2598330** [comment]
我也发生了类似的问题，目前我的解决方法是加了一个reload

``` javascript
// src/utils/http/axios/checkStatus.ts
...
import router from '/@/router';
...

    case 401:
      error(t('sys.api.errMsg401'));
      const url = window.location.href.split('#');
      const redirect = url.length >= 2 ? url[1] : PageEnum.BASE_HOME
      router.push(`${PageEnum.BASE_LOGIN}?redirect=${redirect}`);
      setTimeout(function () {
        window.location.reload(); // fix 跳转不生效
      }, 500);
      break;
...
```

如果有好的解决方案可以提一下

**Comment by Kchengz** [comment]
有遇到相同的问题

**Comment by zuihou** [comment]
目测将上面的代码放到try catch 代码块中还是不能自动跳转到login页面， 

我在checkStatus.ts  中加入 router.replace({ path: PageEnum.BASE_LOGIN }); 才能跳到login， 但有时候不灵..
```
case 401:
      error(msg || t('sys.api.errMsg401'));
      router.replace({ path: PageEnum.BASE_LOGIN });
```
