### ISSUE TITLE
ApiSelect可以优化下吗？

### ISSUE THREAD

**Issue by fkuepl** [anncwb/vue-vben-admin#518]
优化下第一下点击时再请求接口，右边有个刷新请求的小图标

有些table的界面用户不常用搜索，但偶尔又会使用； 

如果不使用的时候，进入页面也要请求API，有点浪费资源

**Comment by anncwb** [comment]
ApiSelect的`immediate`可以控制是否立即触发，默认是`true`

**Comment by fkuepl** [comment]
immediate，该功能可以使用，谢谢

但有个问题，就是弹窗二次打开的时候ApiSelect中的下拉内容还是上一次的内容，如果下拉的内容有更新，只能F5刷新，用户体验很不好，能加个刷新的小图标，或有别的什么机刷可以触发二次刷新吗？

**Comment by huguangju** [comment]
> 但有个问题，就是弹窗二次打开的时候ApiSelect中的下拉内容还是上一次的内容，如果下拉的内容有更新，只能F5刷新，用户体验很不好，能加个刷新的小图标，或有别的什么机刷可以触发二次刷新吗？

@fkuepl  你这是想每次点击的时候实时获取数据呗，那没必要用 ApiSelect 呀，直接用原生的，在 `focus` 事件触发时请求数据。但如果对数据实时性要求不高的也没必要这样做。
