### ISSUE TITLE
加载表格组件时，提示不能解析

### ISSUE THREAD

**Issue by TheFirstWhiteDream** [anncwb/vue-vben-admin#52]
导航到可搜索表格时，控制台报错如下：
Uncaught (in promise) Error: Couldn't resolve component "default" at "/table/basic"
    at vue-router.esm-bundler.js:1903
runtime-dom.esm-bundler-7ba00f5e.js:1176 [Vue warn]: SyntaxError: Unexpected token '.'
warn @ runtime-dom.esm-bundler-7ba00f5e.js:1176
vue-router.esm-bundler.js:1903 Uncaught (in promise) Error: Couldn't resolve component "default" at "/table/formTable"
    at vue-router.esm-bundler.js:1903

**Comment by anncwb** [comment]
@TheFirstWhiteDream 能否提供下复现步骤。目前预览网站和我本地都是可以的

**Comment by TheFirstWhiteDream** [comment]
> @TheFirstWhiteDream 能否提供下复现步骤。目前预览网站和我本地都是可以的
克隆代码到本地->yarn->yarn serve  使用360浏览器，然后点击 “开启搜索区域” 菜单项，控制台就会提示这个错误

**Comment by anncwb** [comment]
目前vite支持的浏览器还不多。请先使用主流浏览器chrome，火狐或者safair其中的一个
