### ISSUE TITLE
field 为'parentNode'时，无法使用下拉选择(Select、ApiSelect)

### ISSUE THREAD

**Issue by M69W** [anncwb/vue-vben-admin#522]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [✓] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [✓] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug
使用 封装 Form 组件,
**当 schemas 的 field: 'parentNode' 时，再使用下拉组件时页面卡住**
重现操作：
src/views/demo/form/index.vue
```diff
...
{
-      field: 'field4',
+      field: 'parentNode',
      component: 'Select',
      label: '字段4',
      colProps: {
        span: 8,
      },
      componentProps: {
        options: [
          {
            label: '选项1',
            value: '1',
            key: '1',
          },
          {
            label: '选项2',
            value: '2',
            key: '2',
          },
        ],
      },
    },
...
{
-      field: 'field30',
+      field: 'parentNode',
      component: 'ApiSelect',
      label: '远程下拉',
      required: true,
      componentProps: {
        api: optionsListApi,
      },
      colProps: {
        span: 8,
      },
      defaultValue: '0',
    },
```
### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by anncwb** [comment]
这个应该是触碰到dom的关键自对象了，具体原因得排查下
