### ISSUE TITLE
basicForm的 autoFocusFirstItem transformDateFunc fieldMapToTime 提前解构

### ISSUE THREAD

**Issue by shlroland** [anncwb/vue-vben-admin#527]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

如果使用register方法注册form的话，提前解构以后，无法正常拿到修改后的值，建议直接传getProps，在调用的方法内解构

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by anncwb** [comment]
能简单贴下代码吗，不是很懂你的意思

**Comment by shlroland** [comment]
> 能简单贴下代码吗，不是很懂你的意思

   const { transformDateFunc, fieldMapToTime, autoFocusFirstItem } = toRefs(props); 
这里直接拿的props 在后面如果是register或者setprops 不会出现响应情况
