### ISSUE TITLE
v2.0表格示例BUG

### ISSUE THREAD

**Issue by zn98com** [anncwb/vue-vben-admin#53]
点一次，重复出现固定列，BUG？

![T~NKZ9JD9 46X_5RYOO($}Q](https://user-images.githubusercontent.com/10260081/96965739-3ae2d800-153f-11eb-9461-e5642fba8759.png)

**Comment by anncwb** [comment]
没有复现出这个问题。能提供下具体步骤？

**Comment by zn98com** [comment]
切换单击 左边导航



---原始邮件---
发件人: "Vben"<notifications@github.com&gt;
发送时间: 2020年10月23日(周五) 晚上11:48
收件人: "anncwb/vue-vben-admin"<vue-vben-admin@noreply.github.com&gt;;
抄送: "zn98com"<zn98@vip.qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [anncwb/vue-vben-admin] v2.0表格示例BUG (#53)




 
没有复现出这个问题。能提供下具体步骤？

**Comment by anncwb** [comment]
2.0.0.rc5已修复
