### ISSUE TITLE
路由缓存

### ISSUE THREAD

**Issue by codon19** [anncwb/vue-vben-admin#535]
1. 关闭当前缓存页面的标签页，当前缓存页面没有销毁
添加 unmounted ，unmounted不执行，页面输入框填写的数据仍存在
复现链接：https://vvbin.cn/next/#/level/menu2

2. 带参数多tab缓存，打开tab1、tab2后，点击刷新按钮，两个页面的填写的数据均会被清空，然后这两个页面就再也不会缓存，即填写数据切换tab后数据会清空

之前vue2可以通过$destroy()手动去清理组件实例，vue3没有这个api，请问作者对第二个bug会怎么处理？非常感谢vben的开源

**Comment by anncwb** [comment]
第一点是keep-alive启用了，不会执行生命周期，第二点我得在排查下

**Comment by codon19** [comment]
> 第一点是keep-alive启用了，不会执行生命周期

也就是说关闭缓存页面的标签页，并没有销毁对应的组件，这个是不是不太符合正常的产品逻辑？是不是应该和浏览器的标签页逻辑类似更好？

**Comment by a1945472906** [comment]
> > 第一点是keep-alive启用了，不会执行生命周期
> 
> 也就是说关闭缓存页面的标签页，并没有销毁对应的组件，这个是不是不太符合正常的产品逻辑？是不是应该和浏览器的标签页逻辑类似更好？

我也遇到了类似的问题，我在 _/src/store/modules/multipleTab.ts_里
`const close = (route: RouteLocationNormalized) => {
        const { fullPath, meta: { affix } = {} } = route;
        if (affix) {
          return;
        }
        const index = this.tabList.findIndex((item) => item.fullPath === fullPath);
        index !== -1 && this.tabList.splice(index, 1);
        **this.updateCacheTab();**
      };`
加入了这行 目前运行下来没发现什么问题

**Comment by hyperq** [comment]
第二点可能是因为当前页redo的功能有个小问题导致的
如果你获取数据是activited内执行
那么这个问题就是:界面刷新之后在原有的tabList里面存在 但是在tabCacheList并不存在 导致刷新后的组件不会被keep-alive包裹,所以刷新后的组件并不会重新执行activited
可以看看我这个pr #606
