### ISSUE TITLE
Table组件使用useTable设置dataSource，界面展示和getDataSource()时数据错误

### ISSUE THREAD

**Issue by XJH0415** [anncwb/vue-vben-admin#539]
当原始数据的数据值为string[]类型时

问题1：表格列中显示的结果却是将是list数据值拼接
问题2：通过getDataSource()返回的数据中该字段被替换成vNode[]类型的数据

如图：
![image](https://user-images.githubusercontent.com/31836788/116095649-30b2b980-a6db-11eb-9fae-34d6a796e1c2.png)

![image](https://user-images.githubusercontent.com/31836788/116096025-7ff8ea00-a6db-11eb-937d-fa6cb9b9a7e6.png)

我尝试过给Column写在一个format，但是发现format中拿到的text已经变成vNode对象了而不是原始的数据

个人分析：Table会将string[]的数据format成string+string+...格式并通过createVNode或者h函数进行展示，并且format时把原始数据也改变了，导致通过getDataSource()获取数据到的数据是一个VNode对象

不知道是我使用的姿势不对还是Bug，个人认为这是一个Bug，因为这个问题导致无法获取到原始数据

建议：如果是bug，希望作者关注并修复，如果是有必要的功能，可以提供一个选项是否需要此功能

**Comment by XJH0415** [comment]
补充，给Column写format时，拿到的text是原始数据，抱歉，上面的

“**我尝试过给Column写在一个format，但是发现format中拿到的text已经变成vNode对象了而不是原始的数据**”

错误了，可以无视

**Comment by mynetfan** [comment]
复合型字段需要自己写format或者slot等方式对字段值的显示方式进行处理。
