### ISSUE TITLE
采用restful模式开发时 tinymce组件中的uplaod组上传图片时请求头中的不包含Authorization认证信息

### ISSUE THREAD

**Issue by cnwill** [anncwb/vue-vben-admin#540]
采用restful模式开发时 tinymce组件中的uplaod组上传图片时请求头中的不包含Authorization认证信息

**Comment by liyao2598330** [comment]
认证信息自己稍微改一下，加个headers就好了吧。https://2x.antdv.com/components/upload-cn

**Comment by anncwb** [comment]
修改这个组件 加上去就可以了 [ImgUpload](https://github.com/anncwb/vue-vben-admin/blob/main/src/components/Tinymce/src/ImgUpload.vue)
