### ISSUE TITLE
将BasicTable放入BasicModal，表格高度出错

### ISSUE THREAD

**Issue by jenifly** [anncwb/vue-vben-admin#541]
表格高度不受控制，maxHeight，canResize设置都没有效果
效果如图：
![image](https://user-images.githubusercontent.com/22962492/116172266-01349900-a73d-11eb-900f-2dcbd20ca4bf.png)
![image](https://user-images.githubusercontent.com/22962492/116172267-01349900-a73d-11eb-98ba-93de1ce98795.png)
![image](https://user-images.githubusercontent.com/22962492/116172293-0a256a80-a73d-11eb-888d-550973464e3b.png)

modal参数：
```
  <BasicModal
    v-bind="$attrs"
    @register="register"
    width="90%"
    :height="720"
    :useWrapper="false"
    :footer="null"
  >
 <BasicTable ref="tableElRef" @register="registerTable">
...
```
表格参数：
```
size: 'small',
// canResize: true,
immediate: false,
maxHeight: 500,
```

**Comment by dada-cheng** [comment]
怎么解决的
