### ISSUE TITLE
使用上传组件有警告

### ISSUE THREAD

**Issue by zuihou** [anncwb/vue-vben-admin#545]
![image](https://user-images.githubusercontent.com/8500410/116179131-5d9db580-a749-11eb-868b-7ee7aa119fe6.png)

复现地址：本地启动后， http://localhost:3100/#/comp/upload

不知道有什么影响

**Comment by jekip** [comment]
我用 BasicForm 使用 Upload 组件也会这样，请问你解决了吗？
