### ISSUE TITLE
table 优化

### ISSUE THREAD

**Issue by fkuepl** [anncwb/vue-vben-admin#546]
table的dataSource初使数据设置为[],,使用setTableData后，高度不再自适应，需要自己上下列代码，高度才会又自适应，而且setTimeout不能去除，这是正常的吗？

setTimeout(function(){
        tableCF.redoHeight();
 },600)

**Comment by fkuepl** [comment]
setTimeout的时间控制不好，数据越多，渲染越慢，时间要越长，有别的什么办法处理吗？

**Comment by mynetfan** [comment]
使用nextTick
