### ISSUE TITLE
useTable useSearchForm: true 模式下 想获取搜索表单的value用来根据搜索条件进行column的动态展示

### ISSUE THREAD

**Issue by enjkvbej** [anncwb/vue-vben-admin#55]

**Comment by enjkvbej** [comment]
```
columns = [
{
    title: 'xxx',
    dataIndex: 'xxx',
    show: {key: true} // key is form options key
 }],
```
I think to add property 'show' to control column to show or hide.

**Comment by anncwb** [comment]
可以formConfig内监听onSubmit事件获取values。然后通过表格提供的setColumns动态设置列

**Comment by enjkvbej** [comment]
已解决

**Comment by Buggersldx** [comment]
@enjkvbej 方便说一下吗，我需要获取 table中的form表单的数值，使用在我一个function里面，但是我找不到方法

**Comment by mynetfan** [comment]
> @enjkvbej 方便说一下吗，我需要获取 table中的form表单的数值，使用在我一个function里面，但是我找不到方法

table有getForm方法。参见https://vvbin.cn/doc-next/comp/table.html#methods

**Comment by Buggersldx** [comment]
@mynetfan 我找到了这个 但是调用实现没头绪  一直有警告 也出不来
