### ISSUE TITLE
Select 在Modal 里下拉选项 在内层顶出滚动条

### ISSUE THREAD

**Issue by wl19** [anncwb/vue-vben-admin#554]
![image](https://user-images.githubusercontent.com/51466251/116341371-635fcd80-a813-11eb-90e1-f446c62971d5.png)

![image](https://user-images.githubusercontent.com/51466251/116341296-357a8900-a813-11eb-810a-f2f5da3bb240.png)

![image](https://user-images.githubusercontent.com/51466251/116341620-d701da80-a813-11eb-9834-34335dbcbda6.png)
经过测试 当Modal 使用minHeight属性就会出现该情况

**Comment by mynetfan** [comment]
试试在componentProps下添加：
getPopupContainer: () => document.body

**Comment by wl19** [comment]
> 试试在componentProps下添加：
> getPopupContainer: () => document.body
可以
