### ISSUE TITLE
卡在启动页面

### ISSUE THREAD

**Issue by hugangyi110** [anncwb/vue-vben-admin#559]
console

[vite] connecting...
client:202 [vite] connected.
persistent.ts:21 Uncaught SyntaxError: Unexpected token .

----------------------------------------
error in persistent.ts:21

export class Persistent {
  static getLocal(key) {
    return localMemory.get(key)?.value;
  }

**Comment by xiaoxian521** [comment]
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(157, 165, 180); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(49, 54, 63); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">he<span> </span><code style="box-sizing: border-box; background-color: var(--color-markdown-code-bg); color: rgb(175, 97, 97) !important; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; border-radius: 6px;">Chrome 80+</code><span> </span>browser is recommended for local development</p><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(157, 165, 180); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(49, 54, 63); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Support modern browsers, not IE</p>

IE | Edge | Firefox | Chrome | Safari
-- | -- | -- | -- | --
not support | last 2 versions | last 2 versions | last 2 versions | last 2 versions

**Comment by xiaoxian521** [comment]
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(157, 165, 180); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(49, 54, 63); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">he<span> </span><code style="box-sizing: border-box; background-color: var(--color-markdown-code-bg); color: rgb(175, 97, 97) !important; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, monospace; font-size: 13.6px; padding: 0.2em 0.4em; margin: 0px; border-radius: 6px;">Chrome 80+</code><span> </span>browser is recommended for local development</p><p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(157, 165, 180); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(49, 54, 63); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Support modern browsers, not IE</p>

IE | Edge | Firefox | Chrome | Safari
-- | -- | -- | -- | --
not support | last 2 versions | last 2 versions | last 2 versions | last 2 versions
