### ISSUE TITLE
主题设置遇到类似缓存问题

### ISSUE THREAD

**Issue by wansiliang** [anncwb/vue-vben-admin#560]
### Describe the bug

我之前把颜色调成 #ffffff 白色。发现代码和实际效果不一致，疑似编译缓存问题，后来双开浏览器同一配置展现不一样的效果。如下图

![image](https://user-images.githubusercontent.com/25665379/116669093-bf238580-a9d0-11eb-9ce7-494e396fa939.png)

更改代码在此处

![image](https://user-images.githubusercontent.com/25665379/116669247-eed28d80-a9d0-11eb-8032-2833b7e5846d.png)

看看是什么问题，

**Comment by wansiliang** [comment]
![image](https://user-images.githubusercontent.com/25665379/116670094-e7f84a80-a9d1-11eb-84ad-e45cccf1599b.png)


修改端口后，能正确展示代码设置颜色。应该是有编译缓存吧

**Comment by waka3** [comment]
全局的设置保存在LocalStorage， 需要清除才会生效

**Comment by anncwb** [comment]
修改配置文件需要清空缓存
