### ISSUE TITLE
activated 不执行

### ISSUE THREAD

**Issue by hyperq** [anncwb/vue-vben-admin#563]
### Describe the bug

在views里面的组件内 activated 不执行,

### Reproduction

在预览版本的项目里面也试过了也是不执行

## System Info

- Operating System:macos 11.3.0
- Node version:v14.11.0
- Package manager (npm/yarn/pnpm) and version:yarn

**Comment by xiaoxian521** [comment]
```
import { onActivated } from "vue"
```

**Comment by hyperq** [comment]
是组件没有名称的问题导致的
