### ISSUE TITLE
到底该如何监听FormItem值得变化呢？

### ISSUE THREAD

**Issue by lolysc** [anncwb/vue-vben-admin#568]
抱歉，遇到一个技术问题。在本框架下，到底该如何监听一个Form里普通栏位的变化呢，不用框架很容易。本框架找不到哪里入手，比如A字段变化后，让B字段的值根据A字段来计算。我需要监听A字段的值的变化。registerForm里schemas已经配置，但如何监听schemas里的A字段呢？

**Comment by mynetfan** [comment]
componentProps里写onChange（具体看是什么时间名，大多数组件是change）

**Comment by lolysc** [comment]
> componentProps里写onChange（具体看是什么事件名，大多数组件是change）

谢谢答复。但是onChange是绑定的组件里的事件，onChange只能拿到变化后的值，拿不到整个model。我需要的是能够外层监听。讲白了，就是如何watch一个schema的值得变化。框架封装的太厚实，已经配置了FormSchema[]，发觉想拿个BasicForm的model都很难，监听某个栏位的值更难。

**Comment by mynetfan** [comment]
{
    field: 'fieldA',
    label: 'LabelA',
    component: 'Input',
    required: true,
    componentProps: ({ formModel, formActionType }) => {
      return {
        placeholder: ''PlaceHolder,
        onChange: () => {
          nextTick(() => {
            formActionType.updateSchema({
              field: 'FieldB',
              helpMessage: formModel.FieldA,
            });
          });
        },
      };
    },
  }

类似这样

**Comment by mynetfan** [comment]
仅供参考，我自己是这样做的。不过，也许在setup中处理应该会更好。

**Comment by anncwb** [comment]
参考示例，componentProps改为函数方式即可

**Comment by lolysc** [comment]
componentProps里配置onChange的方案确实是可以的，但是我本意是想直接watch到model里数据的变化，不想通过事件去获取变化，而是想按照数据监听思路来。在MVVM里，一切都是数据，直接监听数据，不要管事件，但找了一圈没找到方法怎么监听form里model的变化。而且调用ApiSelect组件后，onChange只能拿到变化后的value，拿不到变化的option。框架给限定了只传了一个value，而andDesign-Vue的原始change参数是两个function(value, option:Option/Array<Option>)。

**Comment by skyzfdance** [comment]
我给 Form 增加了一个 emit，当 onChange 的时候，直接执行。类似于 
`<BasicForm @register="register" @submit="handleSubmit " />`
`onChange: async () => {
            const { submit } = formActionType;
            const res = await submit();
            console.log(res);
},`

`function handleSubmit(){ }`


我不知道这样的做法对不对，但是功能是实现了。

**Comment by qinghechaoge** [comment]
> 我给 Form 增加了一个 emit，当 onChange 的时候，直接执行。类似于 `<BasicForm @register="register" @submit="handleSubmit " />` `onChange: async () => { const { submit } = formActionType; const res = await submit(); console.log(res); },`
> 
> `function handleSubmit(){ }`
> 
> 我不知道这样的做法对不对，但是功能是实现了。

你这个能用吗？ 我这切换后执行三次，并且没有参数

**Comment by Mo-jon** [comment]
经过阅读 BasicForm 源码发现，提供了 emit 更新数据事件 @field-value-change

![1711680387796](https://github.com/vbenjs/vue-vben-admin/assets/52648362/81805aeb-23d2-40da-aa07-6e362800e728)

于是我这样实现了监听
```vue
<template>
  <div>
    <div>{{ formData.name }}</div>
    <BasicForm @register="register" @field-value-change="changeFormData" />
  </div>
</template>
<script setup lang="ts">
  import { ref } from 'vue';
  import { BasicForm, useForm } from '/@/components/Form';

  const formData: any = ref({});
  const [register, { getFieldsValue }] = useForm({
    schemas: [
      {
        component: 'Input',
        label: '别名',
        field: 'name',
      },
    ],
  });
  function changeFormData() {
    formData.value = getFieldsValue();
    console.log('表单数据更新', formData.value);
  }
</script>

```

![1711681018993](https://github.com/vbenjs/vue-vben-admin/assets/52648362/09459eaa-2be1-487d-94cd-2df86bf6b2e0)
