### ISSUE TITLE
tab标签动态修改名称

### ISSUE THREAD

**Issue by kongsiyu** [anncwb/vue-vben-admin#571]
当时用带参路由同一页面打开多个标签时（例如同时查看多个用户详情），标签名称全部是一样的不易查看，可以提供一个动态修改tab的api吗

**Comment by xiaoxian521** [comment]
能否提供个截图

**Comment by kongsiyu** [comment]
![image](https://user-images.githubusercontent.com/8521224/117423902-c8be6780-af53-11eb-997e-2eedf3e10d52.png)


![image](https://user-images.githubusercontent.com/8521224/117423824-b3e1d400-af53-11eb-9dc7-aba69483bd85.png)

**Comment by mynetfan** [comment]
```
...
  import { useRouter } from 'vue-router';
  import { useMultipleTabStore } from '/@/store/modules/multipleTab';
...
  setup(){
      const tabStore = useMultipleTabStore();
      const router = useRouter();
      const currentTab = tabStore.getTabList.find(
        // 以下函数只比对了path，你应该适当修改一下，加上路由参数比对
        (item) => item.path === router.currentRoute.value.path
      )!;
    ....
    //在你需要修改的地方类似下面这样
    currentTab.meta.title = '修改后的名字';
  }
```

以上是代码片段，只贴出了关键代码。仅供参考

**Comment by kongsiyu** [comment]
可以的，感谢~

**Comment by NickyXu1989** [comment]
经过测试以下代码可行
版本 | 2.5.2

import { useRoute } from 'vue-router';
import { useMultipleTabStore } from '/@/store/modules/multipleTab';
setup(){
        const router = useRouter();
        const tabStore = useMultipleTabStore();
        const currentTab = tabStore.getTabList.find(
          // 以下函数只比对了path，你应该适当修改一下，加上路由参数比对
          (item) => item.fullPath === route.fullPath
        )!;
        currentTab.meta.title = '新的名字';
  }

**Comment by mynetfan** [comment]
> 经过测试以下代码可行
> 版本 | 2.5.2
> 
> import { useRoute } from 'vue-router';
> import { useMultipleTabStore } from '/@/store/modules/multipleTab';
> setup(){
> const router = useRouter();
> const tabStore = useMultipleTabStore();
> const currentTab = tabStore.getTabList.find(
> // 以下函数只比对了path，你应该适当修改一下，加上路由参数比对
> (item) => item.fullPath === route.fullPath
> )!;
> currentTab.meta.title = '新的名字';
> }

2.5.2 已添加了内置方法修改tab标题。

```
  import { useTabs } from '/@/hooks/web/useTabs';
  const { setTitle } = useTabs();
  setTitle('你的新标题');
```

**Comment by C-racker** [comment]
请问面包屑如何动态修改？
