### ISSUE TITLE
Component emitted event "register" but it is neither declared in the emits option nor as an "onRegister" prop.

### ISSUE THREAD

**Issue by Walk4Muscle** [anncwb/vue-vben-admin#586]
我自定义了几个独立的 Modal组件，组件内部使用`useModalInner`，在主页面中进行了`useModal`的调用，但是在载入父页面的时候，报了vue warn：

> [Vue warn]: Component emitted event "register" but it is neither declared in the emits option nor as an "onRegister" prop. 
  at <BasicModal onRegister= (3) [ƒ, ƒ, ƒ] title="编辑客户" onOk=fn<submit> > 

//独立modal我是这么定义的
```//template
<BasicModal v-bind="$attrs" @register="registerModal" :title="getTitle" @ok="submit">
    <BasicForm @register="registerForm" />
  </BasicModal>
```
```
///setup function
const [registerModal, { closeModal, setModalProps }] = useModalInner((data) => {
        resetFields();
        setModalProps({ confirmLoading: false });
        isUpdate.value = !!data?.isUpdate;

        if (unref(isUpdate)) {
          setFieldsValue({
            ...data.record,
          });
        }
      });
```

```
//父函数调用
<EditModal @register="editModalReg" @submit-callback="editCallback" />
...
//script
...
const [editModalReg, { openModal }] = useModal();
...
```

**Comment by Walk4Muscle** [comment]
> 警告的意思是你没有在emits选项中定义register事件，也没有定义一个名字为onRegister的属性。
> 如果你的组件有一个register事件，就要在emits中定义。
> ![image](https://user-images.githubusercontent.com/17241274/117795890-266af080-b281-11eb-8c9f-c5f1fd29faa3.png)

谢谢，就是说我如果有自定义的事件的话，还要把这些引用组件中用到的事件补到emits里面。
这个问题是解决了，但总感觉怪怪的。。。

**Comment by mynetfan** [comment]
https://vue3js.cn/docs/zh/guide/component-custom-events.html#%E5%AE%9A%E4%B9%89%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8B%E4%BB%B6

**Comment by Walk4Muscle** [comment]
为什么demo在跑的时候没有warning呢，https://github.com/anncwb/vue-vben-admin/blob/main/src/views/demo/comp/modal/Modal2.vue 这个demo也没有特别定义emits事件啊

**Comment by mynetfan** [comment]
你怎么还在纠结这个问题啊？
你的需要是因为你封装的EditModal抛出了register等事件。你发的这个demo的链接并没有抛出事件。

**Comment by Walk4Muscle** [comment]
那为什么demo不会抛出这个事件呢？我只是想知道这两处不一样的原因啊

**Comment by mynetfan** [comment]
Demo里已经是最终的页面了，它的register是由BasicModal内部抛出的事件，没有继续往上级抛出任何事件，只需要BasicModal内部有emits定义就可以了。而你已经封装为了EditModal组件，你的EditModal需要向外抛出register等事件，所以在你的EditModal里要定义emits

**Comment by horizon188** [comment]
我也会这样也是跟你一样的写法，而且在组件内定义了emits: ['handleClick', 'register',]还是会warm，楼主解决了吗

**Comment by horizon188** [comment]
我也会这样也是跟你一样的写法，而且在组件内定义了emits: ['handleClick', 'register',]还是会warm，楼主解决了吗
