### ISSUE TITLE
退出登录 在登录 会一直loading

### ISSUE THREAD

**Issue by weizheng1992** [anncwb/vue-vben-admin#59]
<p align="center">
   <img width="100%" src="https://user-images.githubusercontent.com/10727313/97248562-06bc2f80-183d-11eb-9f40-385cc883f354.jpg">
    <img width="100%" src="https://user-images.githubusercontent.com/10727313/97248611-205d7700-183d-11eb-97d6-ea3b0e773512.jpg">

</p>

**Comment by anncwb** [comment]
未还原出你的情况，我这边正常。可以提供下复现步骤或者有什么特殊步骤。loading的截图也可以提供下

**Comment by weizheng1992** [comment]
现在没有不复现了
