### ISSUE TITLE
编译后production环境初始化报错

### ISSUE THREAD

**Issue by kongsiyu** [anncwb/vue-vben-admin#594]
Uncaught SyntaxError: Invalid left-hand side in assignment
Uncaught TypeError: Cannot destructure property 'VITE_GLOB_APP_TITLE' of 't' as it is undefined.

serve是正常的,build之后不行

![image](https://user-images.githubusercontent.com/8521224/118064648-fe3cd800-b3cd-11eb-88ec-f90fecdd4fb6.png)

**Comment by kongsiyu** [comment]
已解决：环境变量是存在window对象下面的一个动态名称变量下的，变量名来自package.json中的name，由于name中使用了'-'导致非法变量名，'-'改为'_'即可

**Comment by AndroidMilk** [comment]
> 已解决：环境变量是存在window对象下面的一个动态名称变量下的，变量名来自package.json中的name，由于name中使用了'-'导致非法变量名，'-'改为'_'即可

请问我也出现了这样的错误，但是看到vue-vben-admin同样适用了'-'，但是不报错

**Comment by Codeniu** [comment]
> 已解决：环境变量是存在window对象下面的一个动态名称变量下的，变量名来自package.json中的name，由于name中使用了'-'导致非法变量名，'-'改为'_'即可

具体是怎么改的呢，我尝试了不同的方式，还是报错，即时是把vite-plugins-html注释掉不用，还是会报这个错误

**Comment by BobinYang** [comment]
[[[import.meta.env as unknown as GlobEnvConfig.](https://github.com/jeecgboot/jeecg-boot/issues/3792)](https://github.com/jeecgboot/jeecg-boot/issues/3792)](https://github.com/jeecgboot/jeecg-boot/issues/3792)
