### ISSUE TITLE
BasicTable 怎么能自定义列绑定参数和事件？

### ISSUE THREAD

**Issue by West121** [anncwb/vue-vben-admin#600]
BasicTable 怎么能自定义列绑定参数和事件？例如自定义列是 Switch 组件。怎么动态绑定 checked 属性，以及 change 事件？
![f6f450b6c3552da8367abb5ac6da706](https://user-images.githubusercontent.com/29170680/118204250-5b995d80-b490-11eb-8d02-8718eab7f545.png)

**Comment by West121** [comment]
看文档已解决。

**Comment by songjiyang** [comment]
```
     <template #controlGroup="{ record }">
          <Switch
            :checked="record.controlGroup"
            @change="record.controlGroup = !record.controlGroup"
          />
        </template>
```
