### ISSUE TITLE
表单有封装头像上传吗？

### ISSUE THREAD

**Issue by West121** [anncwb/vue-vben-admin#603]
表单组件有封装头像上传组件吗？我看文档有个 ImageUpload 组件，代码里却没有。
![46934b86915f6c2961273ce4e1bc380](https://user-images.githubusercontent.com/29170680/118220220-b7beaa80-b4ad-11eb-99ef-a1b447796795.png)
主要想要的是表单里有类似这样的上传组件吗？
![25bb60a8a66efdad388472c137fdf2b](https://user-images.githubusercontent.com/29170680/118220239-cd33d480-b4ad-11eb-9964-38717e28c99c.png)

**Comment by hyperq** [comment]
应该是被移除了  可以自己实现一个  [自行添加需要的组件类型](https://vvbin.cn/doc-next/comp/form.html#%E8%87%AA%E8%A1%8C%E6%B7%BB%E5%8A%A0%E9%9C%80%E8%A6%81%E7%9A%84%E7%BB%84%E4%BB%B6%E7%B1%BB%E5%9E%8B)

**Comment by mynetfan** [comment]
就是Upload啊

**Comment by anncwb** [comment]
目前没有，会加

**Comment by zuihou** [comment]
> 目前没有，会加

厚脸皮提个需求建议😛： 1、能上传头像；2、能裁剪；3、能选择系统内置头像（头像图片打包到项目文件夹）；4、支持在表单上传，然后在分页列表、表单、系统右上角、个人中心等任何地方回显头像（上传的或者选择的头像）；5、其他头像组件的优秀功能。

**Comment by fkuepl** [comment]
能调整角度更好

**Comment by anncwb** [comment]
8e410fc
