### ISSUE TITLE
主题色衍生色生成错误

### ISSUE THREAD

**Issue by jiangmaniu** [anncwb/vue-vben-admin#604]
![image](https://user-images.githubusercontent.com/50100681/118238666-68877280-b4cb-11eb-9df7-cfa1f68f4acb.png)
`modeColors` 变量是表示生成暗色的主题衍生色吗？

我打印了这两个变量控制台显示的是同样的值：
![image](https://user-images.githubusercontent.com/50100681/118238682-6f15ea00-b4cb-11eb-9f0f-4312bc7b7f96.png)

解构出来前面的 `colors` 变量被后面的 `modeColors` 覆盖了

**Comment by mynetfan** [comment]
你为什么不把[...colors, ...modeColors]也打印出来看看是不是像你说的那样被覆盖了呢？

**Comment by jiangmaniu** [comment]
@mynetfan 抱歉，我看错成对象解构了。第一个问题我还是有些疑惑，如果 `modeColors ` 变量不是表示生成的暗色主题衍生色，那请问 `colors` 变量和 `modeColors` 变量有什么区别吗？

**Comment by jiangmaniu** [comment]
我的理解是 `modeColors` 是用来表示生成暗色主题衍生色的。如果是我理解的这样，那程序中的代码是有问题的，我可以修复它。
