### ISSUE TITLE
开发的时候经常报这个错。刷新就好了。

### ISSUE THREAD

**Issue by zhanghaijun666** [anncwb/vue-vben-admin#61]
runtime-dom.esm-bundler-d76e4317.js:1477 Uncaught (in promise) TypeError: Cannot read property 'id' of null
    at getId (runtime-dom.esm-bundler-d76e4317.js:1477)
    at runtime-dom.esm-bundler-d76e4317.js:1494
    at Array.sort (<anonymous>)
    at flushJobs (runtime-dom.esm-bundler-d76e4317.js:1494)

![QQ图片20201027162637](https://user-images.githubusercontent.com/30174740/97275690-3553fd80-1871-11eb-89d7-a3dabc4c917d.png)

**Comment by weizheng1992** [comment]
对我也有

**Comment by anncwb** [comment]
这个是热更新问题，这个还不确定是vite，vue及antv其中哪个的问题。后续我支持跟进下，有解决方案我会发在这里

**Comment by aios** [comment]
**weizheng1992** Also for me
**anncwb** This is a hot update issue. I am not sure which of vite, vue or antv is the issue. I will follow up with my support and I will post a solution here

**Comment by anncwb** [comment]
@aios I'm still investigating what caused it

**Comment by aios** [comment]
@anncwb I am catched that when deleting image on a dashboard 
https://prnt.sc/vdck2x

**Comment by anncwb** [comment]
open https://github.com/vitejs/vite/issues/1021

**Comment by anncwb** [comment]
vue3.0.3 will fix the problem
