### ISSUE TITLE
菜单用 top-menu，Console一堆警告

### ISSUE THREAD

**Issue by waney** [anncwb/vue-vben-admin#617]
菜单用 top-menu 的话Console一堆警告，找不出原因很影响开发，每次要拉一截。版本V2.3.0

`reactivity.esm-bundler.js:337 Set operation on key "default" failed: target is readonly. {__vInternal: 1, default: ƒ}
set @ reactivity.esm-bundler.js:337
normalizeObjectSlots @ runtime-core.esm-bundler.js:2794
updateSlots @ runtime-core.esm-bundler.js:2867
updateComponentPreRender @ runtime-core.esm-bundler.js:4408
componentEffect @ runtime-core.esm-bundler.js:4342
reactiveEffect @ reactivity.esm-bundler.js:42
updateComponent @ runtime-core.esm-bundler.js:4251
processComponent @ runtime-core.esm-bundler.js:4186
patch @ runtime-core.esm-bundler.js:3791
componentEffect @ runtime-core.esm-bundler.js:4368
reactiveEffect @ reactivity.esm-bundler.js:42
updateComponent @ runtime-core.esm-bundler.js:4251
processComponent @ runtime-core.esm-bundler.js:4186
patch @ runtime-core.esm-bundler.js:3791
componentEffect @ runtime-core.esm-bundler.js:4368
reactiveEffect @ reactivity.esm-bundler.js:42
callWithErrorHandling @ runtime-core.esm-bundler.js:154
flushJobs @ runtime-core.esm-bundler.js:384
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:286
queueJob @ runtime-core.esm-bundler.js:280
run @ reactivity.esm-bundler.js:183
trigger @ reactivity.esm-bundler.js:189
set2 @ reactivity.esm-bundler.js:300
handleMenuChange @ BasicMenu.vue:155
async function (async)
handleMenuChange @ BasicMenu.vue:154
(anonymous) @ BasicMenu.vue:110
listenerRouteChange @ routeChange.ts:26
setup @ BasicMenu.vue:108
callWithErrorHandling @ runtime-core.esm-bundler.js:154
setupStatefulComponent @ runtime-core.esm-bundler.js:6542
setupComponent @ runtime-core.esm-bundler.js:6503
mountComponent @ runtime-core.esm-bundler.js:4206
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
patchKeyedChildren @ runtime-core.esm-bundler.js:4647
patchChildren @ runtime-core.esm-bundler.js:4449
processFragment @ runtime-core.esm-bundler.js:4171
patch @ runtime-core.esm-bundler.js:3784
componentEffect @ runtime-core.esm-bundler.js:4368
reactiveEffect @ reactivity.esm-bundler.js:42
callWithErrorHandling @ runtime-core.esm-bundler.js:154
flushJobs @ runtime-core.esm-bundler.js:384
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:286
queueJob @ runtime-core.esm-bundler.js:280
run @ reactivity.esm-bundler.js:183
trigger @ reactivity.esm-bundler.js:189
scheduler @ reactivity.esm-bundler.js:851
run @ reactivity.esm-bundler.js:183
trigger @ reactivity.esm-bundler.js:189
set value @ reactivity.esm-bundler.js:761
genMenus @ useLayoutMenu.ts:98
async function (async)
genMenus @ useLayoutMenu.ts:98
watch.immediate @ useLayoutMenu.ts:61
callWithErrorHandling @ runtime-core.esm-bundler.js:154
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:163
job @ runtime-core.esm-bundler.js:2096
doWatch @ runtime-core.esm-bundler.js:2143
watch @ runtime-core.esm-bundler.js:2004
useSplitMenu @ useLayoutMenu.ts:58
setup @ index.vue:58
callWithErrorHandling @ runtime-core.esm-bundler.js:154
setupStatefulComponent @ runtime-core.esm-bundler.js:6542
setupComponent @ runtime-core.esm-bundler.js:6503
mountComponent @ runtime-core.esm-bundler.js:4206
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
mountChildren @ runtime-core.esm-bundler.js:3975
mountElement @ runtime-core.esm-bundler.js:3896
processElement @ runtime-core.esm-bundler.js:3868
patch @ runtime-core.esm-bundler.js:3788
mountChildren @ runtime-core.esm-bundler.js:3975
processFragment @ runtime-core.esm-bundler.js:4141
patch @ runtime-core.esm-bundler.js:3784
mountChildren @ runtime-core.esm-bundler.js:3975
mountElement @ runtime-core.esm-bundler.js:3896
processElement @ runtime-core.esm-bundler.js:3868
patch @ runtime-core.esm-bundler.js:3788
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
mountChildren @ runtime-core.esm-bundler.js:3975
mountElement @ runtime-core.esm-bundler.js:3896
processElement @ runtime-core.esm-bundler.js:3868
patch @ runtime-core.esm-bundler.js:3788
mountChildren @ runtime-core.esm-bundler.js:3975
processFragment @ runtime-core.esm-bundler.js:4141
patch @ runtime-core.esm-bundler.js:3784
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
mountChildren @ runtime-core.esm-bundler.js:3975
processFragment @ runtime-core.esm-bundler.js:4141
patch @ runtime-core.esm-bundler.js:3784
mountChildren @ runtime-core.esm-bundler.js:3975
mountElement @ runtime-core.esm-bundler.js:3896
processElement @ runtime-core.esm-bundler.js:3868
patch @ runtime-core.esm-bundler.js:3788
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
mountChildren @ runtime-core.esm-bundler.js:3975
processFragment @ runtime-core.esm-bundler.js:4141
patch @ runtime-core.esm-bundler.js:3784
mountChildren @ runtime-core.esm-bundler.js:3975
mountElement @ runtime-core.esm-bundler.js:3896
processElement @ runtime-core.esm-bundler.js:3868
patch @ runtime-core.esm-bundler.js:3788
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
mountChildren @ runtime-core.esm-bundler.js:3975
processFragment @ runtime-core.esm-bundler.js:4141
patch @ runtime-core.esm-bundler.js:3784
mountChildren @ runtime-core.esm-bundler.js:3975
mountElement @ runtime-core.esm-bundler.js:3896
processElement @ runtime-core.esm-bundler.js:3868
patch @ runtime-core.esm-bundler.js:3788
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
mountChildren @ runtime-core.esm-bundler.js:3975
processFragment @ runtime-core.esm-bundler.js:4141
patch @ runtime-core.esm-bundler.js:3784
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
mountChildren @ runtime-core.esm-bundler.js:3975
processFragment @ runtime-core.esm-bundler.js:4141
patch @ runtime-core.esm-bundler.js:3784
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
componentEffect @ runtime-core.esm-bundler.js:4298
reactiveEffect @ reactivity.esm-bundler.js:42
effect @ reactivity.esm-bundler.js:17
setupRenderEffect @ runtime-core.esm-bundler.js:4263
mountComponent @ runtime-core.esm-bundler.js:4222
processComponent @ runtime-core.esm-bundler.js:4182
patch @ runtime-core.esm-bundler.js:3791
render2 @ runtime-core.esm-bundler.js:4883
mount @ runtime-core.esm-bundler.js:3077
app.mount @ runtime-dom.esm-bundler.js:1259
(anonymous) @ main.ts:57
async function (async)
(anonymous) @ main.ts:39
(anonymous) @ main.ts:60
Show 183 more frames
reactivity.esm-bundler.js:337 Set operation on key "default" failed: target is readonly. {__vInternal: 1, default: ƒ}`
![微信截图_20210518121957](https://user-images.githubusercontent.com/69211/118589672-69721a00-b7d3-11eb-8bf0-3a0d07b69767.png)

## System Info

- Operating System: windows 10
- Node version: v14.15.1
- Package manager (npm/yarn/pnpm) and version: yarn

**Comment by anncwb** [comment]
ant-design-vue的问题，得等他们修复

**Comment by anncwb** [comment]
fixed 905e5b714b582548f32feca723012124343686a6

**Comment by waney** [comment]
BUG 重现。 @anncwb
