### ISSUE TITLE
useTable页面单页换成60条点击一项 表格行样式会断

### ISSUE THREAD

**Issue by ljw-codeking** [anncwb/vue-vben-admin#619]
第一次提issue不会上传图片有点小尴尬，可以去页面上操作一下这个很好复习的
1,打开useTable页面
2.切换为每页100条
3.点击一条数据然后滚动

Please fill in as much of the template below as you’re able.

P.S. have you seen our support and contributing docs?
-->

**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by anncwb** [comment]
这个应该只是滚动的时候会断掉，停止之后是正常的。应该是ant-design-vue的问题
