### ISSUE TITLE
BasicTable使用expandedRowRender时候，展开行的宽度会根据 colum的fixed来决定，并且换行会导致表格显示错乱

### ISSUE THREAD

**Issue by renco971015** [anncwb/vue-vben-admin#621]
- 不设置fixed属性
![O2DP~96O1059G4HF_O35$QS](https://user-images.githubusercontent.com/45613137/118759580-e371d400-b8a3-11eb-9f43-5d5fbb88fd7f.png)

- 若第一列设置了fiexd属性
![3D{V1JD9PLWXE $R}}7BTVW](https://user-images.githubusercontent.com/45613137/118759686-13b97280-b8a4-11eb-9140-b16a03f4baca.png)

**Comment by mynetfan** [comment]
Ant design vue的表格本来就不支持这样做。fixed列不能与展开行一起用、展开行不能与树形数据一起用

**Comment by renco971015** [comment]
> Ant design vue的表格本来就不支持这样做。fixed列不能与展开行一起用、展开行不能与树形数据一起用

了解了，谢谢！

**Comment by anncwb** [comment]
如上，确实组件库不支持两个一起使用

**Comment by 15191362069** [comment]
想请教一下如何让他默认展开

**Comment by lovelyJason** [comment]
我有疑问
为什么作者文档是这么写的
![image](https://github.com/vbenjs/vue-vben-admin/assets/50656459/4a3b7b62-ba6b-4f00-8a99-580520c35fcf)

expandedRowRender明明可以用，我都用了， 但是expandColumnTitle不能用，一用就报错
