### ISSUE TITLE
使用后端权限模式,刷新浏览器后,控制台报错,且无法进入页面

### ISSUE THREAD

**Issue by yaseiakira** [anncwb/vue-vben-admin#622]
我使用后端权限模式,登录成功,且能够跳转到指定的页面,菜单也显示正常
然后我使用浏览器的刷新按钮,刷新页面
进入loading加载页,弹出显示 '菜单加载中' ,弹窗消失,之后就一直停留在loading页面没反应,查看控制台报错如下:

[Vue Router warn]: Component "default" in record with path "/system" is not a valid component. Received "undefined".
[Vue Router warn]: Unexpected error when starting the router: Error: Invalid route component
 at extractComponentsGuards (vue-router.esm-bundler.js:1962)
 at vue-router.esm-bundler.js:3089

Uncaught (in promise) Error: Invalid route component
 at extractComponentsGuards (vue-router.esm-bundler.js:1962)
 at vue-router.esm-bundler.js:3089

**Comment by mynetfan** [comment]
你至少得把后端返回的数据发一下吧。什么都不提供，怎么知道问题出在哪儿？

**Comment by yaseiakira** [comment]
抱歉,现在补上,以下是后端返回的
`
[{
			"name": "system",
			"component": "LAYOUT",
			"path": "/system",
			"redirect": "/system/account",
			"children": [{
				"name": "account",
				"component": "/sys/setting/account/account",
				"path": "account",
				"redirect": null,
				"children": null,
				"meta": {
					"title": "账号管理",
					"icon": "ion:people-sharp"
				}
			}, {
				"name": "roles",
				"component": "/sys/setting/roles/roles",
				"path": "roles",
				"redirect": null,
				"children": null,
				"meta": {
					"title": "角色分权",
					"icon": "ion:shield-checkmark-outline"
				}
			}],
			"meta": {
				"title": "系统设置",
				"icon": "ion:settings-outline"
			}
		}]
`

**Comment by mynetfan** [comment]
两次返回的数据一样吗？

**Comment by mynetfan** [comment]
另外，你用的是精简版还是完全版？

**Comment by yaseiakira** [comment]
使用的精简版,两次数据一样的
最开始登录之后都没问题,但是只要重新刷新页面就报错了

**Comment by mynetfan** [comment]
精简版已经很久没有同步代码了，可能有没有处理的BUG。要么等精简版同步代码，要么自己比对一下完整版和精简版的区别并更新

**Comment by yaseiakira** [comment]
OK,那我尝试对比一下代码,是不是对比路由和权限相关的代码?

**Comment by renjf1** [comment]
1、修改permission mode（权限模式）：src>settings>projectSetting.ts
2、添加左侧菜单栏 src>router>menus>modules，继承MenuModule

先确认以上两步是否修改
