### ISSUE TITLE
同时使用 ant vue 与 element Plus 的问题

### ISSUE THREAD

**Issue by YLQZ** [anncwb/vue-vben-admin#628]
### Describe the bug
1.当前项目下 同时使用less与scss 既 同时使用 ant vue 与element Plus 时，element 自定义变量，在 组件内全量引入（非main）
element 在当前组件内使用其组件时 丢失大量的class(或者 大量class 不起作用) 导致基础组件与element官网效果差异巨大
2. 在用自定义变量的方式引入 element时，
    /* 改变主题色变量 */ $--color-primary: teal; /* 改变 icon 字体路径变量，必需 */
    $--font-path: '~element-plus/lib/theme-chalk/fonts'; 
    @import "~element-plus/packages/theme-chalk/src/index";
    
    import './element-variables.scss'

报错： @import "~element-plus/packages/theme-chalk/src/index"; 路径找不到
 解决：@import "/node_modules/element-plus/packages/theme-chalk/src/index";
此解决方式仅在dev环境下有效 在build后运行 会爆找不到/node_modules··· 路径

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by YLQZ** [comment]
经过其他测试   vite下 使用两种UI 并且自定义  没有问题，只在当前架构下有问题

**Comment by anncwb** [comment]
尝试配置别名。将  `~`这个转化成空字符串

**Comment by YLQZ** [comment]
@anncwb 那打包后 element-plus 直接样式丢失怎么办呢
