### ISSUE TITLE
basic table 固定 action 的情况下会出现空白列

### ISSUE THREAD

**Issue by West121** [anncwb/vue-vben-admin#629]
basic table 固定 action 的情况下会出现空白列，全部不够选会出现，勾选一列也会出现。
![Snipaste_2021-05-20_16-37-34](https://user-images.githubusercontent.com/29170680/118947577-0f678500-b98a-11eb-9c7a-60c20768f30a.png)

**Comment by anncwb** [comment]
ant design vue的表格，你需要保证所有列设置的宽度大于总宽度，否则就会出现空白列。或者你可以留一列不设置宽度，让它自适应宽度也可以

**Comment by West121** [comment]
> ant design vue的表格，你需要保证所有列设置的宽度大于总宽度，否则就会出现空白列。或者你可以留一列不设置宽度，让它自适应宽度也可以

哦哦，好的。
