### ISSUE TITLE
vite-plugin-mock 和vite的proxy同时开启问题

### ISSUE THREAD

**Issue by unforesndprson** [anncwb/vue-vben-admin#63]
vite-plugin-mock 的mock数据如果不存在的话，接口会一直处于pending状态，vite的proxy不起作用

**Comment by anncwb** [comment]
能提供下复现步骤或者测试接口吗，我这边正常

**Comment by unforesndprson** [comment]
我是直接把mock/sys/user.ts的/api/login数据注释，登录时/api/login会一直pending直到超时

**Comment by anncwb** [comment]
登录注释后代理到后台是吗？可以提供下截图或者更详细的信息？

**Comment by anncwb** [comment]
尝试先将 /src/utils/http/axios/index.ts 内 的beforeRequestHook函数里面的所有`config.params={}`改成`config.params=undefined`

**Comment by unforesndprson** [comment]
1.config.params=>undefined 
![undefined](https://user-images.githubusercontent.com/26316210/97380485-1baec680-1902-11eb-8e15-6b43a8c3c43f.png)
2.设置代理地址 期待https://getman.cn/mock/login返回{test:1}
![env](https://user-images.githubusercontent.com/26316210/97380537-384afe80-1902-11eb-83b9-02cc36ec746c.png)

**Comment by anncwb** [comment]
我测试看看

**Comment by anncwb** [comment]
这个接口是get，登录是post

**Comment by unforesndprson** [comment]
临时找了个模拟接口的地址，post应该也是可以的吧。
但不管代不代理，我这边测试找不到mock数据时，接口会一直pending
![image](https://user-images.githubusercontent.com/26316210/97382400-4864dd00-1906-11eb-9f0b-566cfe2b3700.png)

**Comment by unforesndprson** [comment]
临时找了个模拟接口的地址，post应该也是可以的吧。
但不管代不代理，我这边测试找不到mock数据时，接口会一直pending
![login](https://user-images.githubusercontent.com/26316210/97382679-d4770480-1906-11eb-9799-dd4f4f784ac8.jpg)

**Comment by anncwb** [comment]
文档有这个问题。proxy代理https还有问题。刚看是https接口

**Comment by anncwb** [comment]
https://vvbin.cn/doc-next/guide/qa/#%E6%9C%AC%E5%9C%B0%E4%BB%A3%E7%90%86%E5%88%B0-https-%E9%97%AE%E9%A2%98

**Comment by unforesndprson** [comment]
咦 有点不明白，我本地关掉 VITE_USE_MOCK，代理https是没问题的
然后我想实现的是 如何在使用vite-plugin-mock的时候，用proxy代理那些mock没有配置的接口，不管proxy代理的是http或https

**Comment by anncwb** [comment]
我再注意下这个问题

**Comment by anncwb** [comment]
已找到原因，是因为vite-plugin-mock我用了bodyparse导致的。下一版修复
