### ISSUE TITLE
设置为后台模式后，affix的bug

### ISSUE THREAD

**Issue by auaa** [anncwb/vue-vben-admin#632]
设置为后台模式后，设置affix为true，会出现多个一样的tab。
![image](https://user-images.githubusercontent.com/7787272/118994022-92073900-b9b8-11eb-8103-9a3409c72d14.png)
我调试了一下，useMultipleTabs.ts（20行），打印出来的routes，很多重复。
希望解决一下。这个应该是vue.addRouter的bug

**Comment by anncwb** [comment]
尝试了一下，并未出现你的问题，是否可以在示例内复现出这个问题呢？可以的话给我个步骤

![image](https://user-images.githubusercontent.com/28132598/120346427-f073d600-c32d-11eb-8e1b-e4a45f3bec6a.png)

**Comment by anncwb** [comment]
Hello @auaa. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by auaa** [comment]
@anncwb 找到原因了，我后台返回alias字段原因。如果返回json中有alias，就会出现此问题
