### ISSUE TITLE
在router 有component 下创建 子路由 在菜单栏不显示

### ISSUE THREAD

**Issue by weizheng1992** [anncwb/vue-vben-admin#64]
目前 
![image](https://user-images.githubusercontent.com/10727313/97408168-b3c6a300-1936-11eb-9560-3070064074d3.png)
期望
![image](https://user-images.githubusercontent.com/10727313/97408287-d789e900-1936-11eb-9077-1ef510e0d0dc.png)

**Comment by anncwb** [comment]
写两个compoentn好像没有用处吧。 项目为了实现keepalive。会把所有的路由转化成2层路由。所以你这样写最后只会取最下面那层。上面的路由其实是没有用的。只为结构清晰

**Comment by weizheng1992** [comment]
我想在只有一级菜单的情况下，创建详情页  。
