### ISSUE TITLE
树形组件右键菜单拿不到node信息

### ISSUE THREAD

**Issue by fishjimi** [anncwb/vue-vben-admin#641]
https://github1s.com/anncwb/vue-vben-admin/blob/HEAD/src/views/demo/tree/EditTree.vue

参考这个文件中的代码，右键菜单的 handler 中打印 node 只能拿到里面的eventId, 拿不到title或者label，里面都是undefined

**Comment by mynetfan** [comment]
node的$attrs里有节点的数据。

console.log('点击了新增，节点数据为', node.$attrs?.node);

**Comment by fishjimi** [comment]
6666，太6了.... 都是夜猫子，
我正在写递归查找节点，写到一半刚好可以不用写了哈哈哈 多谢
