### ISSUE TITLE
notifications not translating

### ISSUE THREAD

**Issue by Darkmift** [anncwb/vue-vben-admin#643]
Hi folks,

The notifications are not translating to English.
See attached image

steps...click language icon change local and click on notifications

![image](https://user-images.githubusercontent.com/12433441/119265924-530ff800-bbf1-11eb-9510-1f8e36c851c6.png)

**Comment by anncwb** [comment]
Sorry, there are many places in the project that are not configured for translation, including sample pages. This workload is relatively large and will be gradually improved
