### ISSUE TITLE
F5刷新页面， index.html 会出现2个样式

### ISSUE THREAD

**Issue by zuihou** [anncwb/vue-vben-admin#644]
如下2个图，F5刷新系统，会显示index.html页面，样式会出现2个样式，第一个样式很快就会闪过，第二个样式停留的时间会久一点。但能明显感觉到2个画面的样式不同（背景色、字体大小、位置等）

本地启动时，刷新就能复现，但看你的线上环境，好像不能复现。是什么原因？

![image](https://user-images.githubusercontent.com/8500410/119268240-a8193180-bc24-11eb-9b53-b249f4681a6e.png)

![image](https://user-images.githubusercontent.com/8500410/119268249-aea7a900-bc24-11eb-8252-84f371ca9dfc.png)

**Comment by anncwb** [comment]
本地启动会css没加载完成，所以颜色不一样。加载后改变了颜色。可以在index.html把背景色改为白色就不会了。
