### ISSUE TITLE
暗黑主题部分组件颜色不正确

### ISSUE THREAD

**Issue by mynetfan** [anncwb/vue-vben-admin#645]
1、disabled状态的link button在暗黑主题下文字颜色不正确：
![image](https://user-images.githubusercontent.com/17241274/119268724-d26bee80-bc26-11eb-866c-254a4a6c19ba.png)
![image](https://user-images.githubusercontent.com/17241274/119268735-def04700-bc26-11eb-861c-b0a320280635.png)

2、alert 在暗黑主题下配色不正确：
以下是https://vvbin.cn/上的演示效果
![image](https://user-images.githubusercontent.com/17241274/119268786-152dc680-bc27-11eb-87b3-2142d0c64d08.png)
以下是ant design vue的演示效果
![image](https://user-images.githubusercontent.com/17241274/119268835-4c03dc80-bc27-11eb-92bd-71f8db3eed76.png)

3、tree组件的checkbox在暗黑主题下的选中状态显示不正确：
![image](https://user-images.githubusercontent.com/17241274/119268916-a0a75780-bc27-11eb-9fad-1ed54942bdf8.png)

4、tree组件的节点选中状态在暗黑主题下显示不正确：
![image](https://user-images.githubusercontent.com/17241274/119268957-ca607e80-bc27-11eb-9111-5e941c637f23.png)

5、tinymce 组件没有暗黑主题

## System Info

- Operating System: Win10  Build 19042
- Node version: 14.15
- Package manager (npm/yarn/pnpm) and version: yarn 1.22.10

**Comment by M69W** [comment]
> 3、tree组件的checkbox在暗黑主题下的选中状态显示不正确：

因为重新设置了 `border: 2px solid #fff;` 会导致 原先 设置的 border-top: 0; border-left: 0; 失效；
**临时解决方法**：追加  `border-top: 0; border-left: 0;` 即可

**Comment by mynetfan** [comment]
fixed：
https://github.com/anncwb/vue-vben-admin/commit/8cf004a5f59895e2487c3a350c83000e585b897e
https://github.com/anncwb/vue-vben-admin/commit/42812162c46832ce4d3e332bd579c042309115bc
https://github.com/anncwb/vue-vben-admin/commit/9b7ede09b9efe4d5a15ab0cdeadac480a29c0f62
https://github.com/anncwb/vue-vben-admin/commit/8cf004a5f59895e2487c3a350c83000e585b897e

**Comment by M69W** [comment]
此处漏了一个地方：https://vvbin.cn/next/#/comp/table/treeTable
Pr：https://github.com/anncwb/vue-vben-admin/pull/951
