### ISSUE TITLE
表格编辑的时候，无法对同一行其他单元格赋值。

### ISSUE THREAD

**Issue by lolysc** [anncwb/vue-vben-admin#646]
如题。

**Comment by lolysc** [comment]
http://localhost:3101/#/comp/table/editRowTable
以这个路由为例：我输入某单元格的时候，希望能改变其他单元格的值。@edit-change拦截到的data.record给其他栏位赋值，没有效果。发觉基类里返回的是toRaw(record)，但是即使去掉toRaw依然无效。
EditableCell.vue
table.emit?.('edit-change', {
          column: props.column,
          value: unref(currentValueRef),
          record:props.record
          // record: toRaw(props.record),
        });

**Comment by anncwb** [comment]
目前不支持这个功能

**Comment by mynetfan** [comment]
@lolysc 已在 https://github.com/anncwb/vue-vben-admin/commit/fe2bcfc6f74159c355f3be153a316869fdb8b644 添加支持及演示页面。

**Comment by lolysc** [comment]
@anncwb ，已经验证通过，感谢支持！
