### ISSUE TITLE
克隆项目后本地 yarn 安装依赖时报错

### ISSUE THREAD

**Issue by jiangmaniu** [anncwb/vue-vben-admin#647]
![image](https://user-images.githubusercontent.com/50100681/119292643-623f8600-bc83-11eb-80c5-6b2acb4b86a8.png)

node: v14.17.0

npm: v6.14.13

yarn: v1.22.10

**Comment by anncwb** [comment]
你的电脑或者node版本是64位的？

**Comment by jiangmaniu** [comment]
@anncwb 
![image](https://user-images.githubusercontent.com/50100681/119428200-076b6480-bd3f-11eb-8eed-ae05398d1797.png)
![image](https://user-images.githubusercontent.com/50100681/119428263-24079c80-bd3f-11eb-8c14-29e9be00e1fe.png)

**Comment by jiangmaniu** [comment]
这个问题搞了我一天，结果重启一下电脑就莫名其妙好了，我也不知道为什么。先关闭了。如有知道原因的大佬很欢迎您留言告诉我。
