### ISSUE TITLE
代码 lint

### ISSUE THREAD

**Issue by maicWorkGithub** [anncwb/vue-vben-admin#648]
- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug
编辑器 webstorm
lint 规则和你们的代码冲突，整屏的红色提示

![image](https://user-images.githubusercontent.com/15863224/119304053-46df7580-bc99-11eb-9f9d-3d3cf4f1eb1a.png)

![image](https://user-images.githubusercontent.com/15863224/119304079-51017400-bc99-11eb-81ec-ae6051ee2406.png)

### Reproduction

1，clone 项目
2，运行 `yarn install`
3，随便打开一个 src 下的源码文件

## System Info

- Operating System: Windows 10
- Node version: 14
- Package manager (npm/yarn/pnpm) and version: yarn 1.22

**Comment by anncwb** [comment]
webstorm可以自行搜索下解决方案，或者禁用eslint扩展

**Comment by maicWorkGithub** [comment]
> webstorm可以自行搜索下解决方案，或者禁用eslint扩展

能透露一下关键字吗，谢谢
