### ISSUE TITLE
CodeEditor 高度自适应时垂直滚动条总是可见

### ISSUE THREAD

**Issue by tky753** [anncwb/vue-vben-admin#655]
### Problem

![image](https://user-images.githubusercontent.com/18205977/119634066-eee57200-be44-11eb-8277-6e87bfd1c72b.png)
![image](https://user-images.githubusercontent.com/18205977/119634289-32d87700-be45-11eb-88fc-4b96ce75ae63.png)
```html
<a-card>
  <template #title>
    <a-button>{{ t('common.saveText') }}</a-button>
  </template>
  <CodeEditor v-model:value="fileContentRef" mode="javascript" />
</a-card>
```

### Expected behaviour

能否自动计算高度，使垂直滚动条不显示？

**Comment by mynetfan** [comment]
https://vvbin.cn/next/#/comp/editor/json
演示页面就是如此

**Comment by tky753** [comment]
@mynetfan 所以这是不是可以改进啊。还有演示界面如此，你是不是用手机看的

**Comment by mynetfan** [comment]
@tky753 电脑啊。演示界面就是高度足够就不会显示滚动条，高度不够时才显示。

**Comment by tky753** [comment]
@mynetfan  演示界面 PageWrapper 设置了 **contentFullHeight**，默认就给你拉满了，所以感受不出来。
