### ISSUE TITLE
Support multiple languages

### ISSUE THREAD

**Issue by Philipp-M** [anncwb/vue-vben-admin#66]
### Problem

Currently only Chinese is supported. It would be great to be able to easily switch between multiple languages.

### Expected behaviour

Maybe add a button in the top bar similar as in https://github.com/PanJiaChen/vue-element-admin to switch between the languages.

**Comment by anncwb** [comment]
There is this plan, but it may not start in the near future, and it will be done in a separate branch later

**Comment by aios** [comment]
@Philipp-M @anncwb i think i maked it...

**Comment by anncwb** [comment]
Already supported
