### ISSUE TITLE
升级后BasicTable组件操作列出现问题

### ISSUE THREAD

**Issue by xietongjian** [anncwb/vue-vben-admin#661]
### Describe the bug
升级后BasicTable组件，操作列本来是固定的如果列比较多的时候显示不出来了。
在改变窗口变小的情况下显示正常
![image](https://user-images.githubusercontent.com/16096832/119791551-814e4a00-bf07-11eb-8d9c-8c126c20745a.png)

放大窗口后滚动条拉完了也显示不出来了。
![image](https://user-images.githubusercontent.com/16096832/119791378-5cf26d80-bf07-11eb-9fbd-a80c78d43b43.png)

官方例子可以复现：
复现步骤是改变窗口宽度
https://vvbin.cn/next/#/comp/table/fixedColumn

**Comment by mynetfan** [comment]
请暂时先退回到2.4版本，2.4 release之后的commits先不要同步

**Comment by anncwb** [comment]
fixed 566280422de0537c4e31496eaaa95a9d51fe9458
