### ISSUE TITLE
企业微信无法进入页面

### ISSUE THREAD

**Issue by xiaochong44** [anncwb/vue-vben-admin#664]
### Describe the bug

企业微信PC版 打开无法进入页面，调试报下面错误
Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

**Comment by anncwb** [comment]
本地开发还是打包

**Comment by xiaochong44** [comment]
@anncwb 我是本地开发，测试不行，以为我写的代码有问题，就用企业微信pc端直接打开你的demo也一样的错误
你用企业微信PC版直接打开https://vvbin.cn/next/，就能看到错误

**Comment by M69W** [comment]
内核原因？

**Comment by opamine** [comment]
开发企业微信内部应用？这年头腾讯自己都不会用这玩意儿吧

**Comment by anncwb** [comment]
企业微信不打算兼容，你可以尝试看看在`.env.production`内将`VITE_LEGACY `值改为`true`再试试
