### ISSUE TITLE
页面刷新，在响应错误处理钩子中，调用退出登录，成功跳转登录页面，页面一直处于loading，无法显示登录表单

### ISSUE THREAD

**Issue by jekip** [anncwb/vue-vben-admin#671]
1、需求场景，当账号被禁用，期望是退出登录，并且跳转登录页面
尝试在：responseInterceptorsCatch 中 判断 
createErrorModal({
          title: '提示',
          content: msg ? msg : t('sys.api.networkExceptionMsg'),
          onOk: async ()=> {
           //这里尝试2种方案 都无效
           方案1
            userStore.setToken(undefined);
            userStore.setSessionTimeout(true);
           方案2
            await userStore.logout(true);
          }
});
tip: 这里只有在刷新页面，那一刻无效，如果是账号被禁用之后，只是切换页面，调用接口，这里可以正常跳转登录页面

**Comment by xietongjian** [comment]
> 这种情况请不要使用方案1，这个方案仅用于会话过期，重新登录后仍然保持登录之前的状态，也就是说页面不会刷新（登录页面覆盖在之前的页面之上）。
> 方案2是有什么问题吗？
    确实有这个问题，如果后台项目重启后，刷新页面时是新的会话，会返回状态码401，此时页面其实接口都没返回数据，页面上是没数据的，登录页面会覆盖在上面，然后登录成功后覆盖的登录页消失。然后就会看到没数据的页面。

**Comment by jekip** [comment]
我说的这种场景，方案1 和方案2 都存在该问题，就是 push 到 login 页面了，页面会一直处于loading，没有显示登录表单，你可以尝试一下

**Comment by mynetfan** [comment]
我自己就是这样做的，不过，我放在了src\utils\http\axios\checkStatus.ts的checkStatus函数内，该函数也是由responseInterceptorsCatch调用的，并未发现你说的问题。
另外，项目的演示页面https://vvbin.cn/next/#/feat/session-timeout模拟了这种场景，也可正常工作。

**Comment by jekip** [comment]
checkStatus函数内，我也尝试过针对我那种场景也是一样，项目演示模拟的场景和我所说的不一样
1、项目模拟的场景是，所有的路由/页面渲染完成
2、我所说的场景是，A账号正常使用的情况下，账号被禁用了，此时手动刷新页面的情况下，接口给出了code，我期望这个时候，在responseInterceptorsCatch 或者 checkStatus 函数内，能强制退出，push到login页面
3、同样的代码，如果是这种场景，此时不刷新页面，而是随便去一个页面，这时候钩子中代码就能正常到login页面

**Comment by xietongjian** [comment]
他们的项目演示页面没做后台数据请求，那种场景模拟不出来

**Comment by mynetfan** [comment]
模拟了你的问题，以下步骤你看是否跟你所描述的相同：
1、登录，切换到任意子路由
2、后台禁用账号，注销Token
3、刷新页面，此时页面会发起请求获取菜单，收到后端返回的code不正确，回到了登录界面（测试时采用了你所说的方案1的处理方式）；
4、重新登录其它账号，登录成功，但没有导航菜单、路由等基础数据，并且停留在了刷新之前的页面

**Comment by mynetfan** [comment]
@xietongjian 已确认你所描述的问题。

@jekip 你所描述的跟 @xietongjian 所描述的有区别，你的问题我无法重现。

**Comment by xietongjian** [comment]
> 你的问题我无法重现。

都是登录问题，确实他那个问题我也没重现出来。

**Comment by anncwb** [comment]
Hello @jekip. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by jekip** [comment]
1、代码片段
![11111111](https://user-images.githubusercontent.com/19426584/120054728-3564e780-c064-11eb-90e8-d9d062d10009.png)
2、重新步骤，分配子账号正常权限，登陆成功，获取菜单显示页面，此时用admin账号禁用该账号，子账号刷新页面之后，确实进了钩子函数，也调用了 logout方法，重定向到了 login页面，只是页面一直处于loading
![2222222222](https://user-images.githubusercontent.com/19426584/120054773-912f7080-c064-11eb-9cf1-5a0ffa2bda62.png)
![333333333](https://user-images.githubusercontent.com/19426584/120054775-94c2f780-c064-11eb-9457-97a728210821.png)
![444444444](https://user-images.githubusercontent.com/19426584/120054777-97255180-c064-11eb-996c-d8a684541b7b.png)

**Comment by mynetfan** [comment]
当前版本未能重现

**Comment by Mikasa33** [comment]
更新“新增用户登录过期示例”代码后，我的项目也出现了一些问题。
我的项目菜单是通过后台接口获取的。

第一种情况：
1. 当新打开浏览器，访问业务页面地址的时候，此时肯定是登录过期状态，会展示登录界面，但路由地址依旧是业务页面的地址。
2. 现在进行登录，成功后会展示业务页面，由于此时路由没有改变，是不会请求后台接口加载菜单的。

第二种情况：
1. 当登录过期，展示登录界面的时候，路由地址依旧是业务页面的地址，没有变化。
2. 现在进行登录，成功后会展示业务页面，页面中使用了 useTable 的表格组件，此时是不会自动调用接口获取最新的列表数据的。

**Comment by mynetfan** [comment]
> 更新“新增用户登录过期示例”代码后，我的项目也出现了一些问题。
> 我的项目菜单是通过后台接口获取的。
> 
> 第一种情况：
> 
> 1. 当新打开浏览器，访问业务页面地址的时候，此时肯定是登录过期状态，会展示登录界面，但路由地址依旧是业务页面的地址。
> 2. 现在进行登录，成功后会展示业务页面，由于此时路由没有改变，是不会请求后台接口加载菜单的。
> 
> 第二种情况：
> 
> 1. 当登录过期，展示登录界面的时候，路由地址依旧是业务页面的地址，没有变化。
> 2. 现在进行登录，成功后会展示业务页面，页面中使用了 useTable 的表格组件，此时是不会自动调用接口获取最新的列表数据的。

用户登录过期示例演示的登录页面是覆盖在业务页面之上的，本身这种设计的目的是为了保留已过期的页面的状态，使得成功登录之后仍然可以继续之前的业务状态，所以不会重新请求菜单也不会重新让页面中的table加载远程数据。
最近的commit针对这种情况有一点小改动：如果登录后的用户不是过期之前的用户（通过userId区分），会刷新整个页面以便丢弃老用户的页面状态。
更新这种过期登录方法并没有摒弃正常的登录流程。如果你不需要这种过期后重新登录仍然回到之前状态的逻辑，可以继续使用之前的过期登录逻辑（直接切换路由到登录页面），默认的演示逻辑在src\utils\http\axios\checkStatus.ts第22行附近userStore.logout(true)和userStore.setSessionTimeout(true)是两种不同的重新登陆方法

**Comment by Mikasa33** [comment]
是的，目前根据我个人的需求，应该是需要使用之前的登录逻辑，我自行修改一下，感谢您的回复！ @mynetfan
