### ISSUE TITLE
文件上传，自定义地址没有转发到后台代理地址上，仍然用的本地前端地址请求

### ISSUE THREAD

**Issue by zn98com** [anncwb/vue-vben-admin#676]
文件上传，自定义地址没有转发到后台代理地址上，仍然用的本地前端地址请求，如：
export function ImporterExcel(
  params: UploadFileParams,
  onUploadProgress?: (progressEvent: ProgressEvent) => void
) {
  return defHttp.uploadFile<UploadApiResult>(
    {
      url: '/api/Public/ImporterExcel',
      onUploadProgress,
    },
    params
  );
}

**Comment by anncwb** [comment]
给一下你的上传地址配置

**Comment by zn98com** [comment]
/**
&nbsp;*&nbsp;导入Excel
&nbsp;*/
export&nbsp;function&nbsp;ImporterExcel(
&nbsp;&nbsp;params:&nbsp;UploadFileParams,
&nbsp;&nbsp;onUploadProgress?:&nbsp;(progressEvent:&nbsp;ProgressEvent)&nbsp;=&gt;&nbsp;void
)&nbsp;{
&nbsp;&nbsp;return&nbsp;defHttp.uploadFile<UploadApiResult&gt;(
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;url:&nbsp;'/Public/ImporterExcel',
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;onUploadProgress,
&nbsp;&nbsp;&nbsp;&nbsp;},
&nbsp;&nbsp;&nbsp;&nbsp;params
&nbsp;&nbsp;);
}



上面url不跳转到后台地址，如果加上后台IP可以直接访问
url:&nbsp;'http://111.11.11.11/Public/ImporterExcel',




成都赛珂琪科技有限公司

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "anncwb/vue-vben-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月31日(星期一) 上午9:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [anncwb/vue-vben-admin] 文件上传，自定义地址没有转发到后台代理地址上，仍然用的本地前端地址请求 (#676)





 
给一下你的上传地址配置

**Comment by anncwb** [comment]
尝试了一下，可以正常代理。你给的信息太乱，根本看不出什么问题，也没有错误信息
