### ISSUE TITLE
table onchange 提示 need function not array

### ISSUE THREAD

**Issue by godaangel** [anncwb/vue-vben-admin#677]
code 
```
    const [registerTable, { reload, getColumns }] = useTable({
        showIndexColumn: false,
        columns: getBasicColumns(),
        onChange: (pagination: any, __: any, sorter: { [key: string]: string }) => {
        },
        ellipsis: false,
    });
```

warning:

[Vue warn]: Invalid prop: type check failed for prop "onChange". Expected Function, got Array  
  at <ATable ref="tableElRef" size="middle" customRow=fn<customRow>  ... > 
  at <BasicTable onRegister=fn<register> dataSource= [{…}] > 

version: 
vben 2.3.0
ant-design-vue 2.1.6

**Comment by mynetfan** [comment]
注意，不能使用useTable来注册事件，useTable只可用来设置props。请直接将事件绑定在Template中的BasicTable节点上。如：
`<BasicTable @register="registerTable" @change="onChange" />`

**Comment by mynetfan** [comment]
https://github.com/anncwb/vue-vben-admin/commit/9f5085c9f9f46b09391156b17091c1771bc13026

此commit解决useTable无法注册onChange的问题。
