### ISSUE TITLE
需求增强：使用localforage做数据存储，无上限存储数据

### ISSUE THREAD

**Issue by GavinChain** [anncwb/vue-vben-admin#679]

**Comment by anncwb** [comment]
目前localstorage只用于存储一些简单信息，5M完全够用。你的场景是什么？

**Comment by M69W** [comment]
应该是引入第三方插件，突破这种存储限制？
这个看个人需求吧

**Comment by mynetfan** [comment]
localStorage不可能无上限，这取决于浏览器的限制，大部分浏览器现在是5MB，safari  之前的版本限制为2.5MB，新版本尚不清楚，但应该不会超过5MB。

**Comment by jiangmaniu** [comment]
可以考虑引入 indexedDB

**Comment by GavinChain** [comment]
> 目前localstorage只用于存储一些简单信息，5M完全够用。你的场景是什么？

缓存多平台菜单信息(随时可切换不同平台菜单),缓存消息日志,缓存报表信息等,会有些缓存需求

**Comment by GavinChain** [comment]
> 目前localstorage只用于存储一些简单信息，5M完全够用。你的场景是什么？

缓存多平台菜单信息(随时可切换不同平台菜单),缓存消息日志,缓存报表信息等,会有些缓存需求

**Comment by GavinChain** [comment]
> localStorage不可能无上限，这取决于浏览器的限制，大部分浏览器现在是5MB，safari 之前的版本限制为2.5MB，新版本尚不清楚，但应该不会超过5MB。

localforage理论无上限,底层由indexedDB实现,异步缓存

**Comment by mynetfan** [comment]
> > localStorage不可能无上限，这取决于浏览器的限制，大部分浏览器现在是5MB，safari 之前的版本限制为2.5MB，新版本尚不清楚，但应该不会超过5MB。
> 
> localforage理论无上限,底层由indexedDB实现,异步缓存

不是能不能存，是浏览器让不让存。超过5MB浏览器根本不让继续写，这是浏览器的限制。你想要无限制，就直接用indexedDB，而不是LocalStorage。

**Comment by GavinChain** [comment]
> 目前localstorage只用于存储一些简单信息，5M完全够用。你的场景是什么？

大型系统,需要做一些异步任务推送等,这些业务异步存储在

> > > localStorage不可能无上限，这取决于浏览器的限制，大部分浏览器现在是5MB，safari 之前的版本限制为2.5MB，新版本尚不清楚，但应该不会超过5MB。
> > 
> > 
> > localforage理论无上限,底层由indexedDB实现,异步缓存
> 
> 不是能不能存，是浏览器让不让存。超过5MB浏览器根本不让继续写，这是浏览器的限制。你想要无限制，就直接用indexedDB，而不是LocalStorage。
localforage  是localforage[http://localforage.docschina.org/] 不是 localstoreage

**Comment by GavinChain** [comment]
> > 目前localstorage只用于存储一些简单信息，5M完全够用。你的场景是什么？
> 
> 大型系统,需要做一些异步任务推送等,这些业务异步存储在
> 
> > > > localStorage不可能无上限，这取决于浏览器的限制，大部分浏览器现在是5MB，safari 之前的版本限制为2.5MB，新版本尚不清楚，但应该不会超过5MB。
> > > 
> > > 
> > > localforage理论无上限,底层由indexedDB实现,异步缓存
> > 
> > 
> > 不是能不能存，是浏览器让不让存。超过5MB浏览器根本不让继续写，这是浏览器的限制。你想要无限制，就直接用indexedDB，而不是LocalStorage。
> > localforage  是localforage[http://localforage.docschina.org/] 不是 localstoreage,它主要解决了indexedDB复杂操作,localforage.setItem(key,value)即实现无限存储

**Comment by mynetfan** [comment]
恕我眼拙，看错了，一直都以为你说的是LocalStorage。

**Comment by GavinChain** [comment]
"localforage": "^1.9.0",即简单实现了无上限缓存问题,上手很简单,可以做demo页,做一个千人薪资Demo,会体现出它对大型业务的益处

**Comment by anncwb** [comment]
这个感觉你可以自己引入就行。跟现有系统应该也是不冲突吧
