### ISSUE TITLE
表格在有些复杂页面会卡死

### ISSUE THREAD

**Issue by ErnestWangZuNian** [anncwb/vue-vben-admin#681]
最新2.4版本修复了之前有些表格卡死的情况 

但是有些场景下 表格会出现卡死 一直在创建表格 一进表格就卡死

不好提供代码 描述一下场景 就是页面是一个表格页面 从其它页面跳转到表格页面  这个其它页面是有keep-alive的  跳到改表格页面 表格卡死 表格就是基础的分页表格

**Comment by anncwb** [comment]
这个没办法测试，只能提供复现示例，或者你看看在示例页面中会不会，给个复现步骤

**Comment by anncwb** [comment]
Hello @ErnestWangZuNian. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.
