### ISSUE TITLE
Electron 引入失败

### ISSUE THREAD

**Issue by Aimumu** [anncwb/vue-vben-admin#683]
引入Vue3项目集成Electron

> vue add electron-builder 成功
“scripts”：{
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
}
> yarn electron:serve 报错
**$ vue-cli-service electron:serve
'vue-cli-service' 不是内部或外部命令，也不是可运行的程序**

请问vue-vben-admin 如何正确使用Electron
感谢！

**Comment by M69W** [comment]
此项目不是用 vue-cli，用的是 vite。

https://github.com/search?q=vite+Electron

**Comment by Aimumu** [comment]
vue add electron-builder目前不支持vue3 且跟此项目框架不符合，感谢回复~
