### ISSUE TITLE
抽屉里面是一个table列表，如果我开启上面的搜索表单，页面就直接卡死了，关都关不掉，如果不开启上面的搜索表单，就是正常的，这是什么问题？

### ISSUE THREAD

**Issue by liyaxu123** [anncwb/vue-vben-admin#684]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

抽屉里面是一个table列表，如果我开启上面的搜索表单，页面就直接卡死了，关都关不掉，如果不开启上面的搜索表单，就是正常的，这是什么问题？

### Reproduction

![11](https://user-images.githubusercontent.com/55610041/120259769-1d40d280-c2c7-11eb-8a76-b287d927d117.png)

## System Info

- Operating System: windows
- Node version: v14.15.0
- Package manager (npm/yarn/pnpm) and version:

**Comment by mynetfan** [comment]
未能重现你描述的问题。
![image](https://user-images.githubusercontent.com/17241274/120264528-94c72f80-c2d0-11eb-87f6-9e00a4ef0de9.png)

**Comment by anncwb** [comment]
Hello @liyaxu123. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by liyaxu123** [comment]
好的谢谢，我在找找原因

**Comment by cats1** [comment]
> 
> 
> 好的谢谢，我在找找原因

我也遇到了相同的问题，请问问题解决了嘛

**Comment by liyaxu123** [comment]
在开发别的功能，这个我还没处理，我一会再试试

**Comment by liyaxu123** [comment]
> 的谢谢，我在找找原因
我在开发别的功能，这个我还没处理，我一会再试试

**Comment by ErnestWangZuNian** [comment]
表格那块有些地方确实会卡死 我目前遇到的是   windows上面表格会卡死
