### ISSUE TITLE
开启标签页缓存后 TabDropDown中的方法未修改缓存信息

### ISSUE THREAD

**Issue by bangxingni** [anncwb/vue-vben-admin#685]
RT  
![image](https://user-images.githubusercontent.com/20875524/120282643-ea113a00-c2ec-11eb-9f53-7b5dbd4bfe50.png) 
这些方法的store后面未加   
cacheTab && Persistent.setLocal(MULTIPLE_TABS_KEY, this.tabList);

关闭标签后刷新标签仍存在

**Comment by anncwb** [comment]
能描述下你的信息？ 不清楚你的问题是什么

**Comment by anncwb** [comment]
Hello @bangxingni. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by bangxingni** [comment]
![image](https://user-images.githubusercontent.com/20875524/120404091-28a00680-c378-11eb-894c-65bb54d7ce62.png)
 开启标签缓存后，标签栏操作关闭标签 缓存没有刷新
