### ISSUE TITLE
升级到最新版本后，使用VSCode 无法断点调试的

### ISSUE THREAD

**Issue by nameLogen** [anncwb/vue-vben-admin#686]
升级到最新版本后，使用VSCode 无法断点调试，是还需要修改什么地方吗？  升级前是可以正常断点调试的。
![image](https://user-images.githubusercontent.com/23234230/120315240-b2b38500-c30e-11eb-9f3b-b42108752690.png)
![image](https://user-images.githubusercontent.com/23234230/120315293-c7901880-c30e-11eb-9bff-8487f8905111.png)

**Comment by nameLogen** [comment]
![image](https://user-images.githubusercontent.com/23234230/120316075-9b28cc00-c30f-11eb-9003-540554ffa2fd.png)
这些地方还能断到点，其他地方的断点，会无效。或者跳到该位置上

**Comment by nameLogen** [comment]
![image](https://user-images.githubusercontent.com/23234230/120316290-d75c2c80-c30f-11eb-99db-6727cbebc8bd.png)
工程没有什么区别。只是多了几个自己的界面而已。

**Comment by anncwb** [comment]
这个我个人没用使用过，我认为应该是插件对代码进行了转化，导致了行数错误。你可以尝试还原到之前的版本具体测试看看，或者给我一个可用的git commit id

**Comment by nameLogen** [comment]
> 这个我个人没用使用过，我认为应该是插件对代码进行了转化，导致了行数错误。你可以尝试还原到之前的版本具体测试看看，或者给我一个可用的git commit id

还原到上个版本的。就没啥问题。 算了我先用上个版本的吧。谢了！
