### ISSUE TITLE
使用useForm的setProps设置表单的 props 参数schemas时，根据一个判断值切换会不更新页面，会一直以第二次设置的为准

### ISSUE THREAD

**Issue by IFnGSiYu** [anncwb/vue-vben-admin#688]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by IFnGSiYu** [comment]
if (modelType.value === 3) {
        console.log('重置密码');
        setProps({ schemas: resetPsdformSchema});
      } else {
        setProps({ schemas: accountFormSchema })
}
这样设置，是我用的方法不对，还是一个bug

**Comment by anncwb** [comment]
这个可以直接使用一个computed，传入Form组件即可

``` js

const getSchemas=computed(()=>{
return modelType.value === 3? resetPsdformSchema: accountFormSchema
})

<Form schemas="getSchemas"></Form>


```

**Comment by IFnGSiYu** [comment]
大概明白了，通过computed获取传过来的参数，还是对vue3的api不太熟，感谢解答

**Comment by IFnGSiYu** [comment]
我昨天描述问题没说好，问题应该是动态设置schemas 后，再updateSchema更新会造成视图不会更新

**Comment by mynetfan** [comment]
未能重现问题。
![image](https://user-images.githubusercontent.com/17241274/120573111-a8e56b00-c44f-11eb-9d5a-2bd362b28908.png)
测试如图代码可正常工作。

**Comment by anncwb** [comment]
Hello @IFnGSiYu. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by IFnGSiYu** [comment]
这样设置不同的schemas
if (modelType.value === 3) {
console.log('重置密码');
setProps({ schemas: resetPsdformSchema});
} else {
setProps({ schemas: accountFormSchema })
}
然后updateSchema会出现问题

**Comment by mynetfan** [comment]
你给的代码片段不足以重现问题，请提供足够的可以重现问题的演示代码。我再加一个onBtn2Click设置schemas2也没能出现问题。

**Comment by mynetfan** [comment]
已找到问题。

**Comment by IFnGSiYu** [comment]
期待解决方案

**Comment by crazy6995** [comment]
model 其实也会出现这个问题，最后我直接放到了 template 内 <BasicForm :model="formDataRef"> ，使用useForm()会出现这个问题，目测是响应性的问题。。。（但是我看内部具有对 props 的整体watch，当formDataRef变更时，这个watch并没有被触发【P.s有时候莫名其妙就好了。。】）
