### ISSUE TITLE
Modal弹窗里面的表单通过一个参数设置不同的schemas，弹窗的高度不会自适应，求解

### ISSUE THREAD

**Issue by IFnGSiYu** [anncwb/vue-vben-admin#691]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by IFnGSiYu** [comment]
弹窗的高度不会以配置项的多少自适应，而是以最多项高度，检查div会有一个css，    min-height: 200px;height: 601px;，求解怎么去掉这个height

**Comment by mynetfan** [comment]
动态设置Modal内容需要自行处理Modal高度。https://github.com/anncwb/vue-vben-admin/commit/f732b569042f7fe77c85cb295538ddd85561f7e9 该commit已为useModalInner添加了redoModalHeight，并且在Modal演示页面演示了如何在Modal内动态加载内容之后更新Modal的高度。
