### ISSUE TITLE
BasicTree有没有一个props参数设置以后，可以获取子节点没有勾选完全的情况下拿到父节点的值

### ISSUE THREAD

**Issue by IFnGSiYu** [anncwb/vue-vben-admin#698]
### Problem
我没有在文档中找到这个参数，所以加了一个checkedAllKeys 

 onCheck: (v: CheckKeys, info: any) => {
          state.checkedKeys = v;
          const rawVal: any = toRaw(v);
          let checkedKey = [...rawVal, ...info.halfCheckedKeys];
          state.checkedAllKeys = checkedKey;
          emit('update:value', rawVal);
          emit('check', rawVal);
        },
在这个监听传值
watch(
      () => state.checkedKeys,
      () => {
        // const v = toRaw(state.checkedKeys);
        const v = toRaw(state.checkedAllKeys);
        console.log('change',v);
        emit('update:value', v);
        emit('change', v);
      }
    );
有大神提供更简便方法麻烦贴下代码

**Comment by anncwb** [comment]
可以看看ant-design-vue文档，那边可以支持，BasicTree就可以支持
