### ISSUE TITLE
精简版可以再精简些吗

### ISSUE THREAD

**Issue by cereschen** [anncwb/vue-vben-admin#70]
项目很不错
不过依赖的包太多了 有一些并不是必须的

**Comment by anncwb** [comment]
目前看了，只有`vue-i18n`这个包可以精简。你指的是还有哪些？

**Comment by cereschen** [comment]
抱歉 我收回刚才的话
我主要指的是vscode的一系列配置(例如捆绑langguage server)
但是如果去掉这些 用户自己来集成有些麻烦
考虑到这样的情况
我自己处理一下就好了 
最后还是感谢这个项目 工程化做的很棒
