### ISSUE TITLE
更新之后本地启动只能使用localhost访问了

### ISSUE THREAD

**Issue by yanduhantan1991** [anncwb/vue-vben-admin#702]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [ ] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

A clear and concise description of what the bug is..

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by mynetfan** [comment]
package.json第12行的vite后面加--host，注意空格
`"dev": "vite --host"`

**Comment by yanduhantan1991** [comment]
> package.json第12行的vite隔加--host，注意空格
> `"dev": "vite --host"`
多谢，我改了下vite.config.ts
