### ISSUE TITLE
项目编译正常，浏览器运行

### ISSUE THREAD

**Issue by TsundereQueen** [anncwb/vue-vben-admin#704]
http://xxy-1258031202.picsh.myqcloud.com/86166f2f-f11b-4034-9ee4-251094f10f3b.png

Uncaught SyntaxError: Unexpected token .

**Comment by M69W** [comment]
麻烦提供重现代码

**Comment by TsundereQueen** [comment]
就拉下来，然后按照readme命令操作完启动就会出现此错误

**Comment by mynetfan** [comment]
请提供浏览器版本、Nodejs版本、操作系统版本

**Comment by anncwb** [comment]
这个是浏览器版本低
