### ISSUE TITLE
在Mac系统下安装好依赖运行项目报错

### ISSUE THREAD

**Issue by 13076079291** [anncwb/vue-vben-admin#708]
Vben-Admin版本: 2.4.1

Mac系统版本：Mac OS Bigsur 11.3.1

Node版本：14.17.0

报错内容： TypeError: Cannot read property 'endsWith' of undefined

按照官网文档安装依赖 Windows下正常运行，Mac下报以上错误。重试过安装依赖问题依旧存在。
<img width="893" alt="截屏2021-06-06 下午12 25 30" src="https://user-images.githubusercontent.com/85353476/120912503-51026a80-c6c2-11eb-840c-f21ec5fe1b7c.png">

**Comment by mynetfan** [comment]
在你的MAC电脑上打开根目录下的vite.config.ts，在第31行左右的`const viteEnv = wrapperEnv(env);`之后插入以下代码：
`console.log({ env, viteEnv });`
然后再尝试yarn serve启动vite开发服务，启动过程中控制台会输出读取到的你的环境变量，请将它们截图贴出来看一下，大概类似下面这样的：
![image](https://user-images.githubusercontent.com/17241274/120913374-5616e800-c6c9-11eb-9dc6-153ccd259940.png)

**Comment by mynetfan** [comment]
已确认，系.env文件丢失所致

**Comment by smilingFlower** [comment]
@mynetfan 请问是从哪里看出是.env文件丢失所致的问题

**Comment by sun-shu** [comment]
你应该是采用复制粘贴的方式创建的项目 MAC的访达默认会把.开头的文件隐藏 所以没复制全，打开隐藏文件把所有.系列的拿过去就好了
