### ISSUE TITLE
谷歌浏览器开发useTable组件出现卡死

### ISSUE THREAD

**Issue by 6155952** [anncwb/vue-vben-admin#709]
![1622953362(1)](https://user-images.githubusercontent.com/56713496/120912499-3cbe6d80-c6c2-11eb-8f18-5cefa5e53109.jpg)

笔记本开发，使用谷歌浏览器开发这个组件时出现卡死，一开始以为是本地运行的问题，去了项目演示地址访问也是出现一样的问题，换了火狐开发没发现问题，node.js版本是12.16.1

**Comment by mynetfan** [comment]
请贴出操作系统版本以及浏览器的具体版本

**Comment by 6155952** [comment]
操作系统：window10企业版;
谷歌浏览器：版本 91.0.4472.77（正式版本） （32 位）

**Comment by init-center** [comment]
出现了同样的问题，换火狐后正常
操作系统： windows 10 家庭中文版
操作系统版本： 19041.488
浏览器版本： Google Chrome 已是最新版本
版本 91.0.4472.77（正式版本） （64 位）

**Comment by init-center** [comment]
> 出现了同样的问题，换火狐后正常
> 操作系统： windows 10 家庭中文版
> 操作系统版本： 19041.488
> 浏览器版本： Google Chrome 已是最新版本
> 版本 91.0.4472.77（正式版本） （64 位）

https://vvbin.cn/next/#/comp/table/formTable
直接访问这个地址即可复现

**Comment by anncwb** [comment]
duplicate #720
