### ISSUE TITLE
Cascader 选项从后台获取，怎么操作？

### ISSUE THREAD

**Issue by lorenzozozo** [anncwb/vue-vben-admin#711]
{
      field: 'shortname',
      component: 'Cascader',
      label: '产品分类',
      colProps: {
        span: 12,
      },
      componentProps: {
        options: CategoryOptions,
      },
    },

我希望CategoryOptions这个数据是自己从后台服务获取的，请问怎么使用呢？

**Comment by mynetfan** [comment]
参考`src\views\demo\system\role\RoleDrawer.vue`中远程获取权限菜单数据的演示代码

**Comment by lorenzozozo** [comment]
谢谢

**Comment by lorenzozozo** [comment]
有像ApiSelect这样的组件吗

**Comment by mynetfan** [comment]
暂未封装

**Comment by lorenzozozo** [comment]
大神能否封装一个？

**Comment by lorenzozozo** [comment]
或者是否有动态修改options值的方式？
