### ISSUE TITLE
vite有没有类似webpack这种模块化打包呢

### ISSUE THREAD

**Issue by wsxe9988** [anncwb/vue-vben-admin#717]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

vite有没有类似webpack这种模块化打包呢
比如项目的业务模块在views下面不同模块是不同文件夹，如果局部更新的话，能否将views文件夹下新增的文件夹局部打包后替换到生产环境

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by anncwb** [comment]
你可以到vite提问
