### ISSUE TITLE
BasicTable 特定情况卡死重现 

### ISSUE THREAD

**Issue by sleidstDST** [anncwb/vue-vben-admin#720]
浏览器版本：
Google Chrome 90.0.4430.212（正式版本） (x86_64)
屏幕分辨率：
13.3寸 2565*1600 屏幕无缩放
![image](https://user-images.githubusercontent.com/26705989/120967539-2683e080-c79a-11eb-85df-e9ec767f20b4.png)
#

1、重现步骤
  1）用谷歌浏览器缩放到80%
  2）打开（其他table都可重现） https://vvbin.cn/next/#/comp/table/formTable
  3）调整表格每页显示条数，只要表格出现竖向滚动条即可
  4）这时候触发表格重新计算高度，比如此页面点击搜索区域 “收起”按钮
 卡死了。。。。。  

 其实重现也简单： 只要确保表格数据量能达到表格能产生竖向滚动条 ，这时候调用表格重新取数或者调整浏览器高度（只要能触发表格重新计算高度就行）

 我电脑是按如上步骤重现的，我在同事电脑上把浏览器缩放到90%就能重现

![image](https://user-images.githubusercontent.com/26705989/120967698-634fd780-c79a-11eb-8038-00f18b83da50.png)

2、出问题代码
代码在这里会进入死循环
![image](https://user-images.githubusercontent.com/26705989/120972397-49b18e80-c7a0-11eb-883b-fdd0f69d062e.png)

**Comment by init-center** [comment]
很奇怪，我试了一下，只有chrome才会出现，火狐没问题，甚至同样是chromium内核的edge也没问题

**Comment by sleidstDST** [comment]
@mynetfan  这个不是点击from收起按钮的问题哦，是表格本身计算高度导致死循环卡死的

**Comment by anncwb** [comment]
@sleidstDST 现在还会出现？

**Comment by anncwb** [comment]
我试了下不会出现了

**Comment by sleidstDST** [comment]
@anncwb  可以尝试下，从后台取数，先渲染出表格，后台加载数据后出现表格滚动条时就会卡死

**Comment by init-center** [comment]
> 我试了下不会出现了

简单试了一下不卡死了，但是 HP ProBook 440 G8 NoteBook PC，1920x1080分辨率下，屏幕缩放125%， 下面的分页栏一直在鬼畜地抖动

**Comment by 6155952** [comment]
@init-center  我也出现这个问题了，笔记本，谷歌，1920x1080分辨率下，屏幕缩放100%，下面的分页栏一直在鬼畜地抖动，还是那个页面

**Comment by anncwb** [comment]
确认下了，这个问题是vue版本的问题，目前是`3.0.11`，升级到 `3.1.0-beta.7`问题消失，但是目前升级后还有bug，所以后面3.1.0发布在进行升级

**Comment by anncwb** [comment]
closed 8eba7fb52786d1977e4cb7b67673d74c91c5c827
