### ISSUE TITLE
不能使用a-upload

### ISSUE THREAD

**Issue by ii8080cn** [anncwb/vue-vben-admin#721]
<a-upload
    name="file"
    :multiple="true"
    action="https://www.mocky.io/v2/5cc8019d300000980a055e76"
    :headers="headers"
    @change="handleChange"
  >
    <a-button> <a-icon type="upload" /> Click to Upload </a-button>
  </a-upload>

**Comment by anncwb** [comment]
组件需要自行引入，例如`import { Upload } from 'ant-design-vue'`
