### ISSUE TITLE
windicss class貌似只对src有效，我再根目录创建一个目录，存放vue文件，里面的windicss样式无效

### ISSUE THREAD

**Issue by GavinChain** [anncwb/vue-vben-admin#729]
windicss class貌似只对src有效，我再根目录创建一个目录，存放vue文件，里面的windicss样式无效

**Comment by anncwb** [comment]
可以设置下windicss插件的scan扫描目录，默认是src
![image](https://user-images.githubusercontent.com/28132598/121283145-396af200-c90d-11eb-8dfa-1832b1524b8c.png)

**Comment by GavinChain** [comment]
好的，谢谢
