### ISSUE TITLE
自定义控件里面使用BasicTable报错->ReferenceError: Cannot access 'BasicForm' before initialization     at BasicTable.vue:65

### ISSUE THREAD

**Issue by xietongjian** [anncwb/vue-vben-admin#731]
自定义控件里面使用BasicTable报错：
```
ReferenceError: Cannot access 'BasicForm' before initialization     at BasicTable.vue:65
```

![image](https://user-images.githubusercontent.com/16096832/121283522-dcbc0700-c90d-11eb-97a3-34a27f6d5fe7.png)

我看到你们应该也遇到过。里面有行代码是注释掉的，如果能够解决当然更好。
![image](https://user-images.githubusercontent.com/16096832/121283864-71bf0000-c90e-11eb-99bf-a421536c3d80.png)

**Comment by anncwb** [comment]
因为现在表格内已经使用了Form了，你在Form又实用了Table，所以双向循环出错了

**Comment by xietongjian** [comment]
> 因为现在表格内已经使用了Form了，你在Form又使用了Table，所以双向循环出错了

嗯，明白了，谢谢。
我直接用Antd的表格就可以了。

**Comment by IFnGSiYu** [comment]
Table作为Form的slot高度不自适应，求解决一下
