### ISSUE TITLE
左侧Menu在sidebar模式下，关闭菜单手风琴模式。打开subMenu时会抖动

### ISSUE THREAD

**Issue by Sorwnqe** [anncwb/vue-vben-admin#732]
似乎在已经有一个submenu打开时，去点击另外的subMenu时，菜单会发生跳动，上方已经打开的subMenu有时会自动关闭。
[https://vvbin.cn/next/#/page-demo/desc/basic](https://vvbin.cn/next/#/page-demo/desc/basic)现在就存在这个bug。
设置：
![image](https://user-images.githubusercontent.com/42724987/121286592-9ddc8000-c912-11eb-8ea4-8fa3296b8213.png)

![image](https://user-images.githubusercontent.com/42724987/121286346-450ce780-c912-11eb-8d5a-304f4ec8ec6d.png)

复现步骤->在已打开某个subMenu（例如：权限管理）时，点击打开下方的其他subMenu子项（例如：基础详情页），则上方权限管理会随着点击发生跳动，有时还会自动收起subMenu

**Comment by crazy6995** [comment]
俺也一样。  先用手风琴吧。
