### ISSUE TITLE
引入“ant-design-vue”的FormItem时出错，我明显引入的是2.1.2版本的，可提示时1.7.5？请问什么原因？

### ISSUE THREAD

**Issue by lorenzozozo** [anncwb/vue-vben-admin#734]
![1623231395412](https://user-images.githubusercontent.com/83060885/121331268-4b6a8600-c949-11eb-9d78-31410632231b.jpg)
引入“ant-design-vue”的FormItem时出错，我明显引入的是2.1.2版本的，可提示时1.7.5？请问什么原因？

**Comment by mynetfan** [comment]
请看ant design vue的文档，了解FormItem、SelectOption之类的子组件的用法。
https://2x.antdv.com/components/form-cn#API
你所说的FormItem是Form的子组件Item。
本项目的以下文件也有演示FormItem的用法：
src\views\sys\login\LoginForm.vue
