### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by anncwb** [anncwb/vue-vben-admin#74]
If you have good suggestions or ideas, please feel free to mention them here.

如果您有好的建议或者想法，欢迎在这里提。

**Comment by everstarmy** [comment]
能否考虑将router扁平化，不将layout和router分开写，增加字段showInMenus  showInBreadcrumb。

**Comment by anncwb** [comment]
最新版的layout可以忽略不写。  后续这个我可以加下，自由选择。 showInMenus想了想应该只在后台返回菜单的模式下有效，前台权限模式下只要菜单不写就可以。showInBreadcrumb这个目前面包屑还有点问题，需要在调整下

**Comment by aios** [comment]
Generator of scaffold with mock. 
1. Make 1-3 templates like an a dashboard, tables, etc...
2. Make simple generator with plugins/api for contribute other or someone can write what he want to generate inside (or may be hooks)
3. Make commands for generate
4. Profit)

**Comment by anncwb** [comment]
@aios Are you interested in writing points 2 and 3

**Comment by anncwb** [comment]
@aios I may not have enough time, if you are interested, you can contribute to him

**Comment by aios** [comment]
@anncwb will try)

**Comment by LingJunZhu** [comment]
我觉得IView  Admin Pro 的顶部和标签页可以借鉴下 
https://adminpro.iviewui.com/login  
![image](https://user-images.githubusercontent.com/39548095/102568656-df882d00-411e-11eb-8c4c-338faaabba50.png)

**Comment by harrytran998** [comment]
Why you don't try the auto-import components with Vite? I think it's really useful when having an option in Vite config to enable/disable this feature! It depends on the team, context...

**Comment by mynetfan** [comment]
希望左侧菜单混合模式下可以左侧的菜单支持click、hover两种触发展开的方式，谢谢！

**Comment by anncwb** [comment]
> Why you don't try the auto-import components with Vite? I think it's really useful when having an option in Vite config to enable/disable this feature! It depends on the team, context...

Vite import is not suitable for project use. So I wrote an implementation myself

**Comment by anncwb** [comment]
> 希望左侧菜单混合模式下可以左侧的菜单支持click、hover两种触发展开的方式，谢谢！

可以 下版

**Comment by TrumanWwW** [comment]
大佬，有没有想法出个js版的，ts版的学不动了(非纯前端)

**Comment by anncwb** [comment]
> 大佬，有没有想法出个js版的，ts版的学不动了(非纯前端)

没打算。不想类型校验直接全部写any就一样了。没差

**Comment by anncwb** [comment]
> 希望左侧菜单混合模式下可以左侧的菜单支持click、hover两种触发展开的方式，谢谢！

见 0419a07

**Comment by yuyiRai** [comment]
表单能不能支持一下inline布局
（顺便吐槽一下，学过后端怎么会学不动ts

**Comment by anncwb** [comment]
> 表单能不能支持一下inline布局
> （顺便吐槽一下，学过后端怎么会学不动ts

不支持。可以只用colSpan代替

**Comment by tomasky** [comment]
src/components/Verify/src/DragVerify.tsx
```ts
+      const widthNum = wrapEl.clientWidth; //parseInt(width as string);
```
保证整体宽度适应设备100%

**Comment by jenifly** [comment]
侧边菜单拖拽，这个拖拽功能可不可以单独抽离出一个组件？

**Comment by zhengycsh** [comment]
有webpack的版本么，强烈建议安排一个！！！

**Comment by anncwb** [comment]
> 侧边菜单拖拽，这个拖拽功能可不可以单独抽离出一个组件，支持上下、左右分块，甚至是分多块拖拽？

后面我在加个拖拽组件

**Comment by anncwb** [comment]
> 有webpack的版本么，强烈建议安排一个！！！

没打算

**Comment by jenifly** [comment]
> > 侧边菜单拖拽，这个拖拽功能可不可以单独抽离出一个组件，支持上下、左右分块，甚至是分多块拖拽？
> 
> 后面我在加个拖拽组件

辛苦啦

**Comment by leavest** [comment]
打算升级echarts5.0吗

**Comment by luckdolphin** [comment]
图表可以看下antv

**Comment by anncwb** [comment]
> 打算升级echarts5.0吗

有

**Comment by anncwb** [comment]
> 图表可以看下antv

感觉echarts够了。antv可以自己集成

**Comment by anncwb** [comment]
The discussion has moved to https://github.com/anncwb/vue-vben-admin/discussions/251

**Comment by qingmang** [comment]
![图片](https://user-images.githubusercontent.com/67047984/140481427-7c907763-aacf-4c6b-894f-d67079a49aa7.png)

建议左侧菜单混合模式下 子菜单改为浅色，个人觉得比深色好看
