### ISSUE TITLE
 BasicTable组件作为BasicForm的slot时，BasicTable的高度不会自适应

### ISSUE THREAD

**Issue by IFnGSiYu** [anncwb/vue-vben-admin#744]
<BasicForm @register="register">
        <template #form-Table>
          <BasicTable
            @register="registerTable"
            @edit-end="handleEditEnd"
            @edit-cancel="handleEditCancel"
            @edit-change="handleEditChange"
          >
          </BasicTable>
        </template>
      </BasicForm>

{
    label: '',
    field: 'tabledate',
    component: 'Input',
    slot: 'form-Table',
    // required: true,
    // colProps: {
    //   span: 24,
    //   // offset: 1,
    // },
  },

**Comment by anncwb** [comment]
form里面的table需要自己指定高度
