### ISSUE TITLE
mock中_前缀的文件，没有忽略其中的请求

### ISSUE THREAD

**Issue by GavinChain** [anncwb/vue-vben-admin#745]
![1 EE_UJOVC@~J3$IICB}Y~F](https://user-images.githubusercontent.com/40415260/121490229-67ccf800-ca07-11eb-8ae3-ccbe879d0602.png)

**Comment by M69W** [comment]
https://github.com/anncwb/vue-vben-admin/blob/main/mock/_createProductionServer.ts#L7
改这里试试？
