### ISSUE TITLE
弹窗展示高度在本地运行和打包上线后不一样

### ISSUE THREAD

**Issue by yanduhantan1991** [anncwb/vue-vben-admin#749]
当弹窗中的表单组件过多出现时，本地运行会出现滚动条，线上是都展示出来，滚动这个弹窗。导致现在在本地修改的 样式，上线后无法使用。

**Comment by anncwb** [comment]
给个截图或者复现示例

**Comment by yanduhantan1991** [comment]
![本地](https://user-images.githubusercontent.com/29156295/121652313-19cef780-cace-11eb-840e-acc40e3482e7.png)
![线上](https://user-images.githubusercontent.com/29156295/121652331-1d627e80-cace-11eb-9106-acdddc9deabe.png)

第一个是本地样式，第二个是线上样式

**Comment by yanduhantan1991** [comment]
补充一下，如果是在iframe中运行的话就是第二张图的效果

**Comment by mynetfan** [comment]
你这两张图并不是同一个Modal。另外，仅根据你所提供的信息没能重现问题。

**Comment by anncwb** [comment]
Hello @yanduhantan1991. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.
