### ISSUE TITLE
BasicTable在空数组绑定的情况下，新增后界面不刷新，强制也没用，而实际数据是在内存中的。

### ISSUE THREAD

**Issue by lolysc** [anncwb/vue-vben-admin#752]
以这个为例:page-demo/form/high
datasource绑定了data，当默认的data有行数据的时候，新增按钮有效；但如果默认的data是个空数组，则新增按钮无效，界面不刷新。强制调用实例的forceupdate都不行。

**Comment by mynetfan** [comment]
已获悉此问题。
临时解决方案：在data.push后setTableData(data)
