### ISSUE TITLE
ROLE权限模式隐藏不了外链吗

### ISSUE THREAD

**Issue by moonnow** [anncwb/vue-vben-admin#753]
![1F075AC3FAAADA7BB3CE251C50E02E01](https://user-images.githubusercontent.com/39480435/121692309-8f50bd00-cafa-11eb-9752-d9e09b9a08cd.jpg)
![DC14B737C4F47F5FD873F4EF327FF26B](https://user-images.githubusercontent.com/39480435/121692330-94157100-cafa-11eb-93de-7d21f638e20e.jpg)

**Comment by mynetfan** [comment]
测试正常

**Comment by moonnow** [comment]
![image](https://user-images.githubusercontent.com/39480435/121695772-f4f27880-cafd-11eb-97c9-4522b8d542a2.png)
![image](https://user-images.githubusercontent.com/39480435/121695827-05a2ee80-cafe-11eb-9e6c-e0193d00ff27.png)
我拉最新代码有测试了一次还是不行，正常菜单路由没问题，就是跳转外部链接时候就隐藏不了

**Comment by mynetfan** [comment]
外链菜单不支持角色权限分配

**Comment by moonnow** [comment]
明白了  谢谢
