### ISSUE TITLE
defHttp  requestOptions 新增属性无法覆盖的问题

### ISSUE THREAD

**Issue by yaseiakira** [anncwb/vue-vben-admin#754]
我尝试在defhttp 中的requestOptions 新增一个 custom 属性,当接口请求发生500 错误的时候使用,代码如下:
function createAxios(opt?: Partial<CreateAxiosOptions>) {
  return new VAxios(
    deepMerge(
      {
       ......
        // 配置项，下面的选项都可以在独立的接口请求中覆盖
        requestOptions: {
          custom:'',
          // 默认将prefix 添加到url
          joinPrefix: true,
         ......
        },
      },
      opt || {}
    )
  );
}

// 接口调用
export function someMethod(params, mode: ErrorMessageMode = 'message') {
  return defHttp.post(
    {
      url: apiurl,
      params
    },
    {
      errorMessageMode: mode,
      custom:'some data'
    }
  );
}

// 在 responseInterceptorsCatch 中访问该属性,发现居然还是最开始的初始值,并没有被覆盖
responseInterceptorsCatch: (error: any) => {
   ......
    console.log(error?.response?.config.requstOptions?.custom); // 还是空字符串,而不是 'some data'
    return Promise.reject(error);
  },

**Comment by anncwb** [comment]
custom 这个并没有被合并到请求参数内，可以参考其他的参数用法。
