### ISSUE TITLE
关于多个端口的问题

### ISSUE THREAD

**Issue by nbaiguo** [anncwb/vue-vben-admin#759]
如果后端是微服务的，在本地调试的时候基本是没有网关，直接用端口的，这样的话在配置文件里面要怎么配置多个代理的，我试了下用 VITE_PROXY = [["/connect","http://localhost:8081"],["/upload","http://localhost:3300/upload"]] 不行的。

**Comment by mynetfan** [comment]
1、保持VITE_GLOB_API_URL为空
2、每个对接口的访问加上前缀/connect1、/connect2、/connect3……
3、VITE_PROXY = [["/connect1","http://localhost:8081"],["/connect2","http://localhost:8082"],["/connect3","http://localhost:8083"],["/upload","http://localhost:3300/upload"]]

**Comment by anncwb** [comment]
Hello @nbaiguo. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by minilite** [comment]
我在重新保存热更新时报以下错误：
[vite] http proxy error:
Error: Must provide a proper URL as target
