### ISSUE TITLE
表格组件功能开发

### ISSUE THREAD

**Issue by Layczm** [anncwb/vue-vben-admin#76]
名称：表格组件
描述：表格组件看你都封装得差不多了，在想能不能顺便把弹框表单编辑及工具类的新增，导入，导出，批量操作这些都完善下
在线参考示例: https://xuliangzhan_admin.gitee.io/vxe-table/v4/table/advanced/template#/table/advanced/popupEdit

**Comment by aios** [comment]
**Translate to en:**
Name: Form component
Description: You can see that the form components are almost encapsulated. I wonder if you can add pop-up form editing and tools to add, import, export, and batch operations.
Online reference example: https://xuliangzhan_admin.gitee.io/vxe-table/v4/table/advanced/template#/table/advanced/popupEdit

**Comment by zhenzhenChange** [comment]
表格的功能，看过一个 AVue 的，也挺丰富。
还有它的表单，集成了超级多的东西。
https://avuejs.com/doc/form/form-doc
好想要啊好像要~
