### ISSUE TITLE
同一浏览器能登录两个不同的用户？

### ISSUE THREAD

**Issue by xucaiming** [anncwb/vue-vben-admin#761]
同一个浏览器能开两个窗口分别登录不同的用户？ 这样数据不会篡数据吗？ 然后用户登录后将浏览器 url 改成 /login 也没有跳转到首页，希望解决一下这个问题！

**Comment by M69W** [comment]
正常来说，不能解决这个问题

**Comment by mynetfan** [comment]
> 正常来说，不能解决这个问题
> 
> 重现步骤：
> 
> ```
> 1. 右上角头像，锁定屏幕，
> 2. 当前页面正常锁定，
> 3. 复制当前 链接url，当前浏览器，新打开窗口粘贴之前打开的url，之前的锁定效果失效。
> ```

fixed in https://github.com/anncwb/vue-vben-admin/commit/d7b84c78744f7d0077a779b232e1358040b50383
