### ISSUE TITLE
开启多标签页面缓存，多个页面公用组件不刷新

### ISSUE THREAD

**Issue by W-ambition** [anncwb/vue-vben-admin#763]
### Describe the bug

当多个页面开启页面缓存，这些页面存在公用组件，当其中一个页面打开后，其他页面再打开，他们的公用组件不会重新加载，用的都是第一个页面的缓存数据。
怎样才能让这些公用组件在不同的页面下都重新加载？

**Comment by anncwb** [comment]
可以给个示例或者复现步骤？

**Comment by anncwb** [comment]
Hello @W-ambition. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.
