### ISSUE TITLE
富文本插件 Failed to resolve import "tinymce/tinymce

### ISSUE THREAD

**Issue by java8site** [anncwb/vue-vben-admin#769]
使用的是精简版，form表单使用富文本插件时候报 
Failed to resolve import "tinymce/tinymce" from "src\components\Tinymce\src\Editor.vue". Does the file ex
ist

**Comment by anncwb** [comment]
精简版的依赖是被删除了，可以参考完整版本把依赖装一下，`yarn add tinymce `
