### ISSUE TITLE
表格用setProps动态设置pageSize后没有变化

### ISSUE THREAD

**Issue by IFnGSiYu** [anncwb/vue-vben-admin#777]
setProps({
          title: '账号列表11',
          api: getAccountList,
          columns,
          formConfig: {
            labelWidth: 120,
            schemas: searchFormSchema,
          },
          useSearchForm: true,
          showTableSetting: false,
          bordered: true,
          pagination: {
            pageSize: 20,
          },
          actionColumn: {
            width: 280,
            title: '操作',
            dataIndex: 'action',
            slots: { customRender: 'action' },
          },
        });

**Comment by mynetfan** [comment]
设置分页相关的数据，请使用setPagination
