### ISSUE TITLE
TableAction 怎样使用权限控制actions列的显示和隐藏？使用PermissionCode

### ISSUE THREAD

**Issue by gudufy** [anncwb/vue-vben-admin#778]
### Problem

TableAction 怎样使用权限控制actions列的显示和隐藏？使用PermissionCode

**Comment by zuihou** [comment]
![image](https://user-images.githubusercontent.com/8500410/123135176-13ecf500-d484-11eb-8eb5-0fe3d9efc2c6.png)


auth 配置成对应的 权限编码 
判断逻辑在：

hasPermission(value?: RoleEnum | RoleEnum[] | string | string[], def = true)

**Comment by anncwb** [comment]
@zuihou 这个能麻烦在文档加下吗，给你文档仓库权限了
