### ISSUE TITLE
vuex的书写方式？

### ISSUE THREAD

**Issue by nikolausliu** [anncwb/vue-vben-admin#78]
想请教下作者，vuex如果想用ts，除了vuex-module-decorators装饰器那种写法，还有别的组织方式吗？感觉那样写着太难受了

**Comment by anncwb** [comment]
可以使用vuex的useStore来进行书写。

**Comment by anncwb** [comment]
这点其实我一开始没想好就用了。  后续可能会优化下，尽量配合最新的vuex4写法

**Comment by nikolausliu** [comment]
@anncwb 好的，蟹蟹
