### ISSUE TITLE
登录后再刷新页面，router.beforeEach里面的逻辑执行了两遍

### ISSUE THREAD

**Issue by xucaiming** [anncwb/vue-vben-admin#780]
登录后再刷新页面，router.beforeEach里面的逻辑执行了两遍，不知道是不是No match found for location with path "/dashboard/analysis"这个警告导致，请问这个问题怎么解决？已经被这个问题困住了几天了。。。谢谢大佬指点迷津！
![image](https://user-images.githubusercontent.com/34827768/122627503-78096500-d0e2-11eb-975d-8ad0450e99f2.png)

**Comment by xucaiming** [comment]
还有个问题就是 router.addRoute 为什么要放在 router.beforeEach里面执行？ 这样的话每次路由跳转都会执行一次 router.addRoute影响前端性能。为什么不把router.addRoute逻辑单独抽离出来执行?

**Comment by mynetfan** [comment]
不要大惊小怪。执行两次是因为重定向的原因
