### ISSUE TITLE
整体交互动画在Mac端卡顿

### ISSUE THREAD

**Issue by 13076079291** [anncwb/vue-vben-admin#782]
整体交互动画在Mac端卡顿

**Comment by M69W** [comment]
可否提供视频 或 相应的电脑配置？

**Comment by 13076079291** [comment]
> 可否提供视频或相应的电脑配置？

MacBook Pro 2018款 15.6英寸 16G运行 256G固态 i7处理器 4G独立显卡。只有在Chrome上会出现卡顿问题。其他Safari和打包的客户端都不会出现很明显的卡顿 Chrome版本：91.0.4472.106

**Comment by 13076079291** [comment]
> 可否提供视频 或 相应的电脑配置？

视频我发到群里了

**Comment by bihell** [comment]
@13076079291  是卡的,我都卡习惯了.好在正式部署就没啥问题
