### ISSUE TITLE
Cropper 组件如何在Form使用

### ISSUE THREAD

**Issue by zuihou** [anncwb/vue-vben-admin#783]
1、Cropper 组件如何在Form使用？ 简单看了下源码，是否并没有封装到Form组件中。 

2、自己尝试着，参考Upload组件对Cropper进行简单修改，遇到一个问题：Cropper内的value值无法和表单上的参数进行绑定。 能否解释下Upload组件的value值是如何在表单上的value绑定起来的？

**Comment by anncwb** [comment]
目前没放到form内，现在的样式感觉并不适合放在表单内部

**Comment by mynetfan** [comment]
> 1、Cropper 组件如何在Form使用？ 简单看了下源码，是否并没有封装到Form组件中。
> 
> 2、自己尝试着，参考Upload组件对Cropper进行简单修改，遇到一个问题：Cropper内的value值无法和表单上的参数进行绑定。 能否解释下Upload组件的value值是如何在表单上的value绑定起来的？

表单组件的值起作用必须满足2点：
1、有名为value的prop，用于给组件设置值
2、会抛出change事件，参数为组件的当前新值
