### ISSUE TITLE
后台加载菜单支持问号路由参数

### ISSUE THREAD

**Issue by 734839030** [anncwb/vue-vben-admin#786]
测试时候path上加参数会报404，需求是希望给客户功能丰满，一个模块可以配置多个菜单，然后通过路由参数控制一些差异性。
![image](https://user-images.githubusercontent.com/12107198/122702483-0d8f2b00-d282-11eb-97e5-23423d41b5b3.png)

**Comment by mynetfan** [comment]
请使用类似下面的方法定义路由：
```
{path:'/sys/param/:type'}
```

**Comment by mynetfan** [comment]
参考Demo:
https://vvbin.cn/next/#/feat/testTab/id1

**Comment by crazy6995** [comment]
@734839030 

估计可以参考这个玩意儿，目前只做了基于 params 的。
#824

**Comment by thinkershare** [comment]
> 请使用类似下面的方法定义路由：
> 
> ```
> {path:'/sys/param/:type'}
> ```

这个模式导航菜单和面包屑菜单都无法按照预期工作

**Comment by crazy6995** [comment]
@734839030 已提交pr，支持参数菜单（路由），但目前仅能支持params形式。改改也能支持query #845

**Comment by thinkershare** [comment]
> @734839030 已提交pr，支持参数菜单（路由），但目前仅能支持params形式。改改也能支持query #845

感谢,

**Comment by 734839030** [comment]
> @734839030 已提交pr，支持参数菜单（路由），但目前仅能支持params形式。改改也能支持query #845

thanks
