### ISSUE TITLE
打包后antd样式重复

### ISSUE THREAD

**Issue by JoyZ1122** [anncwb/vue-vben-admin#788]
抱歉！我重新编辑下问题
场景：全局引入了antd所以和configStyleImportPlugin 局部导入样式重复了 但是我注释了局部导入代码 打包运行会报错 请问我应该怎么解决

**Comment by anncwb** [comment]
我在测试环境并没有看到，可以提供下复现步骤？

**Comment by anncwb** [comment]
Hello @JoyZ1122. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by M69W** [comment]
可以重现，

![image](https://user-images.githubusercontent.com/15809201/123498619-b9aa8a80-d663-11eb-8078-64894607885a.png)
![image](https://user-images.githubusercontent.com/15809201/123498627-c4fdb600-d663-11eb-9dbe-c0594954b5d3.png)
![image](https://user-images.githubusercontent.com/15809201/123498634-d5ae2c00-d663-11eb-8773-2a3dc382a7df.png)
