### ISSUE TITLE
在template根节点下注释，会导致跳转不了其他界面

### ISSUE THREAD

**Issue by snhwv** [anncwb/vue-vben-admin#79]
### Subject of the issue

在template根节点下注释，会导致跳转不了其他界面。

![image](https://user-images.githubusercontent.com/31102731/98114787-bd28b000-1ee0-11eb-887d-18beeed3fd84.png)

比如现在在基础表格界面，点击菜单栏“树形表格”，会一直loading。

![image](https://user-images.githubusercontent.com/31102731/98115412-c0706b80-1ee1-11eb-8b85-6bd4e9e2c03e.png)

**Comment by anncwb** [comment]
动画标签 下template下面只要保证一个根节点  注释也不行
