### ISSUE TITLE
在BasicModal中嵌套BasicTable，两者高度均未能正确显示

### ISSUE THREAD

**Issue by jenifly** [anncwb/vue-vben-admin#791]
具体表现：
![image](https://user-images.githubusercontent.com/22962492/122852437-30cddf00-d343-11eb-981f-02b6a98a8079.png)
![image](https://user-images.githubusercontent.com/22962492/122852268-eba9ad00-d342-11eb-91f5-b748d74a1d4f.png)

```
<template>
  <BasicModal
    v-bind="$attrs"
    @register="register"
    width="90%"
    :height="732"
    :title="titleRef"
    :useWrapper="false"
    :footer="null"
    centered
    @visibleChange="visibleChange"
  >
    <BasicTable @register="registerTable">
      <template #clear="{ record }">
        <AButton size="small" type="link" color="error" @click=""
          ><Icon icon="ant-design:minus-square-outlined"
        /></AButton>
      </template>
      <template #action="{ record }">
        <TableAction :actions="createActions(record)" />
      </template>
    </BasicTable>
    <Modal @register="registerModal" />
  </BasicModal>
</template>
```

```
const [registerTable, { getColumns, setColumns, reload, setTableData }] = useTable({
      ...
      inset: true,
      maxHeight: 680,
    });
```
数据加载：
![image](https://user-images.githubusercontent.com/22962492/122852632-85715a00-d343-11eb-8651-16d2548aad2a.png)

**Comment by mynetfan** [comment]
我认为你这里应当给modal内的table一个固定height而不是maxHeight，或者关闭modal的自适应高度。可能是表格的不确定高度和modal的自适应高度不能兼容

**Comment by jenifly** [comment]
> 我认为你这里应当给modal内的table一个固定height而不是maxHeight，或者关闭modal的自适应高度。可能是表格的不确定高度和modal的自适应高度不能兼容

f12这样的...不晓得一个为啥一个高度是6百多，一个才一百多
![image](https://user-images.githubusercontent.com/22962492/122854012-ae92ea00-d345-11eb-8a48-232db248485c.png)
![image](https://user-images.githubusercontent.com/22962492/122854122-d08c6c80-d345-11eb-9e54-e739e4f81ee4.png)

**Comment by mynetfan** [comment]
请不要同时启用Modal的自适应高度和内部table的自适应高度再试

**Comment by jenifly** [comment]
> 请不要同时启用Modal的自适应高度和内部table的自适应高度再试

嗯嗯，感谢，我更新到3.x，然后设一下表格的canResize，就行了。之前2.3中canResize没有用

**Comment by jenifly** [comment]
但是canResize设置为false后，maxHeight属性失效了。表格垂直滚动条不再出现。表格高度大于父容器时撑开父容器的滚动条，滚动时表格标题栏会随之滚动

**Comment by mynetfan** [comment]
Modal中的表格需要给定高度，不能自适应。你需要给一个height

**Comment by jenifly** [comment]
BasicTable没有height这个属性，ant的table组件也没有。如果height直接加在标签上没有意义呀

**Comment by mynetfan** [comment]
我说的给一个height指的是固定表头，设置scroll。比如：
```
  <BasicTable
    ...
        :scroll: "{ y: 400 }",
        :canResize: "false",
  />
```
这样就相当于给了表格高度

**Comment by anncwb** [comment]
@jenifly 如 @mynetfan 所说，现在的modal和表格都是响应式高度，需要关闭其中一个的响应式，否则会导致高度错误。

**Comment by jenifly** [comment]
嗯嗯，但我发现问题在获取数据这里，不管我如何关闭响应式都有问题。
之前获取数据：
![image](https://user-images.githubusercontent.com/22962492/123354528-70403980-d596-11eb-9e4e-20aa9c5eb78a.png)
修改之后：
![image](https://user-images.githubusercontent.com/22962492/123354742-d0cf7680-d596-11eb-8de3-9b0cf30693b2.png)
然后关闭一个响应式就没有问题了，获取数据好像是得错开，哪怕给1ms也不会出现问题。
