### ISSUE TITLE
优化tree组件遍历函数支持批量插入子节点

### ISSUE THREAD

**Issue by bbkkkk8** [anncwb/vue-vben-admin#793]
### Subject of the feature
优化tree组件遍历函数支持批量插入子节点
### Problem

1. 当树节点非常大的时候，插入节点的函数出现性能不佳
2. api仅提供了插入单个子节点，插入多个节点重复调用性能较差

### Expected behaviour

1. 在treeHelper forEach中及时终止遍历
2. 提供批量插入node api

### Alternatives
1 .treeHelper forEach 修改
export function forEach<T = any>(
  tree: T[],
  func: (n: T) => any,
  config: Partial<TreeHelperConfig> = {}
): void {
  config = getConfig(config);
  const list: any[] = [...tree];
  const { children } = config;
  for (let i = 0; i < list.length; i++) {
    //func 返回true就终止遍历，避免无意义循环
    if (func(list[i])) {
      return;
    }
    children && list[i][children] && list.splice(i + 1, 0, ...list[i][children]);
  }
}

2. useTree添加批量插入node api

  /**
   * 批量添加子节点
   * 发现 forEach有性能问题，每个节点非得走一遍，无法终止
   */
  function insertNodesByKey({ parentKey = null, list, push = 'push' }: InsertNodeParams) {
    const treeData: any = cloneDeep(unref(treeDataRef));
    if (!list || list.length < 1) {
      return;
    }
    if (!parentKey) {
      for (let i = 0; i < list.length; i++) {
        treeData[push](list[i]);
      }
    } else {
      const { key: keyField, children: childrenField } = unref(getReplaceFields);
      if (!childrenField || !keyField) return;

      forEach(treeData, (treeItem) => {
        if (treeItem[keyField] === parentKey) {
          treeItem[childrenField] = treeItem[childrenField] || [];
          for (let i = 0; i < list.length; i++) {
            treeItem [childrenField]  [push]  (list[i]);
          }
          treeDataRef.value = treeData;
          return true;
        }
      });
    }
  }

**Comment by anncwb** [comment]
欢迎提交一个pr来解决这个问题，目前没有适当的场景来测试你的这个问题，所以最好可以帮忙弄一个pr

**Comment by anncwb** [comment]
close d97aa92
