### ISSUE TITLE
表格分页条抖动的问题

### ISSUE THREAD

**Issue by init-center** [anncwb/vue-vben-admin#794]
表格的分页条一直在抖动，目前在我的电脑上是开启了搜索表单区域以后并且windows缩放125%时会出现这个问题，表格的高度是否一直在计算？
电脑 HP ProBook 440 G8 NoteBook PC，1920x1080分辨率，125%缩放下。
打开这个页面可复现：https://vvbin.cn/next/#/comp/table/formTable

**Comment by anncwb** [comment]
closed 8eba7fb52786d1977e4cb7b67673d74c91c5c827

**Comment by JerryJeck** [comment]
pr:https://github.com/vbenjs/vue-vben-admin/pull/2125 ，
