### ISSUE TITLE
Table新增了一个属性isShowEditIcon，判断是否显示编辑单元格后面的√和×图标，有些时候并不需要这两个图标，楼主觉得有必要可以加上

### ISSUE THREAD

**Issue by IFnGSiYu** [anncwb/vue-vben-admin#795]
//EditableCell.vue      
const getRowEditable = computed(() => {
        const { editable } = props.record || {};
        const { isShowEditIcon } = props.column || {};
        return isShowEditIcon ? !!editable : !isShowEditIcon;
        // return !!editable;
      });

**Comment by mynetfan** [comment]
多数编辑组件需要图表来提交或者撤销操作。少量类似于checkbox或者switch之类的编辑组件，可直接使用slot自定义单元格渲染。
