### ISSUE TITLE
TableAction 下拉按钮点击失效！

### ISSUE THREAD

**Issue by fengbindev** [anncwb/vue-vben-admin#796]
当我开启表格列勾选后，表格的TableAction下拉按钮点击失效，并且不断弹出警告。
效果如下所示：
![image](https://user-images.githubusercontent.com/28595220/122943301-7cb36f00-d3a9-11eb-93fc-dd9d017fce57.png)

我的表格代码如下：
![image](https://user-images.githubusercontent.com/28595220/122943513-ac627700-d3a9-11eb-9f3b-63a333b37eeb.png)
![image](https://user-images.githubusercontent.com/28595220/122943599-bc7a5680-d3a9-11eb-9223-b8ff9714a650.png)

**Comment by mynetfan** [comment]
警告是ant design vue和vue版本的兼容问题，目前请无视这些警告。
但你说的点击失效我测试没有问题，请检查自己的代码。

**Comment by fengbindev** [comment]
> 警告是ant design vue和vue版本的兼容问题，目前请无视这些警告。
> 但你说的点击失效我测试没有问题，请检查自己的代码。

我仔细检查了代码，还是没发现哪里有问题，我不确定是否是我写错了，我上传了我的代码，如果有时间，请帮我看一下是不是我哪里写的有问题，十分感谢。
`
<template>
  <PageWrapper dense contentFullHeight fixedHeight contentClass="flex">
    <DeptTree class="w-1/4 xl:w-1/5" @select="handleSelect" />
    <BasicTable @register="registerTable" class="w-3/4 xl:w-4/5">
      <template #toolbar>
        <a-button type="primary" @click="handleCreate">新增账号</a-button>
        <a-button
          :loadingEnabled="loadingEnabled"
          type="primary"
          @click="handleEnableBatch"
          :disabled="getSelectRowKeys().length == 0"
          >启用</a-button
        >
        <a-button
          :loadingDisabled="loadingDisabled"
          type="primary"
          @click="handleDisabledBatch"
          :disabled="getSelectRowKeys().length == 0"
          >禁用</a-button
        >
        <a-button
          :loadingDel="loadingDel"
          color="error"
          @click="handleDeleteBatch"
          :disabled="getSelectRowKeys().length == 0"
          >删除</a-button
        >
      </template>
      <template #action="{ record }">
        <TableAction
          :actions="[
            {
              icon: 'ion:git-compare-outline',
              onClick: handlePermission.bind(null, record),
            },
            {
              icon: 'clarity:note-edit-line',
              onClick: handleEdit.bind(null, record),
            },
          ]"
          :dropDownActions="[
            {
              label: '删除',
              color: 'error',
              popConfirm: {
                title: '是否确认删除',
                confirm: handleDelete.bind(null, record),
              },
            },
            {
              label: '修改密码',
              onClick: handleModifyPassword.bind(null, record),
            },
          ]"
        />
      </template>
    </BasicTable>
    <UserModal @register="registerModal" @success="handleSuccess" />
    <MenuPermissionModal @register="permissionRegisterModel" />
  </PageWrapper>
</template>
<script lang="ts">
  import { defineComponent, ref } from 'vue';

  import { BasicTable, useTable, TableAction } from '/@/components/Table';
  import { getUserListByPage, setUserStatus, deleteUser } from '/@/api/system/system';
  import { PageWrapper } from '/@/components/Page';
  import DeptTree from './DeptTree.vue';

  import { useModal } from '/@/components/Modal';
  import UserModal from './UserModal.vue';
  import MenuPermissionModal from '../components/MenuPermissionModal.vue';

  import { columns, searchFormSchema } from './user.data';

  export default defineComponent({
    name: 'UserManager',
    components: {
      BasicTable,
      PageWrapper,
      DeptTree,
      UserModal,
      TableAction,
      MenuPermissionModal,
    },
    setup() {
      let loadingEnabled = ref(false);
      let loadingDisabled = ref(false);
      let loadingDel = ref(false);
      const [registerModal, { openModal }] = useModal();
      const [registerTable, { reload, getSelectRowKeys }] = useTable({
        title: '账号列表',
        api: getUserListByPage,
        rowKey: 'userName',
        columns,
        formConfig: {
          labelWidth: 120,
          schemas: searchFormSchema,
        },
        useSearchForm: true,
        showTableSetting: true,
        bordered: true,
        rowSelection: {
          type: 'checkbox',
        },
        actionColumn: {
          width: 120,
          title: '操作',
          dataIndex: 'action',
          slots: { customRender: 'action' },
        },
      });

      function handleCreate() {
        openModal(true, {
          isUpdate: false,
        });
      }

      function handleEdit(record: Recordable) {
        openModal(true, {
          record,
          isUpdate: true,
        });
      }

      async function handleDelete(record: Recordable) {
        await deleteUser(record.userName);
        reload();
      }

      function handleModifyPassword() {}

      async function handleEnableBatch() {
        loadingEnabled.value = true;
        await setUserStatus(getSelectRowKeys().join(), true);
        reload();
        loadingEnabled.value = false;
      }

      async function handleDisabledBatch() {
        loadingDisabled.value = true;
        await setUserStatus(getSelectRowKeys().join(), false);
        reload();
        loadingDisabled.value = false;
      }

      async function handleDeleteBatch() {
        loadingDel.value = true;
        await deleteUser(getSelectRowKeys().join());
        reload();
        loadingDel.value = false;
      }

      function handleSuccess() {
        reload();
      }

      function handleSelect(branchInnercode = '') {
        reload({ searchInfo: { branchInnercode } });
      }
      /***************************权限范围Modal***********************************/

      const [permissionRegisterModel, permissionModalMethods] = useModal();

      function handlePermission(record: Recordable) {
        permissionModalMethods.openModal(true, { id: record.userName, type: 'U' });
      }

      return {
        registerTable,
        registerModal,
        getSelectRowKeys,
        handleCreate,
        handleEdit,
        handleDelete,
        handleSuccess,
        handleSelect,
        permissionRegisterModel,
        handlePermission,
        handleModifyPassword,
        handleEnableBatch,
        handleDisabledBatch,
        handleDeleteBatch,
        loadingEnabled,
        loadingDisabled,
        loadingDel,
      };
    },
  });
</script>
`

**Comment by fengbindev** [comment]
> 警告是ant design vue和vue版本的兼容问题，目前请无视这些警告。
> 但你说的点击失效我测试没有问题，请检查自己的代码。
TableAction组件，下拉按钮空白处点击无用，必须点击到文字才行。拉取最新代码2.5.0测试，如下图所示，空白处点击无效。
![image](https://user-images.githubusercontent.com/28595220/123102807-01fd5900-d468-11eb-8068-d94d66d1b703.png)

**Comment by mynetfan** [comment]
未能重现，测试没有问题。

**Comment by fengbindev** [comment]
> 未能重现，测试没有问题。

修改FixedColumn.vue文件，增加以下代码，然后点击第一个按钮空白处试试。
`{
              label: '启用启用启用启用',
              popConfirm: {
                title: '是否启用？',
                confirm: handleOpen.bind(null, record),
              },
            },`
![image](https://user-images.githubusercontent.com/28595220/123105033-075ba300-d46a-11eb-827b-93e8c14f8d3e.png)
