### ISSUE TITLE
table使用form表单筛选时候select在添加mode:multiple时候有问题

### ISSUE THREAD

**Issue by brandyjoxic** [anncwb/vue-vben-admin#797]
这边有个需求，就是表格筛选下拉框需要多选，于是用了select的多选功能
然后发现table这边在接口筛选的时候，就不会如期正常添加对应的参数
![1624417853(1)](https://user-images.githubusercontent.com/30428285/123029759-35ae9380-d414-11eb-82e7-aedb14498187.png)
虽然可以通过beforeFetch来达到目的，但是这就一点都不好了
还是想把basicForm里相关的地方和table的dataSource那里调教好来解决这个问题，不过找到要改的位置还是比较费劲的，我还在找怎么改这里。暂且还是先提交给你们~

**Comment by mynetfan** [comment]
其实这就是数组参数的传输方式，没有问题。

**Comment by anncwb** [comment]
get方式这个是正常的
