### ISSUE TITLE
 .git can't be found,husky也许这个只是开发人员在使用，小白的话会觉得莫名其妙，不能安装依赖,也许可以写在文档中

### ISSUE THREAD

**Issue by GavinChain** [anncwb/vue-vben-admin#799]
.git can't be found,husky也许这个只是开发人员在使用，小白的话会觉得莫名其妙，不能安装依赖
,也许可以写在文档中,比如如果安装失败，那么请git init一下

**Comment by anncwb** [comment]
文档可以好好翻一翻在开始，https://vvbin.cn/doc-next/guide/#%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96

**Comment by xixichensh** [comment]
机智如楼主
