### ISSUE TITLE
富文本引入 请求链接错误

### ISSUE THREAD

**Issue by weizheng1992** [anncwb/vue-vben-admin#80]
![14019169C501A3F130FD452A081390EC](https://user-images.githubusercontent.com/10727313/98214361-5d361600-1f81-11eb-80d9-8b82e6d250b0.jpg)
你写的例子没问题  
我引入 什么也没改  链接错误了

**Comment by weizheng1992** [comment]
suffix: '.min',
 base_url: CDN_URL,

**Comment by anncwb** [comment]
> suffix: '.min',
> base_url: CDN_URL,

我补一下

**Comment by ximo-156** [comment]
> > 后缀：'.min'，
> > base_url：CDN_URL，
> 
> 我补一下

这个是补充在哪里的

**Comment by ximo-156** [comment]
![image](https://github.com/vbenjs/vue-vben-admin/assets/117827636/ae9c9e82-95b4-44fd-be24-e3ce77da9b48)


> > > 后缀：'.min'，
> > > base_url：CDN_URL，
> > 
> > 
> > 我补一下
> 
> 这是补充在哪里的

![image](https://github.com/vbenjs/vue-vben-admin/assets/117827636/0b206eae-f016-475b-ab46-fee4ed58d888)

**Comment by ximo-156** [comment]
> > > 后缀：'.min'，
> > > base_url：CDN_URL，
> > 
> > 
> > 我补一下
> 
> 这是补充在哪里的

![image](https://github.com/vbenjs/vue-vben-admin/assets/117827636/e4f29694-8732-499d-8d07-d72a43a730ae)
