### ISSUE TITLE
tailwind内边距，外边距无效

### ISSUE THREAD

**Issue by GavinChain** [anncwb/vue-vben-admin#800]
tailwind内边距，外边距无效

**Comment by anncwb** [comment]
可以给个代码，如果不是项目的问题，可以带tailwind提问

**Comment by anncwb** [comment]
Hello @GavinChain. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by bangxingni** [comment]
/src/design/tailwind.css  加入 

/*! @import */
@tailwind base;
@tailwind components;
@tailwind utilities;

**Comment by crazy6995** [comment]
> /src/design/tailwind.css 加入
> 
> /*! @import */
> @tailwind base;
> @tailwind components;
> @tailwind utilities;

已解决，感谢。

**Comment by dlbqianduan** [comment]
”tailwind内边距，外边距无效"这个问题怎么解决啊？该有的配置都有了，之前用的windicss, 更新之后用tailwindcss就是不生效
