### ISSUE TITLE
表格列在设置fixed后，出现空白列

### ISSUE THREAD

**Issue by jenifly** [anncwb/vue-vben-admin#808]
在不设置fixed时，列宽是自动充满整个表格宽度，当有一个列被设置fixed时，列宽成了实际设置的宽度，留出了空白列
![image](https://user-images.githubusercontent.com/22962492/123355852-12612100-d599-11eb-8ae0-84151f9e86dc.png)
如果不设置列宽，这个空白列会被未设置列宽的列填满，但是如果表格宽度不够显示所有列的时候，未设置列宽的列其列宽直接为0，导致不可见。
能否给列加一个minWidth属性，或者提供一个属性控制是否让剩余列占满剩余宽度

**Comment by mynetfan** [comment]
这种情况需要设置scroll:{x:???}，给表格设置一个横向的滚动宽度。???的取值应当为所有有确定宽度的列的宽度的总和（包括固定列）再加上你想要为弹性宽度列所保留的最小宽度。

**Comment by jenifly** [comment]
嗯嗯，这样相当于给弹性列留出了空间。
但是如果我有多个弹性列，又想给弹性列宽度按一个比例分摊；又或者如果我想将空白的地方的宽度，按列宽比例分配到各个列上该怎么操作列？
