### ISSUE TITLE
菜单配置项(不是路由的)提供了hideMenu和disabled选项，但是并不生效

### ISSUE THREAD

**Issue by brandyjoxic** [anncwb/vue-vben-admin#810]
文档里,menu有提供这两个配置项，但是看到代码里计算是否显示菜单的时候并没有把menu相关的加进去，只加了路由的配置

在simpleSubMenu.vue下建议将下面这句话改下，至少hideMenu就生效了
`const getShowMenu = computed(() => !props.item?.meta?.hideMenu);`
改为
`const getShowMenu = computed(() => !props.item?.meta?.hideMenu && !props.item?.hideMenu);`

disabled暂时没看到相关代码，期待你们的下次完善

另：你们的权限控制只针对了路由，没有针对菜单，未来会对菜单进行权限控制吗（主要是同一路由，传参不同的菜单要权限配置，这个路由里没法同步办到）

再次感谢~！

**Comment by anncwb** [comment]
可以切换成路由映射菜单模式就可以了
