### ISSUE TITLE
导航栏模式-顶部菜单栏模式在src/settings/projectSettings.ts内设置无效

### ISSUE THREAD

**Issue by GlassesWu** [anncwb/vue-vben-admin#819]
如题：
在src/settings/projectSettings.ts内设置menuSetting对象字段type值为MenuTypeEnum.TOP_MENU时启动项目不生效，导航栏为SIDEBAR设置，同时setting按钮在导航栏消失，设置为MenuTypeEnum.SIDEBAR、MenuTypeEnum.MIX、MenuTypeEnum.MIX_SIDEBAR时正常

**Comment by mynetfan** [comment]
```
    // Menu mode
    mode: MenuModeEnum.HORIZONTAL,
    // Menu type
    type: MenuTypeEnum.TOP_MENU,
```

这是顶栏菜单的配置。如果你不理解配置项，请使用设置Drawer中提供的“拷贝”功能。
