### ISSUE TITLE
表格中的单元格修改BUG

### ISSUE THREAD

**Issue by zn98com** [anncwb/vue-vben-admin#82]
![qa](https://user-images.githubusercontent.com/10260081/98434235-e6c42000-2108-11eb-9bb7-2284e6d1cc95.png)

![3](https://user-images.githubusercontent.com/10260081/98434250-0e1aed00-2109-11eb-912f-a4df3d16db9c.png)

![4](https://user-images.githubusercontent.com/10260081/98434256-1c690900-2109-11eb-9167-f15daf4d1196.png)

**Comment by anncwb** [comment]
rowKey为id 需要是字符串类型
