### ISSUE TITLE
请问使用useTable的时候怎么设置分页数量

### ISSUE THREAD

**Issue by 6155952** [anncwb/vue-vben-admin#821]
![image](https://user-images.githubusercontent.com/56713496/123627658-d8b44280-d844-11eb-9f03-148c9db41aaa.png)
如图，这边一直显示的10条，请问这个字段属性要在哪里设置才能显示正确的数量呢

**Comment by bihell** [comment]
src/settings/componentSetting.ts

defaultPageSize: 10,

**Comment by 6155952** [comment]
> src/settings/componentSetting.ts
> 
> defaultPageSize: 10,

找到啦，谢谢回复

**Comment by linjiade627** [comment]
> src/settings/componentSetting.ts
> 
> defaultPageSize: 10,

修改这个参数是全局都受影响。如果我想仅仅设置某个页面上某个表格的默认页数为5，该怎么设置呢？

**Comment by M69W** [comment]
好像是这样？
```
<BasicTable
  @change="getPagination"
>

getPagination (pagination) {
  console.dir(pagination)
  pagination.pageSize = 2
}
```
