### ISSUE TITLE
modal destroyOnClose无效

### ISSUE THREAD

**Issue by snowchenlei** [anncwb/vue-vben-admin#822]
1.
modal destroyOnClose无效。
modal打开后点击关闭，文本框的内容不会被清空。
2.
`openModal(true);`不传第二个参数在modal页面无回调，无法做初始化。
create/edit共用页面需要根据参数进行初始化数据。
``` html
 <BasicModal
    v-bind="$attrs"
    @register="register"
    :title="userId === '' ? t('AbpIdentity.NewRole') : t('AbpIdentity.Edit')"
  >
    <a-form layout="vertical" :model="formState">
      <a-form-item :label="t('AbpIdentity.RoleName')">
        <a-input v-model:value="formState.name" :placeholder="t('AbpIdentity.RoleName')" />
      </a-form-item>
      <a-form-item>
        <a-checkbox v-model:checked="formState.isDefault" name="isDefault">
          {{ t('AbpIdentity.DisplayName:IsDefault') }}
        </a-checkbox>
      </a-form-item>
      <a-form-item>
        <a-checkbox v-model:checked="formState.isPublic" name="isPublic">
          {{ t('AbpIdentity.DisplayName:IsPublic') }}
        </a-checkbox>
      </a-form-item>
    </a-form>
  </BasicModal>
```
3. 
modal点击确定后当前页面也无法根据modal页面的处理结果进行操作
![image](https://user-images.githubusercontent.com/26211283/123728974-ca0e6f80-d8c6-11eb-8ef0-c0493c48d038.png)
这三个事件无法满足。因为需要modal页面api提交成功后当前页面才做操作

**Comment by mynetfan** [comment]
1. destroyOnClose 经测试有效。
2. openModal不穿第二个参数，请问你如何在modal中得知当前是create还是edit？？？
3. modal中api提交成功后你需要自己抛出自定义的事件由父组件捕获。modal提供的只是自身事件。
相关问题，Demo中都有演示，请查看Demo

**Comment by snowchenlei** [comment]
有效关闭后文本框内容为什么没有被清空？destroyOnClose的功能不是这个作用？
没有传id就是create有就是edit

**Comment by mynetfan** [comment]
我测试destroyOnClose已按预期工作。如果你的异常请贴你的代码。
openModal本来就是如此设计的。useModalInner的参数是一个回调函数，这个回调函数不是用来响应openModal的，是用来接受外部传递的数据。你看一下Demo中系统管理中的几个页面，都有演示如何在Modal中初始化create和edit场景。如果你一定不愿意在openModal中传参，visible-change事件可以利用。

**Comment by snowchenlei** [comment]
好的，谢谢。之前demo没有看到系统管理，一直在组件里面找
