### ISSUE TITLE
FormSchema 里面设置dynamicRules或者rules 正则 required设置为false,表单提交时不通过

### ISSUE THREAD

**Issue by valiantzhao** [anncwb/vue-vben-admin#837]
Hi:
  FormSchema 里面设置dynamicRules或者rules 正则 required设置为false,表单提交时不通过。
  e.g:
  

>  {
    field: 'ip',
    label: '设备IP',
    component: 'Input',
    rules: [
      {
        required: true,
        type: 'regexp',
        validator: checkIP,
      },
    ],
  },

>  export const checkIP=(rule, value)=> {
  const ipReg = /^((2[0-4]\d|25[0-5]|[01]?\d\d?)\.){3}(2[0-4]\d|25[0-5]|[01]?\d\d?)$/;
  if (!ipReg.test(value)) {
    return Promise.reject('请输入正确的IP格式');
  } else {
    return Promise.reject();
  }
}

**Comment by kryosssss** [comment]
const creditCodeRules = async (_rule: RuleObject, value: string) => {
  const ValidTel = isValidData('creditCode', value)
  if (!ValidTel.isRight) {
    return Promise.reject(ValidTel.val)
  }
  return Promise.resolve()
}

rules: [{ validator: creditCodeRules, trigger: 'blur' }, { required: true }]

**Comment by mynetfan** [comment]
校验通过返回resolve，不通过返回resolve。

**Comment by valiantzhao** [comment]
换成Promise.resolve() 这个也不正确
