### ISSUE TITLE
顶部菜单模式，菜单背景设置无效，文字颜色BUG

### ISSUE THREAD

**Issue by sunxy** [anncwb/vue-vben-admin#838]

**Comment by mynetfan** [comment]
顶部菜单模式使用顶栏主题来改变菜单样式。设置中的菜单主题只作用于侧边菜单。

**Comment by sunxy** [comment]
[http://118.31.173.221/static/1.png](url)

**Comment by sunxy** [comment]
[](url)
![image](https://user-images.githubusercontent.com/5026875/123942424-b568cf00-d9cd-11eb-994e-6e34b34b6a6c.png)

**Comment by sunxy** [comment]
![image](https://user-images.githubusercontent.com/5026875/123942529-cdd8e980-d9cd-11eb-9696-482d9edbedc2.png)

**Comment by sunxy** [comment]
![image](https://user-images.githubusercontent.com/5026875/123942849-1b555680-d9ce-11eb-9379-058861718ac3.png)
