### ISSUE TITLE
关于.husky文件的存在导致无法提交的问题

### ISSUE THREAD

**Issue by kryosssss** [anncwb/vue-vben-admin#840]
系统：window
（在mac上没有任何问题）

使用在window上拉下项目后，使用yarn安装依赖后，便无法提交，各种lint不存在问题。

**Comment by mynetfan** [comment]
请贴出具体的错误信息。

**Comment by anncwb** [comment]
Hello @kryosssss. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by kryosssss** [comment]
mac电脑拉取后，提交了修改信息，window电脑正常拉取，重新Yarn后，无法提交，提交错误是lintstagedrc校验位通过

**Comment by kryosssss** [comment]
mac电脑拉取后，提交了修改信息，window电脑正常拉取，重新Yarn后，无法提交，提交错误是lintstagedrc校验位通过
只提交了暂存文件，更改了console.log的内容。 mac上正常提交
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
⧗   input: test
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky - pre-commit hook exited with code 1 (error)
![1451625187805_ pic_hd](https://user-images.githubusercontent.com/66454922/124205787-8b6df480-db14-11eb-8173-c3b2d6ca2881.jpg)

**Comment by anncwb** [comment]
看看文档，git message遵守规范写。不需要就删除
