### ISSUE TITLE
useForm appendSchemaByField只能一次添加一个schema

### ISSUE THREAD

**Issue by 1sm23** [anncwb/vue-vben-admin#847]
### Subject of the feature

希望能加个 appendSchemas 支持一次性添加 schema 数组

**Comment by mynetfan** [comment]
批量追加schema可使用updateSchema，该方法会根据field更新已有的schema、追加之前没有的schema

**Comment by vintonHuang** [comment]
updateSchema 有这个追加之前没有schema的功能吗？我看源码代码写着好像没有这个功能吧。难道我看错了

**Comment by vintonHuang** [comment]
目前appendSchemaByField这个问题已经解决了
