### ISSUE TITLE
[Table]无滚动条情况也显示

### ISSUE THREAD

**Issue by Strive-Java** [anncwb/vue-vben-admin#849]
### Bug 描述
Table 列表宽高刚好的情况下，为什么滚动条是显示的，也无法滚动

### 期望
Table 列表内容自适应的情况下，期望不用显示滚动条，这样就不会影响美观
![image](https://user-images.githubusercontent.com/20058791/124235971-7f9c2580-db48-11eb-9e6e-e0e47924e82a.png)

**Comment by mynetfan** [comment]
修复于 https://github.com/anncwb/vue-vben-admin/commit/735028c43055e8e80ebc7344af0cd0f51c744f98
实验性修复，实际效果有待观察
