### ISSUE TITLE
Axios请求格式化请求参数一个小问题

### ISSUE THREAD

**Issue by colinin** [anncwb/vue-vben-admin#850]
不知道怎么描述，直接贴出问题点所在吧，在beforeRequestHook中对于所有非GET请求参数进行格式化，如果没有传递**params**参数，例如 **POST**、**PUT**请求，那么传递的**data**数据会被覆盖

https://github.com/anncwb/vue-vben-admin/blob/8819af083c80389453153c2b5f84b3bd1e408ba5/src/utils/http/axios/index.ts#L103-L110

 问题复现:
 
 ```js
import { defHttp } from '/@/utils/http/axios';
defHttp.put({
  data: { value: 1 },
  url: 'http://localhost:8080'
})
```

此时观察控制台网络请求，请求体中**Request Payload**为空

![image](https://user-images.githubusercontent.com/35512826/124343034-14f7f200-dbfb-11eb-8cde-571ef08e5243.png)

**Comment by mynetfan** [comment]
所有的参数一律通过params提交，无论是GET还是POST、PUT。如果有params以及data同时存在的场景，请自己按照defHttp的参考简单封装一个axios实例。

**Comment by colinin** [comment]
OK，理解错了项目中axios的逻辑

**Comment by mynetfan** [comment]
修改了一下你提到的地方，保持原用法不变，但是兼容你说的用法。非GET请求时，如果同时存在data和params，不会丢弃data数据；如果只存在params，仍然像之前那样会被视作data。
