### ISSUE TITLE
handleSearchInfoFn -A space parameter problem （created on 2021.7.3）

### ISSUE THREAD

**Issue by shushuquan** [anncwb/vue-vben-admin#851]
### Issue Description

When I console the parameters by handleSearchInfoFn , but  a  space parameter was found. In fact, I have never defined it in searchFormSchema.

### Reproduction

use  table demo in src\views\demo\system\account\index.vue, add code  in the following

```
        handleSearchInfoFn:(data)=>{
           console.log(data)
        }, 
```
`{account: "Joseph", nickname: "qrt", "": undefined}`

## System Info

- Operating System: win10
- Node version: v12.19.1
- Package manager (npm/yarn/pnpm) and version: 6.14.8/1.22.10/no

**Comment by mynetfan** [comment]
fixed in: https://github.com/anncwb/vue-vben-admin/commit/791b323dbd30acd7fabfe9c3fb6e528916311ffd
