### ISSUE TITLE
Basic 基础组件 - 文档示例代码文件引入不对

### ISSUE THREAD

**Issue by xietongjian** [anncwb/vue-vben-admin#852]
![image](https://user-images.githubusercontent.com/16096832/124348101-9c089280-dc1a-11eb-93b0-0f87d67aebc6.png)
import { BasicTitle } from '/@/components/Baisc/index'  
Baisc改成Basic
import { BasicTitle } from '/@/components/Basic/index'

**Comment by mynetfan** [comment]
谢谢，已修复。文档问题可在[此处提Issue](https://github.com/anncwb/vue-vben-admin-doc/issues)

**Comment by xietongjian** [comment]
本来想到那提的。对，还有个问题，这个链接点不过去，所以就...
![image](https://user-images.githubusercontent.com/16096832/124349303-f86eb080-dc20-11eb-89da-3f8faf25c9a5.png)

**Comment by mynetfan** [comment]
fixed
