### ISSUE TITLE
fetchSetting不能局部配置吗？

### ISSUE THREAD

**Issue by ZetRe** [anncwb/vue-vben-admin#855]
首先我对table组件进行了全局fetchSetting的配置，
对于某个特殊的接口，由于特殊返回格式需要单独对API结果进行解析，我在useTable() 中对fetchSetting进行了更改，useTable中更改fetchSetting的规则，全局都会进行更改。特殊的table倒是可以显示数据了，但是造成了其他table加载不了数据了。
我不知道是我用的不对，还是本身就是这种设计的？
我还试了 afterFetch ，由于数据没有解析对，afterFetch中参数为空，也不能实现我的需求。
我看了文档没发现对响应结果处理好一点的接口。

**Comment by mynetfan** [comment]
请更新到最新代码

**Comment by mynetfan** [comment]
https://github.com/anncwb/vue-vben-admin/commit/b4a3f936cd19bf1fff3a331bacad60e79d2d6c22
