### ISSUE TITLE
给树形结构添加默认值的时候，控制台报错

### ISSUE THREAD

**Issue by kryosssss** [anncwb/vue-vben-admin#859]
给树形结构添加默认值时，第一次都会出现不存在的报错警告！
warning.js:34 Warning: '0-0-0' does not exist in the tree.

mock代码
const roleList = (() => {
  const result: any[] = [];
  for (let index = 0; index < 4; index++) {
    result.push({
      id: index + 1,
      orderNo: `${index + 1}`,
      roleName: ['超级管理员', '管理员', '文章管理员', '普通用户'][index],
      roleValue: '@first',
      createTime: '@datetime',
      remark: '@cword(10,20)',
      menu: ['0-0-0'],
      'status|1': ['0', '1'],
    });
  }
  return result;
})();

**Comment by mynetfan** [comment]
如果你的树形数据是异步加载的，那么这个警告是可能会出现的，你需要将设置默认值的操作放在已经获取异步数据并且设置给tree之后才可以避免此警告。
