### ISSUE TITLE
弹窗 Table 高度问题

### ISSUE THREAD

**Issue by snihwxf** [anncwb/vue-vben-admin#871]
![image](https://user-images.githubusercontent.com/31719079/124616553-c3748f00-dea8-11eb-8bd2-62c2ec44fa46.png)

**Comment by mynetfan** [comment]
basicTable不支持在basicModal内自适应高度。

**Comment by snihwxf** [comment]
那这个要怎么解决，设置高度也没有效果

**Comment by mynetfan** [comment]
table设置高度使用scroll属性，详见 https://2x.antdv.com/components/table-cn#components-table-demo-fixed-header
