### ISSUE TITLE
打包后单机运行问题

### ISSUE THREAD

**Issue by jenifly** [anncwb/vue-vben-admin#873]
请问有没有一个参数控制打包时，不采取cdn的方式打包。否则在未连接到互联网的环境下，有相当多的插件都无法使用。

**Comment by anncwb** [comment]
可以描述清楚你的问题

**Comment by jenifly** [comment]
像这种有些图标加载不出，md插件用不了，有些样式也有问题。能不能全打包成一个单机可以用的...
![屏幕截图 2021-07-13 112147](https://user-images.githubusercontent.com/22962492/125385192-9e15e280-e3cc-11eb-99ad-9807a0dc0094.png)

**Comment by littlecxm** [comment]
打包推荐electron

**Comment by mynetfan** [comment]
离线运行时请勿使用Iconify 图标。参考文档的icon使用的相关章节：https://vvbin.cn/doc-next/dep/icon.html#svg-sprite-%E5%9B%BE%E6%A0%87，

**Comment by Little-Fan** [comment]
> 离线运行时请勿使用Iconify 图标。参考文档的icon使用的相关章节：[https://vvbin.cn/doc-next/dep/icon.html#svg-sprite-%E5%9B%BE%E6%A0%87，](https://vvbin.cn/doc-next/dep/icon.html#svg-sprite-%E5%9B%BE%E6%A0%87%EF%BC%8C)

问题是离线的时候，路由上定义图标是直接“bx:bx-home”,这样定义的，必须使用iconify图标多嘛，为什么默认的路由上能显示出图标来，我自己在iconify上找的图标，就显示不出来
