### ISSUE TITLE
表单TreeSelect组件，replaceFields里面的title，期待能支持对象，如：meta.title

### ISSUE THREAD

**Issue by dbgrowth** [anncwb/vue-vben-admin#874]
首先，非常感谢作者的作品，看得出是花了很大心思的，精心打磨过的，完成度非常高，非常感谢作者的开源精神。

我在使用的时候，发现一个小问题，由于我主要是做后端，前端不太熟练，自己弄了好久没搞定，故将该问题抛出来，若作者有时间，能帮忙，不甚感激。

请往下看，

业务场景，https://vvbin.cn/next/#/system/menu ，新增菜单，上级菜单的下拉选择时的菜单label的中文名显示。
文件，menu.data.ts，
```
  {
    field: 'parentMenu',
    label: '上级菜单',
    component: 'TreeSelect',
    componentProps: {
      replaceFields: {
        title: 'meta.title', //就是这里，官方实例的数据是不需要用对象的方式，直接就有menuName的中文名字段。
        key: 'id',
        value: 'id',
      },
      getPopupContainer: () => document.body,
    },
    show: ({ values }) => isMenu(values.type),
  },
```

菜单数据是后端下发的，格式如下：
{
	CreatedAt: "0001-01-01T00:00:00Z"
	UpdatedAt: "0001-01-01T00:00:00Z"
	children: null
	component: "/system/user/index"
	id: 3
	meta: {
		affix: null
		carryParam: null
		currentActiveMenu: ""
		frameSrc: ""
		hideBreadcrumb: null
		hideChildrenInMenu: null
		hideMenu: null
		hideTab: null
		icon: ""
		ignoreAuth: null
		ignoreKeepAlive: false
		isLink: null
		orderNo: 1
		single: null
		title: "用户管理"
		transitionName: ""
	}
	name: "User"
	parentId: "2"
	path: "user"
	redirect: ""
}

现状，只要是meta里面的，都不能正常显示出来。
期望，meta对象里面的，也能正常取出来。
不知道我描述清除了没有:smile

**Comment by mynetfan** [comment]
TreeSelect 组件是ant design vue的组件，你的需求需要ant design vue支持才可以
