### ISSUE TITLE
Safari 卡在启动画面

### ISSUE THREAD

**Issue by shlk20** [anncwb/vue-vben-admin#875]
首先感谢作者的无私分享这么优秀的作品，我在使用中发现这样一个问题，麻烦抽空看一下，先提前感谢。

## 问题描述

在使用Safari浏览器时，无论是本地调试还是访问 [官方在线预览地址](https://vvbin.cn/next/) ，都一直停在启动页，控制台结果如图：

<img width="1438" alt="WX20210707-170308@2x" src="https://user-images.githubusercontent.com/4349839/124731880-3a5f6580-df45-11eb-91e8-ecef762bccba.png">

## 系统信息

- Operating System: macOS Big Sur 11.4
- Safari Version: 14.1.1
- Node Version: 16.4.2

**Comment by bihell** [comment]
我跟你一样,不过我已经放弃safari了
