### ISSUE TITLE
有一些复杂的业务，需要在表单展示各种组件，请问怎么和BasicForm结合

### ISSUE THREAD

**Issue by acegank** [anncwb/vue-vben-admin#879]
例如：
`<BasicForm @register="registerForm">
      <template #tabs="{ model, field }">
        
        <Card
          :tab-list="tabListTitle"
          v-bind="$attrs"
          :active-tab-key="activeKey"
          @tabChange="onTabChange"
        >
          <p v-if="activeKey === 'tab1'">
            <VisitAnalysis />
          </p>
          <p v-if="activeKey === 'tab2'">
            <VisitAnalysisBar />
          </p>
        </Card>
      </template>
    </BasicForm>`

这里的Card是antd的组件，那么tabListTitle, activeKey, onTabChange 这些怎么和BasicForm结合

或者说如果表单比较复杂，该怎么处理比较好

**Comment by anncwb** [comment]
特殊组件用slot，或者独立封装成组件嵌入Form，具体可以参考表单示例代码

**Comment by acegank** [comment]
请问直接写slot 或者 封装成组件 通过componentMap注册进去  哪种方式推荐

**Comment by mynetfan** [comment]
多场和复用的组件封装成组件，没有在其它地方用的直接写slot
