### ISSUE TITLE
路由缓存无效

### ISSUE THREAD

**Issue by kailong321200875** [anncwb/vue-vben-admin#88]
看了下官方demo，路由 meta.ignoreKeepAlive: true 应该是控制路由不缓存的，所以所有路由应该都是默认，可是，我试了一下官方demo里面的From-基础表单，随便输入改变页面表单值，切换到其他路由页在切换回来，是没有缓存最后一次状态的。而源码里面，基础表单的ignoreKeepAlive是没有设置值的。

**Comment by anncwb** [comment]
满足缓存有3个条件 
1. 路由设置name
2.页面设置name   两个name要一致
3.需要放在pageLayout内
示例没做的原因是name故意都没写。不想让它缓存
