### ISSUE TITLE
BasicTable 带 Form 的 希望中间加上插槽可以自定义东西

### ISSUE THREAD

**Issue by 869123771** [anncwb/vue-vben-admin#881]
![Uploading QQ图片20210708183254.png…]()

**Comment by zsl1549** [comment]
怎么解决的？

**Comment by 869123771** [comment]
官方解决了呀。。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月4日(星期天) 晚上9:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vbenjs/vue-vben-admin] BasicTable 带 Form 的 希望中间加上插槽可以自定义东西 (#881)





 
怎么解决的？

**Comment by zsl1549** [comment]
![image](https://user-images.githubusercontent.com/32888522/205494710-b76ce1e4-dfc0-4eeb-bbfe-b2c42c348869.png)

**Comment by zsl1549** [comment]
@869123771 求大哥指点一下  我写在这里 怎么都出不来 ，不知道怎么操作了

**Comment by 869123771** [comment]
你去看表格有个插槽就是这个呀，在表单 和表格中间插入东西。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月4日(周日) 晚上9:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [vbenjs/vue-vben-admin] BasicTable 带 Form 的 希望中间加上插槽可以自定义东西 (#881)




 
@869123771 求大哥指点一下  我写在这里 怎么都出不来 ，不知道怎么操作了
