### ISSUE TITLE
线上打包发布环境通过nginx映射访问，FormSchema验证出现卡死

### ISSUE THREAD

**Issue by AndroidMilk** [anncwb/vue-vben-admin#886]
表单输入，再删除填写的内容，会出现卡死的现象，请问是bug吗？

**Comment by mynetfan** [comment]
Demo中未能重现，请提供复现代码

**Comment by anncwb** [comment]
Hello @AndroidMilk. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by AndroidMilk** [comment]
目前已查明原因，应该是海外集群构建节点导致产生的文件有缺失，谢谢
