### ISSUE TITLE
是否可以考虑增加一个非国际化的版本

### ISSUE THREAD

**Issue by ccj-csf** [anncwb/vue-vben-admin#890]

**Comment by mynetfan** [comment]
https://vvbin.cn/doc-next/guide/settings.html#%E5%A4%9A%E8%AF%AD%E8%A8%80%E9%85%8D%E7%BD%AE

把showPicker改为false，就没有多语言切换了。

**Comment by ccj-csf** [comment]
> https://vvbin.cn/doc-next/guide/settings.html#%E5%A4%9A%E8%AF%AD%E8%A8%80%E9%85%8D%E7%BD%AE
> 
> 把showPicker改为false，就没有多语言切换了。

这个的确是一种，但是多余的依赖还在在，也可以像antd pro提供个命令的方式来移除
