### ISSUE TITLE
能否把演示环境的后台部分代码也开源出来？

### ISSUE THREAD

**Issue by liujiliang2008** [anncwb/vue-vben-admin#898]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by mynetfan** [comment]
演示页面的接口数据全部都在mock里
