### ISSUE TITLE
布局问题报告

### ISSUE THREAD

**Issue by mynetfan** [anncwb/vue-vben-admin#90]
截止到2.0.0-rc.10：
导航栏模式设置为混合模式，且开启分隔菜单时
1、菜单折叠按钮设置为不显示或在底部显示时，顶部的logo右侧原来的折叠按钮的占位没有去除，会多出一部分空白
![image](https://user-images.githubusercontent.com/17241274/99355292-f69aeb80-28e2-11eb-93ad-8e647c7c7519.png)
2、左侧菜单在折叠状态时，顶部的LOGO部分没有自动缩小为图标状态，并且左侧菜单项因为没有图标而显示不正常（开启“折叠菜单显示名称”选项后此问题解决）。希望LOGO部分在左侧菜单折叠时也能像“左侧菜单导航模式”那样自动缩小到只剩下一个图标。
![image](https://user-images.githubusercontent.com/17241274/99355537-6c9f5280-28e3-11eb-89ce-0461be1b002a.png)

**Comment by anncwb** [comment]
希望LOGO部分在左侧菜单折叠时也能像“左侧菜单导航模式”那样自动缩小到只剩下一个图标
======================
这点 应该是logo嵌入在菜单内才缩小这样逻辑才对吧

**Comment by mynetfan** [comment]
> 希望LOGO部分在左侧菜单折叠时也能像“左侧菜单导航模式”那样自动缩小到只剩下一个图标
> 
> ======================
> 
> 这点 应该是logo嵌入在菜单内才缩小这样逻辑才对吧

这个可能是我自以为是，我个人觉得LOGO部分的文字应该在左侧菜单收缩时也隐藏起来。

谢谢您的关注

**Comment by anncwb** [comment]
希望LOGO部分在左侧菜单折叠时也能像“左侧菜单导航模式”那样自动缩小到只剩下一个图标。

====

 这个问题给菜单设置图标应该就可以
