### ISSUE TITLE
[Table]滚动条样式错位

### ISSUE THREAD

**Issue by snowchenlei** [anncwb/vue-vben-admin#902]
![image](https://user-images.githubusercontent.com/26211283/125545134-0d25ee3b-f992-4944-a877-86d23b3602b0.png)
如图所示，如果包含action将出现双滚动条。
火狐浏览器，示例中的表格既能看到效果。

**Comment by mynetfan** [comment]
什么情况下出现的？我在firefox中打开没有发现你截图的情况。说说你的具体的系统版本、firefox版本、出现这种情况的操作步骤

**Comment by anncwb** [comment]
Hello @snowchenlei. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by snowchenlei** [comment]
> 什么情况下出现的？我在firefox中打开没有发现你截图的情况。说说你的具体的系统版本、firefox版本、出现这种情况的操作步骤

请F12并向上拉，让TableContent出现滚动条

**Comment by snowchenlei** [comment]
firefox 国际版89.0.2(x64)
[https://vvbin.cn/next/#/comp/table/authColumn](https://vvbin.cn/next/#/comp/table/authColumn)

**Comment by mynetfan** [comment]
未能重现。
如果你本地有滚动条问题，尝试注释src/design/ant/index.less第4行的@import './table.less'试试。

**Comment by snowchenlei** [comment]
线上的，不是本地的

**Comment by snowchenlei** [comment]
https://user-images.githubusercontent.com/26211283/125551913-90bd26c0-f145-4f7b-b5c7-f67492189828.mp4

**Comment by snowchenlei** [comment]
`.ant-table-body {
    overflow: auto !important;
}`
应该是这段代码问题，横坐标轴一隐藏就会出现

**Comment by mynetfan** [comment]
> 注释src/design/ant/index.less第4行的@import './table.less'试试。

上面已经说过了的。

**Comment by snowchenlei** [comment]
注释了是可以的

**Comment by M69W** [comment]
火狐浏览器可以重现，
**当设置显示table 条数的高度 大于 table 高度时就会出现滚动条**

![image](https://user-images.githubusercontent.com/15809201/125585316-e49aab23-b014-4541-bf43-def6c68ef0c7.png)


当然，屏蔽 @import './table.less'; 可以临时解决此问题

**Comment by mynetfan** [comment]
这个table.less只是为了解决在高度足够显示数据的情况下，仍然会显示滚动条的问题，看起来这个在火狐下工作不正常。

**Comment by snowchenlei** [comment]
注释是会解决这个问题，但会带来新问题，出现了层次滚动条
![image](https://user-images.githubusercontent.com/26211283/125586424-14666536-cdce-494d-946c-25778bb88644.png)

**Comment by mynetfan** [comment]
这就是我上面提到的，在不需要显示滚动条的时候，它仍然显示了滚动条

**Comment by snowchenlei** [comment]
还有个问题，.ant-table-body的height计算问题，距离底部滚动条有较大空白。上图应该很容易看出

**Comment by mynetfan** [comment]
开启了自适应页面高度不就会这样吗？table总是填满整个页面的剩余高度，而无论内部有多少条数据

**Comment by mynetfan** [comment]
https://github.com/anncwb/vue-vben-admin/commit/6350224a1bf74572dde3e71c04d8fb370d7aacf2

滚动样式补丁暂时移除。
