### ISSUE TITLE
修改 tab 标题bug

### ISSUE THREAD

**Issue by q7486828035** [anncwb/vue-vben-admin#906]
在 useTabs.ts 35行中，
`  function getCurrentTab() {
    const route = unref(currentRoute);
    return tabStore.getTabList.find((item) => item.Path === route.Path)!;
  }
`
不应该为path ，应为 fullpath，其他文件中都是fullpath

**Comment by mynetfan** [comment]
对于route对象来说，fullPath和path的值都是一样的。
