### ISSUE TITLE
多个BasicTable如何注册获取数据

### ISSUE THREAD

**Issue by acegank** [anncwb/vue-vben-admin#907]
需求：
用户可以自行添加多个表格，填写不同的数据。

通过循环出来的BasicTable，如何注册呢，useTable怎么导出多个registerTable，并且registerTable也要return出去

希望可以有代码示例，感谢

**Comment by acegank** [comment]
usetable注册应该是不可行吧，我看示例有通过ref去获取的，请问是不是采用ref这种方式

**Comment by zhangfugui727** [comment]
理论来说都是可以的，你可以试试包装成对象去处理，或者用函数组件动态渲染类似来尝试

**Comment by acegank** [comment]
目前采用ref方式，但这种方式有个问题就是循环只能固定，不然声明好像没办法处理

**Comment by zhangfugui727** [comment]
> 目前采用ref方式，但这种方式有个问题就是循环只能固定，不然声明好像没办法处理

这样可以吗，我没试过
```
<template>
  <div v-for="item in items" :ref="refs[item]" />
</template>
```
```
setup
const refs = ref({});
return refs;
```

**Comment by mynetfan** [comment]
https://v3.cn.vuejs.org/guide/migration/array-refs.html#frontmatter-title
