### ISSUE TITLE
Form 使用Tinymce 时，重置表单后， 富文本的值不会跟着重置

### ISSUE THREAD

**Issue by ZetRe** [anncwb/vue-vben-admin#909]

**Comment by mynetfan** [comment]
说明你所使用的版本

**Comment by anncwb** [comment]
Hello @ZetRe. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by ZetRe** [comment]
> 说明你所使用的版本

"2.5.2"

**Comment by mynetfan** [comment]
此问题已修复。
https://github.com/anncwb/vue-vben-admin/commit/d95815b5031984e224140eb1b1d46e2dbf80abc1
https://github.com/anncwb/vue-vben-admin/commit/35e1347029e29a83a9648b6b398e6863cc40fca9

**Comment by mynetfan** [comment]
此Issue先关闭。如果最新版本中仍然发现此问题，请重新打开此Issue
