### ISSUE TITLE
Table 组件分页，点击页码，控制台会报错

### ISSUE THREAD

**Issue by im-qrh** [anncwb/vue-vben-admin#911]
Table 组件分页，点击页码，控制台会报错，连着输出三条以下错误
```
VM31:1 Uncaught TypeError: Cannot read property 'match' of null
    at gn (<anonymous>:1:342)
    at _n (<anonymous>:1:604)
```

**Comment by mynetfan** [comment]
请提供问题复现代码或链接

**Comment by anncwb** [comment]
Hello @im-qrh. Please provide the complete reproduction steps and code. Issues labeled by `need reproduction` will be closed if no activities in 3 days.

**Comment by im-qrh** [comment]
> 请提供问题复现代码或链接

[https://vvbin.cn/next/#/comp/table/fetchTable](https://vvbin.cn/next/#/comp/table/fetchTable)
VbenAdmin 的远程加载示例，
