### ISSUE TITLE
无限重定向

### ISSUE THREAD

**Issue by wyyooo** [anncwb/vue-vben-admin#912]
系统内权限模式为 BACK 模式

![2021-07-15_004110](https://user-images.githubusercontent.com/87439846/125660656-37297549-832a-4a7e-8a74-f03cb7665951.png)

**Comment by mynetfan** [comment]
请提供版本号，以及你后端接口返回的菜单数据。

**Comment by mynetfan** [comment]
fixed : https://github.com/anncwb/vue-vben-admin/commit/4b46a84c2b85e8da799426c54b3381ae93183db4
