### ISSUE TITLE
setTableData 设置新数据视图不更新

### ISSUE THREAD

**Issue by ckbabby** [anncwb/vue-vben-admin#913]
你好，我发现使用setTableData 不更新 视图，查找文档发现只有这个还有setprops 更新表数据，刚开时接触vue3 ，麻烦大家帮我看看是什么问题，谢谢了！
[Basic.zip](https://github.com/anncwb/vue-vben-admin/files/6820857/Basic.zip)

**Comment by mynetfan** [comment]
你在useTable时传入的数据源就是dataSource这个常量。之后再次setTableData时仍然传入的是同一个常量，这并不会引起视图更新，因为前后数据相同（我并不是指dataSource的内容，而是指它自身）vue不能检测到数据变化。
要么使用table提供的更新行数据的API（有好几种方式），要么在setTableData时通过cloneDeep等方法复制一份新的dataSource内容传递过去。

**Comment by ckbabby** [comment]
@mynetfan  非常感谢你的回复，我把对应的方法换成
      function handleFormSubmit() {
        validate().then((data) => {
          updateTableDataRecord(data.id, data);
          openModal(false);
        });
      }
发现视图还是不更新的，不知道我是否调用方法错误导致，我关闭从新打开form发现form 有更新的，谢谢！
