### ISSUE TITLE
跨页进行选择时，getSelectRows获取部分选择数据，getSelectRowKeys获取数据

### ISSUE THREAD

**Issue by fengyulf** [anncwb/vue-vben-admin#914]
### Describe the bug

跨页进行选择时，getSelectRows获取数据不对，getSelectRowKeys获取数据正常

### Reproduction

![image](https://user-images.githubusercontent.com/44594721/125742272-7aaa60bf-ddd5-4e34-abe9-1a467a4cea70.png)

Please check it out, thank you

**Comment by mynetfan** [comment]
getSelectRows只能获得当前页面的数据。table不会存储当前页以外的行数据，所以getSelectRowKeys没有其它页的数据

**Comment by fengyulf** [comment]
getSelectRowKeys是可以获取所有选择的数据，getSelectRows只能获得部分数据

**Comment by 364** [comment]
> getSelectRowKeys是可以获取所有选择的数据，getSelectRows只能获得部分数据

你好，请问 `getSelectRows` 跨页获取解决了吗，我也遇到同样的问题

**Comment by mynetfan** [comment]
getSelectRows 不支持跨页。getSelectRows只会获得当前页面中的数据

**Comment by 364** [comment]
> getSelectRows 不支持跨页。getSelectRows只会获得当前页面中的数据

好吧，我想到了一种解决方法，在 `beforeFetch` 跨页点击时存储当页选择的

**Comment by 364** [comment]
> getSelectRows 不支持跨页。getSelectRows只会获得当前页面中的数据

本来我想用 `selection-change` 去解决，但是这个事件行点击不会响应

**Comment by mynetfan** [comment]
已经对getSelectRows做了改动，使之支持跨页选择与getSelectRowKeys保持一致

**Comment by fengyulf** [comment]
thank you
