### ISSUE TITLE
BasicTable的expandedRowRender的几个bug

### ISSUE THREAD

**Issue by jenifly** [anncwb/vue-vben-admin#916]
![image](https://user-images.githubusercontent.com/22962492/125767545-660e805a-3f21-4826-9f8c-376430ed84ca.png)

**Comment by mynetfan** [comment]
table 不支持 扩展行与固定列同时使用。

**Comment by jenifly** [comment]
嗯嗯，但是滚动条还是有点问题...

**Comment by 15191362069** [comment]
你好想请教一下expandedRowRender如何设置默认展开呢
