### ISSUE TITLE
内嵌链接，首次打开显示一半问题

### ISSUE THREAD

**Issue by anTi-by** [anncwb/vue-vben-admin#919]
官方体验平台：https://vvbin.cn/next/
版本：2.6.0
模块：外部页面=》项目文档(内嵌)
预期：点击打开内嵌页面页面铺满显示
结果：页面没有铺满显示，刷新页面之后会铺满显示
![image](https://user-images.githubusercontent.com/22879975/125885464-f9b2164b-2b42-47de-8e05-49482cb9719d.png)

**Comment by mynetfan** [comment]
使用外部页面时，最好关闭页面动画，否则可能会出现此问题

**Comment by anncwb** [comment]
close d76cfd7
