### ISSUE TITLE
页面的一些警告

### ISSUE THREAD

**Issue by zuihou** [anncwb/vue-vben-admin#921]
1. 分页组件
![image](https://user-images.githubusercontent.com/8500410/125887075-779675b2-9b95-4527-bdbe-9e9c639c93d7.png)
![image](https://user-images.githubusercontent.com/8500410/125887068-4f3d08b6-461c-4665-97c2-d9b9a2e13d45.png)

分页接口返回的total 为字符串就会报警告。

场景： 为了防止精度丢失， 后端会将Long 类型的值 以字符串形式返回给前端

**Comment by zuihou** [comment]
2.  菜单管理页面 
![image](https://user-images.githubusercontent.com/8500410/125887124-044a9aa1-e17c-443a-baa3-c03e9e38f389.png)

**Comment by mynetfan** [comment]
你的记录数量能有多大可以达到丢失精度的程度？

**Comment by zuihou** [comment]
> 你的记录数量能有多大可以达到丢失精度的程度？

全局统一处理的啊，比如Long 类型的雪花id 等， 都会统一按照字符串返回。

刚好total 也是long类型的。

**Comment by mynetfan** [comment]
在axios的transform中转换，或者在包装api访问的函数中转换

**Comment by mynetfan** [comment]
问题1请自行修改src/components/Table/src/hooks/useDataSource.ts第244行附近，将resultTotal从string转换为number。
问题2可能需要antv优化table的滚动才会消除此警告。当前版本的antv有过一次优化，但尚未完全解决。
