### ISSUE TITLE
editCellTable 不处于编辑状态，通过getDataSource获取的值修改，值修改了但是显示不发生变化

### ISSUE THREAD

**Issue by VENI-VIDIVICI** [anncwb/vue-vben-admin#922]
src\views\demo\table\EditCellTable.vue
function add() {
  let data = getDataSource()
  data.forEach(item => {
    item.name7 = item.name1
  })
}

**Comment by mynetfan** [comment]
你的版本说一下

**Comment by VENI-VIDIVICI** [comment]
vben-admin@2.6.0 直接从main拉下来的
