### ISSUE TITLE
表格内的配置例如input等如何监听其他配置的input

### ISSUE THREAD

**Issue by acegank** [anncwb/vue-vben-admin#923]
比如排班计划，  总共只能排满30个班次， 表格内某日排班次数的input输入后，需要对其他日期的班次与当前输入班次进行数学运算（加减），那么如何获取其他日期内对应班次的值呢

**Comment by mynetfan** [comment]
Demo里有演示，可编辑行的那一页：
https://vvbin.cn/next/#/comp/table/editRowTable

**Comment by mynetfan** [comment]
演示的是获取同一行的其它正在编辑的值，不支持在当前编辑行中获取其它行正在编辑但尚未提交的值。

**Comment by acegank** [comment]
不需要获取其他行尚未提交的，如果获取其他行已经提交的值呢，比如编辑第一行的时候，获取剩余行数的值

**Comment by mynetfan** [comment]
getDatSource

**Comment by acegank** [comment]
表格通过schemas配置，表格内的输入框监听是onChange，怎么配合getDatSource呢

**Comment by mynetfan** [comment]
看Demo和文档

**Comment by acegank** [comment]
大佬能给个地址吗，实在找不到
