### ISSUE TITLE
 角色档案 > 超级管理员 > 编辑 => 菜单form列,套一层div，报错

### ISSUE THREAD

**Issue by GavinChain** [anncwb/vue-vben-admin#926]
### Describe the bug

角色档案 > 超级管理员 > 编辑 => 菜单form列,套一层div，报错

### Reproduction

![image](https://user-images.githubusercontent.com/40415260/125905525-820349dc-ebd0-46c4-b3ff-c076b323feef.png)

## System Info

![image](https://user-images.githubusercontent.com/40415260/125905773-23742da6-b7d2-4cd8-9ed1-f1eee70cc7bd.png)

**Comment by mynetfan** [comment]
当前版本未能重现

**Comment by GavinChain** [comment]
好的，覆盖了下当前版本BasicForm,修复了该问题，我关闭当前问题了

**Comment by GavinChain** [comment]
好的，覆盖了下当前版本BasicForm,修复了该问题，我关闭当前问题了
