### ISSUE TITLE
优化项目首页加载速度

### ISSUE THREAD

**Issue by JokerLoLgrey** [anncwb/vue-vben-admin#928]
### Subject of the feature
优化项目首页加载速度

### Problem

目前首页加载太慢了，基本需要3s~4s，希望能够优化到1s左右

**Comment by mynetfan** [comment]
请不要以开发环境下的加载速度作评估。
生产环境下如果服务器带宽足够，初次打开因为需要下载资源文件，加载可能需要数秒，之后再刷新或者重新进入就很快了。

**Comment by JokerLoLgrey** [comment]
> 请不要以开发环境下的加载速度作评估。
> 生产环境下如果服务器带宽足够，初次打开因为需要下载资源文件，加载可能需要数秒，之后再刷新或者重新进入就很快了。
![image](https://user-images.githubusercontent.com/33446705/126093757-106c7fe6-73bf-4750-97aa-a45c5aade94b.png)
还是很慢

**Comment by carl-jin** [comment]
最近把老项目从 webpack 迁移到 vite 时又遇到这个问题了，记录了下优化的方法， 虽然没有从实质上解决问题，但是也加速不少，[https://carljin.com/vite-resolve-request-files-a-ton.html](https://carljin.com/vite-resolve-request-files-a-ton.html)
