### ISSUE TITLE
顶部Tag标签刷新功能，不会执行mounted钩子

### ISSUE THREAD

**Issue by TothingWay** [anncwb/vue-vben-admin#93]
我看到你在vue-router官方提到的issue：https://github.com/vuejs/vue-router-next/issues/557，
在router-view上添加key，会使keep-alive失效，但是不添加，redirect无法真正做到刷新，请问有什么好的解决方法吗？

**Comment by anncwb** [comment]
我试了下是可以的

**Comment by TothingWay** [comment]
@anncwb 发现您的项目是可以的，我在借鉴您项目的实现遇到了这个问题，百思不得其解

**Comment by anncwb** [comment]
可以参考项目。加key可以实现。具体细节我没看代码也不清楚
