### ISSUE TITLE
表格组件 序号列 序号大于 10000 以后 序号列宽度不够会往下掉

### ISSUE THREAD

**Issue by im-qrh** [anncwb/vue-vben-admin#930]
表格组件 序号列 序号大于 10000 以后 序号列宽度不够会往下掉，不会自适应宽度
![image](https://user-images.githubusercontent.com/82321234/125914151-b003a6b3-d030-4aa4-aadd-755003795e39.png)

**Comment by mynetfan** [comment]
这不是BUG，通过indexColumnProps去配置序号列的prop。
