### ISSUE TITLE
updateTableDataRecord 问题

### ISSUE THREAD

**Issue by ckbabby** [anncwb/vue-vben-admin#932]
你好，我使用updateTableData 更新表数据后不刷新，或许是调用方法不对，麻烦给我一下案例，谢谢了！
[Basic.zip](https://github.com/anncwb/vue-vben-admin/files/6834221/Basic.zip)

**Comment by mynetfan** [comment]
你自己提供了dataSource属性，在updateTableData后又调用了reload，被修改的数据就会还原为dataSource。

**Comment by ckbabby** [comment]
> 你自己提供了dataSource属性，在updateTableData后又调用了reload，被修改的数据就会还原为dataSource。

你好，reload 是我没执行updateTableData 不行后加进去尝试的，我删除了reload 后还是不行

**Comment by ckbabby** [comment]
非常感谢你，我更新了组件，已经可以了，谢谢！
