### ISSUE TITLE
BasicDrawer组件设置mask属性为false后，页面打不开抽屉，版本2.6.0

### ISSUE THREAD

**Issue by liyaxu123** [anncwb/vue-vben-admin#935]
![image](https://user-images.githubusercontent.com/55610041/126092958-4980d11e-649f-41f1-875e-9284109521d4.png)

**Comment by mynetfan** [comment]
mask为false时，不可使用百分比宽度。
要么不使用mask，要么给一个固定的宽度如： 400px
