### ISSUE TITLE
希望可编辑表格可以加入级联面板，apitreeselect。

### ISSUE THREAD

**Issue by songweionline** [anncwb/vue-vben-admin#936]
希望可编辑表格可以加入级联面板，apitreeselect。
另外在column的设置里：
{
    title: '上级部门',
    dataIndex: 'parentId',
    width: 120,
    editRow: true,
    editComponent: 'ApiTreeSelect',
    editComponentProps: {
      api: getDeptList,
      params: { pagination: false },
      replaceFields: { title: 'deptName', key: 'id', children: 'children', value: 'id' },
      onClick: () => {},
      onBlur: () => {
        console.log(true);
      },
      onFocus: () => {},
      onMousedown: () => {},
    },
    editValueMap: (value) => {
      const useBackEndOptionDataStore = useBackEndOptionDataStoreWithOut();
      const deptTreeOptionData = treeToList(toRaw(useBackEndOptionDataStore.getDeptTreeOptions));
      let displayValue = null;
      deptTreeOptionData.forEach((item) => {
        if (item.id === value) {
          displayValue = item.deptName;
        }
      });
      if (displayValue) {
        return displayValue;
      } else {
        return '';
      }
    },
  },
这里的editValueMap是否可以获取到editComponent里的api得到的option数据？并且是要加载表格的时候就能获取。或者有别的办法可以获取到option用于正确显示数据？

**Comment by mynetfan** [comment]
https://github.com/anncwb/vue-vben-admin/commit/52af1dd0d494e66c0af20f886dcc2b983cbb096f
