### ISSUE TITLE
piana 不能this当前state中的变量，这个计划是什么？

### ISSUE THREAD

**Issue by GavinChain** [anncwb/vue-vben-admin#939]
piana 不能this当前state中的变量，这个计划是什么？

**Comment by mynetfan** [comment]
说明白一点，在哪儿用this？

**Comment by GavinChain** [comment]
> 说明白一点，在哪儿用this？

piana的action中, this无语法支持，this es6报错，不影响运行

**Comment by anncwb** [comment]
贴出的你的代码。目测应该是函数没定义返回值类型，需要显示的定义返回值类型

**Comment by GavinChain** [comment]
> 贴出的你的代码。目测应该是函数没定义返回值类型，需要显示的定义返回值类型

![image](https://user-images.githubusercontent.com/40415260/126154305-bdfab658-a2a8-4160-8bfe-939cb9efb9d7.png)
所有的this都是语法检测错误，无法定向到变量

**Comment by GavinChain** [comment]
> 所有的this都是语法检测错误，无法定向到变量

这个后期会有什么变动，以支持this定向到state中

**Comment by GavinChain** [comment]
已经可以了，疏忽了，抱歉
