### ISSUE TITLE
table 行单击无效

### ISSUE THREAD

**Issue by zn98com** [anncwb/vue-vben-admin#94]
table 行单击无效

 const [registerTable, { setLoading, setColumns, setTableData,setSelectedRowKeys, getDataSource }] = useTable(
        getSkqTable({
          pagination: false,
          isTreeTable: true,
          customRow: (record: any, index: number) => {
            return {
              on: {
                click: (event: any) => {
                  console.log('customRow',record, index);
                  // data.selectedRowKeys = [index];
                  // data.selectedRows = [record];
                }
              }
            };
          },
          rowSelection: {
             onChange: onSelectChange,
            type: 'radio'
          },
          actionColumn: { width: 3 }
        } as skqTableProps)
      );

![1](https://user-images.githubusercontent.com/10260081/99532144-cafd2b80-29de-11eb-9d40-4a5b49f35b94.png)

**Comment by luger1990** [comment]
我也遇到这个问题了，请问这是个问题吗？最新版还不行 @anncwb
