### ISSUE TITLE
内嵌页面展示出现BUG

### ISSUE THREAD

**Issue by mishizhiya** [anncwb/vue-vben-admin#945]
- Operating System: windows 10,google浏览器91.0.4472.164（正式版本） （64 位）
https://vvbin.cn/next/ 2021-07-20
复现步骤登录之后先点击左侧菜单-图表-Echarts-地图
再点击外部页面-项目文档(内嵌),出现页面高度不正确的问题
![1](https://user-images.githubusercontent.com/54994665/126292378-8736e541-ffee-4166-82c6-3f09e2a4c44a.png)

**Comment by mynetfan** [comment]
目前内嵌外部页面不能很好地支持页面动画。如果你有内嵌页面的需求，请关闭页面动画。

**Comment by mynetfan** [comment]
重复Issue
