### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by zuoyifeng** [anncwb/vue-vben-admin#947]
目前版本兼容性太差，就算是chrome也只完美兼容80版本以上，有点诧异，
没办法选择性兼容浏览器吗？比如舍弃某些组件或者功能！

**Comment by mynetfan** [comment]
chrome要求v80以上指的是开发环境下。
生产环境无此要求。

**Comment by janly-li** [comment]
> chrome要求v80以上指的是开发环境下。 生产环境无此要求。

请问生产环境能兼容到chrome v42版本吗，还有开发环境只能兼容到v80以上吗？有没有解决办法
