### ISSUE TITLE
可编辑树形表格，展开箭头与内容高度不能对齐

### ISSUE THREAD

**Issue by songweionline** [anncwb/vue-vben-admin#948]
![image](https://user-images.githubusercontent.com/57444642/126417022-8fa454af-1d79-4359-ac5f-911a1a3139e7.png)
未修改可编辑树形表格超长内容显示之前，可以在表格的index.vue文件中添加样式解决对齐问题。
<style scoped>
  ::v-deep(.vben-editable-cell) {
    display: inline-block;
    position: relative;
  }
</style>

修改可编辑表格超长内容显示之后：
![image](https://user-images.githubusercontent.com/57444642/126417920-8d0fcdca-3076-455b-8ceb-59cd4d6176e6.png)
即使删除上面的css样式也依然不能对齐。

**Comment by mynetfan** [comment]
首先，不建议在编辑功能与树形数据一起使用。其次，这个问题可以在树形表格第一列留一个空列放展开图标，部门名称单独一列
