### ISSUE TITLE
moment 多语言引入问题

### ISSUE THREAD

**Issue by zhongshuyi** [anncwb/vue-vben-admin#958]
我发现 在src\locales\lang\en.ts 中 导入的 momentLocale 以及定义的momentLocaleName 均为 'eu', 为巴斯克语
而英语 (英国) 是'en-gb' ,虽然我在使用moment().format()时并未发现错误,不知道您怎么处理的,但我还是提交这个错误
![image](https://user-images.githubusercontent.com/53006829/126621710-373b984c-aabd-499e-a589-7b45c68005d4.png)

**Comment by mynetfan** [comment]
fixed: https://github.com/anncwb/vue-vben-admin/commit/27207a78caccb04372e0275c5cee526ec460de0e
