### ISSUE TITLE
打包运行后 a 标签颜色 不正确（不是主题色，本地运行是 主题色）

### ISSUE THREAD

**Issue by ejlchina** [anncwb/vue-vben-admin#961]
![image](https://user-images.githubusercontent.com/29403889/126630539-f317c61c-f658-40ad-97cd-401f5bb40fa2.png)

只有手动切换一次 主题色 时，才会和 主题色 一致：

![image](https://user-images.githubusercontent.com/29403889/126630760-60e9bbdf-4c61-4672-bc37-1d668123a3ce.png)

**Comment by M69W** [comment]
试试：
右上角，设置，最后一个，清除登录

**Comment by mynetfan** [comment]
重复issue #960

**Comment by frankchen211** [comment]
我的项目打包后也有这个问题，按照方法无效，并且改变系统主题颜色无效。

> 试试： 右上角，设置，最后一个，清除登录
