### ISSUE TITLE
浏览器自动填充，比如记住密码等，会造成输入框黑暗模式无效

### ISSUE THREAD

**Issue by zxiaozhou** [anncwb/vue-vben-admin#962]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [✅] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [ ] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [ ] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

浏览器记住密码等自动输入框填充会造成黑暗模式无效
<img width="1680" alt="1 9 07 09 AM" src="https://user-images.githubusercontent.com/62740686/126727063-538be602-fcc1-4a8c-b053-a97f2b59a99c.png">

### Reproduction

1. 现有所有版本去掉代码中登录页账号密码默认值
2. 启动软件，并登录系统，同时点击记住密码
3. 退出登录，同时切换到黑暗模式，此时发现浏览器自动填充后账号密码输入框样式异常，不是黑暗模式

## System Info

- Operating System: macos
- Node version: 14
- Package manager (npm/yarn/pnpm) and version: yarn v1.22.10

**Comment by mynetfan** [comment]
fixed: https://github.com/anncwb/vue-vben-admin/commit/cebc6a590e1a19af7380a55aed43b23af274df0a
