### ISSUE TITLE
EditableCell 自定义labelField 和valueField 无效

### ISSUE THREAD

**Issue by ckbabby** [anncwb/vue-vben-admin#963]
<img width="841" alt="222" src="https://user-images.githubusercontent.com/22540944/126727585-d8db36a3-9524-4839-afd5-bfc5bab563fe.png">
EditableCell 自定义labelField 和valueField 无效,谢谢了

**Comment by mynetfan** [comment]
问题描述不清，没有说明你所使用的版本，以及问题所所涉组件是Select还是ApiSelect或者其它组件。请使用最新版本测试。
Select没有labelField、valueField属性，所以无效。
ApiSelect有这两个属性，但已经可以自动转换，没有问题

如果不提供更多信息，本Issue将被关闭

**Comment by ckbabby** [comment]
[11.zip](https://github.com/anncwb/vue-vben-admin/files/6866340/11.zip)
你好，我测试最新版代码也存在这个问题，麻烦你看看，谢谢了
![11](https://user-images.githubusercontent.com/22540944/126732475-f1fc6083-06bf-4a6b-9b35-7dd8f2318b5c.jpg)

**Comment by mynetfan** [comment]
请参考demo：
https://vvbin.cn/next/#/comp/table/editRowTable
