### ISSUE TITLE
请问如何点击菜单跳转到一个新的页面，类似a标签里的target: "_blank"功能

### ISSUE THREAD

**Issue by yangyanju** [anncwb/vue-vben-admin#965]
我正在开发数据大屏的功能，需要点击菜单重新打开一个新页面，展示我的大屏数据，这样方便F11全屏。
我以前的项目是在路由菜单的meta里添加这个,target: '_blank'：
{
          path: '#/datav',
          name: 'Datav',
          meta: { title: '新七天实时销售', keepAlive: false ,target: '_blank'},
          component: () => import('@/views/datav/index')
        },

**Comment by mynetfan** [comment]
path提供完整url，http开头的那种，就会在新窗口中打开

**Comment by yangyanju** [comment]
> 路径提供完整url，http开头的那个，就会在新窗口中打开

谢谢回复，我的路径不是外部链接，改成http://localhost:3100/#/datav/live-datav这种不会单独打开新页面

**Comment by mynetfan** [comment]
无论是不是外部链接，你在新窗口打开就相当于外部链接，一样的道理

**Comment by yangyanju** [comment]
> 无论是不是外部链接，你在新窗口打开就相当于外部链接，一样的道理

是这样写吗，我改成这样菜单里都不显示了。。。。
const datav: AppRouteModule = {
  path: '/datav',
  name: 'Datav',
  component: LAYOUT,
  meta: {
    icon: 'ri:funds-box-line',
    title: '大屏作战图',
  },
  children: [
    {
      path: 'http://localhost:3100/#/datav/live-datav',
      name: 'LiveDatav',
      component: () => import('/@/views/datav/liveDatav.vue'),
      meta: {
        title: '实时销售',
      },
    },
  ],
};

**Comment by mynetfan** [comment]
外部链接不能和业务组件component一起使用

**Comment by yangyanju** [comment]
> 外部链接不能和业务组件component一起使用

那我要跳转内部链接，应该怎么跳转呢

**Comment by mynetfan** [comment]
当你打开一个新的浏览器窗口或者标签时，目标页面已经是一个独立的页面，跟原先页面没有关系。要跳转内部链接，也需要拼接成一个完整的http开头的链接才可以，所配置的component不会起作用（因为已经不在当前页面）。

**Comment by ZackLeonardo** [comment]
@mynetfan 请问：如果是后台路由的话，如何设置component: () => import('/@/views/datav/liveDatav.vue')呢，component里是string，现在支持后台吗，还是要修改源码？

**Comment by yangyanju** [comment]
这是自动回复，已收到您的邮件，我将尽快给您回复。

**Comment by ZackLeonardo** [comment]
如何做到：1. 在浏览器新标签页打开vben项目里的一个页面（path为url）; 2.同时这个新页面只显示内容（为fullContent）。

**Comment by ZackLeonardo** [comment]
> 如何做到：1. 在浏览器新标签页打开vben项目里的一个页面（path为url）; 2.同时这个新页面只显示内容（为fullContent）。

这个是可以参照Main-out来实现。后台路由的话，如何实现？

**Comment by ZackLeonardo** [comment]
> > 如何做到：1. 在浏览器新标签页打开vben项目里的一个页面（path为url）; 2.同时这个新页面只显示内容（为fullContent）。
> 
> 这个是可以参照Main-out来实现。后台路由的话，如何实现？

在path里用url
