### ISSUE TITLE
强烈建议 精简版的把i18n去掉把 配置这个太麻烦了况且很少用到这个功能 能用到国际化的企业估计也不会选这个模板了

### ISSUE THREAD

**Issue by taolei1990** [anncwb/vue-vben-admin#966]
### Subject of the feature

Describe your issue here.

### Problem

If the feature requests relates to a problem, please describe the problem you are trying to solve here.

### Expected behaviour

What should happen? Please describe the desired behaviour.

### Alternatives

What are the alternative solutions? Please describe what else you have considered?

**Comment by mynetfan** [comment]
你在配置里关掉就行了

**Comment by taolei1990** [comment]
> 你在配置里关掉就行了
我的意思是不要引入这个依赖 减少体积

**Comment by mynetfan** [comment]
并不能减少，比如ant-design-vue就依赖i18n

**Comment by xu-Aurora** [comment]
> 你在配置里关掉就行了

咨询下，在那里关闭，哪个文件，我没有找到

**Comment by ezewu** [comment]
国际化真没有需求，要是真的国际化了，估计全是自己写了
