### ISSUE TITLE
BasicTable 里的apiSelect第一次不会加载对应显示文本值

### ISSUE THREAD

**Issue by yanzubenyan** [anncwb/vue-vben-admin#967]
![image](https://user-images.githubusercontent.com/87842137/126733950-1acca5e3-6589-4796-bf63-3dbfd924ea03.png)
![image](https://user-images.githubusercontent.com/87842137/126733951-731be820-0691-4f01-bdae-db06fb5c7318.png)

**Comment by mynetfan** [comment]
apiSelect和apiTreeSelect组件作为编辑组件时，本来的设计是用于那些仅有新增行的表格。如果你的table不仅用于新增行，还需要编辑已有数据，请使用Select和TreeSelect并自行填充options、treeData，apiSelect、apiTreeSelect不适合此场景

**Comment by Toplus2333** [comment]
在editComponentProps有一个immediate: true,入参变化时可以实时响应再次发起请求
