### ISSUE TITLE
使用tailwindcss的时候 改变样式类 无法热更新样式 需要重启服务

### ISSUE THREAD

**Issue by wzanbaichi** [anncwb/vue-vben-admin#970]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- ☑️ Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- ☑️ Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- ☑️ This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug
在代码中改变class 比如 ```class="w-20"```修改为```class="w-32"``` 在控制台style中看不到w-32的样式分配
重启服务之后生效
下面是官方的issue
[https://github.com/tailwindlabs/tailwindcss/issues/4940](url)

你们在开发的时候有没有遇到这个问题呢？ 是怎么解决的？

## System Info

- Operating System: maxos
- Node version:16.5.0
- Package manager (npm/yarn/pnpm) and version:1.22.10
- vite version: 2.4.3
- tailwindcss version: 2.2.7

**Comment by Weilence** [comment]
我碰到了，去掉tailwind.config.js中的mode: 'jit'就行了

**Comment by wzanbaichi** [comment]
@Weilence 

> 我碰到了，去掉tailwind.config.js中的mode: 'jit'就行了

就是希望能够开启JIT模式并且解决热更新的问题，不开的话css包会很大，而且很多特性用不了

**Comment by urfreespace** [comment]
+1，遇到同样的问题，且发现另一个问题，见：https://github.com/anncwb/vue-vben-admin/issues/1013

**Comment by urfreespace** [comment]
不只是tailwind，自定义的class也一样，也没有热更新效果 @wzanbaichi

**Comment by anncwb** [comment]
可以给我复现步骤，我这边热更应该是没问题

**Comment by mynetfan** [comment]
使用从未用过的新class需要重启服务，否则样式无效

**Comment by wzanbaichi** [comment]
@anncwb 使用从未用过的新class需要重启服务，否则样式无效

**Comment by cncn123** [comment]
tailwind热更新失败，但直接写style可以热更新

**Comment by anncwb** [comment]
升级到2.7.0
