### ISSUE TITLE
BasicTable 全屏显示之后编辑列，单元格中的下拉列表失效，全屏不能完整显示

### ISSUE THREAD

**Issue by 17607106326** [anncwb/vue-vben-admin#978]
![image](https://user-images.githubusercontent.com/50573299/126897288-ab0619a9-a67a-4552-bdb6-59ed7671d36c.png)

**Comment by 17607106326** [comment]
![image](https://user-images.githubusercontent.com/50573299/126897264-8c564882-628e-44f6-941c-97943ea35d5b.png)

**Comment by mynetfan** [comment]
已经修复过了，你有重新打开这个Issue干嘛？

**Comment by mynetfan** [comment]
https://github.com/anncwb/vue-vben-admin/commit/a07ab6d7aa1060f856649a9bdbec9dfa50b14f26
https://github.com/anncwb/vue-vben-admin/commit/a5a9b3fb34c64b6ea9c9ab3d58045f6e5963952b
https://github.com/anncwb/vue-vben-admin/commit/dce3fb0f20516aaf4817281f5d08109e53a73ecb

演示页面：https://vvbin.cn/next/#/comp/table/editRowTable

**Comment by 17607106326** [comment]
感谢，搜的时候估计没搜对，没找到，不好意思



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月25日(星期天) 晚上7:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [anncwb/vue-vben-admin] BasicTable 全屏显示之后编辑列，单元格中的下拉列表失效，全屏不能完整显示 (#978)





 
a07ab6d
 a5a9b3f
 dce3fb0
 
演示页面：https://vvbin.cn/next/#/comp/table/editRowTable
