### ISSUE TITLE
他怎么提示类型是数组，我明明是方法，

### ISSUE THREAD

**Issue by shijunti19** [anncwb/vue-vben-admin#98]
### Subject of the issue

Describe your issue here.
```
const [
        registerTable,
        {setColumns,setTableData }
      ] = useTable({
        canResize: true,
        title: 'useTable示例',
        titleHelpMessage: '使用useTable调用表格内方法',
        // api: demoListApi,
        columns: [],
        bordered:true,
        striped:true,
        loading:false,
        pagination:{ pageSize: 15 },
        rowKey: 'id',
        onChange:handleTableChange,
        rowSelection: {
          type: 'checkbox',
        },
      });


   function handleTableChange(
        pagination: PaginationProps,
        // @ts-ignore
        filters: Partial<Record<string, string[]>>,
        sorter: SorterResult
      ) {
        console.log("pagination",pagination);
        console.log("filters",filters);
        console.log("sorter",sorter);
        return;
      }

```
然后他会报错
![image](https://user-images.githubusercontent.com/5392211/99879379-afe12480-2c47-11eb-9809-3540f875d347.png)

### Your environment

- **OS**: 
- **Packages**: 
- **Env**: 

### Steps to reproduce

Tell us how to reproduce this issue. Please provide a working and simplified example.

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub. This will get you the fastest support. 🎉

### Expected behaviour

What should happen?
按理就是复制出来写自己的逻辑啊，不可能检测类型错误啊
### Actual behaviour

What happens instead?

**Comment by godaangel** [comment]
遇到问题 +1 
版本 2.3.0

**Comment by godaangel** [comment]
请问这个问题解决了吗 @anncwb

**Comment by mynetfan** [comment]
此issue已关闭。过时的版本不会再去验证，如果新版本同样发现此问题，请重新提issue。
