### ISSUE TITLE
Tinymce组件value双向绑定的BUG

### ISSUE THREAD

**Issue by Weilence** [anncwb/vue-vben-admin#981]
文档中提到Tinymce组件应当是value(v-model)

但是
1. prop中既有modelValue，也有value
2. emit中只有modelValue，没有value
3. 初始化只有value有效，modelValue无效

这导致这个组件既不能使用modelValue双向绑定（因为无法初始化），也不能使用value双向绑定（因为无法emit到外部）

**Comment by mynetfan** [comment]
请看富文本在表单中的使用例子------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月26日(星期一) 中午1:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[anncwb/vue-vben-admin] Tinymce组件value双向绑定的BUG (#981)

**Comment by Weilence** [comment]
文档的例子我看了，但是问题如图所示，v-model中的value是没变的，但文档说是双向绑定。
value(v-model)在组件上不是应该写成v-model:value="xxxx"吗？
![image](https://user-images.githubusercontent.com/11787429/126972575-29e3f4b2-3d5e-4135-a363-dc6b7ef9d088.png)
![image](https://user-images.githubusercontent.com/11787429/126972987-f4b7fe31-fab8-4a0f-90ee-aa8ed8fac777.png)
![image](https://user-images.githubusercontent.com/11787429/126972747-cda08b74-4f1a-4fec-a0d3-84b6db21d96d.png)

**Comment by mynetfan** [comment]
你所使用的版本？

**Comment by mynetfan** [comment]
经测试没有问题。
如果你使用的是较老的版本，请更新或者根据commits记录做对应的代码同步。
遇到问题请先在当前版本测试是否已修复，或者查阅[更新日志](https://github.com/anncwb/vue-vben-admin/blob/main/CHANGELOG.zh_CN.md)看是否有相关fix。
