### ISSUE TITLE
treeedit 节点内容太长，无法点击编辑按钮

### ISSUE THREAD

**Issue by zn98com** [anncwb/vue-vben-admin#99]
treeedit 节点内容太长，按钮在下行时,点击不到按钮.

![1](https://user-images.githubusercontent.com/10260081/99923406-94256d80-2d70-11eb-97f4-83f89e39be8d.png)

**Comment by anncwb** [comment]
可以先将宽度加大，后面修改

**Comment by xietongjian** [comment]
节点内容太长的问题我也遇到了，名称太长或层级太深的时候直接被隐藏掉了。如果名称太长，是否可以设置横向滚动条？
