### ISSUE TITLE
修改任意代码，都会导致整个页面reload，且刷新很慢

### ISSUE THREAD

**Issue by urfreespace** [anncwb/vue-vben-admin#992]
**⚠️ IMPORTANT ⚠️ Please check the following list before proceeding. If you ignore this issue template, your issue will be directly closed.**

- [x] Read [the docs](https://anncwb.github.io/vue-vben-admin-doc/).
- [x] Make sure the code is up to date. (Some bugs have been fixed in the latest code)
- [x] This is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/anncwb/vue-vben-admin/discussions) or join our [Discord](https://discord.gg/8GuAdwDhj6) Chat Server.

### Describe the bug

修改任意代码，都会导致整个页面reload，且刷新很慢，日志输出是[vite] page reload xxxx
但是用create-vite创建一个demo项目，修改任意代码，页面反应非常迅速，不会reload，只会局部update，日志输出是[vite] page update xxxx

### Reproduction

Please describe the steps of the problem in detail to ensure that we can restore the correct problem

## System Info

- Operating System:
- Node version:
- Package manager (npm/yarn/pnpm) and version:

**Comment by mynetfan** [comment]
请更新到最新代码

**Comment by urfreespace** [comment]
> 请更新到最新代码

已是最新代码，但问题依旧，可能是我问题描述不够清晰，这种reload非常影响开发体验，还请在帮忙看看，非常谢谢，问题描述和测试如下：

1. vue-vben-admin中修改任意页面代码，都会导致整个页面reload，且刷新很慢，日志输出是`[vite] page reload xxxx`，注意重点，日志输出中是`reload`
2. 用create-vite创建一个demo项目，修改demo中任意代码，页面反应非常迅速，不会reload，只会局部update，日志输出是[vite] page update xxxx，注意重点日志输出中是`update`
3. vue-vben-admin的页面reload非常影响开发体验，影响迭代效率

**Comment by mynetfan** [comment]
请同步最近几个commits，特别是依赖更新部分。2.6.1及最近几个版本确有此问题。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月27日(星期二) 晚上8:24
***@***.***&gt;;
***@***.***&gt;;&quot;State ***@***.***&gt;;
主题:&nbsp;Re: [anncwb/vue-vben-admin] 修改任意代码，都会导致整个页面reload，且刷新很慢 (#992)

**Comment by urfreespace** [comment]
> 请同步最近几个commits，特别是依赖更新部分。2.6.1及最近几个版本确有此问题。------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年7月27日(星期二) 晚上8:24 ***@***.***&gt;; ***@***.***&gt;;&quot;State ***@***.***&gt;; 主题:&nbsp;Re: [anncwb/vue-vben-admin] 修改任意代码，都会导致整个页面reload，且刷新很慢 (#992)

确定是已同步所有最近的commits，问题依旧，这个问题是暂时无法解决吗？我测试了下好像跟vue-router有关，但没找到具体原因，您那边目前针对这个问题有计划或者思路吗？

**Comment by mynetfan** [comment]
当前版本没有重现你所描述的问题------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月27日(星期二) 晚上9:31
***@***.***&gt;;
***@***.***&gt;;&quot;State ***@***.***&gt;;
主题:&nbsp;Re: [anncwb/vue-vben-admin] 修改任意代码，都会导致整个页面reload，且刷新很慢 (#992)

**Comment by mynetfan** [comment]
你可以克隆一个干净的当前仓库测试

**Comment by urfreespace** [comment]
> 你可以克隆一个干净的当前仓库测试

非常感谢，我rm了node_modules重新install后，问题解决
