### ISSUE TITLE
浏览器兼容问题

### ISSUE THREAD

**Issue by Ruio9244** [anncwb/vue-vben-admin#993]
打包后，看到index.html有以下代码
```js
<link rel="modulepreload" href="/main/assets/vendor.c45e8c14.js">
<link rel="stylesheet" href="/main/assets/vendor.41758fd5.css">
<link rel="stylesheet" href="/main/assets/index.36908db9.css">
```
QQ浏览器无法支持，请问有好的解决办法么？

**Comment by mynetfan** [comment]
你什么版本的QQ浏览器？我测试是可以的。不支持modulepreload的浏览器已经是古董级别或者非主流版本。

**Comment by Ruio9244** [comment]
> 你什么版本的QQ浏览器？我测试是可以的。不支持modulepreload的浏览器已经是古董级别或者非主流版本。

![image](https://user-images.githubusercontent.com/9160957/127422313-20a2ef13-86a8-49d6-bb7a-8fec6b3074a0.png)

**Comment by mynetfan** [comment]
演示站点不能正常打开？

**Comment by mynetfan** [comment]
测试没有问题，一切正常。QQ浏览器不能用于开发环境，因为它的chromiun版本太低。
生产环境下QQ浏览器没有问题
